LANSA.addComponent({id:"A06CHA01",nm:"A06ResourceMonitor",ot:"rp",tp:"Reusable Part",pt:"ap",de:"Resource Monitor",tl:15000300},function(l,oI,u){var cL="ENG";if(l.gCL()=="FRA"){cL=l.gCL();}var Fd={F1:{ic:0,nm:"STD_INT",ft:"I",ln:4,dc:0,ec:"J",lb:{"ENG":"Std Integer","FRA":"?"}[cL],h1:{"ENG":"Standard","FRA":"?"}[cL],h2:{"ENG":"Integer","FRA":"?"}[cL],h3:{"ENG":"Field","FRA":"?"}[cL],de:{"ENG":"Standard Integer field","FRA":"?"}[cL],dv:0,ia:["FE","RB"]},F2:{ic:0,nm:"STD_TIMX",ft:"T",ln:8,dc:0,lb:{"ENG":"Std RDMLX time","FRA":"?"}[cL],
h1:{"ENG":"Standard","FRA":"?"}[cL],h2:{"ENG":"RDMLX","FRA":"?"}[cL],h3:{"ENG":"Time","FRA":"?"}[cL],de:{"ENG":"Standard RDMLX Time field","FRA":"?"}[cL],dv:l.SqlNull,ia:["ASQN","FE","ISO"]},F3:{nm:"STD_COUNT",ft:"P",ln:7,dc:0,lb:{"ENG":"Standard count","FRA":"Nombre standard"}[cL],h1:{"ENG":"Standard","FRA":"Nomnre"}[cL],h2:{"ENG":"count","FRA":"Standard"}[cL],h3:" ",de:{"ENG":"Standard count","FRA":"Dénombrement standard"}[cL],dv:0,ia:["FE","RB"]}};var cO=l.rC(oI,{an:"PRIM_PANL",fd:Fd,rm:["dt"],
mt:{AdjustCurrentUsage:{}},co:function(){cO.aN.call(this);this.aF("A06CHA01",Fd);var C0=this.cR("LAYOUTMAIN","PRIM_TBLO");var C1=this.cR("LAYOUTMAINROW1","PRIM_TBLO","Row");var C2=this.cR("LAYOUTMAINCOLUMN1","PRIM_TBLO","Column");var C3=this.cR("LAYOUTMAINROW2","PRIM_TBLO","Row");var C4=this.cR("LAYOUTMAINITEM1","PRIM_TBLO","Item");var C5=this.cR("LAYOUTMAINITEM2","PRIM_TBLO","Item");var C6=this.cR("LAYOUTMAINITEM3","PRIM_TBLO","Item");var C7=this.cR("TEXT","PRIM_MD","Label");var C8=this.cR("STATUS","PRIM_MD","Label");
var C9=this.cR("LINECHART","PRIM_CHRT","LineChart");var C10=this.cR("LINECHARTCAPTION","PRIM_CHRT","LineChartCaption");var C11=this.cR("LINECHARTVALUE","PRIM_CHRT","LineChartValue");var C12=this.cR("TIMER","PRIM_TIMR");var C13=this.cF("CURRENTUSAGE",Fd.F1.Dc);var C14=this.cF("CURRENTTIME",Fd.F2.Dc);var C15=this.cF("RANDOMNUMBER",Fd.F1.Dc);C0.iC();C1.setDisplayPosition(1);C1.setParent(C0);C1.setHeight(58);C1.setUnits("PIXELS");C1.iC();C2.setDisplayPosition(1);C2.setParent(C0);C2.iC();C3.setDisplayPosition(2);
C3.setParent(C0);C3.iC();C4.setAlignment("TOPCENTER");C4.setColumn(C2);C4.setManage(C9);C4.setParent(C0);C4.setRow(C3);C4.setMarginBottom(20);C4.setMarginLeft(12);C4.setMarginRight(12);C4.iC();C5.setColumn(C2);C5.setManage(C7);C5.setParent(C0);C5.setRow(C1);C5.iC();C6.setAlignment("CENTERRIGHT");C6.setColumn(C2);C6.setManage(C8);C6.setParent(C0);C6.setRow(C1);C6.setSizing("CONTENTWIDTHANDHEIGHT");C6.setMarginRight(8);C6.iC();C7.setDisplayPosition(2);C7.setLeft(0);C7.setParent(this);C7.setTabPosition(1);
C7.setTop(0);C7.setWidth(498);C7.setHeight(58);C7.setCaptionMarginLeft(16);C7.setCaptionMarginRight(16);C7.setCaption("Resource Monitor");C7.setThemeDrawStyle("Heading3");C7.iC();C8.setCaption("30%");C8.setDisplayPosition(1);C8.setLeft(434);C8.setParent(this);C8.setTabPosition(2);C8.setThemeDrawStyle("Heading2");C8.setTop(8);C8.setWidth(56);C8.setHeight(43);C8.setCaptionAlignment("CENTER");C8.setPaddingLeft(8);C8.setPaddingRight(8);C8.setPaddingBottom(8);C8.setPaddingTop(8);C8.iC();C9.setDisplayPosition(3);
C9.setHeight(190);C9.setLeft(12);C9.setParent(this);C9.setTabPosition(3);C9.setTabStop(false);C9.setTop(58);C9.setWidth(474);C9.setAnimationDuration(0);C9.setThemeDrawStyle("Subheading");C9.setAxes("LEFT");C9.setGridLines("HORIZONTAL");C9.setHintShow(false);C9.setHintShowOfParent(false);C9.iC();C10.setParent(C9);C10.iC();C11.setDisplayPosition(1);C11.setParent(C9);C11.setThemeDrawStyle("Border(255,207,68,1)");C11.setPointStyle("NONE");C11.setBorderWidth(2);C11.setLineStyle("STRAIGHT");C11.iC();C12.setStartup("MANUAL");
C12.iC();C13.aD();C13.iC();C14.aD();C14.iC();C15.aD();C15.iC();C9.aH("FORMATTICK",this,e4);C12.aH("TICK",this,e3);this.setDisplayPosition(1);this.setHeight(270);this.setLeft(0);this.setTabPosition(1);this.setTop(0);this.setWidth(500);this.setLayoutManager(C0);this.setThemeDrawStyle("Shadow2+Card+LightDark");this.aH("CREATEINSTANCE",this,e1);this.aH("INITIALIZE",this,e2);}});function e1(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#COM_OWNER.CreateInstance",28);r.ln=28;{r.ln=30;m.STATUS.set("");r.ln=31;
m.LINECHART.getPrimaryAxis().setBeginAtZero(false);}r.ln=33;r.e();};function e2(sender,Ps){var f=this.FLD.A06CHA01,m=this.REF,r=l.eR(this,cO,"#COM_OWNER.Initialize",35);r.ln=35;{r.ln=38;m.CURRENTTIME.set(l.t.Now(m.CURRENTTIME.get()));r.ln=39;m.CURRENTUSAGE.set(57);r.ln=42;m.CURRENTTIME.set(l.t.Adjust(m.CURRENTTIME.get(),-300));r.ln=44;for(var i1=1,s1=1,t1=l.tI(300);f.F3.set(i1),(((s1>=0)&&(i1<=t1))||((s1<0)&&(i1>=t1)));i1+=s1){r.ln=46;m.CURRENTTIME.set(l.t.Adjust(m.CURRENTTIME.get(),1));r.ln=48;this.mthADJUSTCURRENTUSAGE();
r.ln=50;m.LINECHARTCAPTION.set(l.t.AsDisplayString(m.CURRENTTIME.get(),"HHSMMSSS"));r.ln=51;m.LINECHARTVALUE.set(m.CURRENTUSAGE.get());r.ln=52;m.LINECHART.addEntry();}r.ln=57;m.TIMER.mthSTART();}r.ln=59;r.e();};function e3(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Timer.Tick",61);r.ln=61;{r.ln=63;m.CURRENTTIME.set(l.t.Now(m.CURRENTTIME.get()));r.ln=65;this.mthADJUSTCURRENTUSAGE();r.ln=67;m.STATUS.set(l.cat(l.n.AsString(m.CURRENTUSAGE.get()),"%"));r.ln=70;m.LINECHART.deleteEntry(1);r.ln=73;m.LINECHARTCAPTION.set(l.t.AsDisplayString(m.CURRENTTIME.get(),"HHSMMSSS"));
r.ln=74;m.LINECHARTVALUE.set(m.CURRENTUSAGE.get());r.ln=75;m.LINECHART.addEntry();r.ln=77;{var v1=m.CURRENTUSAGE.get();if(r.ln=79,l.n.gt(v1,70)){r.ln=81;m.STATUS.setThemeDrawStyle("Heading2+Rounded+DarkError");}else if(r.ln=83,l.n.gt(v1,60)){r.ln=85;m.STATUS.setThemeDrawStyle("Heading2+Rounded+MediumError");}else{r.ln=89;m.STATUS.setThemeDrawStyle("Heading2");}r.ln=91;}}r.ln=93;r.e();};cO.mthADJUSTCURRENTUSAGE=function(){var m=this.REF,r=l.mR(this,cO,"AdjustCurrentUsage",95);r.ln=95;{r.ln=97;m.RANDOMNUMBER.set(l.n.Mod(l.add64(l.mul64(7,m.RANDOMNUMBER.get()),3),3259));
r.ln=99;m.CURRENTUSAGE.set(l.add(l.zap(m.CURRENTUSAGE.get(),22,0),l.sub(l.zap(l.n.Mod(m.RANDOMNUMBER.get(),11),21,0),5)));r.ln=101;{var v1=m.CURRENTUSAGE.get();if(r.ln=103,l.n.gt(v1,90)){r.ln=105;m.CURRENTUSAGE.set(90);}else if(r.ln=107,l.n.gt(v1,70)){r.ln=109;m.CURRENTUSAGE.set(l.sub(m.CURRENTUSAGE.get(),1));}else if(r.ln=111,l.n.lt(v1,30)){r.ln=113;m.CURRENTUSAGE.set(l.add(m.CURRENTUSAGE.get(),1));}else if(r.ln=115,l.n.lt(v1,10)){r.ln=117;m.CURRENTUSAGE.set(10);}r.ln=119;}}r.ln=121;r.e();};function e4(sender,Ps)
{var r=l.eR(this,cO,"#LineChart.FormatTick",123);var P0=Ps.r("LABEL");var P1=Ps.r("VALUE");r.ln=123;{r.ln=125;P0.set(l.cat(l.n.AsString(P1.get()),"%"));}r.ln=127;r.e();};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"STD_INT"});}{Fd.F2.Dc=function(){this.aN.call(this,Fd.F2);};l.cFC({co:Fd.F2.Dc,an:"PRIM_FLD",fn:"STD_TIMX"});}},{rp:["PRIM_PANL","PRIM_TBLO","PRIM_TBLO.Row","PRIM_TBLO.Column","PRIM_TBLO.Item","PRIM_MD.Label","PRIM_CHRT.LineChart","PRIM_CHRT.LineChartCaption","PRIM_CHRT.LineChartValue","PRIM_TIMR","PRIM_FLD","PRIM_DTIM"]
});