window.LANSA.addSrc("sound",function(d,c,a,b,p){var t,l;t={ALL:0,METADATA:1,NONE:2};l={auto:0,metadata:1,none:2};c.P0a=function(a){q.K.call(this);this.c$=this.tr="";this.jpa=a};var q=c.u(c.P0a,c.Bd);q.R=function(){q.k.R.call(this)};q.Lg=function(){return this.tr};q.Su=function(a){this.tr=a};q.g5=function(){return this.c$==p?"":this.c$};q.u7=function(a){this.c$=a};q.Ps=function(){for(var a=0;a<this.jpa.Kc();a++)this.jpa.Rt(a)===this&&this.jpa.ws(a)};d.Sa(c.P0a,"PRIM_SOND","File",{Aa:{FileName:{a:q.Lg,
f:function(a){this.Su(d.ka(a))}},FileExtension:{a:q.g5,f:function(a){this.u7(d.ka(a))}}},jc:{Delete:q.Ps},df:{bf:"FileExtension"}});c.xvb=function(a){s.K.call(this);this.UBc=a;this.nb=[]};var s=c.u(c.xvb,c.Bd);s.Kc=function(){return this.nb.length};s.te=function(a){return this.Rt(a)};s.Rt=function(a){if(0>a||a>=this.nb.length)throw d.Wv(a,this.nb.length);return this.nb[a]};s.si=function(a,b){var d=new c.P0a(this);d.Su(a);d.u7(b);this.nb.push(d);(d=this.UBc.Ta())&&d.mu()};s.aIa=function(){0==this.Kc()&&
this.nb.push(new c.P0a(this));return this.Rt(0)};s.Kl=function(){this.nb=[];var a=this.UBc.Ta();a&&a.mu()};s.ws=function(a){if(null==this.Rt(a))throw d.Wv(a,this.nb.length);this.nb.splice(a,1)};s.Iid=function(a){for(var b=!1,c=0;c<this.Kc()&&!(b=this.Rt(c).Lg()==a);c++);b&&this.ws(c)};d.Sa(c.xvb,"PRIM_SOND","Files",{Aa:{Item:{a:function(a){return this.Rt(d.O(a)-1)}}},jc:{Add:s.si,RemoveAll:s.Kl,Remove:function(a){return this.ws(d.O(a)-1)}},us:{Rr:function(a){return this.Rt(d.O(a)-1)},Ty:function(){return this.Kc()}},
df:{bf:"Item"}});c.xhc=function(){k.K.call(this);this.E9=0;this.n9=this.L$=!0;this.vZ=1;this.pz=new c.xvb(this);this.Yi=-1;this.Dqa=this.Fqa=this.UY=!1;this.DF=50};var k=c.u(c.xhc,c.Mx);k.Ae=function(){return c.ykc};k.R=function(){k.k.R.call(this)};k.Lg=function(){return 0<this.pz.Kc()?this.pz.Rt(0).Lg():""};k.Su=function(b){this.pz.Kl();var c=this.pz.aIa();c.Lg()!=b&&(c.Su(b),(b=this.Ta())&&b.mu(),this.m(a.g.j))};k.g5=function(){return 0<this.pz.Kc()?this.pz.Rt(0).g5():""};k.u7=function(b){var c=
this.pz.aIa();c.g5()!=b&&(c.u7(b),(b=this.Ta())&&b.mu(),this.m(a.g.j))};k.lYc=function(){return this.pz};k.smb=function(){return this.E9};k.tCb=function(b){this.E9!=b&&(this.E9=b,(b=this.Ta())&&b.mu(),this.m(a.g.j))};k.fnb=function(){return this.UY};k.gob=function(){return this.L$};k.MDb=function(b){this.L$!=b&&(this.L$=b,(b=this.Ta())&&b.mu(),this.m(a.g.j))};k.Ilb=function(){return this.n9};k.TBb=function(b){this.n9!=b&&(this.n9=b,(b=this.Ta())&&b.mu(),this.m(a.g.j))};k.hba=function(){return this.Yi};
k.gnb=function(){return this.Fqa};k.enb=function(){return this.Dqa};k.Kob=function(){return this.DF};k.iOa=function(c){c=b.Lf(c,0,100);this.DF!=c&&(this.DF=c,this.UY=0==this.DF,(c=this.Ta())&&c.mu(),this.m(a.g.j))};k.b0c=function(){return this.vZ};k.DDb=function(b){this.vZ!=b&&(this.vZ=b,(b=this.Ta())&&b.mu(),this.m(a.g.j))};k.Play=function(){this.Ta()&&this.Ta().Play()};k.ni=function(){this.Ta()&&this.Ta().ni()};k.Cyb=function(){this.iOa(0)};d.Ld(c.xhc,"PRIM_SOND",{Aa:{FileName:{a:k.Lg,f:function(a){this.Su(d.ka(a))}},
CycleToStart:{a:k.smb,f:function(a){this.tCb(d.Ca(a))}},ShowControls:{a:k.gob,f:function(a){this.MDb(d.Ca(a))}},Autoplay:{a:k.Ilb,f:function(a){this.TBb(d.Ca(a))}},Preload:{a:function(){return d.wa(this.vZ,t)},f:function(a){this.DDb(d.va(a,t))}},Duration:{a:k.hba},IsMuted:{a:k.fnb},IsPlaying:{a:k.gnb},IsEnded:{a:k.enb},Volume:{a:k.Kob,f:function(a){this.iOa(d.O(a))}}},jc:{Play:k.Play,Stop:k.ni,Mute:k.Cyb}});c.ykc=function(a){e.K.call(this,a)};var e=c.u(c.ykc,c.mo);e.Gd=function(b,c){this.v=document.createElement("audio");
this.v.setAttribute("LANSAHandle",this.hc);this.v.style.position="absolute";this.v.style.overflow="hidden";this.v.style.whiteSpace="nowrap";this.mu();var d=this.v,k=this;d.addEventListener("loadedmetadata",function(){k.L&&(k.L.Yi=d.duration,k.L.Ga(a.Q.Eac))},!1);d.addEventListener("loadeddata",function(){k.L&&k.L.Ga(a.Q.Dac)},!1);d.addEventListener("play",function(){k.L&&(k.L.Fqa=!0,k.L.Dqa=!1,k.L.Ga(a.Q.Wmc))},!1);d.addEventListener("pause",function(){k.L&&(k.L.Fqa=!1,k.L.Ga(a.Q.Otc))},!1);d.addEventListener("ended",
function(){k.L&&(k.v.pause(),k.v.paused=!0,k.L.Dqa=!0,k.L.Ga(a.Q.Jy))},!1);d.addEventListener("volumechange",function(){k.L&&(d.muted||0==d.volume?(k.v.muted=!0,k.L.UY=!0,k.L.DF=0,k.L.Ga(a.Q.Llc)):(k.L.UY=!1,k.L.DF=Math.round(100*d.volume)))},!1);return e.k.Gd.call(this,b,c)};e.mu=function(){this.xza("controls",this.L.L$);this.xza("autoplay",this.L.n9);this.xza("loop",this.L.E9);this.v.setAttribute("preload",d.wa(this.L.vZ,l));this.v.volume=0<this.L.DF?this.L.DF/100:0;this.v.muted=this.L.UY;this.ZIb()};
e.ZIb=function(){this.OAb();var a=this.L.pz.Kc();if(0!=a)for(var b=0;b<a;b++){var c=this.L.pz.Rt(b);this.rEc(this.v,c.tr,c.c$)}};e.rEc=function(a,b,c){var d=document.createElement("source");d.src=b;c&&(d.type="audio/"+c);a.appendChild(d)};e.OAb=function(){var a=this.v;if(a&&(a=a.childNodes)){var b,c,d=[];for(c=0;c<a.length;c++)b=a[c],"SOURCE"==b.nodeName&&d.push(b);for(c=0;c<d.length;c++)b=d[c],b.parentNode.removeChild(b)}};e.ES=function(){return!1};e.f2a=function(){};e.Play=function(){this.v.play!==
p&&this.v.play()};e.ni=function(){this.v.pause!==p&&this.v.pause()}});
