window.LANSA.addSrc("ppnl",function(d,c,a,b,p){d.Pb("PRIM_PHBN");d.Pb("PRIM_IMAG");d.Pb("PRIM_TBLO");a.ayb={OLa:0,Ilc:3};a.CO={Wca:0,Xxa:1,Elc:2};a.CO.G={NONE:a.CO.Wca,POPUP:a.CO.Xxa};a.am={vma:8321,B3a:1,bAb:2,gAb:8,cAb:16,eAb:32,fAb:64,iAb:128,lAb:256,dAb:512,kAb:1024,w$d:2048,jAb:4096,Foc:8192,hAb:16384};a.Cla={R6:0,aX:1,bX:2};a.A9d={Goc:0};a.XQ={mhb:0,ihb:268435456,ohb:536870912};a.XQ.G={HIDDEN:a.XQ.mhb,ALL:a.XQ.ihb,NONE:a.XQ.ohb};a.sya={Dfd:0,qzb:1,cnc:805306368};a.Wg={j2:0,EBa:1,l8a:3,m8a:4,
sIb:5,xxc:6,tIb:7,pxc:8,qxc:9,txc:10,zxc:11,uxc:12,rxc:13,sxc:14,vxc:15,wxc:16,yxc:17};a.Wg.G={NONE:a.Wg.j2,FADEINANDSCALE:a.Wg.EBa,SLIDEINLEFT:a.Wg.l8a,SLIDEINRIGHT:a.Wg.m8a,SLIDEINBOTTOM:a.Wg.sIb,NEWSPAPER:a.Wg.xxc,SLIDEINTOP:a.Wg.tIb,"3DFLIPHORIZONTAL":a.Wg.pxc,"3DFLIPVERTICAL":a.Wg.qxc,"3DSIGN":a.Wg.txc,SUPERSCALED:a.Wg.zxc,"3DSLIT":a.Wg.uxc,"3DROTATEBOTTOM":a.Wg.rxc,"3DROTATEINLEFT":a.Wg.sxc,LETMEIN:a.Wg.vxc,MAKEWAY:a.Wg.wxc,SLIPFROMTOP:a.Wg.yxc};a.Wg.xLa={NONE:a.Wg.j2,FADEINANDSCALE:a.Wg.EBa};
a.Wg.s7d={NONE:a.Wg.j2,FADEIN:a.Wg.EBa,SLIDEINLEFT:a.Wg.l8a,SLIDEINRIGHT:a.Wg.m8a,SLIDEINTOP:a.Wg.tIb,SLIDEINBOTTOM:a.Wg.sIb};a.Wg.c_b={"":a.Wg.j2,"md-effect-1":a.Wg.EBa,"md-effect-21":a.Wg.l8a,"md-effect-2":a.Wg.m8a,"md-effect-3":a.Wg.sIb,"md-effect-4":a.Wg.xxc,"md-effect-7":a.Wg.tIb,"md-effect-8":a.Wg.pxc,"md-effect-9":a.Wg.qxc,"md-effect-10":a.Wg.txc,"md-effect-11":a.Wg.zxc,"md-effect-13":a.Wg.uxc,"md-effect-14":a.Wg.rxc,"md-effect-15":a.Wg.sxc,"md-effect-17":a.Wg.vxc,"md-effect-18":a.Wg.wxc,"md-effect-19":a.Wg.yxc};
c.nhc=function(a){t.K.call(this,a);this.Gc=a};var t=c.u(c.nhc,c.x6);t.mb=function(){t.k.mb.call(this)};t.R=function(){this.ib.h7();t.k.R.call(this)};t.ma=function(){return this.Gc.Hb()};t.Ta=function(){return null};t.fka=function(){return!0};t.Uda=function(){};t.ina=function(){};t.hna=function(){};t.nA=function(){};t.Vx=function(){};t.ava=function(){return null};t.iL=function(){return!1};t.Yd=function(){return!0};t.aO=function(){return!0};t.PN=function(){return!1};t.v0=function(){return!1};t.Ne=function(b){b[0]=
a.k0a;b[1]=a.i0a};t.YJd=function(){};t.VZ=function(a){t.k.VZ.call(this,a)};t.fFc=function(){return!1};t.cma=function(){};t.Ng=function(){};t.kda=function(){};t.Sx=function(){};t.nda=function(){};t.IE=function(){};c.Nx=function(){d.Pb("PRIM_IMAG");d.Pb("PRIM_TBLO");d.Pb("PRIM_LABL");l.K.call(this);this.Nb=b.Mf(10,10,280,120);this.xg=a.am.vma;this.Lm=this.oe=this.gY=this.Ep=null;this.PA=a.Wg.j2;this.JM=a.oh.Qx;this.VSa=this.w3=this.wU=null;this.Fg=new c.pd(0,0);this.kdb=this.Lga=this.bp=this.QD=this.BF=
this.mC=this.Ms=this.SU=this.Dp=null;this.JTa="";this.oTa=12;this.Kga=a.o.Sb;b.ba().H6c(this);this.HEc();b.ba().wSc();var e=null;this.Rs();this.Ms=new c.Zl;this.Ms.sb(new c.qa(0,0,0,30));this.Ms.Oe(!1);this.Ms.vq(!1);this.Ms.Yp(this.Nc);this.Ms.jna(!1);this.mC=new c.$t;this.mC.Oe(!1);this.mC.RE(a.$d.$L);this.mC.Oa(this.Ms);this.mC.xB(a.Hc.gA);this.BF=new c.$t;this.BF.RE(a.$d.hAa);this.BF.Oa(this.Ms);this.BF.Oe(!1);this.BF.za(this,a.Q.sc,this.dNc);this.BF.za(this,a.Q.BG,this.eNc);this.BF.za(this,a.Q.CG,
this.fNc);this.QD=new c.Mw;this.QD.Oa(this.Ms);this.QD.Oe(!1);this.QD.Po(a.dh.zq);this.QD.Ef(!1);this.QD.ug(a.Op.d_b);b.Pc(this.Nc,this.Ms,null,null,1,1);e=b.Pc(this.Nc,this.mC,this.Nc.Dc(0),this.Nc.Mc(0),1,1);e.Wb(a.na.Kq);e.cc(a.ta.Lk);e.Af(2);e=b.Pc(this.Nc,this.BF,this.Nc.Dc(0),this.Nc.Mc(0),1,1);e.Wb(a.na.tC);e.cc(a.ta.sf);e.ve(2);e=b.Pc(this.Nc,this.QD,this.Nc.Dc(0),this.Nc.Mc(0),1,1);e.Wb(a.na.qe);e.cc(a.ta.Lk);this.Oe(!1)};var l=c.u(c.Nx,c.Zl);l.mb=function(){b.ga(this.FId);this.FId=null;
b.ga(this.Ms);this.Ms=null;b.ga(this.mC);this.mC=null;b.ga(this.BF);this.BF=null;b.ga(this.QD);this.QD=null;l.k.mb.call(this)};l.R=function(){b.ga(this.bp);this.bp=null;l.k.R.call(this);this.Sma(null);this.v4a(null);this.z5a(null);this.A5a(null);this.Qma(null);this.YDb(null);b.ba().Wid(this);b.ga(this.Lm);this.Lm=null;b.ga(this.VSa);this.VSa=null};l.Ae=function(){var a=c.xL;this.eS()&&(a=c.qkc);return a};l.FZd=function(){return this.JM};l.Nua=function(){if(null==this.VSa){var a=new c.nhc(this);this.VSa=
b.Cca(a);this.Ia(this,this.rPc)}return this.VSa};l.Sma=function(b){this.Ep!=b&&(this.Ep&&this.Ep.Ha(this),(this.Ep=b)&&this.Ep.Ia(this,this.RVb),this.m(a.g.j))};l.zWc=function(){return this.Ep};l.oja=function(){var a=null;this.Ep&&this.Ep instanceof c.Mx&&(a=this.Ep);return a};l.v4a=function(b){this.gY!=b&&(this.gY&&this.gY.Ha(this),(this.gY=b)&&this.gY.Ia(this,this.FMc),this.m(a.g.j))};l.cRd=function(){return this.gY};l.z5a=function(b){this.wU!=b&&(this.wU&&this.wU.Ha(this),(this.wU=b)&&this.wU.Ia(this,
this.pPc),this.m(a.g.j))};l.DZd=function(){return this.wU};l.A5a=function(b){this.w3!=b&&(this.w3&&this.w3.Ha(this),(this.w3=b)&&this.w3.Ia(this,this.qPc),this.m(a.g.j))};l.EZd=function(){return this.w3};l.Hb=function(){var a=this.oe;!this.oe||this.oe instanceof c.Nx||(a=this.oe);!a&&this.asb()&&(a=this);return a};l.rTd=function(){return this.oe};l.OR=function(){null==this.Lm&&(this.Lm=new c.nla,this.Lm.qsc(),this.Lm.cOa(a.by.g8a));return this.Lm};l.Z_c=function(){return this.Lm};l.W_d=function(){return this.Fg};
l.Rp=function(){this.hh();return this.Cg};l.Hda=function(b){b=this.xg&~a.am.bAb|(b?a.am.bAb:0);this.xg!=b&&(this.xg=b,this.m(a.g.j))};l.Lma=function(b){b=this.xg&~a.am.B3a|(b?a.am.B3a:0);this.xg!=b&&(this.xg=b,this.m(a.g.j))};l.DHa=function(){return 0!=(this.xg&a.am.B3a)};l.RBb=function(b){b=this.xg&~a.am.cAb|(b?a.am.cAb:0);this.xg!=b&&(this.xg=b,this.m(a.g.j))};l.Sta=function(){return 0!=(this.xg&a.am.cAb)};l.XDb=function(b){b=this.xg&~a.am.lAb|(b?a.am.lAb:0);this.xg!=b&&(this.xg=b,this.$X(this.vf()),
this.m(a.g.j))};l.Aob=function(){return 0!=(this.xg&a.am.lAb)};l.n1c=function(){return this.oTa};l.Lsc=function(b){b!=this.oTa&&(this.oTa=b,this.xb(),this.pa(a.g.j))};l.X_d=function(){return this.Kga};l.WNa=function(b){if(this.fsb()||this.Kga!=b)this.Kga=b,this.m(a.g.j)};l.htd=function(){!1==this.fsb()&&(this.Kga=a.o.Sb,this.m(a.g.j))};l.frc=function(b){b=this.xg&~a.am.dAb|(b?a.am.dAb:0);this.xg!=b&&(this.xg=b,this.$X(this.vf()),this.m(a.g.j))};l.RXa=function(){return 0!=(this.xg&a.am.dAb)};l.Pee=
function(b){b=this.xg&~a.am.jAb|(b?a.am.jAb:0);this.xg!=b&&(this.xg=b,this.m(a.g.j))};l.x0c=function(){return 0!=(this.xg&a.am.jAb)};l.Nrc=function(){var b=this.xg&~a.am.hAb|a.am.hAb;this.xg!=b&&(this.xg=b,this.m(a.g.j))};l.K2b=function(){return 0!=(this.xg&a.am.hAb)};l.ctd=function(){var b=this.xg&~a.am.Foc|0;this.xg!=b&&(this.xg=b,this.m(a.g.j))};l.m1c=function(){return 0!=(this.xg&a.am.Foc)};l.PG=function(b){b=this.xg&~a.am.gAb|(b?a.am.gAb:0);this.xg!=b&&(this.xg=b,this.m(a.g.j))};l.Vqd=function(b){b=
this.xg&~a.am.fAb|(b?a.am.fAb:0);this.xg!=b&&(this.xg=b,this.m(a.g.j))};l.Gee=function(b){b=this.xg&~a.am.iAb|(b?a.am.iAb:0);this.xg!=b&&(this.xg=b,this.m(a.g.j))};l.Kda=function(b){b=this.xg&~a.am.eAb|(b?a.am.eAb:0);this.xg!=b&&(this.xg=b,this.m(a.g.j))};l.H1b=function(){return 0!=(this.xg&a.am.eAb)};l.G1b=function(){return this.Dp};l.Qma=function(b){this.Dp!=b&&(null!=this.Dp&&(this.Dp.Ha(this,this.Iib),this.Dp.vb()),this.Dp=b,null!=this.Dp&&(this.Dp.Ba(),this.Dp.Ia(this,this.Iib)),this.$X(this.vf()),
this.pa(a.g.j))};l.k2c=function(){return this.SU};l.YDb=function(b){this.SU!=b&&(null!=this.SU&&(this.SU.Ha(this,this.RXb),this.SU.vb()),this.SU=b,null!=this.SU&&(this.SU.Ba(),this.SU.Ia(this,this.RXb)),this.$X(this.vf()),this.pa(a.g.j))};l.o1c=function(){return this.Nua().Dh()};l.Msc=function(b){this.Nua().Dh()!=b&&(this.Nua().Jb(b),this.m(a.g.j))};l.p1c=function(){return this.Nua().Wk()};l.$a=function(){var a=null;null!=this.Ta()&&(a=this.Ta().$a());return a};l.KUc=function(){var a=!1;if(this.eS()||
!this.asb())a=!0;return a};l.j2c=function(){return this.JTa};l.iud=function(b){this.JTa!=b&&(this.JTa=b,this.xb(),this.pa(a.g.j))};l.Mh=function(){var a=!1;null!=this.Ta()&&(a=this.Ta().$a(),a=b.me[a].WRa);return a};l.frb=function(){return 0!=(this.xg&a.am.bAb)};l.QJa=function(){return 0!=(this.xg&a.am.B3a)};l.Mrb=function(){return 0!=(this.xg&a.am.gAb)};l.V3d=function(){return 0!=(this.xg&a.am.fAb)};l.asb=function(){return 0!=(this.xg&a.am.iAb)};l.eS=function(){return 0!=(this.xg&a.am.kAb)};l.Brb=
function(){return!1};l.fsb=function(){return!1==this.T5b()};l.T5b=function(){return this.Kga!=a.o.Sb};l.u0=function(){var a=!1;this.Hb()==this&&this.Hb().W()&&this.Hb().W()!=this.Lm&&(a=!0);return a};l.P4c=function(){var a=this.u0();a&&!this.W().A_a()&&(a=!1);return a};l.s1=function(){if(null!=this.Ta()){var a=this.Xja()?this.Xja().Lh():"DEFAULT";b.l9a(this.Ta().$a(),a,this.ha.m9)}};l.shd=function(a){var c=!1;this.Mh()&&this.QJa()&&this.oja()&&null!=a&&b.ba().HE(this.oja())==a&&(c=!0);return c};l.thd=
function(a){var c=!1;if(this.Mh()&&this.QJa()&&!this.Brb())if(null==a)c=!0;else for(var d=b.ba().HE(a),c=!0;null!=a&&null!=d;)d==this?(c=!1,a=null):null!=d&&(d.oja()?(d=d.oja(),a=a!=d?d:null):a=null),d=b.ba().HE(a);return c};l.$X=function(d,e){e===p&&(e=!1);if(!b.ba().x0())if(this.Aob()){var f=new c.qa(0,0,d.ja(),30),g=d.ja()-4;this.RXa()&&(g-=f.la());this.SU&&(g-=f.la());this.QD.tb(this.ab());this.QD.pc(Math.min(g,this.QD.vZa(this.QD.ab(),this.QD.mp().length)+10));this.Ms.Ib(this);this.Ms.sb(f);
this.Ms.Qb(""==this.JTa?a.rca:this.JTa);this.mC.Ab(this.RXa());this.mC.pc(f.la());this.mC.Ab(null!=this.SU);this.mC.zd(this.SU);this.mC.sb(new c.qa(this.mC.ue(),this.mC.Re(),Math.min(this.mC.Yc()?this.mC.Yc().Ua():this.Ms.Na(),this.Ms.Na()-4),Math.min(this.mC.Yc()?this.mC.Yc().Na():this.Ms.Na(),this.Ms.Na()-4)));this.BF.Ab(this.RXa());this.BF.sb(new c.qa(this.BF.ue(),this.BF.Re(),30,29));this.BF.Mj(this.Dp?this.Dp:a.oc.JGd);e?b.ba().wEc(this.BF):b.ba().djd(this.BF);this.Ms.W()&&d.Xa(d.$()+f.la())}else this.Ms.Oa(null)};
l.kf=function(a){this.$X(a);l.k.kf.call(this,a)};l.hh=function(){this.u0()||this.Oa(this.OR());this.Mpd(this.eS());this.KUc()&&l.k.hh.call(this)};l.Sk=function(){l.k.Sk.call(this);this.$X(this.vf())};l.Xzb=function(b,c,d){l.k.Xzb(b,c,d);d[0]&&this.wW()!=a.cy.ABa&&this.Aob()&&(d[0]=this.Ms==c||this.QD==c)};l.Ne=function(b){""==b[0]&&(b[0]=a.k0a);""==b[1]&&(b[1]=a.i0a);l.k.Ne.call(this,b)};l.oda=function(a){return this.Bia(this.Ep,a)};l.u3a=function(){this.Sta()&&this.PA==a.Wg.j2&&this.Hb().Sf(!0);
this.E0b()};l.eoc=function(){if(this.Sta()){var a=b.sO();a&&a.Us(this)||this.Hb().Sf(!0)}};l.rhd=function(a){return this.nHa(a)};l.Jya=function(){null!=this.Lm&&(null!=this.Hb()&&this.Uv(this.Hb(),a.ea.d0a),this.Sma(null),this.Mrb()||null==this.gY||this.DHa()||b.lxa()!=this.gY||this.gY.PE(this.gY.lI()),this.v4a(null),this.z5a(null),this.A5a(null));this.frb()&&this.ls()};l.AMa=function(){};l.ZMa=function(){this.Fg.vn(this.ue());this.Fg.Ym(this.Re());this.Mh()&&this.pD(this.JM,this.wU,this.Fg,this.Ep,
this.w3,this.PA)};l.hea=function(d,e,f,g,k){var l=b.Vn();this.u0()&&(l.vn(this.ue()),l.Ym(this.Re()));d==p&&(d=l.Ob());e==p&&(e=l.Ub());f==p&&(f=a.oh.Qx);g==p&&(g=a.Wg.j2);this.pD(f,null,new c.pd(d,e),k,null,g)};l.pD=function(d,e,f,g,k,l){this.yf()&&d==a.oh.ama&&null==e&&g&&g.yf()&&(e=g);this.P4c()||this.Oa(this.OR());d==p&&(d=a.oh.Qx);e==p&&(e=null);f==p&&(f=b.Vn());g==p&&(g=null);k==p&&(k=null);l==p&&(l=a.Wg.j2);if(this.Mh()&&this.asb()){if(this.wU==e&&this.w3==k&&this.Ep==g&&this.JM==d&&this.PA==
l){d=b.Ti(f.Ob(),f.Ub(),this.Hb().Ua(),this.Hb().Na());this.Iya(d);this.OR().sb(new c.qa(0,0,d.ja(),d.la()));f.vn(d.aa());f.Ym(d.$());this.Hb().sb(d);this.ytc(this.Nua().yI());this.Fg=f;return}var q=this.frb();this.Hda(!1);this.Co();this.Jya();this.Hda(q)}this.JM!=a.oh.Qx&&this.W()!=this.Lm&&this.Oa(null);this.xg|=a.am.kAb;this.Dsc(!1);null!=this.Rp()&&(this.Sma(g),this.OR(),this.K2b()&&this.OR().ha.mD(this.oja()?this.oja().ha:null),this.x0c()&&this.Uv(this.OR(),a.ea.c0a),this.v4a(b.lxa()),this.JM=
d,this.PA=l,this.$X(this.vf()),this.z5a(e),this.A5a(k),this.Jfd(f,this.Mrb()),this.W()==this.OR()?this.Uv(this.OR(),a.ea.Ska):this.Uv(this,a.ea.Ska),this.u3a())};l.Co=function(){if(this.Mh()){var c=b.ba().Nk;c&&c.Us(this)&&this.Uv(c,a.ea.Zz);b.ba().vJc(this);null!=this.Ta()&&(c=this.Ta().$a(),b.me[c].bGa());this.Zkb();this.Jya()}else b.ba().w$&&(c=b.ba().w$,c.Ta()&&c.Ta().WRa&&c==this.Ep&&b.ba().Eu(c,!1))};l.gFc=function(a){for(var b=this.ha.yI(),c=null,d=b.length-1;null!=b&&0<=d&&null!=(c=b[d]);d--)a.splice(0,
0,c)};l.Jfd=function(a,c){this.Ta()&&(c||(b.ba().qy&&b.ba().qy.I6b(),b.ba().Ey(this.oja(),!1,this)),this.Kfd(a))};l.Kfd=function(c){if(this.oda(c)&&this.Hb()){this.Hb().hh();this.K2b()&&this.OR().vE(!0);c=this.Lm;c.MW()||c.S2a();c=this.Ta().$a();a.jCa+=2;b.me[c].nEa=a.jCa;b.VJb(c,b.me[c].$g());b.me[c].aAa();var d=b.me[c].L.bp?b.me[c].L.bp.Ta():null;d&&d.v.parentElement!=document.body&&(null!=d.v.parentElement&&d.v.parentElement.removeChild(d.v),d.aAc=!1,d.v.style.zIndex=b.me[c].nEa-1,document.body.appendChild(d.v))}};
l.Iya=function(a){b.vcd(this,a)};b.vcd=function(d,e){switch(d.JM){case a.oh.T2a:var f=b.DE(),f=new c.qa(f.ue()-d.ha.Ki(),f.Re()-d.ha.Uj(),f.Ua()+(d.ha.Ki()+d.ha.Fj()),f.Na()+(d.ha.Uj()+d.ha.hl()));e.SA(f);break;case a.oh.$I:var f=b.DE(),g=0,k=0,g=(f.ja()-e.Ua())/2,k=(f.la()-e.Na())/2;e.Rb(g,k);d.u0()&&e.SA(d.W().Cda(e));break;case a.oh.ama:f=b.DE();g=(f.ja()-e.Ua())/2;k=f.Fa()-e.Na();e.Rb(g,k);d.u0()&&e.SA(d.W().Cda(e));break;case a.oh.Cfd:f=b.DE();g=(f.ja()-e.Ua())/2;e.Rb(g,0);d.u0()&&e.SA(d.W().Cda(e));
break;case a.oh.bnc:f=b.DE();k=(f.la()-e.Na())/2;g=f.Ka()-e.Ua();e.Rb(g,k);d.u0()&&e.SA(d.W().Cda(e));break;case a.oh.$mc:f=b.DE();k=(f.la()-e.Na())/2;e.Rb(0,k);d.u0()&&e.SA(d.W().Cda(e));break;default:b.j1a(e)}};l.Ycd=function(){b.ba();this.bp=new c.Zl;this.bp.za(this,a.Q.Yeb,this.PPc);this.bp.za(this,a.Q.sc,this.QPc);this.yf()&&(this.bp.a0().dg("positioning:flex; alignitems-center; justify-content:center;"),this.bp.Sz().dg("position:fixed; top:0px; right:0px; left:0px;"),this.bp.SR().dg("height:100vh;"));
this.bp.Ud(1);this.bp.Za(0);this.bp.pna(1);this.bp.Xa(0);this.bp.Ab(!1);this.bp.Oe(!1);this.kdb=new c.Xf;this.Lga=new c.yb;this.Lga.Kd(this.kdb)};l.ytc=function(a){var d=b.ba().Bn;this.bp||this.Ycd();if(!this.bp.Xb()){if(this.yf()){var e=b.JL(this.yc(),this.Kga,this.oTa/100,[]);this.bp.kE().dg("class:drawer-shroud;");this.bp.on().dg("background-color:"+e+";")}this.kdb.Qd(this.Kga);this.kdb.Pg(this.oTa);this.bp.Jb(this.T5b()?this.Lga:null);for(e=0;e<a.length;e++)this.bp.Tn(a[e]);null==this.bp.Dh()?
this.bp.Oa(null):(this.bp.Ib(d),this.bp.Ud(1),this.bp.JV())}this.bp.sb(new c.qa(0,0,d.Ua(),d.Na()))};l.Y4c=function(){this.bp&&this.bp.zb()&&this.bp.Mr()};l.Lj=function(c){if(this.m1c()){var d=this.Ta().$a();a.jCa+=2;b.me[d].nEa=a.jCa;b.VJb(d,b.me[d].$g())}l.k.Lj.call(this,c)};l.Bia=function(b,e){var f=!0,g=d.gc(),k=this.Hb().Ua(),l=this.Hb().Na();g.kc("CONTEXT",b);g.GF("LEFT",e.Ob());g.GF("TOP",e.Ub());g.GF("WIDTH",k);g.GF("HEIGHT",l);g.MQ("TRANSITION",this.PA,a.Wg.G);g.pg("CONTINUE",!0);this.Ga(a.Q.az,
g);e.vn(g.wua("LEFT"));e.Ym(g.wua("TOP"));f=g.eh("CONTINUE");k=k==g.wua("WIDTH")?this.Hb().Ua():g.wua("WIDTH");l=l==g.wua("HEIGHT")?this.Hb().Na():g.wua("HEIGHT");k=new c.qa(e.Ob(),e.Ub(),k,l);this.Iya(k);this.OR().sb(new c.qa(0,0,k.ja(),k.la()));e.vn(k.aa());e.Ym(k.$());this.Hb().sb(k);this.PA=g.Mmb("TRANSITION",a.Wg.G);g.Lc();this.Fg=e;return f};l.nHa=function(b){var c=!1,c=d.gc();c.pg("CLOSEPOPUP",!0);this.Ga(a.Q.WQ,c);return c=b?!0:c.eh("CLOSEPOPUP")};l.Zkb=function(){this.Ga(a.Q.vV);this.xg&=
~a.am.kAb;this.Dsc(!0);this.u0()&&this.W().xb()};l.E0b=function(){this.Ga(a.Q.Oyb)};l.PPc=function(){this.bp.zb()||(this.bp.Oa(null),this.AMa())};l.QPc=function(){this.Brb()&&this.QJa()&&b.ba().Eu(this,!1)};l.eNc=function(){this.$X(this.vf(),!0)};l.fNc=function(){this.$X(this.vf())};l.dNc=function(a,c){b.ba().Eu(this,!1);c.rk("HANDLED",!0)};l.rPc=function(){};l.RVb=function(b,c){switch(c.fb){case a.g.Cb:this.Sma(null)}};l.pPc=function(b,c){switch(c.fb){case a.g.Cb:this.z5a(null)}};l.qPc=function(b,
c){switch(c.fb){case a.g.Cb:this.A5a(null)}};l.FMc=function(b,c){switch(c.fb){case a.g.Cb:this.v4a(null)}};l.Iib=function(b,c){switch(c.fb){case a.g.Cb:case a.g.Vb:this.Qma(null)}};l.RXb=function(b,c){switch(c.fb){case a.g.Cb:case a.g.Vb:this.YDb(null)}};l.GGa=l[a.ea.Iwa]=function(){this.eS()&&this.ZMa()};l.kR=l[a.ea.xE]=function(a){l.k.kR.call(this,a);this.$X(this.vf())};l.Fv=l[a.ea.oL]=function(a){l.k.Fv.call(this,a);this.$X(this.vf())};d.Ld(c.Nx,"PRIM_PPNL",{Aa:{CloseOnClick:{a:l.H1b,f:function(a){this.Kda(d.Ca(a))}},
AutoClose:{a:l.DHa,f:function(a){this.Lma(d.Ca(a))}},AutoFocus:{a:l.Sta,f:function(a){this.RBb(d.Ca(a))}},TitleBar:{a:l.Aob,f:function(a){this.XDb(d.Ca(a))}},ShroudColor:{a:function(){return this.fsb()?d.gd:b.tg(this.Kga)},f:function(a){a===d.gd?this.htd():this.WNa(b.Wf(d.ka(a)))}},ShroudOpacity:{a:l.n1c,f:function(a){this.Lsc(d.O(a))}},CloseButton:{a:l.RXa,f:function(a){this.frc(d.Ca(a))}},CloseImage:{a:l.G1b,f:l.Qma},TitleImage:{a:l.k2c,f:l.YDb},ShroudStyle:{a:l.o1c,f:l.Msc},ShroudStyles:{a:l.p1c},
TitleBarThemeDrawStyle:{a:l.j2c,f:function(a){this.iud(d.ka(a))}},IsOpen:{a:l.Mh}},jc:{ShowPopup:function(b,c,e,f,g){this.hea(b===p?p:d.O(b),c===p?p:d.O(c),e===p||""==e?p:d.va(e,a.oh.wcd),f===p||""==f?p:d.va(f,a.Wg.G),g)},ClosePopup:l.Co}});c.owb=function(d){q.K.call(this,d);this.Nb=b.Mf(0,0,300,30);this.oEa=a.sya.Dfd;this.uSa=new c.Nw;this.x9=this.RP=this.QP=null;this.oY=[];this.ocb=null;b.lo(this.uSa);b.ko(this.uSa);this.Yp(this.uSa);this.Oe(!1);this.x9=new c.x1a;this.x9.GNa(a.CO.Elc);this.x9.za(this,
a.Q.az,this.jNc);this.QP=new c.$t;this.QP.Oa(this);this.QP.sb(new c.qa);this.QP.za(this,a.Q.sc,this.kNc);this.QP.DX();this.ocb=new c.khc(this)};var q=c.u(c.owb,c.Zl);q.mb=function(){q.k.mb.call(this)};q.R=function(){q.k.R.call(this);b.ga(this.ocb);this.ocb=null};q.fWc=function(){return this.RP};q.grc=function(b){this.RP!=b&&(null!=this.RP&&(this.RP.Ha(this,this.MVb),this.RP.vb()),this.RP=b,null!=this.RP&&(this.RP.Ba(),this.RP.Ia(this,this.MVb)),this.xb(),this.m(a.g.j))};q.btd=function(b){b=this.xg&
~a.sya.qzb|(b?a.sya.qzb:0);this.oEa!=b&&(this.oEa=b,this.m(a.g.j))};q.job=function(){return 0!=(this.oEa&a.sya.qzb)};q.vpd=function(b){this.SXa()!=b&&(this.oEa=this.oEa&~a.sya.cnc|b,this.xb(),this.vE(),this.Fnc(this.vf()),this.pa(a.g.j))};q.SXa=function(){return this.oEa&a.sya.cnc};q.qmb=function(){var b=null;switch(this.SXa()){case a.XQ.ohb:case a.XQ.mhb:b=q.k.qmb.call(this);break;case a.XQ.ihb:d.Pb("PRIM_PCOL"),b=new c.Rvb(this.x9),b=new c.w6(b)}return b};q.Ne=function(b){""==b[0]&&(b[0]=a.iac);
""==b[1]&&(b[1]=a.s$c);q.k.Ne.call(this,b)};q.Rzb=function(){this.Yp(this.uSa)};q.Rx=function(c,d){q.k.Rx.call(this,c,d);this.Rzb();b.lhc(this,this.uSa,a.La.Tk,a.na.WD,a.ta.Lk,this.Hib)};q.kf=function(a){q.k.kf.call(this,a);this.Fnc(a)};q.Fnc=function(d){switch(this.SXa()){case a.XQ.ohb:for(this.QP.Ab(!1);0<this.oY.length;)this.oY[0].ls();break;case a.XQ.mhb:for(var e=this.oY.length,f=0,g=null,k=this.Gs,l=k.length-1;0<=l&&null!=(g=k[l]);l--)f=Math.max(f,g.Nb.Ka()),g.Tt()>d.Ka()&&(b.jhc(this,g),e++);
k=this.oY;for(l=0;l<k.length&&null!=(g=k[l]);l++)f+g.gb.Ua()<d.Ka()?(g.ls(),l--,e--):g.ma().Ud(l+1);if(0<e)this.QP.Mj(this.RP?this.RP:a.oc.$xb),this.QP.sb(new c.qa(d.Ka()-(d.la()+2),0,d.la(),d.la())),this.QP.Ab(!0),this.x9.q3a();else for(this.QP.Ab(!1);0<this.oY.length;)this.oY[0].ls();break;case a.XQ.ihb:for(;0<this.Gs.length;)b.jhc(this,this.Gs[this.Gs.length-1]);this.QP.Mj(this.RP?this.RP:a.oc.$xb);this.QP.sb(new c.qa(d.Ka()-(d.la()+2),0,d.la(),d.la()));this.QP.Ab(!0);this.x9.q3a()}this.Xb()&&
this.hh()};b.lhc=function(c,d,e,f,g,k){for(var l=null,p=c.Gs,q=1,s=0;s<p.length&&null!=(l=p[s]);s++,q++){var v=d.Jg(l);v||(v=b.Pc(d,l,d.Dc(0),d.Mc(0),1,1),l.za(c,a.Q.XI,k));v.mi(e);v.Wb(f);v.cc(g)}};q.MVb=function(b,c){switch(c.fb){case a.g.Cb:case a.g.Vb:this.grc(null);break;case a.g.j:this.xb()}};q.jNc=function(b,c){this.Ga(a.Q.az,c)};q.kNc=function(b,d){this.x9.pD(a.oh.Qx,this,new c.pd(this.Ut()+this.Ua()-this.x9.Ua(),this.Vt()+this.Na()),this);d.rk("HANDLED",!0)};q.Hib=function(a){this.job()&&
(a=a instanceof c.sla?a:null)&&a.JC()&&!a.JC().Mh()&&(a.ju(),this.ocb.Uh())};d.Sa(c.owb,"PRIM_PPNL","MenuBar",{Aa:{CollapsedMenuImage:{a:q.fWc,f:q.grc},ShowOnHover:{a:q.job,f:function(a){this.btd(d.Ca(a))}},CollapseStyle:{a:function(){return d.wa(this.SXa(),a.XQ.G)},f:function(b){this.vpd(d.va(b,a.XQ.G))}}}});c.khc=function(a){s.K.call(this,500);this.iZ=a};var s=c.u(c.khc,c.f1);s.J_=function(){if(this.iZ.job()){var a=!1,c=!1,d=b.ba().rzb(b.Vn());d?a=!0:(d=b.VW(b.Vn()))&&(d==this.iZ||d.Us(this.iZ))&&
(a=!0);!a&&(d=b.ba().HE(b.sO()))&&(c=a=!0);a||(this.iZ.Ey(),c=!0);c&&this.ni()}return!1};c.x1a=function(){k.K.call(this);this.Nb=b.Mf(0,0,150,150);this.Di=new c.Nw;this.sz=a.ayb.OLa;b.lo(this.Di);b.ko(this.Di);this.Yp(this.Di)};var k=c.u(c.x1a,c.Nx);k.mb=function(){k.k.mb.call(this)};k.R=function(){k.k.R.call(this)};k.GNa=function(b){this.qIa()!=b&&(this.sz=this.sz&~a.ayb.Ilc|b,this.xb(),this.pa(a.g.j))};k.qIa=function(){return this.sz&a.ayb.Ilc};k.Ne=function(b){""==b[0]&&(b[0]=a.kac);""==b[1]&&
(b[1]=a.t$c);k.k.Ne.call(this,b)};k.Rzb=function(){this.Yp(this.Di);this.Kda(!0)};k.Rx=function(c,d){k.k.Rx.call(this,c,d);this.Rzb();b.lhc(this,this.Di,a.La.Tj,a.na.hp,a.ta.ci,this.Hib)};k.q3a=function(){if(this.qIa()!=a.CO.Wca){for(var b=null,d=this.Gs,e=[!0,2,2,0,0],f=0;f<d.length&&null!=(b=d[f]);f++){var g=b instanceof c.sla?b:null;switch(this.qIa()){case a.CO.Xxa:g?g.Vnc(e):e[2]+=b.zb()?b.Na():0;break;case a.CO.Elc:e[1]=Math.max(e[1],b.Ua()),e[2]+=b.zb()?b.Na():0}}for(f=0;f<d.length&&null!=(b=
d[f]);f++)switch(this.qIa()){case a.CO.Xxa:(g=b instanceof c.sla?b:null)&&g.pc(e[1])}this.pc(e[1]+this.ha.Ki()+this.ha.Fj());this.xc(e[2]+this.ha.Uj()+this.ha.hl())}};k.oda=function(a){this.q3a();return k.k.oda.call(this,a)};k.kf=function(a){k.k.kf.call(this,a)};k.TVb=k[a.ea.$sb]=function(a){k.k.TVb.call(this,a);this.q3a()};k.Hib=function(a){(a=a instanceof c.sla?a:null)&&a.ju()};d.Sa(c.x1a,"PRIM_PPNL","Menu",{Aa:{MenuSizing:{a:function(){return d.wa(this.qIa(),a.CO.G)},f:function(b){this.GNa(d.va(b,
a.CO.G))}}}});c.mhc=function(a){e.K.call(this);this.t$=a};var e=c.u(c.mhc,c.wO);e.y9b=function(){return!0};e.rgb=function(a,b){return e.k.rgb.call(this,a,b,this.t$)};e.Ne=function(){};c.sla=function(){g.K.call(this);this.Nb=b.Mf(0,0,100,25);this.hga=a.Cla.R6;this.sv=0;this.Pbb=this.sNb=this.Zo=this.fU=this.n$=this.WY=this.BQ=null;this.o$=new c.Nw;this.ry=0;this.TM=a.Hc.WC;b.lo(this.o$);b.ko(this.o$);this.Yp(this.o$);this.zNa(!0);this.fU=new c.yb;this.fU.er(a.o.ye);this.fU.Xj(a.o.ye);this.fU.uq(1);
this.fU.fr(1);this.fU.Mo(1);this.fU.No(1);this.n$=new c.$t;this.n$.Oa(this);this.n$.sb(new c.qa(0,0,18,18));this.n$.Jb(this.fU);this.Zo=new c.mhc(this);this.Zo.Oa(this);this.Zo.Af(2);this.Zo.ve(2);this.sNb=b.Pc(this.o$,this.Zo,this.o$.Dc(0),this.o$.Mc(0),1,1);this.Pbb=b.Pc(this.o$,this.n$,this.o$.Dc(0),this.o$.Mc(0),1,1)};var g=c.u(c.sla,c.Zl);g.mb=function(){g.k.mb.call(this)};g.R=function(){g.k.R.call(this);this.f5a(null)};g.JC=function(){return this.Zo.JC()};g.E7=function(b){this.JC()!=b&&(this.Zo.JC()&&
this.Zo.JC().Wp(this,a.Q.az,this.IWb),this.Zo.E7(b),this.Zo.JC()&&this.Zo.JC().za(this,a.Q.az,this.IWb),this.m(a.g.j))};g.yba=function(){return this.Zo.yba()};g.aZc=function(){return this.WY};g.f5a=function(b){this.WY!=b&&(null!=this.WY&&(this.WY.Ha(this,this.HWb),this.WY.vb()),this.WY=b,null!=this.WY&&(this.WY.Ba(),this.WY.Ia(this,this.HWb)),this.Gu(),this.m(a.g.j))};g.Jv=function(){return this.ry};g.eu=function(b){b!=this.ry&&(this.ry=b,this.Gu(),this.pa(a.g.j))};g.hu=function(b){this.TM!=b&&(this.TM=
b,this.Gu(),this.pa(a.g.j))};g.If=function(){return this.Zo.If()};g.Df=function(b){this.If()!=b&&(this.Zo.Df(b),this.m(a.g.j))};g.Rf=function(){return this.Zo.Rf()};g.Af=function(b){this.Rf()!=b&&(this.Zo.Af(b),this.m(a.g.j))};g.Ug=function(){return this.Zo.Ug()};g.ve=function(b){this.Ug()!=b&&(this.Zo.ve(b),this.m(a.g.j))};g.Yg=function(){return this.Zo.Yg()};g.ig=function(b){this.Yg()!=b&&(this.Zo.ig(b),this.m(a.g.j))};g.zm=function(){return this.TM};g.Vja=function(){return 0!=(this.hga&a.Cla.bX)?
!0:!1};g.PNa=function(b){b=this.hga&~a.Cla.bX|(b?a.Cla.bX:0);this.hga!=b&&(this.hga=b,this.Gu(),this.pa(a.g.j))};g.Zg=function(){return 0!=(this.hga&a.Cla.aX)?!0:!1};g.Ei=function(b){var d=this.nI();if(b&&0!=d&&null!=this.W())for(var e=null,f=this.W().ng,g=0;g<f.length&&null!=(e=f[g]);g++)if(e instanceof c.sla){var k=e;k!=this&&k.nI()==d&&k.Ei(!1)}b=this.hga&~a.Cla.aX|(b?a.Cla.aX:0);this.hga!=b&&(this.hga=b,this.Gu(),this.pa(a.g.j))};g.nI=function(){return this.sv};g.w7=function(b){this.sv!=b&&(this.sv=
b,this.Gu(),this.pa(a.g.j))};g.rob=function(){return this.BQ};g.$5a=function(a){this.BQ!=a&&(this.BQ=a)};g.Ne=function(b){""==b[0]&&(b[0]=a.hac);g.k.Ne.call(this,b)};g.ju=function(){var a=b.ba().HE(this);(null==a||a.Mh())&&this.JC()&&!this.JC().Mh()&&this.Zo.nHb(!0)};g.tJa=function(){var a=b.ba().HE(this);(null==a||a.Mh())&&this.JC()&&this.JC().Mh()&&this.Zo.nHb(!0)};g.Vnc=function(b){var d=null,e=this.fc&&this.fc instanceof c.owb?this.fc:null,f=this.ry;this.Zg()?(d=this.Vja()?a.oc.zlc:a.oc.ylc,this.fU.er(a.o.pT),
this.fU.Xj(a.o.tea)):(this.fU.er(a.o.ye),this.fU.Xj(a.o.ye));this.WY&&(d=this.WY);d&&0==f&&(f=Math.min(this.Na(),d.Na()));this.Zo.Qb(a.X$c);this.Zo.RS(!1);this.Zo.hu(this.zm());this.Zo.s5a(e?a.WI.ILa:a.WI.JLa);this.Zo.gDb(e?a.rq.Wca:a.rq.Yxa);this.Zo.LL(a.Xw.SQ);this.Zo.Lza(!1);this.Zo.tb(this.ab());this.Zo.Po(a.dh.zq);this.n$.Mj(d);this.n$.sb(new c.qa(this.n$.ue(),this.n$.Re(),f,f));this.sNb.cc(a.ta.Qg);this.sNb.Af(e?0:f+2);this.Pbb.cc(a.ta.sf);this.Pbb.Wb(a.na.Kq);this.Pbb.Af(e?0:2);this.Zo.qk(!1,
!0);var g=this.Zo.nN(),k=this.Zo.jja();e?(g+=f+4,d&&(g+=f+4)):(g+=60,k+=10);!0==b[0]&&(this.xc(k),b[1]=Math.max(b[1],g),b[2]+=this.zb()?k:0,b[3]+=g,b[4]+=k)};g.Rx=function(a,b){g.k.Rx.call(this,a,b);this.Vnc([!1,0,0])};g.gf=function(a){var d=!1;this.nI()&&this.Ei(!0);d=g.k.gf.call(this,a);if(!d){a=b.ba().tz;for(var e=null,f=0;f<a.length&&null!=(e=a[f]);f++)e instanceof c.x1a&&b.ba().Eu(e,!1)}return d};g.IWb=function(a,b){b.Esd(this)};g.HWb=function(b,c){switch(c.fb){case a.g.Cb:case a.g.Vb:this.f5a(null);
break;case a.g.j:this.Gu()}};d.Sa(c.sla,"PRIM_PPNL","MenuItem",{Aa:{Checked:{a:g.Zg,f:function(a){this.Ei(d.Ca(a))}},MenuPopup:{a:g.JC,f:g.E7},RadioItem:{a:g.Vja,f:function(a){this.PNa(d.Ca(a))}},GroupIndex:{a:g.nI,f:function(a){this.w7(d.O(a))}},Image:{a:g.aZc,f:g.f5a},ImageHeight:{a:g.Jv,f:function(a){this.eu(d.O(a))}},MarginLeft:{a:g.Rf,f:function(a){this.Af(d.O(a))}},MarginTop:{a:g.If,f:function(a){this.Df(d.O(a))}},MarginBottom:{a:g.Yg,f:function(a){this.ig(d.O(a))}},MarginRight:{a:g.Ug,f:function(a){this.ve(d.O(a))}},
Alignment:{a:function(){return d.wa(this.zm(),a.Hc.TQ)},f:function(b){this.hu(d.va(b,a.Hc.TQ))}}},jc:{ShowMenu:g.ju,HideMenu:g.tJa}});c.ihc=function(a,b,c){f.K.call(this);this.iZ=a;this.gb=b;this.JHd=b.rg();-1==c&&(c=this.iZ.oY.length);this.iZ.oY.splice(c,0,this);this.gb.Ia(this,this.Dv);this.gb.Oa(a.x9)};var f=c.u(c.ihc,c.Bd);f.R=function(){var a=this.iZ.Gs.length+1;this.gb.Ha(this,this.Dv);this.iZ.oY.splice(this.iZ.oY.indexOf(this),1);this.gb.Ib(this.iZ);this.gb.Ud(a);this.gb.sb(this.JHd);f.k.R.call(this)};
f.ma=function(){return this.gb};b.jhc=function(a,b){-1==a.oY.indexOf(b)&&new c.ihc(a,b,0)};f.jp=function(b,c){switch(c.fb){case a.g.Cb:this.ls()}};c.qkc=function(a){v.K.call(this,a);this.WRa=!1;this.pC=null;this.zA="";this.nEa=null;this.aha=0};var v=c.u(c.qkc,c.xL);v.l4c=function(){var b=!1,c=d.wa(this.L.PA,a.Wg.c_b);if("md-effect-17"==c||"md-effect-18"==c||"md-effect-19"==c)b=!0;return b};v.Gd=function(a){var c=this;this.v=document.createElement("div");this.v.setAttribute("id",a+this.hc);this.v.setAttribute("LANSAHandle",
this.hc);this.pC=document.createElement("div");this.pC.setAttribute("LANSAHandle",this.hc);c.pC.addEventListener("click",function(a){a=b.Zt(b.tba(a.target||a.srcElement));c.L&&a.tpb()&&c.L.QJa()&&b.ba().Eu(c.L,!1)},!1);return this.v};v.Gea=function(){this.bGa()};v.NIb=function(b){this.zA=d.wa(this.L.PA,a.Wg.c_b);null!=this.nEa&&(b=this.nEa);9999<b&&(""==this.zA?v.k.NIb.call(this,b):this.pC.style.zIndex=b)};v.$m=function(a,c,d,e){a=b.Ti(a,c,d,e);this.L.u0()&&a.SA(this.L.W().bTb(a));v.k.$m.call(this,
a.aa(),a.$(),a.ja(),a.la())};v.aAa=function(){var d=this;this.L.ytc(this.L.Nua().yI());if(""!=this.zA||this.L.yf()){if(1==this.aha&&this.T3a(),0==this.aha){this.aha=2;b.ba().Bn.Ta().v.classList.add("container");if(this.L.yf())if(this.pC.style.left="0px",this.pC.style.right="0px",this.pC.style.height="100vh",this.pC.style.display="flex",this.pC.style.alignItems="center",this.pC.style.justifyContent="center",this.pC.style.zIndex=this.nEa,null!=this.L.wU&&this.L.JM==a.oh.ama){var e=[];b.bF(this.L.wU.$a(),
e);this.v.style.position="absolute";this.v.style.left=e[0]+"px";this.v.style.top=Number(e[1])+Number(e[3])+"px"}else this.L.JM==a.oh.Qx?(this.v.style.position="absolute",this.v.style.left=this.L.ue()+"px",this.v.style.top=this.L.Re()+"px"):(this.v.style.position="",this.v.style.left="",this.v.style.top="");this.pC.setAttribute("class","md-modal "+this.zA);e=b.me[this.L.Hb().Ta().$a()];e.v.style.opacity="";e.v.setAttribute("class","md-content vl-control vl-popup");this.pC.appendChild(this.v);document.body.insertBefore(this.pC,
b.ba().Bn.Ta().v);this.L.yf()&&"absolute"==this.v.style.position&&(e=[],b.bF(this.L.$a(),e),0!=e[2]&&0!=e[3]&&(e=new c.qa(e[0],e[1],e[2],e[3]),b.j1a(e),this.v.style.left=e.aa()+"px",this.v.style.top=e.$()+"px"));this.l4c()&&setTimeout(function(){document.documentElement.classList.add("md-perspective")},25);setTimeout(function(){d.pC.classList.add("md-show");setTimeout(function(){d.L&&d.L.eoc()},300)},100)}}else 2==this.aha&&this.T3a(),0==this.aha&&(this.aha=1,document.body.appendChild(this.v));this.WRa=
!0};v.bGa=function(){this.WRa&&(this.WRa=!1,this.pC.classList.contains("md-show")?this.bpc():this.T3a(),this.L.Y4c())};v.T3a=function(){document.documentElement.classList.contains("md-perspective")&&document.documentElement.classList.remove("md-perspective");switch(this.aha){case 1:this.L.yf()?this.L.bp.removeChild(this.v):document.body.removeChild(this.v);break;case 2:document.body.removeChild(this.pC),this.pC.removeChild(this.v),b.ba().Bn.Ta().v.classList.remove("container")}this.aha=0};v.bpc=function(){var a=
this;this.pC.classList.remove("md-show");setTimeout(function(){a.T3a()},500)};v.cae=function(){this.bpc()}},{rp:["PRIM_PHBN","PRIM_IMAG","PRIM_TBLO"]});
