window.LANSA.addSrc("atlm",function(d,c,a,b,p){d.Pb("PRIM_CPST");a.xha={xFc:0,VRb:1,wFc:2,URb:4,yFc:8,gKd:15};a.lX={Zzb:0,zoc:1,yoc:2,Ihd:3};a.lX.G={VERTICAL:a.lX.Zzb,HORIZONTAL:a.lX.zoc,DISPLAYPOSITION:a.lX.yoc,EO:a.lX.Ihd};a.DKa={zHd:0,lKb:1,xHd:2,BHd:3,yHd:4,AHd:5,uke:6};a.$6d={X1a:0,Y1a:1};a.Hgb={itb:32};c.Qec=function(b,c,d){t.K.call(this);this.Tb=[];this.Tb=c;this.Bj=this.bk=d;this.DDa=this.qFa=0;this.iY=a.xha.xFc};var t=c.u(c.Qec,c.jf);t.R=function(){t.k.R.call(this)};c.XKa=function(){l.K.call(this);
this.ZSa=a.lX.Zzb};d.Pb("PRIM_TBLO");var l=c.u(c.XKa,c.kLa);l.R=function(){l.k.R.call(this)};l.TZd=function(){return this.ZSa};l.wsd=function(b){this.ZSa!=b&&(this.ZSa=b,this.m(a.g.j))};l.Gda=function(a,b){var c=this.eya(a);c.Gda(b);return c};l.WV=function(a){return this.Jg(a).WV()};l.yRd=function(a){return this.Jg(a)};l.qnb=function(){return a.DKa.lKb};l.Jo=function(b,c){var d=l.k.Jo.call(this,b,c);if(d){var e=this.Jg(b);!e||e.WV()!=a.$i.yha&&e.WV()!=a.$i.vha||(d=!1)}return d};l.pq=function(b,c){var d=
l.k.pq.call(this,b,c);if(d){var e=this.Jg(b);!e||e.WV()!=a.$i.eaa&&e.WV()!=a.$i.wha||(d=!1)}return d};l.WUc=function(a){return this.Jg(a)};l.cN=function(a,b,c,e){e===p&&(e=!0);a=d.Cc("PRIM_ATLI");a.uk(b);e&&a.Oa(this);return a};l.udd=function(a,b){return b=this.kf(a,void 0)};l.OTb=function(a){var b=new c.$0a;b.uk(a);return b};l.kf=function(b,d){for(var k=this.YD(b,!0);;){var e=new c.Qec(0,k,d);e.Bj.Xa(e.Bj.Re()+this.mh);e.Bj.Za(e.Bj.ue()+this.lh);e.Bj.Va(e.Bj.Tt()-this.mj);e.Bj.Ja(e.Bj.mN()-this.lj);
switch(this.ZSa){case a.lX.Zzb:this.BV(e,a.$i.yha);this.BV(e,a.$i.vha);this.BV(e,a.$i.eaa);this.BV(e,a.$i.wha);this.BV(e,a.$i.BK);break;case a.lX.zoc:this.BV(e,a.$i.eaa);this.BV(e,a.$i.wha);this.BV(e,a.$i.yha);this.BV(e,a.$i.vha);this.BV(e,a.$i.BK);break;case a.lX.yoc:for(var g=null,f=k,l=0;l<f.length&&null!=(g=f[l]);l++){var p=g;p.Rea!=a.$i.BK&&0==(g.ma().ub&a.Hgb.itb)&&this.Kfb(e,p)}this.BV(e,a.$i.BK)}if(0==e.qFa&&0==e.DDa)break;d.U7(e.qFa,e.DDa)}return new c.qO(d.ja(),d.la())};l.BV=function(b,
c){var d=null,e=b.Tb;switch(c){case a.$i.yha:case a.$i.eaa:case a.$i.BK:for(var g=0;g<e.length&&null!=(d=e[g]);g++){var f=d;if(f.Rea==c){var l=d.ma();0==(l.ub&a.Hgb.itb)&&this.Kfb(b,f)}}break;case a.$i.vha:case a.$i.wha:for(g=e.length-1;0<=g&&null!=(d=e[g]);g--)f=d,f.Rea==c&&(l=d.ma(),0==(l.ub&a.Hgb.itb)&&this.Kfb(b,f))}};l.Kfb=function(b,c){var d=c.W1b(),e,g;switch(c.Rea){case a.$i.yha:g=0;b.iY|=a.xha.VRb;0!=c.rZ&&d.Th(d.ja(),b.bk.la()*c.rZ/100);d.Rb(b.Bj.aa()+c.Rf(),b.Bj.$()+c.If());b.Bj.s4a(b.Bj.aa(),
b.Bj.$()+d.la()+c.If()+c.Yg());e=b.Bj.ja()-(c.Rf()+c.Ug());d.Th(Math.max(e,0),d.la());this.usa(c,d);0<g&&(g>b.Bj.la()&&(d=g-b.Bj.la(),d>b.DDa&&(b.DDa=d)),b.Bj.yqc(0,g));break;case a.$i.vha:g=0;b.iY|=a.xha.wFc;0!=c.rZ&&d.Th(d.ja(),b.bk.la()*c.rZ/100);e=b.Bj.la()-(d.la()+c.If()+c.Yg());0!=(b.iY&a.xha.VRb)&&(e=Math.max(e,0));b.Bj.Th(b.Bj.ja(),e);d.Rb(b.Bj.aa()+c.Rf(),b.Bj.Fa()+c.If());e=b.Bj.ja()-(c.Rf()+c.Ug());d.Th(Math.max(e,0),d.la());this.usa(c,d);0<g&&(g>b.Bj.la()&&(d=g-b.Bj.la(),d>b.DDa&&(b.DDa=
d)),b.Bj.U7(0,-g));break;case a.$i.eaa:g=0;b.iY|=a.xha.URb;0!=c.rZ&&d.Th(b.bk.ja()*c.rZ/100,d.la());d.Rb(b.Bj.aa()+c.Rf(),b.Bj.$()+c.If());e=b.Bj.aa()+d.ja()+c.Rf()+c.Ug();b.Bj.s4a(Math.max(e,b.bk.aa()),b.Bj.$());e=b.Bj.la()-(c.If()+c.Yg());d.Th(d.ja(),Math.max(e,0));this.usa(c,d);0<g&&(g>b.Bj.ja()&&(d=g-b.Bj.ja(),d>b.qFa&&(b.qFa=d)),b.Bj.yqc(g,0));break;case a.$i.wha:g=0;b.iY|=a.xha.yFc;0!=c.rZ&&d.Th(b.bk.ja()*c.rZ/100,d.la());e=b.Bj.ja()-(d.ja()+c.Rf()+c.Ug());0!=(b.iY&a.xha.URb)&&(e=Math.max(e,
0));b.Bj.Th(e,b.Bj.la());d.Rb(b.Bj.Ka()+c.Rf(),b.Bj.$()+c.If());e=b.Bj.la()-(c.If()+c.Yg());d.Th(d.ja(),Math.max(e,0));this.usa(c,d);0<g&&(g>b.Bj.ja()&&(d=g-b.Bj.ja(),d>b.qFa&&(b.qFa=d)),b.Bj.U7(-g,0));break;case a.$i.BK:d.Rb(b.Bj.aa()+c.Rf(),b.Bj.$()+c.If()),e=b.Bj.ja()-(c.Rf()+c.Ug()),g=b.Bj.la()-(c.If()+c.Yg()),d.Th(Math.max(e,0),Math.max(g,0)),this.usa(c,d)}};l.pAb=function(b,c){var d=this.WUc(b);if(d){if(d.WV()==a.$i.yha||d.WV()==a.$i.vha)c[0]=!0;if(d.WV()==a.$i.eaa||d.WV()==a.$i.wha)c[1]=!0}};
d.Ld(c.XKa,"PRIM_ATLM",{Aa:{MarginTop:{a:l.If,f:function(a){this.Df(d.O(a))}},MarginBottom:{a:l.Yg,f:function(a){this.ig(d.O(a))}},MarginLeft:{a:l.Rf,f:function(a){this.Af(d.O(a))}},MarginRight:{a:l.Ug,f:function(a){this.ve(d.O(a))}},MaxHeight:{a:l.GYa,f:function(a){this.Jza(d.O(a))}},MaxWidth:{a:l.HYa,f:function(a){this.Pda(d.O(a))}},MinHeight:{a:l.JYa,f:function(a){this.Kza(d.O(a))}},MinWidth:{a:l.KYa,f:function(a){this.Rda(d.O(a))}},ProcessingOrder:{a:function(){return d.wa(this.ZSa,a.lX.G)},f:function(b){this.wsd(d.va(b,
a.lX.G))}}}})});window.LANSA.addSrc("atli",function(d,c,a,b){a.$i={eSb:0,yha:1,vha:2,eaa:3,wha:4,BK:5,iHc:6};a.$i.G={NONE:a.$i.eSb,TOP:a.$i.yha,BOTTOM:a.$i.vha,LEFT:a.$i.eaa,RIGHT:a.$i.wha,CENTER:a.$i.BK,EO:a.$i.iHc};a.kHc={tsa:0};c.$0a=function(){p.K.call(this);this.rZ=0;this.Rea=a.$i.eSb;this.iY=a.kHc.tsa};var p=c.u(c.$0a,c.lLa);b.a1a=function(a,b,d){var p=new c.$0a;p.Oa(a);p.uk(b);p.Gda(d);return p};p.R=function(){p.k.R.call(this)};p.qnb=function(){return a.DKa.lKb};p.WV=function(){return this.Rea};p.Gda=function(b){this.Rea!=
b&&(this.Rea=b,this.m(a.g.j))};p.xZd=function(){return this.rZ};p.Jee=function(b){0>b?b=0:100<b&&(b=100);this.rZ!=b&&(this.rZ=b,this.m(a.g.j))};p.brb=function(b){var c=!1;if(null!=this.gb&&this.gb.W()===b)if(this.gb.Yd()){if(this.gb.qp()||this.Rea==a.$i.BK)c=!0}else this.gb.qp()&&(c=!0);return c};p.n7b=function(a,b,c){this.Oa(a);this.uk(b);this.Gda(c)};d.Ld(c.$0a,"PRIM_ATLI",{Aa:{MarginTop:{a:p.If,f:function(a){this.Df(d.O(a))}},MarginBottom:{a:p.Yg,f:function(a){this.ig(d.O(a))}},MarginLeft:{a:p.Rf,
f:function(a){this.Af(d.O(a))}},MarginRight:{a:p.Ug,f:function(a){this.ve(d.O(a))}},MaxHeight:{a:p.GYa,f:function(a){this.Jza(d.O(a))}},MaxWidth:{a:p.HYa,f:function(a){this.Pda(d.O(a))}},MinHeight:{a:p.JYa,f:function(a){this.Kza(d.O(a))}},MinWidth:{a:p.KYa,f:function(a){this.Rda(d.O(a))}},Manage:{a:p.ma,f:p.uk},Parent:{a:p.W,f:p.Oa},Attachment:{a:function(){return d.wa(this.WV(),a.$i.G)},f:function(b){this.Gda(d.va(b,a.$i.G))}}}})});
