window.LANSA.addSrc("menu",function(d,c,a,b,p){d.Pb("PRIM_TBLO");d.Pb("PRIM_PPNL");d.Pb("PRIM_IMAG");d.Pb("PRIM_SPBN");a.e2a={S6:16,ryb:16};a.k1={OLa:0,yyb:1,zyb:2,syb:4};a.AO={nlc:0,Qxb:1,Pxb:2};a.AO.G={NONE:a.AO.nlc,BREAK:a.AO.Qxb,BARBREAK:a.AO.Pxb};a.BO={R6:25,fyb:1,dyb:2,V7d:4,gyb:8,eyb:16};a.AO={vdd:0};a.z7d=3;a.y7d=2;a.A7d=255;a.Xcd=768;a.Zkc=256;a.Ykc=512;a.Z1a=65536;a.$1a=131072;a.Exb=262144;a.Gxb=524288;a.Fxb=1048576;a.rge=2;a.qge=2;c.pLa=function(){t.K.call(this);this.YJ=null;this.sz=a.e2a.S6;
this.lU=a.k1.OLa;this.Ep=null;this.Tb=[];this.KM=new c.Nx;this.fra=new c.yb;this.Di=new c.Nw;this.rId=new c.tla;this.qId=new c.Rca;this.rId.it(this.Di);this.qId.it(this.Di);this.KM.Yp(this.Di);this.fra.Xj(b.U(255,255,255));this.fra.Wi(b.jb().lq(a.o.gl));this.fra.uq(1);this.fra.fr(1);this.fra.Mo(1);this.fra.No(1);this.KM.za(this,a.Q.az,this.sPc);this.KM.Jb(this.fra)};var t=c.u(c.pLa,c.Wy);t.mb=function(){this.Tb=null;t.k.mb.call(this)};t.R=function(){null!=this.YJ&&this.l2();for(var a=null;null!=(a=
this.Tb[0]);)a.Oa(null);b.ucd(this);t.k.R.call(this)};t.hYd=function(){return this.YJ};t.lYd=function(){return this.Tb};t.kYd=function(){return this.Tb.length};t.Gja=function(){return this};t.l8c=function(){return 0!=(this.lU&a.k1.zyb)};t.a7c=function(){return 0!=(this.lU&a.k1.syb)};t.nYd=function(){return 0!=(this.lU&a.k1.yyb)};t.Nrd=function(){var b=this.lU&~a.k1.yyb|a.k1.yyb;this.lU!=b&&(this.lU=b,this.pa(a.g.j))};t.vnb=function(){return 0!=(this.sz&a.e2a.ryb)};t.Dee=function(b){b=this.sz&~a.e2a.ryb|
(b?a.e2a.ryb:0);this.sz!=b&&(this.sz=b,this.pa(a.g.j))};t.Sma=function(a){this.Ep!=a&&(this.Ep=a,this.V3a())};t.zWc=function(){return this.Ep};t.My=function(){return this.Tb};t.Bka=function(){return null!=this.YJ||null!=this.Cg};t.J2d=function(){for(var a,b=this.Tb,c=0;c<b.length&&null!=(a=b[c]);c++)if(!0==a.zb())return!0;return!1};t.Rp=function(){null==this.Cg&&this.Ww(b.qb().$D(this));return this.Cg};t.Bia=function(b){var c=d.gc();c.kc("CONTEXT",b);this.Ga(a.Q.az,c);c.Lc()};t.Ry=function(b){this.Bka()&&
this.l2();b.fc=this;this.J8a(b);b.Ia(this,this.FGa);this.pa(a.g.j)};t.s6c=function(b){this.Bka()&&this.l2();b.fc=this;this.J8a(b);b.Ia(this,this.FGa);this.pa(a.g.j)};t.z1=function(b){this.Bka()&&this.l2();b.fc=null;b.Ha(this,this.FGa);this.J8a(b);this.pa(a.g.j)};t.tJa=function(){b.ba();this.l2()};t.Poc=function(a){if(null==this.YJ){if(null!=this.Cg)this.YJ=this.Cg;else{var c=b.ba().YDa;this.YJ=this.Xgb();null!=this.YJ&&(c[this.YJ]=this)}this.U2a(null,a)}};t.l2=function(){if(null!=this.YJ){for(var a,
c=this.Tb,d=0;d<c.length&&null!=(a=c[d]);d++){var k=a.lw;a.Ww(null);a.Mid();k&&k.l2()}null!=this.YJ&&(null!=this.Cg?(this.Ww(null),this.YJ=null):(a=b.ba().YDa,null!=this.YJ&&delete a[this.YJ]));this.YJ=null;this.Ww(null);b.ba().Eu(this.KM,!1)}};t.rgd=function(){};t.Azb=function(){};t.U2a=function(a,b){this.KM.sb(new c.qa(0,0,0,5));for(var d,k=0,l=this.Tb,n=0;n<l.length&&null!=(d=l[n]);n++)k=this.psa(a,b,d,k)};t.psa=function(a,b,c,d,k){return c.psa(a,b,this,d,k)};t.tTb=function(a){for(var b=!1,c,d=
this.Tb,k=0;k<d.length&&null!=(c=d[k]);k++)if(c==a||null!=c.lw&&c.lw.tTb(a)){b=!0;break}return b};t.A3c=function(b){for(var c=!1,d=null,k=this.Tb,l=0;l<k.length&&null!=(d=k[l]);l++)if(d.Xb()&&d.re()){var n=d.lw;if(null!=n&&n.A3c(b)){c=!0;break}if(d.zEa!=a.fa.lNa&&d.zEa==b){d.gf();c=!0;break}}return c};t.$Pd=function(){for(var a=this.Tb,b=null,c=null,d=0;d<a.length&&null!=(c=a[d]);d++)if(c.dba()){b=c;break}return b};t.J8a=function(a){var c=this.Tb.indexOf(a);-1!=c&&this.Tb.splice(c,1);c+=1;if(a.fc==
this){0==a.$g()&&(a.vh=this.Tb.length+1);var d=a.$g(),k=0;0<c&&d>c&&d++;for(var l,c=this.Tb,n=0;n<c.length&&null!=(l=c[n])&&!(l.$g()>=d);n++)k++;this.Tb.splice(k,0,a)}b.scd(this)};t.uMa=function(b){b==a.F_&&(this.Bka()&&this.l2(),this.Yca(),this.pa(a.g.j))};t.Yca=function(){for(var b,c=this.Tb,d=0;d<c.length&&null!=(b=c[d]);d++)b.vh=1,b.pa(a.g.j)};t.Q7d=function(a){var c=b.ba();return null!=c.YDa?c.YDa[a]:null};t.V3a=function(){};t.p3a=function(){b.ba().Eu(this.KM,!1)};t.Azb=function(){};t.bz=function(a){this.lU|=
a};t.wB=function(a){this.lU&=~a};t.hA=function(a,b){this.lU=this.lU&~a|(b?a:0)};t.RVb=function(b,c){switch(c.fb){case a.g.Cb:this.Sma(null)}};t.FGa=function(){this.l8c()?this.bz(a.k1.syb):this.Bka()&&(this.l2(),this.pa(a.g.j))};t.sPc=function(){this.Azb(null,this.KM)};d.Ld(c.pLa,"PRIM_MENU",{Aa:{}});c.lwb=function(){l.K.call(this);this.aC=null};var l=c.u(c.lwb,c.pLa);l.mb=function(){l.k.mb.call(this)};l.R=function(){this.fna(null);l.k.R.call(this)};l.j3b=function(){return this.aC};l.fna=function(b){this.aC!=
b&&(this.aC&&this.aC.bae(this),b&&b.s3d(this),this.pa(a.g.j))};l.rgd=function(){this.Bia(null)};l.U2a=function(a,b){this.KM.sb(new c.qa(0,0,0,5));for(var d,k=0,l=this.Tb,n=0;n<l.length&&null!=(d=l[n]);n++)k=this.psa(a,b,d,k,!0)};l.Xgb=function(){throw 0;};d.Ld(c.lwb,"PRIM_MBAR",{Aa:{}});c.nwb=function(){q.K.call(this);this.kCa=null;this.xKb=0};var q=c.u(c.nwb,c.pLa);q.mb=function(){q.k.mb.call(this)};q.R=function(){this.V3a();q.k.R.call(this)};q.Qde=function(b){b!=this.xKb&&(this.xKb=b,this.V3a(),
this.pa(a.g.j))};q.ARd=function(){return this.xKb};q.CUc=function(){null==this.kCa&&(this.kCa=[]);return this.kCa};q.U2a=function(a,b){this.KM.sb(new c.qa(0,0,0,5));for(var d,k=0,l=this.CUc(),n=0;n<l.length&&null!=(d=l[n]);n++)k=this.psa(a,b,d,k);l=this.Tb;for(n=0;n<l.length&&null!=(d=l[n]);n++)k=this.psa(a,b,d,k)};q.Xgb=function(){return b.Kja()};q.aAa=function(a,b){a===p&&(a=0);b===p&&(b=0);this.lnc(new c.pd(a,b),null,!0,null)};q.lnc=function(c,d){var f=b.ba(),k=!1,k=f.Nk,l=b.ba().ky;this.Bia(d,
c);b.w1a(a.F_);this.Sma(d);k&&this.Uv(k,a.Ra.ozc);null!=l&&l.f6()&&l.uV();this.Poc(this.KM);0<this.KM.Na()&&(k=f.xRb(!0),this.KM.hea(c.Ob(),c.Ub(),a.oh.Qx,p,null),f.xRb(k))};q.V3a=function(){this.l2();if(this.kCa){for(var a;null!=(a=this.kCa[0]);)b.ga(a);this.kCa=null}};q.cNd=function(a,b){var c=b.Kua();c&&c.l9d(b.Cj.BQ)};d.Ld(c.nwb,"PRIM_PMNU",{Aa:{},jc:{Show:q.aAa}});c.Chc=function(){s.K.call(this);this.aC=null};var s=c.u(c.Chc,c.pLa);s.mb=function(){s.k.mb.call(this)};s.R=function(){this.aC&&this.aC.TDb(null);
s.k.R.call(this)};s.j3b=function(){return this.aC};s.fna=function(b){if(this.aC!=b&&!this.tTb(b)){var c=this.aC;this.aC=b;c&&c.cSb(null);this.aC&&this.aC.cSb(this);this.pa(a.g.j,a.Je.e0a)}};s.vnb=function(){var a=s.k.vnb.call(this);a&&(a=this.aC.y8c());return a};s.Gja=function(){var a=null;this.aC&&(a=this.aC.Gja());return a};s.p3a=function(){s.k.p3a.call(this);this.aC.W().p3a()};s.Xgb=function(){return b.Kja()};s.ZDd=function(){if(null!=this.YJ)for(var a,b=this.Tb,c=0;c<b.length&&null!=(a=b[c]);c++){var d=
a.lw;d&&d.l2()}};s.Azb=function(b,c){this.bz(a.k1.zyb);this.Bia(null);this.bz(a.k1.zyb);this.Bka()&&this.a7c()&&(this.ZDd(),this.U2a(b,c));this.bz(a.k1.syb)};d.Ld(c.Chc,"PRIM_SMNU",{Aa:{Parent:{a:s.j3b,f:s.fna}}});c.Xgc=function(){k.K.call(this);this.fc=null;this.tf=a.BO.R6;this.ub=a.AO.vdd;this.eg=a.Z1a|a.$1a;this.zEa=a.fa.lNa;this.XAc=this.vh=this.sv=this.XCc=this.BQ=0;this.i$=this.Da=this.lw=this.fc=null;this.eb=this.Xdb="";this.zY=new c.Zl;this.cRa=new c.$t;this.N9=new c.yb;this.$P=new c.wO;this.Nfa=
b.Pc(null,this.zY,null,null,1,1);this.dRa=b.Pc(null,this.$P,null,null,1,1);this.nDa=b.Pc(null,this.cRa,null,null,1,1);this.cRa.Jb(this.N9);this.cRa.Oa(this.zY);this.$P.Oa(this.zY);this.zY.za(this,a.Q.sc,this.WNc);this.tEc()};var k=c.u(c.Xgc,c.Wy);k.mb=function(){this.aMc();k.k.mb.call(this)};k.R=function(){this.TDb(null);this.Oa(null);k.k.R.call(this);this.zd(null);this.brd()};k.OUd=function(){var a="";this.Z7c()||null!=this.Gja()&&this.Gja()instanceof c.nwb?a=this.ab():this.GVc();return a};k.ab=
function(){return this.eb};k.mp=function(){return this.ab().ze()};k.GVc=function(){this.ab()};k.kTd=function(){return this.GLb};k.O0d=function(){return!0};k.c_d=function(){return!0};k.bZd=function(){return!0};k.wDb=function(){var a=this.Gja();a&&a.Nrd()};k.Zg=function(){return 0!=(this.eg&a.Exb)?!0:!1};k.dba=function(){return 0!=(this.eg&a.Fxb)?!0:!1};k.Pde=function(b){b!=this.erb()&&(this.tf=this.tf&~a.BO.dyb|(b?a.BO.dyb:0),this.pa(a.g.j))};k.nI=function(){return this.sv};k.GYc=function(){return this.XAc};
k.n_c=function(){var b=a.AO.nlc;0!=(this.eg&a.Zkc)?b=a.AO.Qxb:0!=(this.eg&a.Ykc)&&(b=a.AO.Pxb);return b};k.W=function(){return this.fc};k.Gja=function(){var a=null;this.fc&&(a=this.fc.Gja());return a};k.Vja=function(){return 0!=(this.eg&a.Gxb)?!0:!1};k.R_d=function(){return this.zEa};k.S_d=function(){return""};k.L1c=function(){return this.lw};k.rob=function(){return this.BQ};k.v1d=function(){return this.XCc};k.zb=function(){return 0!=(this.eg&a.$1a)?!0:!1};k.tb=function(a){this.eb!=a&&(this.eb=a,
this.a7())};k.ql=function(a){this.ab().pe(a)};k.Ei=function(b){var c=this.nI();if(b&&0!=c&&null!=this.W())for(var d,k=this.W().Tb,l=0;l<k.length&&null!=(d=k[l]);l++)d!=this&&d.nI()==c&&d.Ei(!1);b=b?this.eg|a.Exb:this.eg&~a.Exb;b!=this.eg&&(this.eg=b,this.pa(a.g.j))};k.O4a=function(b){b=b?this.eg|a.Fxb:this.eg&~a.Fxb;b!=this.eg&&(this.eg=b,this.pa(a.g.j))};k.$g=function(){return this.vh};k.Ud=function(b){this.erb()||(null!=this.fc?(this.vh=b,this.fc.J8a(this)):this.vh!=b&&(this.vh=b,this.pa(a.g.j)))};
k.re=function(){return 0!=(this.eg&a.Z1a)?!0:!1};k.Og=function(b){b=b?this.eg|a.Z1a:this.eg&~a.Z1a;b!=this.eg&&(this.eg=b,this.pa(a.g.j))};k.w7=function(b){this.sv!=b&&(this.sv=b,this.pa(a.g.j))};k.Sqd=function(b){this.XAc=b;this.pa(a.g.j)};k.Mrd=function(b){var c=this.eg&~a.Xcd;switch(b){case a.AO.Qxb:c|=a.Zkc;break;case a.AO.Pxb:c|=a.Ykc}c!=this.eg&&(this.eg=c,this.pa(a.g.j))};k.Oa=function(b){this.fc!=b&&(this.fc&&this.fc.z1(this),b&&(this.erb()?b.s6c(this):b.Ry(this)),null!=this.Da&&this.wDb(),
this.pa(a.g.j,a.Je.e0a))};k.PNa=function(b){b=b?this.eg|a.Gxb:this.eg&~a.Gxb;b!=this.eg&&(this.eg=b,this.pa(a.g.j))};k.Usd=function(b){this.zEa!=b&&(this.zEa=b,this.pa(a.g.j))};k.TDb=function(a){this.lw!=a&&(this.lw&&this.lw.fna(null),a&&a.fna(this))};k.$5a=function(b){this.BQ!=b&&(this.BQ=b,this.pa(a.g.j))};k.Ofe=function(a){this.XCc=a};k.Yc=function(){return this.Da};k.zd=function(b){this.Da!=b&&(null!=this.Da&&(this.Da.Ha(this,this.jp),this.Da.vb()),this.Da=b,null!=this.Da&&(this.Da.Ba(),this.Da.Ia(this,
this.jp)),this.wDb(),this.pa(a.g.j))};k.brd=function(){null!=this.i$&&(null!=this.i$&&(this.i$.Ha(this,this.FWb),this.i$.vb()),this.i$=null,null!=this.i$&&(this.i$.Ba(),this.i$.Ia(this,this.FWb)),this.wDb(),this.pa(a.g.j))};k.hXd=function(){return this.i$};k.i2c=function(){return this.Xdb};k.fud=function(b){this.Xdb!=b&&(this.Xdb=b,this.pa(a.g.j,a.Je.s9c))};k.AZa=function(){return 0!=(this.tf&a.BO.fyb)?!0:!1};k.gud=function(b){b!=this.AZa()&&(this.tf=this.tf&~a.BO.fyb|(b?a.BO.fyb:0),this.pa(a.g.j))};
k.zob=function(){return 0!=(this.tf&a.BO.gyb)?!0:!1};k.hud=function(b){b!=this.zob()&&(this.tf=this.tf&~a.BO.gyb|(b?a.BO.gyb:0),this.pa(a.g.j))};k.L_d=function(){return!0};k.bua=function(){return 0!=(this.tf&a.BO.eyb)?!0:!1};k.lrc=function(b){b!=this.bua()&&(this.tf=this.tf&~a.BO.eyb|(b?a.BO.eyb:0),this.pa(a.g.j))};k.Ab=function(b){b=b?this.eg|a.$1a:this.eg&~a.$1a;b!=this.eg&&(this.eg=b,this.pa(a.g.j))};k.K3b=function(){return this.Nb};k.Rp=function(){null==this.Cg&&this.Ww(b.qb().$D(this));return this.Cg};
k.Xb=function(){return null!=this.fc&&this.fc.Bka()?!0:!1};k.p4d=function(){return"-"==this.ab()?!0:!1};k.erb=function(){return 0!=(this.tf&a.BO.dyb)?!0:!1};k.y8c=function(){var a=this.AZa();if(a&&this.zob()){var b=this.W();b&&(a=b.vnb())}return a};k.Z7c=function(){return null!=this.W()&&this.W()instanceof c.lwb};k.gf=function(b){b===p&&(b=null);var c=d.gc();c.kc("CONTEXT",b);this.Ga(a.Q.sc,c);c.Lc()};k.Zhe=function(){if(this.lw)for(var a,b=this.lw.Tb,c=0;c<b.length&&null!=(a=b[c]);c++)a.Ei(!1)};
k.cSb=function(b){this.lw!=b&&(this.lw&&(this.lw.aC==this?this.lw.fna(null):(this.pa(a.g.Udd),this.lw.Ha(this,this.IXb),this.lw=null)),b&&(b.aC!=this?b.fna(this):(this.lw=b,this.lw.Ia(this,this.IXb))),this.pa(a.g.j))};k.S7d=function(a){return b.ba().vSa[a]};k.tEc=function(){this.GLb=b.ba().tRb();b.ba().vSa[this.GLb]=this};k.psa=function(a,b,c,d){return this.dFc(b,d)};k.Mid=function(){this.zY.Oa(null)};k.dFc=function(b,d){if(this.zb()){var f=b.Li(),k=null;this.N9.er(a.o.ye);this.N9.Xj(a.o.ye);this.N9.uq(1);
this.N9.fr(1);this.N9.Mo(1);this.N9.No(1);this.Zg()&&(k=this.Vja()?a.oc.zlc:a.oc.ylc,this.N9.er(a.o.pT),this.N9.Xj(a.o.tea));this.Yc()&&(k=this.Yc());this.Nfa.Oa(f);this.Nfa.ro(f.Dc(0));this.Nfa.Xn(f.Mc(0));this.Nfa.mi(a.La.Tj);this.Nfa.Wb(a.na.hp);this.Nfa.cc(a.ta.ci);this.Nfa.Af(4);this.Nfa.ve(2);this.nDa.Oa(f);this.nDa.ro(f.Dc(0));this.nDa.Xn(f.Mc(0));this.nDa.cc(a.ta.sf);this.nDa.Wb(a.na.Kq);this.nDa.Af(2);this.dRa.Oa(f);this.dRa.ro(f.Dc(0));this.dRa.Xn(f.Mc(0));this.dRa.cc(a.ta.Qg);this.dRa.Af(22);
this.zY.Oa(b);this.zY.Yp(f);this.zY.Ud(d+1);this.zY.WS(this.AZa()?this.Xdb:"");this.$P.RS(!1);this.$P.hu(a.Hc.WC);this.$P.s5a(a.WI.JLa);this.$P.LL(a.Xw.SQ);this.$P.tb(this.ab());this.$P.Po(a.dh.zq);this.$P.E7(this.lw?this.lw.KM:null);this.cRa.Mj(k);this.$P.qk(!1,!0);f=60+this.$P.nN();k=10+this.$P.jja();this.zY.xc(k);this.cRa.sb(new c.qa(2,2,18,18));this.$P.sb(new c.qa(22,2,f,18));b.pc(Math.max(b.Ua(),f));b.xc(b.Na()+this.zY.Na());null!=this.lw&&this.lw.Poc(this.lw.KM);d++}return d};k.aMc=function(){delete b.ba().vSa[this.GLb];
b.ba()};k.hie=function(a){this.Ud(a);null!=this.fc&&this.fc.Yca()};k.a7=function(){this.pa(a.g.j,a.Je.p$b)};k.WNc=function(a,b){this.nI()&&this.Ei(!0);this.gf();this.W()&&this.W().p3a();b.HANDLED.set(!0)};k.IXb=function(){this.Xb()&&this.pa(a.g.j)};k.jp=function(b,c){switch(c.fb){case a.g.Cb:case a.g.Vb:this.zd(null)}};k.FWb=function(b,c){switch(c.fb){case a.g.Cb:case a.g.Vb:this.zd(null)}};d.Ld(c.Xgc,"PRIM_MITM",{Aa:{Parent:{a:k.W,f:k.Oa},Caption:{a:k.ab,f:function(a){this.tb(d.ka(a))}},Checked:{a:k.Zg,
f:function(a){this.Ei(d.Ca(a))}},Default:{a:k.dba,f:function(a){this.O4a(d.Ca(a))}},GroupIndex:{a:k.nI,f:function(a){this.w7(d.O(a))}},HelpContext:{a:k.GYc,f:function(a){this.Sqd(d.O(a))}},MenuBreak:{a:function(){return d.wa(this.n_c(),a.AO.G)},f:function(b){this.Mrd(d.va(b,a.AO.G))}},RadioItem:{a:k.Vja,f:function(a){this.PNa(d.Ca(a))}},SubMenu:{a:k.L1c,f:k.TDb},ShortCut:{a:function(){return d.wa(this.zEa,a.fa.G)},f:function(b){this.Usd(d.va(b,a.fa.G))}},Tag:{a:k.rob,f:function(a){this.$5a(d.O(a))}},
Tip:{a:k.i2c,f:function(a){this.fud(d.ka(a))}},TipShow:{a:k.AZa,f:function(a){this.gud(d.Ca(a))}},TipShowOfParent:{a:k.zob,f:function(a){this.hud(d.Ca(a))}},Enabled:{a:k.re,f:function(a){this.Og(d.Ca(a))}},Visible:{a:k.zb,f:function(a){this.Ab(d.Ca(a))}},DisplayPosition:{a:k.$g,f:function(a){this.Ud(d.O(a))}},Image:{a:k.Yc,f:k.zd}}})},{rp:["PRIM_TBLO","PRIM_PPNL","PRIM_IMAG","PRIM_SPBN"]});
