window.LANSA.addSrc("evp",function(d,c,a,b){var p=a.Mm.eN,t=a.Qn.nia,l=a.bg.Cv,q=a.wp.Xca,s=null;a.Jw={fxa:0,Aca:16,jla:32,hla:64,Vka:128};a.Jw.G={NONE:a.Jw.fxa,LEFT:a.Jw.Aca,TOP:a.Jw.jla,RIGHT:a.Jw.hla,BOTTOM:a.Jw.Vka};a.X0={ika:256,RZa:512,QZa:1024};a.X0.G={LEFT:a.X0.ika,RIGHT:a.X0.RZa,CENTER:a.X0.QZa};a.Y0={WBa:4096,W8a:8192,xJb:16384};a.Y0.G={TOP:a.Y0.WBa,BOTTOM:a.Y0.W8a,CENTER:a.Y0.xJb};a.Hkb={sie:0,wJb:65536};a.NK={t_b:15,B_b:240,z_b:3840,H_b:61440,LPd:983040,u_b:15728640,x_b:251658240,A_b:4026531840};
a.$C={fgd:0,Y2a:256,Z2a:512,qMa:1024,X2a:2048};a.rj={zkb:1,tkb:2,VWa:4,Ckb:8,Dkb:16,ykb:32,Bkb:64,XWa:128,WWa:65536,F_b:131072,Ekb:262144,xkb:524288,E_b:3840,C_b:61440,Bta:4026531840};c.vca=function(b){k.K.call(this);this.oqa=b;this.vq(!1);this.Hrc(p);this.Zk(t);this.Oj(l);this.qo(q);this.zNa(!0);this.Sc&=~a.Wd.iS;this.Sc&=~a.Wd.T0};var k=c.u(c.vca,c.Zl);k.Nb=b.pO();k.mh=0;k.lh=150;k.mj=0;k.lj=0;k.KCa=150;k.JCa=0;k.pb=null;k.vId=null;k.zZ=null;k.wu=null;k.qC=null;k.pv=a.Op.ria;k.be=null;k.uo=0;k.fg=
0;k.DMb=null;k.CMb=null;k.BMb=null;k.zNb=null;k.yNb=null;k.pQ="";k.uDa="";k.MDa="";k.bQ=null;k.Ed=k.Ed|a.tc.hKa|a.tc.Fwa|a.tc.V0|a.tc.Kka|a.tc.jKa;k.uo=a.Mm.OF|a.Jw.Aca|a.X0.ika|a.Y0.xJb;k.fg=a.rj.VWa|a.rj.XWa|a.$C.qMa|a.rj.WWa;k.mb=function(){b.ga(this.be);k.k.mb.call(this)};k.R=function(){k.k.R.call(this);this.hOa(null);this.yma();this.vId=null;this.$da(null);b.ga(this.zZ);this.zZ=null;b.ga(this.bQ);this.bQ=null};k.yw=function(){return this.oqa.yw()};k.U2b=function(){return this.uo&a.NK.z_b};k.fW=
function(){return this.uo&a.NK.B_b};k.bL=function(){return this.fg&a.rj.E_b};k.V2b=function(){return this.uo&a.NK.H_b};k.Vda=function(b){this.pQ!=b&&(this.pQ=b,this.$h(),this.pa(a.g.j))};k.QYa=function(){return this.pQ};k.dua=function(){var a=[""],b=this.nc();b&&b.h4a(a);return a[0]};k.ord=function(b){b|=this.uo&~a.NK.z_b;this.uo!=b&&(this.uo=b,this.xb(),this.pa(a.g.j),this.Hg())};k.ssc=function(b){b|=this.fg&~a.rj.E_b;this.fg!=b&&(this.fg=b,this.xb(),this.pa(a.g.j),this.gJb(),this.Hg())};k.prd=function(b){b|=
this.uo&~a.NK.B_b;this.uo!=b&&(this.uo=b,this.xb(),this.pa(a.g.j),this.Hg())};k.Dkd=function(){var b=new c.qa(0,0,0,0);if(this.fW()!=a.Jw.fxa){for(var b=this.vf(),d=b.Ka(),e=b.Fa(),k=0,n=0,l,p=this.ng,q=0;q<p.length&&null!=(l=p[q]);q++)if(l!=this.hf())var s=l.Wl(),d=Math.min(d,s.aa()),e=Math.min(e,s.$()),k=Math.max(k,s.Ka()),n=Math.max(n,s.Fa());switch(this.fW()){case a.Jw.fxa:b.Th(d,b.la());break;case a.Jw.Aca:b.Th(d,b.la());break;case a.Jw.jla:b.Th(b.ja(),e);break;case a.Jw.hla:b.s4a(k,0);break;
case a.Jw.Vka:b.s4a(0,n)}}return b};k.Zmb=function(){return(this.uo&a.NK.A_b)>>28};k.Hrc=function(b){b=this.uo&~a.NK.A_b|b<<28;this.uo!=b&&(this.uo=b,this.xb(),this.pa(a.g.j),this.Hg())};k.mnb=function(){return this.uo&a.NK.t_b};k.srd=function(b){b|=this.uo&~a.NK.t_b;this.uo!=b&&(this.uo=b,this.xb(),this.Hd(),this.pa(a.g.j),this.Hg())};k.iIa=function(){var b;switch(this.mnb()){case a.Mm.OF:case a.Mm.s4:case a.Mm.nGa:b=this.rb().uda(this.mnb(),a.X5.f_a);break;case a.Mm.eN:b=this.ab()}return b};k.trd=
function(b){b|=this.uo&~a.NK.H_b;this.uo!=b&&(this.uo=b,this.xb(),this.Hd(),this.pa(a.g.j),this.Hg())};k.g_c=function(){return this.lj};k.Crd=function(b){this.lj!=b&&(this.lj=b,this.$Ba(32767,32767),b=0,this.fW()==a.Jw.Vka&&(this.P0()&&this.bL()==a.$C.X2a&&(b=17),this.JCa=this.lj,this.JCa+=b),this.xb(!0),this.Hg(),this.pa(a.g.j))};k.h_c=function(){return this.lh};k.$rc=function(b){this.lh!=b&&(this.lh=b,this.$Ba(32767,32767),b=0,this.fW()==a.Jw.Aca&&(this.P0()&&this.bL()==a.$C.Y2a&&(b=17),this.KCa=
this.lh,this.KCa+=b),this.xb(!0),this.Hg(),this.pa(a.g.j))};k.i_c=function(){return this.mj};k.Frd=function(b){this.mj!=b&&(this.mj=b,this.$Ba(32767,32767),b=0,this.fW()==a.Jw.hla&&(this.P0()&&this.bL()==a.$C.qMa&&(b=17),this.KCa=this.mj,this.KCa+=b),this.xb(!0),this.Hg(),this.pa(a.g.j))};k.j_c=function(){return this.mh};k.Hrd=function(b){this.mh!=b&&(this.mh=b,this.$Ba(32767,32767),b=0,this.fW()==a.Jw.jla&&(this.P0()&&this.bL()==a.$C.Z2a&&(b=17),this.JCa=this.mh,this.JCa+=b),this.xb(!0),this.Hg(),
this.pa(a.g.j))};k.Yg=function(){var b=0,b=this.lj;this.P0()&&this.bL()==a.$C.X2a&&(b+=17);return b};k.Rf=function(){var b=0,b=this.lh;this.P0()&&this.bL()==a.$C.Y2a&&(b+=17);return b};k.Ug=function(){var b=0,b=this.mj;this.P0()&&this.bL()==a.$C.qMa&&(b+=17);return b};k.If=function(){var b=0,b=this.mh;this.P0()&&this.bL()==a.$C.Z2a&&(b+=17);return b};k.zf=function(){return 0!=(this.fg&a.rj.zkb)?!0:!1};k.ai=function(b){b=this.fg&~a.rj.zkb|(b?a.rj.zkb:0);this.fg!=b&&(this.fg=b,this.Cd(a.ea.xKa),this.pa(a.g.j))};
k.k0c=function(){return 0!=(this.fg&a.rj.ykb)?!0:!1};k.Lee=function(b){b=this.fg&~a.rj.ykb|(b?a.rj.ykb:0);this.fg!=b&&(this.fg=b)};k.VZd=function(){return 17};k.Uja=function(){return this};k.l0c=function(){var e=null;if(this.P0()){var f=this.Uja();null==f.$F()&&(null==this.bQ&&(d.Pb("PRIM_PPNL"),this.bQ=new c.Nx),f.lA(this.bQ),f.$F().za(this,a.Q.az,this.cOc),this.Ppc());e=this.zZ}else f=this.Uja(),null!=f.$F()&&(f.$F().za(this,a.Q.az,null),f.lA(null)),b.ga(this.zZ),this.zZ=null;return e};k.rb=function(){if(null==
this.pb){var b=this.oqa;this.eU||0!=(this.fg&a.rj.F_b)?(b.d5a(!1),this.ZBa(b),b.S7(this.eJa()),b.d5a(!this.eJa())):b.d5a(!0);this.vJ(this.pb,b);this.pb=b}return this.pb};k.Cx=function(){return null};k.HR=function(){var a=null;this.hf()&&(a=this.hf().ha);return a};k.iba=function(){var a=null;this.Cx()&&(a=this.Cx().Dh());return a};k.$ma=function(b){this.Cx()&&this.Cx().Dh()!=b&&(this.Cx().Jb(b),this.m(a.g.j))};k.uba=function(){var a=null;this.HR()&&(a=this.HR().Dh());return a};k.dna=function(b){this.HR()&&
this.HR().Dh()!=b&&(this.HR().Jb(b),this.m(a.g.j))};k.fYa=function(){var a=null;this.Cx()&&(a=this.Cx().np());return a};k.U4a=function(b){this.Cx()&&this.Cx().np()!=b&&(this.Cx().yp(b),this.m(a.g.j))};k.dYa=function(){var a=null;this.Cx()&&(a=this.Cx().YA());return a};k.T4a=function(b){this.Cx()&&this.Cx().YA()!=b&&(this.Cx().OG(b),this.m(a.g.j))};k.sYa=function(){var a=null;this.HR()&&(a=this.HR().np());return a};k.l5a=function(b){this.HR()&&this.HR().np()!=b&&(this.HR().yp(b),this.m(a.g.j))};k.lua=
function(){null==this.DMb&&(this.DMb=new c.Lw(this.Cx(),a.bh.o1));return this.DMb};k.gYa=function(){null==this.CMb&&(this.CMb=new c.Lw(this.Cx(),a.bh.n1));return this.CMb};k.eYa=function(){null==this.BMb&&(this.BMb=new c.Lw(this.Cx(),a.bh.cda));return this.BMb};k.uYa=function(){null==this.zNb&&(this.zNb=new c.Lw(this.HR(),a.bh.o1));return this.zNb};k.tYa=function(){null==this.yNb&&(this.yNb=new c.Lw(this.HR(),a.bh.n1));return this.yNb};k.SXc=function(){return this.uDa};k.oqd=function(b){this.uDa!=
b&&(this.uDa=b,this.OPa(),this.pa(a.g.j))};k.pZc=function(){return this.MDa};k.rrd=function(b){this.MDa!=b&&(this.MDa=b,this.OPa(),this.pa(a.g.j))};k.Lu=function(){return this.zf()};k.i4d=function(){return this.Yd()};k.P0=function(){return this.Nba()?this.E_a()?!0:this.k0c():!1};k.E_a=function(){return!1};k.j4d=function(){var b=!1;this.fW()==a.Jw.Aca&&this.bL()==a.$C.Y2a?b=!0:this.fW()==a.Jw.hla&&this.bL()==a.$C.qMa&&(b=!0);return b};k.k4d=function(){var b=!1;this.fW()==a.Jw.jla&&this.bL()==a.$C.Z2a?
b=!0:this.fW()==a.Jw.Vka&&this.bL()==a.$C.X2a&&(b=!0);return b};k.N_=function(){return 0!=(this.fg&a.rj.tkb)?!0:!1};k.Ida=function(b){b=this.fg&~a.rj.tkb|(b?a.rj.tkb:0);this.fg!=b&&(this.fg=b,this.$h(),this.pa(a.g.j))};k.pm=function(){return 0!=(this.fg&a.rj.VWa)?!0:!1};k.po=function(b){b=this.fg&~a.rj.VWa|(b?a.rj.VWa:0);this.fg!=b&&(this.fg=b,this.$h(),this.pa(a.g.j))};k.Wj=function(){return 0!=(this.fg&a.rj.Ckb)?!0:!1};k.Xm=function(b){b=this.fg&~a.rj.Ckb|(b?a.rj.Ckb:0);this.fg!=b&&(this.fg=b,this.$h(),
this.pa(a.g.j))};k.Hx=function(){return 0!=(this.fg&a.rj.Dkb)?!0:!1};k.Wu=function(b){b=this.fg&~a.rj.Dkb|(b?a.rj.Dkb:0);this.fg!=b&&(this.fg=b,this.$h(),this.pa(a.g.j))};k.sd=function(){return 0!=(this.fg&a.rj.Ekb)?!0:!1};k.Ef=function(b){b=this.fg&~a.rj.Ekb|(b?a.rj.Ekb:0);this.fg!=b&&(this.fg=b,this.$h(),this.pa(a.g.j))};k.Nba=function(){return 0!=(this.fg&a.rj.Bkb)?!0:!1};k.Vza=function(b){b=this.fg&~a.rj.Bkb|(b?a.rj.Bkb:0);this.fg!=b&&(this.fg=b,this.$h(),this.pa(a.g.j))};k.oZc=function(){return 0!=
(this.fg&a.rj.xkb)?!0:!1};k.qrd=function(b){var c=this.fg&~a.rj.xkb|(b?a.rj.xkb:0);this.fg!=c&&(this.fg=c,this.hf().Gsc(b),this.pa(a.g.j))};k.CIa=function(){return 0!=(this.fg&a.rj.WWa)?!0:!1};k.FDb=function(b){b=this.fg&~a.rj.WWa|(b?a.rj.WWa:0);this.fg!=b&&(this.fg=b,this.SEd(),this.pa(a.g.j))};k.eJa=function(){return 0!=(this.fg&a.rj.XWa)?!0:!1};k.wud=function(b){if(this.eJa()!=b){var c=null!=this.pb;this.S7(b);this.yma();c&&this.rb();this.$h();this.pa(a.g.j)}};k.S7=function(b){b=this.fg&~a.rj.XWa|
(b?a.rj.XWa:0);this.fg!=b&&(this.fg=b,this.pa(a.g.j))};k.cj=function(){return(this.uo&a.NK.x_b)>>24};k.Zk=function(b){b=this.uo&~a.NK.x_b|b<<24;this.uo!=b&&(this.uo=b,this.$h(),this.pa(a.g.j))};k.Tg=function(){return(this.uo&a.NK.u_b)>>20};k.Oj=function(b){b=this.uo&~a.NK.u_b|b<<20;this.uo!=b&&(this.uo=b,this.$h(),this.pa(a.g.j))};k.tm=function(){return(this.fg&a.rj.C_b)>>12};k.qo=function(b){b=this.fg&~a.rj.C_b|b<<12;this.fg!=b&&(this.fg=b,this.$h(),this.pa(a.g.j))};k.YF=function(){return b.sS()};
k.YYa=function(){return this.wu};k.$da=function(b){this.wu!=b&&(null!=this.wu&&(this.wu.vb(),this.wu.Ha(this)),this.wu=b,null!=this.wu&&(this.wu.Ba(),this.wu.Ia(this,this.qWa)),this.Ppc(),this.Hg(),this.pa(a.g.j))};k.hOa=function(b){this.qC!=b&&(null!=this.qC&&this.qC.Ha(this),this.qC.tk(b),null!=this.qC&&this.qC.Ia(this,this.IQc),this.qk(!0),this.pa(a.g.j))};k.Job=function(){return this.qC};k.ug=function(b){this.pv!=b&&(this.pv=b,this.hf()&&this.hf().ug(b),this.Hg(),this.pa(a.g.j))};k.Qe=function(){return this.pv};
k.kb=function(){return this.rb().kb()};k.ob=function(a){this.rb().ob(a)};k.De=function(){this.Ga(a.Q.Ah)};k.hQd=function(){};k.H0=function(){this.Uv(this,a.ea.Dtb)};k.ZSb=function(){this.lua().Ru(s)};k.Mrc=function(){null==s&&(s=new c.yb,s.er(a.o.eJ),s.fr(2),s.uq(2),s.Mo(2),s.No(2));this.lua().si(s)};k.YZ=function(){return this};k.SEd=function(){this.zZ&&this.zZ.Oe(this.CIa())};k.Ppc=function(){var a=this.wu;null==a&&(a=b.ba().Qua());this.zZ&&this.zZ.zd(a);this.Uja().nJ(a)};k.kf=function(){var a=
this.l0c();if(a){var b=this.aed();a.sb(b)}this.hf()&&(a=this.Dkd(),this.RPa(),this.hf().sb(a))};k.RPa=function(){var b=this.iIa(),c=this.hf();if(c){c.tb(b);c.Og(this.re());switch(this.U2b()){case a.X0.ika:c.Wb(a.yh.Y$);break;case a.X0.RZa:c.Wb(a.yh.zK);break;case a.X0.QZa:c.Wb(a.yh.uC)}switch(this.V2b()){case a.Y0.WBa:c.Po(a.dh.cY);break;case a.Y0.W8a:c.Po(a.dh.jM);break;case a.Y0.xJb:c.Po(a.dh.zq)}}};k.hf=function(){null==this.be&&this.Yd()&&(d.Pb("PRIM_LABL"),this.be=new c.Mw,this.be.Oa(this),this.be.Ef(!1),
this.be.Oe(!1),this.be.vq(!1),this.be.ug(this.Qe()),this.be.ve(5),this.Xb()&&this.be.hh());return this.be};k.eua=function(){return b.sS()};k.aed=function(){var b=this.eua(),d;switch(this.bL()){case a.$C.fgd:d=new c.qa(b.aa(),b.$(),0,0);break;case a.$C.Y2a:d=new c.qa(b.aa()-17,b.$(),17,b.la());break;case a.$C.qMa:d=new c.qa(b.Ka(),b.$(),17,b.la());break;case a.$C.Z2a:d=new c.qa(b.aa(),b.$()-17,b.ja(),17);break;case a.$C.X2a:d=new c.qa(b.aa(),b.Fa(),b.ja(),17)}return d};k.yma=function(){var a=this.pb;
this.pb=null;this.vJ(a,null)};k.ZBa=function(a){this.eJa()&&null==a.Yy()&&this.S7(!1)};k.vJ=function(){};k.gp=function(b,c,d,e,n){if(d==a.Q.iB||d==a.Q.mB||d==a.Q.BG||d==a.Q.CG||d==a.Q.XI||this.Yd()&&d==a.Q.Mq)return n;b==this.zZ&&d==a.Q.sc&&(this.we().lI()!=this.zZ||this.CIa()||this.we().PE(this),this.Qud(),n=!0);return k.k.gp.call(this,b,c,d,e,n)};k.Lz=function(){var a=null;this.fB()&&this.$N()&&(a=this);return a};k.$Ba=function(a,c){this.lh=b.Lf(this.lh,-a,a);a=0<=this.lh?a-this.lh:a+this.lh;this.mj=
b.Lf(this.mj,-a,a);this.mh=b.Lf(this.mh,-c,c);c=0<=this.mh?c-this.mh:c+this.mh;this.lj=b.Lf(this.lj,-c,c)};k.jma=function(){this.RPa();k.k.jma.call(this)};k.fma=function(){this.RPa();k.k.fma.call(this)};k.Msa=function(){var a=this.yw();return a&&(a=a.rv)?new c.axa(a):null};k.Dd=function(){this.VM(a.tc.jS,this.dS());k.k.Dd.call(this)};k.OPa=function(){};k.cOc=function(a,b){this.kXa();b.rk("CONTINUE",!1)};k.IQc=function(b,c){c.fb==a.g.Vb?this.hOa(null):c.fb==a.g.j&&this.qk(!0)};k.qWa=function(b,c){switch(c.fb){case a.g.Cb:case a.g.Vb:c.Cj==
this.wu&&this.$da(null);break;case a.g.j:c.Cj==this.wu&&this.Hg()}};k.cjb=k[a.ea.xKa]=function(){this.$h()};k.wXb=k[a.ea.Dtb]=function(){var a=null!=this.pb;this.yma();a&&this.rb();this.$h()};k.zC=k[a.ea.kS]=function(a){this.Un()||this.rHa();k.k.zC.call(this,a)};k.AC=k[a.ea.lS]=function(a){var b=a.$c;this.wia();b.lg()&&k.k.AC.call(this,a)};k.mPc=k[a.ea.m$b]=function(a){this.P0()&&(this.Qud(),a.Tf=!0)};k.kR=k[a.ea.xE]=function(){this.xb();this.Hg()};k.IGa=k[a.ea.AKa]=function(b){var c=!1,d="";switch(this.Zmb()){case a.Mm.OF:case a.Mm.s4:case a.Mm.nGa:this.rb().uda(this.Zmb(),
a.X5.Wpb,d);break;case a.Mm.eN:d=this.VK()}""!=d&&(b.od.eb=d,c=!0);c||k.k.IGa.call(this,b)};d.Ld(c.vca,"PRIM_EVP",{vC:"PRIM_CTRL",Aa:{Placeholder:{a:k.QYa,f:function(a){this.Vda(d.ka(a))}},UsePicklist:{a:k.eJa,f:function(a){this.wud(d.Ca(a))}},LabelSelectable:{a:k.oZc,f:function(a){this.qrd(d.Ca(a))}},MarginLeft:{a:k.h_c,f:function(a){this.$rc(d.O(a))}},MarginTop:{a:k.j_c,f:function(a){this.Hrd(d.O(a))}},MarginBottom:{a:k.g_c,f:function(a){this.Crd(d.O(a))}},MarginRight:{a:k.i_c,f:function(a){this.Frd(d.O(a))}},
Caption:{a:k.ab,f:function(a){this.tb(d.ka(a))}},HintType:{a:k.Zmb,f:k.Hrc},LabelType:{a:function(){return d.wa(this.mnb(),a.Mm.G)},f:function(b){this.srd(d.va(b,a.Mm.G))}},LabelText:{a:k.iIa},LabelPosition:{a:function(){return d.wa(this.fW(),a.Jw.G)},f:function(b){this.prd(d.va(b,a.Jw.G))}},LabelHorAlignment:{a:function(){return d.wa(this.U2b(),a.X0.G)},f:function(b){this.ord(d.va(b,a.X0.G))}},LabelVerAlignment:{a:function(){return d.wa(this.V2b(),a.Y0.G)},f:function(b){this.trd(d.va(b,a.Y0.G))}},
ReadOnly:{a:k.zf,f:function(a){this.ai(d.Ca(a))}},Ellipses:{a:k.Qe,f:k.ug},EditThemeDrawStyle:{a:k.SXc,f:function(a){this.oqd(d.ka(a))}},LabelThemeDrawStyle:{a:k.pZc,f:function(a){this.rrd(d.ka(a))}}}});var e=k;e.aD=e.applyDefault=function(){this.rb().Z$()}});
