window.LANSA.addSrc("gpbx",function(d,c,a,b){a.lSc={Vje:0,Uje:9,jHd:6,Wje:5,Xje:10};a.c3c={AUc:0};c.Ofc=function(){p.K.call(this);this.AMb=a.lSc.jHd;this.zM=a.c3c.AUc;this.DQ=new c.qa;new c.qa;this.Ed=this.Ed|a.tc.Kka|a.tc.jKa|a.tc.Tsb|a.tc.MI|a.tc.U0|a.tc.LI;this.Sc=this.Sc|a.Wd.iS|a.Wd.T0;this.Oe(!1)};var p=c.u(c.Ofc,c.sL);p.Ae=function(){return c.Qjc};p.hee=function(b){this.AMb!=b&&(this.AMb=b,this.m(a.g.j),this.Sy())};p.VVd=function(){return this.AMb};p.$s=function(a){p.k.$s.call(this,a);this.cfd()};
p.BIb=function(){if(this.Xb()){var a=this.xe(),a=Math.abs(a.Na()),d=this.vf();this.Yd();this.Yd();d.Za(d.aa()+a);new c.qa;""==this.ab()?(d.Va(d.aa()),d.Ja(a)):(this.ab(),d.Va(d.aa()+this.nN()),d.Ja(this.jja()),d.Va(d.Ka()+a));b.Xk(this.DQ,d)||(this.DQ=d,this.xb());this.$s(!0)}};p.kf=function(a){a.Xa(a.$()+this.DQ.la());a.Za(a.aa()+4);a.Va(a.Ka()-4);a.Ja(a.Fa()-4);p.k.kf.call(this,a)};p.gid=function(a,b,c){a.Xa(a.$()+this.DQ.la());a.Za(a.aa()+4);a.Va(a.Ka()-4);a.Ja(a.Fa()-4);p.k.gid.call(this,a,b,
c)};p.Sk=function(){p.k.Sk.call(this);this.Cd(a.ea.xE)};p.Dd=function(){var b=this.dS()||this.pn()&&(this.j6()||this.QW());this.VM(a.tc.jS,b);p.k.Dd.call(this)};p.cJ=function(a){var b=!1,b=a.yc().F3a(this,this.ha.qh,this.j6(),this.QW(),a);!1==b&&p.k.cJ.call(this,a)};p.w1=function(a){var b=!1;null!=a.yc()&&a.ma().pn()&&(b=a.yc().G3a(this,this.ha.qh,a,this.j6(),this.QW()));!1==b&&p.k.w1.call(this,a)};p.Ne=function(b){""==b[1]&&(b[1]=a.H$b);p.k.Ne.call(this,b)};p.cfd=function(){var a=this.vf(),a=this.xC(a,
null),c=this.vf();c.Xa(c.$()+this.DQ.la()/2+1);c.Za(c.aa()+2);c.Va(c.Ka()-2);c.Ja(c.Fa()-2);var d=this.Ta().$a(),k=this.ab();b.me[d].ei(k,c,this.DQ);b.ga(a)};p.Fv=p[a.ea.oL]=function(a){this.BIb();p.k.Fv.call(this,a)};p.Ev=p[a.ea.NI]=function(){p.k.Ev.call(this);this.BIb()};p.kR=p[a.ea.xE]=function(){this.BIb();this.Sy()};p.RPc=p[a.ea.wtb]=function(){this.$h()};d.Ld(c.Ofc,"PRIM_GPBX",{Aa:{Caption:{a:p.ab,f:function(a){this.tb(d.ka(a))}},ThemeStyle:{a:function(){return d.wa(this.UR(),a.by.G)},f:function(b){this.cOa(d.va(b,
a.by.G))}}}});c.Qjc=function(a){t.K.call(this,a);this.eb=this.G9a=this.nQa=this.Ke=this.jd=null};var t=c.u(c.Qjc,c.xL);t.Gd=function(a,b){var c=null;t.k.Gd.call(this,a,b);this.G9a=4;this.jd=document.createElement("div");this.Ke=document.createElement("div");this.nQa=document.createElement("div");this.eb=document.createElement("span");this.v.appendChild(this.jd);this.v.appendChild(this.Ke);this.v.appendChild(this.nQa);this.v.appendChild(this.eb);this.Hqb(this.jd,this.G9a);this.Hqb(this.Ke,0);this.Hqb(this.nQa,
0);c=this.jd.style;c.borderTopWidth="0px";c=this.Ke.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.nQa.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.eb.style;c.position="absolute";c.whiteSpace="nowrap";c.cursor="inherit";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";return this.v};t.Hqb=function(a,b){var c=a.style;c.position="absolute";
c.overflowX="hidden";c.overflowY="hidden";c.whiteSpace="nowrap";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.outline="none";c.background="rgba(0,0,0,0)";c.borderTopWidth="1px";c.borderBottomWidth="1px";c.borderLeftWidth="1px";c.borderRightWidth="1px";c.borderTopLeftRadius=b+"px";c.webkitBorderTopLeftRadius=b+"px";c.borderTopRightRadius=b+"px";c.webkitBorderTopRightRadius=b+"px";c.borderBottomLeftRadius=b+"px";c.webkitBorderBottomLeftRadius=
b+"px";c.borderBottomRightRadius=b+"px";c.webkitBorderBottomRightRadius=b+"px"};t.ei=function(a,b,c){var d=this.jd.style;d.left=b.aa()+"px";d.top=b.$()+"px";d.width=b.ja()+"px";d.height=b.la()+"px";d.borderColor=this.Rn();d=this.Ke.style;d.left=b.aa()+this.G9a-1+"px";d.top=b.$()+"px";d.width=c.aa()-b.aa()+"px";d.height="1px";d.borderColor=this.Rn();d=this.nQa.style;d.left=c.Ka()+2+"px";d.top=b.$()+"px";d.width=b.Ka()-this.G9a-c.Ka()+"px";d.height="1px";d.borderColor=this.Rn();d=this.eb.style;d.left=
c.aa()+7+"px";d.top=c.$()+2+"px";d.height=c.la()+"px";d.width=c.ja()+"px";this.eb.textContent=a}});
