LANSA.addComponent({id:"BPFAPP004",nm:"BPFEmailSettingsDataClient",ot:"rp",tp:"Reusable Part",pt:"ap",de:"Data Model Client for Email Settings",tl:15000300},function(l,oI,u){var cL="ENG";var Fd={F1:{nm:"BPFFLD013",an:"BPFCodeGroup",ft:"NV",ln:128,dc:0,lb:"Codes Group Nam",h1:"Codes",h2:"Group",h3:"Name",de:"Codes Group Name",dv:"",ia:["FE","LC"]},F2:{nm:"BPFFLD014",an:"BPFCodeName",ft:"NV",ln:256,dc:0,lb:"Code Table Name",h1:"Code",h2:"Table",h3:"Name",de:"Code Table Name",dv:"",ia:["FE","LC"]},F3:
{nm:"BPFFLD015",an:"BPFCodeSequence",ft:"P",ln:7,dc:0,lb:"Code Sequence",h1:"Code",h2:"Sequence",h3:"",de:"Code Sequence",dv:0,ia:["FE","RB"]},F4:{nm:"BPFFLD016",an:"BPFCodeAlphaValue",ft:"NV",ln:2048,dc:0,lb:"Codes Alpha Val",h1:"Codes",h2:"Alpha",h3:"Value",de:"Codes Alpha Value",dv:"",ia:["ASQN","LC"]},F5:{nm:"BPFFLD017",an:"BPFCodeNumericValue",ft:"S",ln:15,dc:0,lb:"Codes Numeric V",h1:"Codes",h2:"Numeric",h3:"Value",de:"Codes Numeric Value",dv:0,ia:["FE","RB"]},F6:{nm:"BPFFLD018",an:"BPFCodeDescription",
ft:"NV",ln:4096,dc:0,lb:"Code Descriptio",h1:"Code",h2:"Description",h3:"",de:"Code Description",dv:"",ia:["ASQN","LC"]},F7:{nm:"STATUS",an:"Status",ft:"A",ln:256,dc:0,lb:"Generic Status",h1:"Generic",h2:"Status",h3:"Field",de:"Generic Status Field",dv:"",ia:["FE","LC"]}};var cO=l.rC(oI,{an:"PRIM_OBJT",fd:Fd,pt:{ControlSettings:{da:"r"},SMTPSettings:{da:"r"},Templates:{da:"r"},Template:{da:"na"}},mt:{LoadControlSettings:{},LoadSMTPSettings:{},SaveSMTPSettings:{},SendTest:{ps:{"TestAddress":{pt:"i"
}}},LoadEmailTemplates:{ps:{"ForIsoCode":{pt:"i"}}},LoadEmailTemplate:{ps:{"ForIsoCode":{pt:"i"},"TemplateID":{pt:"i"}}}},ev:{OnLoadControlSettingsCompleted:{},OnLoadControlSettingsFailed:{},OnLoadSMTPSettingsCompleted:{},OnLoadSMTPSettingsFailed:{},OnSaveSMTPSettingsCompleted:{},OnSaveSMTPSettingsFailed:{},OnTestSendCompleted:{},OnTestSendFailed:{},OnLoadEmailTemplatesCompleted:{},OnLoadEmailTemplatesFailed:{},OnLoadEmailTemplateCompleted:{},OnLoadEmailTemplateFailed:{}},co:function(){cO.aN.call(this);
var f=this.aF("BPFAPP004",Fd);var C0=this.cR("CONTROLSETTINGS","PRIM_LCOL");var C1=this.cR("SMTPSETTINGS","PRIM_LCOL");var C2=this.cR("TEMPLATES","PRIM_LCOL");C0.setCollects("BPFCLS008");C0.iC();C1.setCollects("BPFCLS009");C1.iC();C2.setCollects("BPFCLS010");C2.iC();C0.aLF({"BPFFLD013":f.F1,"BPFFLD014":f.F2,"BPFFLD015":f.F3,"BPFFLD016":f.F4,"BPFFLD017":f.F5});C1.aLF({"BPFFLD013":f.F1,"BPFFLD014":f.F2,"BPFFLD015":f.F3,"BPFFLD016":f.F4,"BPFFLD017":f.F5,"BPFFLD018":f.F6});C2.aLF({"BPFFLD013":f.F1,"BPFFLD016":f.F4});
}});cO.mthGETTEMPLATE=function(p1){var m=this.REF,r=l.pR(this,cO,"GetTemplate",41);var P0=r.cPD("PROPERTY");var P1=r.cP("KEY","PRIM_ALPH");P1.set(p1);r.ln=41;{r.ln=45;{var l1=m.TEMPLATES.cI();while(l1.step()){var ITEM=r.sR("ITEM",l1.item());r.ln=47;if(l.s.ne(l.s.UpperCase(ITEM.getTEMPLATEID()),l.s.UpperCase(P1.get()))){continue;}r.ln=49;P0=r.sR("P0",ITEM);r.ln=51;break;r.ln=53;}l1.end();r.dR("ITEM");}}r.ln=55;return r.rR(P0);};cO.mthLOADCONTROLSETTINGS=function(){var f=this.FLD.BPFAPP004,m=this.REF,r=l.mR(this,cO,"LoadControlSettings",62),mth=r;
var C0=r.cDR("REQUEST","BPFSVR004","GETCONTROLSETTINGS");C0.iC();C0.aH("COMPLETED",this,e1);C0.aH("FAILED",this,e2);r.ln=62;{r.ln=68;C0.mthEXECUTEASYNC({},{FLD:{"BPFFLD007":f.F7},LIST:{"CODESGROUP":m.CONTROLSETTINGS}});}r.ln=91;r.e();function e1(sender,Ps){var r=l.eR(this,cO,"#Request.Completed",70,mth);r.ln=70;{r.ln=72;if(l.s.eq(f.F7.get(),"OK")){r.ln=74;this.fE("ONLOADCONTROLSETTINGSCOMPLETED");}else{r.ln=78;this.fE("ONLOADCONTROLSETTINGSFAILED");}}r.ln=82;r.e();}function e2(sender,Ps){var r=l.eR(this,cO,"#Request.Failed",84,mth);
var P0=Ps.r("HANDLED");var P1=Ps.r("REASON");r.ln=84;{r.ln=86;P0.set(true);r.ln=87;this.fE("ONLOADCONTROLSETTINGSFAILED");}r.ln=89;r.e();}};cO.mthLOADSMTPSETTINGS=function(){var f=this.FLD.BPFAPP004,m=this.REF,r=l.mR(this,cO,"LoadSMTPSettings",94),mth=r;var C0=r.cDR("REQUEST","BPFSVR004","GETSMTPSETTINGS");C0.iC();C0.aH("COMPLETED",this,e3);C0.aH("FAILED",this,e4);r.ln=94;{r.ln=100;C0.mthEXECUTEASYNC({},{FLD:{"BPFFLD007":f.F7},LIST:{"CODESGROUP":m.SMTPSETTINGS}});}r.ln=123;r.e();function e3(sender,Ps)
{var r=l.eR(this,cO,"#Request.Completed",102,mth);r.ln=102;{r.ln=104;if(l.s.eq(f.F7.get(),"OK")){r.ln=106;this.fE("ONLOADSMTPSETTINGSCOMPLETED");}else{r.ln=110;this.fE("ONLOADSMTPSETTINGSFAILED");}}r.ln=114;r.e();}function e4(sender,Ps){var r=l.eR(this,cO,"#Request.Failed",116,mth);var P0=Ps.r("HANDLED");var P1=Ps.r("REASON");r.ln=116;{r.ln=118;P0.set(true);r.ln=119;this.fE("ONLOADSMTPSETTINGSFAILED");}r.ln=121;r.e();}};cO.mthSAVESMTPSETTINGS=function(){var f=this.FLD.BPFAPP004,m=this.REF,r=l.mR(this,cO,"SaveSMTPSettings",125),mth=r;
var C0=r.cDR("REQUEST","BPFSVR004","SETSMTPSETTINGS");C0.iC();C0.aH("COMPLETED",this,e5);C0.aH("FAILED",this,e6);r.ln=125;{r.ln=131;C0.mthEXECUTEASYNC({LIST:{"CODESGROUP":m.SMTPSETTINGS}},{FLD:{"BPFFLD007":f.F7}});}r.ln=154;r.e();function e5(sender,Ps){var r=l.eR(this,cO,"#Request.Completed",133,mth);r.ln=133;{r.ln=135;if(l.s.eq(f.F7.get(),"OK")){r.ln=137;this.fE("ONSAVESMTPSETTINGSCOMPLETED");}else{r.ln=141;this.fE("ONSAVESMTPSETTINGSFAILED");}}r.ln=145;r.e();}function e6(sender,Ps){var r=l.eR(this,cO,"#Request.Failed",147,mth);
var P0=Ps.r("HANDLED");var P1=Ps.r("REASON");r.ln=147;{r.ln=149;P0.set(true);r.ln=150;this.fE("ONSAVESMTPSETTINGSFAILED");}r.ln=152;r.e();}};cO.mthSENDTEST=function(p0){var f=this.FLD.BPFAPP004,r=l.mR(this,cO,"SendTest",156),mth=r;var P0=r.cP("TESTADDRESS","PRIM_ALPH");P0.set(p0);var C0=r.cDR("REQUEST","BPFSVR004","SENDTESTEMAIL");C0.iC();C0.aH("COMPLETED",this,e7);C0.aH("FAILED",this,e8);r.ln=156;{r.ln=163;C0.mthEXECUTEASYNC({FLD:{"ALPHAVALUE":P0.get()}},{FLD:{"BPFFLD007":f.F7}});}r.ln=186;r.e();
function e7(sender,Ps){var r=l.eR(this,cO,"#Request.Completed",165,mth);r.ln=165;{r.ln=167;if(l.s.eq(f.F7.get(),"OK")){r.ln=169;this.fE("ONTESTSENDCOMPLETED");}else{r.ln=173;this.fE("ONTESTSENDFAILED");}}r.ln=177;r.e();}function e8(sender,Ps){var r=l.eR(this,cO,"#Request.Failed",179,mth);var P1=Ps.r("HANDLED");var P2=Ps.r("REASON");r.ln=179;{r.ln=181;P1.set(true);r.ln=182;this.fE("ONTESTSENDFAILED");}r.ln=184;r.e();}};cO.mthLOADEMAILTEMPLATES=function(p0){var f=this.FLD.BPFAPP004,m=this.REF,r=l.mR(this,cO,"LoadEmailTemplates",189),mth=r;
var P0=r.cP("FORISOCODE","PRIM_DC","UnicodeString");P0.set(p0);var C0=r.cDR("REQUEST","BPFSVR004","GETEMAILTEMPLATES");C0.iC();C0.aH("COMPLETED",this,e9);C0.aH("FAILED",this,e10);r.ln=189;{r.ln=196;C0.mthEXECUTEASYNC({FLD:{"BPFFLD081":P0.get()}},{FLD:{"BPFFLD007":f.F7},LIST:{"CODESGROUP":m.TEMPLATES}});}r.ln=219;r.e();function e9(sender,Ps){var r=l.eR(this,cO,"#Request.Completed",198,mth);r.ln=198;{r.ln=200;if(l.s.eq(f.F7.get(),"OK")){r.ln=202;this.fE("ONLOADEMAILTEMPLATESCOMPLETED");}else{r.ln=206;
this.fE("ONLOADEMAILTEMPLATESFAILED");}}r.ln=210;r.e();}function e10(sender,Ps){var r=l.eR(this,cO,"#Request.Failed",212,mth);var P1=Ps.r("HANDLED");var P2=Ps.r("REASON");r.ln=212;{r.ln=214;P1.set(true);r.ln=215;this.fE("ONLOADEMAILTEMPLATESFAILED");}r.ln=217;r.e();}};cO.mthLOADEMAILTEMPLATE=function(p0,p1){var f=this.FLD.BPFAPP004,m=this.REF,r=l.mR(this,cO,"LoadEmailTemplate",221),mth=r;var P0=r.cP("FORISOCODE","PRIM_DC","UnicodeString");var P1=r.cP("TEMPLATEID","PRIM_ALPH");P0.set(p0);P1.set(p1);
var C0=r.cDR("REQUEST","BPFSVR004","GETEMAILTEMPLATE");C0.iC();C0.aH("COMPLETED",this,e11);C0.aH("FAILED",this,e12);r.ln=221;{r.ln=229;C0.mthEXECUTEASYNC({FLD:{"BPFFLD081":P0.get(),"CODEGROUP":P1.get()}},{FLD:{"BPFFLD007":f.F7},LIST:{"CODESGROUP":m.TEMPLATES}});}r.ln=252;r.e();function e11(sender,Ps){var r=l.eR(this,cO,"#Request.Completed",231,mth);r.ln=231;{r.ln=233;if(l.s.eq(f.F7.get(),"OK")){r.ln=235;this.fE("ONLOADEMAILTEMPLATECOMPLETED");}else{r.ln=239;this.fE("ONLOADEMAILTEMPLATESFAILED");}
}r.ln=243;r.e();}function e12(sender,Ps){var r=l.eR(this,cO,"#Request.Failed",245,mth);var P2=Ps.r("HANDLED");var P3=Ps.r("REASON");r.ln=245;{r.ln=247;P2.set(true);r.ln=248;this.fE("ONLOADEMAILTEMPLATEFAILED");}r.ln=250;r.e();}};cO.getCONTROLSETTINGS=function(){return this.REF.CONTROLSETTINGS;};cO.getSMTPSETTINGS=function(){return this.REF.SMTPSETTINGS;};cO.getTEMPLATES=function(){return this.REF.TEMPLATES;};cO.getTEMPLATE=function(KEY_1){return this.mthGETTEMPLATE(KEY_1);};},{rp:["PRIM_OBJT","PRIM_LCOL","PRIM_WEB.DataRequest","PRIM_FLD"],
dc:["BPFCLS008","BPFCLS009","BPFCLS010"]});