LANSA.addComponent({id:"BPFAVW008",nm:"BPFUserActivityDownloadView",ot:"wv",tp:"View",pt:"ap",de:"Portal Download User Activity Data",tl:15000300},function(l,oI,u){var cO=l.rC(oI,{an:"PRIM_VIEW",mt:{BuildOptions:{}},co:function(){cO.aN.call(this);var C0=this.cA("SESSION","BPFAPP002");var C1=this.cA("NAVIGATE","BPFAPP001");var C2=this.cR("STRINGS","BPFVLR008");var C3=this.cR("ROUNDEDCORNERSTYLE","PRIM_VS","Style");var C4=this.cR("NAVIGATIONLINKSTYLE","PRIM_VS","Style");var C5=this.cR("MAINLAYOUT","PRIM_TBLO");
var C6=this.cR("LAYOUTCOLUMN1","PRIM_TBLO","Column");var C7=this.cR("LAYOUTCOLUMN2","PRIM_TBLO","Column");var C8=this.cR("LAYOUTCOLUMN3","PRIM_TBLO","Column");var C9=this.cR("LAYOUTCOLUMN4","PRIM_TBLO","Column");var C10=this.cR("LAYOUTCOLUMN5","PRIM_TBLO","Column");var C11=this.cR("LAYOUTROW1","PRIM_TBLO","Row");var C12=this.cR("LAYOUTROW2","PRIM_TBLO","Row");var C13=this.cR("MAINLAYOUTITEM1","PRIM_TBLO","Item");var C14=this.cR("MAINLAYOUTITEM2","PRIM_TBLO","Item");var C15=this.cR("MAINLAYOUTITEM3","PRIM_TBLO","Item");
var C16=this.cR("CONTROLLAYOUT","PRIM_TBLO");var C17=this.cR("LAYOUT1ROW1","PRIM_TBLO","Row");var C18=this.cR("LAYOUT1ROW2","PRIM_TBLO","Row");var C19=this.cR("CONTROLCOLUMN1","PRIM_TBLO","Column");var C20=this.cR("CONTROLCOLUMN2","PRIM_TBLO","Column");var C21=this.cR("CONTROLCOLUMN3","PRIM_TBLO","Column");var C22=this.cR("LAYOUT1ITEM1","PRIM_TBLO","Item");var C23=this.cR("CONTROLLAYOUTITEM1","PRIM_TBLO","Item");var C24=this.cR("CONTROLLAYOUTITEM2","PRIM_TBLO","Item");var C25=this.cR("PANELHEADING","PRIM_MD","Label");
var C26=this.cR("INSTRUCTIONTEXT","PRIM_MD","Label");var C27=this.cR("CONTROLPANEL","PRIM_PANL");var C28=this.cR("TIMERANGEDROPDOWN","PRIM_MD","Dropdown");var C29=this.cR("PANELACTION","PRIM_MD","FlatButton");var C30=this.cR("DIVIDER","PRIM_PANL");this.cD("CURRENTUSER");if((C0!=null)&&(C0.iI()==false)){C0.iC();}if((C1!=null)&&(C1.iI()==false)){C1.iC();}C2.iC();C3.setCornerBottomLeft(8);C3.setCornerBottomRight(8);C3.setCornerTopLeft(8);C3.setCornerTopRight(8);C3.setBorderLeft(1);C3.setBorderTop(1);
C3.setBorderRight(1);C3.setBorderBottom(1);C3.iC();C4.setCursor("HAND");C4.iC();C5.setMarginTop(24);C5.iC();C6.setDisplayPosition(1);C6.setParent(C5);C6.setMinWidth(8);C6.iC();C7.setDisplayPosition(2);C7.setParent(C5);C7.setMaxWidth(60);C7.iC();C8.setDisplayPosition(3);C8.setParent(C5);C8.setWidth(96);C8.setMinWidth(280);C8.setMaxWidth(880);C8.iC();C9.setDisplayPosition(4);C9.setParent(C5);C9.setMaxWidth(60);C9.iC();C10.setDisplayPosition(5);C10.setParent(C5);C10.setMinWidth(8);C10.iC();C11.setDisplayPosition(1);
C11.setParent(C5);C11.setHeight(93);C11.setUnits("CONTENT");C11.iC();C12.setDisplayPosition(2);C12.setParent(C5);C12.iC();C13.setAlignment("TOPLEFT");C13.setColumn(C7);C13.setManage(C25);C13.setParent(C5);C13.setRow(C11);C13.setSizing("CONTENTHEIGHTFITTOWIDTH");C13.setFlow("DOWN");C13.setColumnSpan(3);C13.iC();C14.setAlignment("TOPLEFT");C14.setColumn(C7);C14.setManage(C26);C14.setParent(C5);C14.setRow(C11);C14.setSizing("CONTENTHEIGHTFITTOWIDTH");C14.setFlow("DOWN");C14.setMarginTop(24);C14.setColumnSpan(3);
C14.iC();C15.setAlignment("TOPLEFT");C15.setColumn(C8);C15.setManage(C27);C15.setParent(C5);C15.setRow(C12);C15.setSizing("FITTOWIDTH");C15.setFlow("DOWN");C15.setMarginTop(24);C15.iC();C16.setSizing("CONTENTHEIGHT");C16.iC();C17.setDisplayPosition(1);C17.setParent(C16);C17.setUnits("CONTENT");C17.setHeight(96);C17.iC();C18.setDisplayPosition(2);C18.setParent(C16);C18.setUnits("PIXELS");C18.setHeight(62);C18.iC();C19.setDisplayPosition(1);C19.setParent(C16);C19.setMinWidth(44);C19.iC();C20.setDisplayPosition(2);
C20.setParent(C16);C20.setWidth(98);C20.iC();C21.setDisplayPosition(3);C21.setParent(C16);C21.setMinWidth(44);C21.iC();C22.setColumn(C20);C22.setManage(C28);C22.setParent(C16);C22.setRow(C17);C22.setSizing("FITTOWIDTH");C22.setAlignment("TOPLEFT");C22.setFlow("DOWN");C22.setMarginTop(16);C22.iC();C23.setAlignment("CENTERRIGHT");C23.setColumn(C20);C23.setManage(C29);C23.setParent(C16);C23.setRow(C18);C23.setSizing("NONE");C23.iC();C24.setAlignment("TOPLEFT");C24.setColumn(C19);C24.setManage(C30);C24.setParent(C16);
C24.setRow(C18);C24.setSizing("FITTOWIDTH");C24.setColumnSpan(3);C24.iC();C25.setCaption("Download Activity Data");C25.setDisplayPosition(1);C25.setLeft(350);C25.setParent(this);C25.setTabPosition(1);C25.setThemeDrawStyle("Heading1");C25.setTop(24);C25.setWidth(1000);C25.setIcon("arrow_back");C25.setCaptionMarginLeft(24);C25.setHeight(31);C25.setWordWrap(true);C25.setStyle(C4);C25.iC();C26.setCaptionAlignment("TOPLEFT");C26.setDisplayPosition(2);C26.setHeight(38);C26.setLeft(350);C26.setParent(this);
C26.setTabPosition(2);C26.setTop(79);C26.setWidth(1000);C26.setWordWrap(true);C26.setCaption("Select the range of time you wish to clear you activity history data. Be aware that the data will be permantely removed, so you will not longer be able to view and download your site activity.");C26.iC();C27.setDisplayPosition(3);C27.setHeight(160);C27.setLeft(410);C27.setParent(this);C27.setTabPosition(3);C27.setTabStop(false);C27.setTop(141);C27.setWidth(880);C27.setThemeDrawStyle("Card");C27.setStyle(C3);
C27.setLayoutManager(C16);C27.iC();C28.setCaption("Time Range");C28.setDisplayPosition(1);C28.setLeft(44);C28.setParent(C27);C28.setTabPosition(1);C28.setTop(16);C28.setWidth(790);C28.setHeight(80);C28.setStyle(C4);C28.iC();C29.setCaption("Download");C29.setDisplayPosition(2);C29.setLeft(734);C29.setParent(C27);C29.setTabPosition(2);C29.setThemeDrawStyle("ForegroundMediumPrimary");C29.setTop(109);C29.setStyle(C4);C29.iC();C30.setDisplayPosition(3);C30.setHeight(8);C30.setLeft(0);C30.setParent(C27);
C30.setTabPosition(3);C30.setTabStop(false);C30.setThemeDrawStyle("TopDivider");C30.setTop(96);C30.setWidth(878);C30.iC();C25.aH("CLICK",this,e3);C29.aH("CLICK",this,e4);this.setDisplayPosition(1);this.setTabPosition(1);this.setWidth(1700);this.setHeight(800);this.setLayoutManager(C5);this.setVerticalScroll(true);this.aH("CREATEINSTANCE",this,e1);this.aH("INITIALIZE",this,e2);}});function e1(sender,Ps){var r=l.eR(this,cO,"#COM_OWNER.CreateInstance",65);r.ln=65;{}r.ln=67;r.e();};function e2(sender,Ps)
{var m=this.REF,r=l.eR(this,cO,"#COM_OWNER.Initialize",69);r.ln=69;{r.ln=72;this.setrefCURRENTUSER(m.SESSION.ref.getCURRENTUSER());r.ln=74;this.mthBUILDOPTIONS();r.ln=76;l.gW("BPFPORTAL").getVIEWSPANEL().mthSETWAITINGSTATE("OFF");}r.ln=78;r.e();};function e3(sender,Ps){var r=l.eR(this,cO,"#PanelHeading.Click",81);r.ln=81;{r.ln=83;l.WEB().getHistory().mthGOBACK(u);}r.ln=85;r.e();};function e4(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#PanelAction.Click",88);r.ln=88;{r.ln=90;l.gW("BPFPORTAL").getVIEWSPANEL().mthSETWAITINGSTATE("ON");
r.ln=91;m.CURRENTUSER.mthDOWNLOADSESSIONS(l.s.AsNumber(m.TIMERANGEDROPDOWN.getValue()));}r.ln=93;r.e();};function e5(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#CurrentUser.OnSessionDownloadCompleted",96);r.ln=96;{r.ln=98;l.gW("BPFPORTAL").getVIEWSPANEL().mthSETWAITINGSTATE("OFF");r.ln=99;l.gW("BPFPORTAL").mthSHOWTOASTER(m.STRINGS.getTEXT("CURRENTUSER.ONSESSIONDOWNLOADCOMPLETED"));r.ln=101;l.WEB().getHistory().mthGOBACK(u);}r.ln=103;r.e();};function e6(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#CurrentUser.OnSessionDownloadFailed",105);
r.ln=105;{r.ln=107;l.gW("BPFPORTAL").getVIEWSPANEL().mthSETWAITINGSTATE("OFF");r.ln=108;l.gW("BPFPORTAL").mthSHOWTOASTER(m.STRINGS.getTEXT("CURRENTUSER.ONSESSIONDOWNLOADFAILED"),7500);}r.ln=110;r.e();};cO.mthBUILDOPTIONS=function(){var m=this.REF,r=l.mR(this,cO,"BuildOptions",114);r.ln=114;{r.ln=117;m.PANELHEADING.setCaption(m.STRINGS.getTEXT("PANELHEADING.CAPTION"));r.ln=118;m.INSTRUCTIONTEXT.setCaption(m.STRINGS.getTEXT("INSTRUCTIONTEXT.CAPTION"));r.ln=119;m.TIMERANGEDROPDOWN.setCaption(m.STRINGS.getTEXT("TIMERANGEDROPDOWN.CAPTION"));
r.ln=120;m.PANELACTION.setCaption(m.STRINGS.getTEXT("PANELACTION.CAPTION"));r.ln=123;m.TIMERANGEDROPDOWN.getItems().mthREMOVEALL();r.ln=126;m.TIMERANGEDROPDOWN.getItems().mthADD("1",m.STRINGS.getTEXT("TIMERANGEDROPDOWN.1"));r.ln=127;m.TIMERANGEDROPDOWN.getItems().mthADD("7",m.STRINGS.getTEXT("TIMERANGEDROPDOWN.7"));r.ln=128;m.TIMERANGEDROPDOWN.getItems().mthADD("30",m.STRINGS.getTEXT("TIMERANGEDROPDOWN.30"));r.ln=129;m.TIMERANGEDROPDOWN.getItems().mthADD("99",m.STRINGS.getTEXT("TIMERANGEDROPDOWN.99"));
r.ln=132;m.TIMERANGEDROPDOWN.setValue("99");}r.ln=134;r.e();};cO.setrefCURRENTUSER=function(rn){if(this.REF.CURRENTUSER!=null){this.REF.CURRENTUSER.rH("ONSESSIONDOWNLOADCOMPLETED",this,e5);this.REF.CURRENTUSER.rH("ONSESSIONDOWNLOADFAILED",this,e6);}this.sR("CURRENTUSER",rn);if(this.REF.CURRENTUSER!=null){this.REF.CURRENTUSER.aH("ONSESSIONDOWNLOADCOMPLETED",this,e5);this.REF.CURRENTUSER.aH("ONSESSIONDOWNLOADFAILED",this,e6);}};},{rc:["BPFAPP002","BPFAPP001","BPFVLR008"],rp:["PRIM_VIEW","PRIM_VS.Style","PRIM_TBLO","PRIM_TBLO.Column","PRIM_TBLO.Row","PRIM_TBLO.Item","PRIM_MD.Label","PRIM_PANL","PRIM_MD.Dropdown","PRIM_MD.FlatButton"],
dc:["BPFCLS002"]});