LANSA.addComponent({id:"BPFCLS010",nm:"BPFEmailTemplateDataClass",ot:"rp",tp:"Reusable Part",pt:"ap",de:"Email Template Data Class",tl:15000300},function(l,oI,u){var cL="ENG";var Fd={F1:{nm:"BPFFLD013",an:"BPFCodeGroup",ft:"NV",ln:128,dc:0,lb:"Codes Group Nam",h1:"Codes",h2:"Group",h3:"Name",de:"Codes Group Name",dv:"",ia:["FE","LC"]},F2:{nm:"BPFFLD016",an:"BPFCodeAlphaValue",ft:"NV",ln:2048,dc:0,lb:"Codes Alpha Val",h1:"Codes",h2:"Alpha",h3:"Value",de:"Codes Alpha Value",dv:"",ia:["ASQN","LC"]},
F3:{nm:"BPFFLD044",an:"BPFGenericBlob",ft:"BL",ln:0,dc:0,lb:"Portals Generic",h1:"Portals",h2:"Generic",h3:"Blob",de:"Portals Generic Blob",dv:l.SqlNull,ia:["ASQN","LC"]},F4:{nm:"BPFFLD014",an:"BPFCodeName",ft:"NV",ln:256,dc:0,lb:"Code Table Name",h1:"Code",h2:"Table",h3:"Name",de:"Code Table Name",dv:"",ia:["FE","LC"]},F5:{nm:"BPFFLD015",an:"BPFCodeSequence",ft:"P",ln:7,dc:0,lb:"Code Sequence",h1:"Code",h2:"Sequence",h3:"",de:"Code Sequence",dv:0,ia:["FE","RB"]},F6:{nm:"BPFFLD017",an:"BPFCodeNumericValue",
ft:"S",ln:15,dc:0,lb:"Codes Numeric V",h1:"Codes",h2:"Numeric",h3:"Value",de:"Codes Numeric Value",dv:0,ia:["FE","RB"]},F7:{nm:"BPFFLD018",an:"BPFCodeDescription",ft:"NV",ln:4096,dc:0,lb:"Code Descriptio",h1:"Code",h2:"Description",h3:"",de:"Code Description",dv:"",ia:["ASQN","LC"]},F8:{nm:"BPFFLD045",an:"BPFGenericCLOB",ft:"CL",ln:0,dc:0,lb:"Portal Generic",h1:"Portal",h2:"Generic",h3:"CLOB",de:"Portal Generic CLOB",dv:l.SqlNull,ia:["ASQN","LC"]},F9:{nm:"STATUS",an:"Status",ft:"A",ln:256,dc:0,lb:"Generic Status",
h1:"Generic",h2:"Status",h3:"Field",de:"Generic Status Field",dv:"",ia:["FE","LC"]}};var cO=l.rC(oI,{an:"PRIM_OBJT",fd:Fd,pt:{TemplateID:{da:"r"},DisplayName:{da:"r"},Properties:{da:"r"},PropertyValue:{da:"na"},Body:{da:"r"},File:{da:"na"}},mt:{Load:{ps:{"ForIsoCode":{pt:"i"}}},Save:{ps:{"ForIsoCode":{pt:"i"}}},Download:{}},ev:{OnLoadCompleted:{},OnLoadFailed:{},OnSaveCompleted:{},OnSaveFailed:{}},co:function(){cO.aN.call(this);var f=this.aF("BPFCLS010",Fd);var C0=this.cA("BROWSER","BPFWGT001");var C1=this.cR("PROPERTIES","PRIM_LCOL");
var C2=this.cR("READER","PRIM_WEB","ClobReader");var C3=this.cR("BODYHTML","PRIM_DC","UnicodeString");if((C0!=null)&&(C0.iI()==false)){C0.iC();}C1.setCollects("BPFCLS009");C1.iC();C2.iC();C3.iC();C2.aH("COMPLETED",this,e1);C1.aLF({"BPFFLD013":f.F1,"BPFFLD014":f.F4,"BPFFLD015":f.F5,"BPFFLD016":f.F2,"BPFFLD017":f.F6,"BPFFLD018":f.F7});this.aLF({"BPFFLD013":f.F1,"BPFFLD016":f.F2});}});cO.mthGETPROPERTYVALUE=function(p1){var m=this.REF,r=l.pR(this,cO,"GetPropertyValue",38);var P0=r.cP("PROPERTY","PRIM_ALPH");
var P1=r.cP("KEY","PRIM_ALPH");P1.set(p1);r.ln=38;{r.ln=42;{var l1=m.PROPERTIES.cI();while(l1.step()){var ITEM=r.sR("ITEM",l1.item());r.ln=44;if(l.s.ne(l.s.UpperCase(ITEM.getCODENAME()),l.s.UpperCase(P1.get()))){continue;}r.ln=46;P0.set(ITEM.getVALUE());r.ln=48;break;r.ln=50;}l1.end();r.dR("ITEM");}}r.ln=52;return r.rV(P0.get());};cO.mthSETPROPERTYVALUE=function(p0,p1){var m=this.REF,r=l.pR(this,cO,"SetPropertyValue",54);var P0=r.cP("PROPERTY","PRIM_ALPH");var P1=r.cP("KEY","PRIM_ALPH");P0.set(p0);
P1.set(p1);r.ln=54;{r.ln=58;{var l1=m.PROPERTIES.cI();while(l1.step()){var ITEM=r.sR("ITEM",l1.item());r.ln=60;if(l.s.ne(l.s.UpperCase(ITEM.getCODENAME()),l.s.UpperCase(P1.get()))){continue;}r.ln=62;ITEM.setVALUE(P0.get());r.ln=64;break;r.ln=66;}l1.end();r.dR("ITEM");}}r.ln=68;r.e();};function e1(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Reader.Completed",71);var P0=Ps.r("DATA");r.ln=71;{r.ln=73;m.BODYHTML.set(P0.get());r.ln=76;this.fE("ONLOADCOMPLETED");}r.ln=78;r.e();};cO.mthLOAD=function(p0){
var f=this.FLD.BPFCLS010,m=this.REF,r=l.mR(this,cO,"Load",81),mth=r;var P0=r.cP("FORISOCODE","PRIM_DC","UnicodeString");P0.set(p0);var C0=r.cDR("REQUEST","BPFSVR004","GETTEMPLATEDATA");C0.iC();C0.aH("COMPLETED",this,e2);C0.aH("FAILED",this,e3);r.ln=81;{r.ln=88;C0.mthEXECUTEASYNC({FLD:{"BPFFLD081":P0.get(),"ALPHAVALUE":f.F1.get()}},{FLD:{"BPFFLD045":f.F8,"BPFFLD007":f.F9},LIST:{"CODESGROUP":m.PROPERTIES}});}r.ln=112;r.e();function e2(sender,Ps){var r=l.eR(this,cO,"#Request.Completed",90,mth);r.ln=90;
{r.ln=92;if(l.s.eq(f.F9.get(),"OK")){r.ln=95;m.READER.mthREAD(f.F8.get());}else{r.ln=99;this.fE("ONLOADFAILED");}}r.ln=103;r.e();}function e3(sender,Ps){var r=l.eR(this,cO,"#Request.Failed",105,mth);var P1=Ps.r("HANDLED");var P2=Ps.r("REASON");r.ln=105;{r.ln=107;P1.set(true);r.ln=108;this.fE("ONLOADFAILED");}r.ln=110;r.e();}};cO.mthSAVE=function(p0){var f=this.FLD.BPFCLS010,m=this.REF,r=l.mR(this,cO,"Save",114),mth=r;var P0=r.cP("FORISOCODE","PRIM_DC","UnicodeString");P0.set(p0);var C0=r.cDR("REQUEST","BPFSVR004","SAVETEMPLATEDATA");
C0.iC();C0.aH("COMPLETED",this,e4);C0.aH("FAILED",this,e5);r.ln=114;{r.ln=121;C0.mthEXECUTEASYNC({FLD:{"BPFFLD081":P0.get(),"BPFFLD013":f.F1.get(),"BPFFLD044":f.F3.get()},LIST:{"CODESGROUP":m.PROPERTIES},sm:"M"},{FLD:{"BPFFLD007":f.F9}});r.ln=124;f.F3.set(l.SqlNull);}r.ln=148;r.e();function e4(sender,Ps){var r=l.eR(this,cO,"#Request.Completed",126,mth);r.ln=126;{r.ln=128;if(l.s.eq(f.F9.get(),"OK")){r.ln=130;f.F2.set(m.PROPERTIES.get(1).getVALUE());r.ln=131;this.fE("ONSAVECOMPLETED");}else{r.ln=135;
this.fE("ONSAVEFAILED");}}r.ln=139;r.e();}function e5(sender,Ps){var r=l.eR(this,cO,"#Request.Failed",141,mth);var P1=Ps.r("HANDLED");var P2=Ps.r("REASON");r.ln=141;{r.ln=143;P1.set(true);r.ln=144;this.fE("ONSAVEFAILED");}r.ln=146;r.e();}};cO.mthDOWNLOAD=function(){var f=this.FLD.BPFCLS010,m=this.REF,r=l.mR(this,cO,"Download",150);r.ln=150;{r.ln=152;m.BROWSER.ref.mthDOWNLOAD(f.F8.get(),this.getPROPERTYVALUE("BODY_TEMPLATE"));}r.ln=154;r.e();};cO.getTEMPLATEID=function(){var f=this.FLD.BPFCLS010;return f.F1.get();
};cO.getDISPLAYNAME=function(){var f=this.FLD.BPFCLS010;return f.F2.get();};cO.getPROPERTIES=function(){return this.REF.PROPERTIES;};cO.getPROPERTYVALUE=function(KEY_1){return this.mthGETPROPERTYVALUE(KEY_1);};cO.setPROPERTYVALUE=function(KEY_1,v){this.mthSETPROPERTYVALUE(v,KEY_1);};cO.getBODY=function(){return this.REF.BODYHTML.get();};cO.setFILE=function(v){var f=this.FLD.BPFCLS010;f.F3.set(v);};},{rc:["BPFWGT001"],rp:["PRIM_OBJT","PRIM_LCOL","PRIM_WEB.ClobReader","PRIM_DC.UnicodeString","PRIM_WEB.DataRequest","PRIM_FLD"],
dc:["BPFCLS009"]});