LANSA.addComponent({id:"BPFPNL012",nm:"BPFPasswordResetCheckingPanel",ot:"rp",tp:"Reusable Part",pt:"ap",de:"Portal Password Reset Checking",tl:15000300},function(l,oI,u){var cO=l.rC(oI,{an:"PRIM_VIEW",mt:{SetStrings:{},HandleDeviceChanged:{},SetForMobile:{},SetForTablet:{},SetForDesktop:{}},co:function(){cO.aN.call(this);var C0=this.cA("SESSION","BPFAPP002");var C1=this.cA("NAVIGATE","BPFAPP001");var C2=this.cR("STRINGS","BPFPLR012");var C3=this.cR("LAYOUT","PRIM_TBLO");var C4=this.cR("LAYOUTCOLUMN1","PRIM_TBLO","Column");
var C5=this.cR("LAYOUTCOLUMN2","PRIM_TBLO","Column");var C6=this.cR("LAYOUTCOLUMN3","PRIM_TBLO","Column");var C7=this.cR("LAYOUTROW1","PRIM_TBLO","Row");var C8=this.cR("LAYOUTROW2","PRIM_TBLO","Row");var C9=this.cR("LAYOUTITEM1","PRIM_TBLO","Item");var C10=this.cR("LAYOUTITEM2","PRIM_TBLO","Item");var C11=this.cR("LAYOUTITEM3","PRIM_TBLO","Item");var C12=this.cR("LAYOUTITEM4","PRIM_TBLO","Item");var C13=this.cR("MOBILELAYOUT","PRIM_TBLO");var C14=this.cR("MOBILELAYOUTCOLUMN1","PRIM_TBLO","Column");
var C15=this.cR("MOBILELAYOUTROW1","PRIM_TBLO","Row");var C16=this.cR("MOBILELAYOUTITEM1","PRIM_TBLO","Item");var C17=this.cR("MOBILELAYOUTITEM2","PRIM_TBLO","Item");var C18=this.cR("MOBILELAYOUTITEM3","PRIM_TBLO","Item");var C19=this.cR("DIALOGLOGO","PRIM_MD","Label");var C20=this.cR("MAININSTRUCTION","PRIM_MD","Label");var C21=this.cR("SECONDARINSTRUCTION","PRIM_MD","Label");var C22=this.cR("PANELTEXT","PRIM_MD","Label");this.cD("DIALOG");if((C0!=null)&&(C0.iI()==false)){C0.iC();}if((C1!=null)&&(C1.iI()==false))
{C1.iC();}C2.iC();C3.iC();C4.setDisplayPosition(1);C4.setParent(C3);C4.iC();C5.setDisplayPosition(3);C5.setParent(C3);C5.setUnits("CONTENT");C5.setWidth(252);C5.iC();C6.setDisplayPosition(2);C6.setParent(C3);C6.iC();C7.setDisplayPosition(1);C7.setParent(C3);C7.iC();C8.setDisplayPosition(2);C8.setParent(C3);C8.setHeight(48);C8.setUnits("PIXELS");C8.iC();C9.setAlignment("TOPLEFT");C9.setColumn(C5);C9.setManage(C19);C9.setParent(C3);C9.setRow(C7);C9.setSizing("FITTOHEIGHT");C9.iC();C10.setAlignment("TOPLEFT");
C10.setColumn(C4);C10.setManage(C20);C10.setParent(C3);C10.setRow(C7);C10.setSizing("CONTENTHEIGHTFITTOWIDTH");C10.setFlow("DOWN");C10.setColumnSpan(2);C10.iC();C11.setAlignment("TOPLEFT");C11.setColumn(C4);C11.setFlow("DOWN");C11.setManage(C21);C11.setParent(C3);C11.setRow(C7);C11.setSizing("CONTENTHEIGHTFITTOWIDTH");C11.setMarginBottom(24);C11.setColumnSpan(2);C11.iC();C12.setManage(C22);C12.setParent(C3);C12.setRow(C7);C12.setColumn(C4);C12.setAlignment("TOPLEFT");C12.setFlow("DOWN");C12.setColumnSpan(2);
C12.iC();C13.iC();C14.setDisplayPosition(1);C14.setParent(C13);C14.iC();C15.setDisplayPosition(1);C15.setParent(C13);C15.iC();C16.setManage(C20);C16.setParent(C13);C16.setRow(C15);C16.setSizing("CONTENTHEIGHTFITTOWIDTH");C16.setColumn(C14);C16.setAlignment("TOPLEFT");C16.setFlow("DOWN");C16.iC();C17.setAlignment("TOPLEFT");C17.setColumn(C14);C17.setFlow("DOWN");C17.setManage(C21);C17.setParent(C13);C17.setRow(C15);C17.setSizing("CONTENTHEIGHTFITTOWIDTH");C17.iC();C18.setAlignment("TOPLEFT");C18.setColumn(C14);
C18.setFlow("DOWN");C18.setManage(C22);C18.setParent(C13);C18.setRow(C15);C18.setSizing("CONTENTHEIGHTFITTOWIDTH");C18.setMarginTop(16);C18.iC();C19.setDisplayPosition(1);C19.setLeft(414);C19.setParent(this);C19.setTabPosition(1);C19.setThemeDrawStyle("Heading3+ForegroundTheme");C19.setTop(0);C19.setHeight(378);C19.setWidth(252);C19.setCaptionAlignment("CENTER");C19.setWordWrap(true);C19.setIconAlignment("ABOVECAPTION");C19.setIcon("hourglass_full");C19.setIconHeight(118);C19.setIconThemeDrawStyle("ForegroundMediumPrimary");
C19.setCaptionMarginLeft(14);C19.setCaptionMarginRight(14);C19.setCaption("We know you busy, wont be long now");C19.iC();C20.setDisplayPosition(2);C20.setLeft(0);C20.setParent(this);C20.setTabPosition(2);C20.setThemeDrawStyle("Heading2");C20.setTop(0);C20.setHeight(19);C20.setWordWrap(true);C20.setWidth(414);C20.setCaption("Checking... well be done in moment");C20.iC();C21.setDisplayPosition(3);C21.setLeft(0);C21.setParent(this);C21.setTabPosition(3);C21.setHeight(19);C21.setWordWrap(true);C21.setWidth(414);
C21.setCaption("Just checking with our systems now");C21.setTop(19);C21.iC();C22.setCaption("It pay to be careful, so we are just checking our systems to ensure all is well before we before we process this account request. We know you busy, so we are checking as fast as we can.");C22.setDisplayPosition(4);C22.setLeft(0);C22.setParent(this);C22.setTabPosition(4);C22.setTop(62);C22.setHeight(378);C22.setWidth(414);C22.setCaptionAlignment("TOPLEFT");C22.setWordWrap(true);C22.iC();l.WEB().aH("DEVICECHANGED",this,e2);
this.setDisplayPosition(1);this.setHeight(426);this.setTabPosition(1);this.setWidth(666);this.setLayoutManager(C3);this.aH("INITIALIZE",this,e1);}});function e1(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#COM_OWNER.Initialize",60);r.ln=60;{r.ln=63;this.setrefDIALOG(l.gW("BPFPORTAL").getPASSWORDRESETDIALOG());r.ln=65;this.mthSETSTRINGS();r.ln=67;this.mthHANDLEDEVICECHANGED();}r.ln=69;r.e();};function e2(sender,Ps){var r=l.eR(this,cO,"#SYS_WEB.DeviceChanged",72);r.ln=72;{r.ln=74;this.mthHANDLEDEVICECHANGED();
}r.ln=76;r.e();};cO.mthSETSTRINGS=function(){var m=this.REF,r=l.mR(this,cO,"SetStrings",82);r.ln=82;{r.ln=84;m.MAININSTRUCTION.setCaption(m.STRINGS.getTEXT("MAININSTRUCTION.CAPTION"));r.ln=85;m.SECONDARINSTRUCTION.setCaption(m.STRINGS.getTEXT("SECONDARINSTRUCTION.CAPTION"));r.ln=86;m.PANELTEXT.setCaption(m.STRINGS.getTEXT("PANELTEXT.CAPTION"));r.ln=87;m.DIALOGLOGO.setCaption(m.STRINGS.getTEXT("DIALOGLOGO.CAPTION"));}r.ln=89;r.e();};cO.mthHANDLEDEVICECHANGED=function(){var r=l.mR(this,cO,"HandleDeviceChanged",92);
r.ln=92;{r.ln=94;{var v1=l.WEB().getDevice();if(r.ln=96,l.s.eq(v1,"MOBILE")){r.ln=98;this.mthSETFORMOBILE();}else if(r.ln=100,l.s.eq(v1,"TABLET")){r.ln=102;this.mthSETFORTABLET();}else{r.ln=106;this.mthSETFORDESKTOP();}r.ln=108;}}r.ln=110;r.e();};cO.mthSETFORMOBILE=function(){var m=this.REF,r=l.mR(this,cO,"SetForMobile",112);r.ln=112;{r.ln=115;m.DIALOGLOGO.setVisible(false);r.ln=118;if((this.getLayoutManager()!==m.MOBILELAYOUT)){r.ln=120;this.setLayoutManager(m.MOBILELAYOUT);}}r.ln=123;r.e();};cO.mthSETFORTABLET=function()
{var m=this.REF,r=l.mR(this,cO,"SetForTablet",125);r.ln=125;{r.ln=128;m.DIALOGLOGO.setVisible(false);r.ln=131;if((this.getLayoutManager()!==m.LAYOUT)){r.ln=133;this.setLayoutManager(m.LAYOUT);}}r.ln=137;r.e();};cO.mthSETFORDESKTOP=function(){var m=this.REF,r=l.mR(this,cO,"SetForDesktop",139);r.ln=139;{r.ln=142;m.DIALOGLOGO.setVisible(true);r.ln=145;if((this.getLayoutManager()!==m.LAYOUT)){r.ln=147;this.setLayoutManager(m.LAYOUT);}}r.ln=151;r.e();};cO.setrefDIALOG=function(rn){this.sR("DIALOG",rn);
};},{rc:["BPFAPP002","BPFAPP001","BPFPLR012"],rp:["PRIM_VIEW","PRIM_TBLO","PRIM_TBLO.Column","PRIM_TBLO.Row","PRIM_TBLO.Item","PRIM_MD.Label"],dc:["BPFDLG004"]});