LANSA.addComponent({id:"BPFPNL004",nm:"BPFLoginUserPasswordPanel",ot:"rp",tp:"Reusable Part",pt:"ap",de:"Portal Login User Password Panel",tl:15000300},function(l,oI,u){var cO=l.rC(oI,{an:"PRIM_VIEW",pt:{Value:{da:"r"}},mt:{HandleNext:{},HandleLoginFailed:{},HandleLoginActive:{},DisplayFieldErrors:{ps:{"EditField":{pt:"i"},"Message":{pt:"i"}}}},co:function(){cO.aN.call(this);var C0=this.cA("SESSION","BPFAPP002");var C1=this.cA("NAVIGATE","BPFAPP001");var C2=this.cR("STRINGS","BPFPLR004");var C3=this.cR("NAVIGATIONLINKSTYLE","PRIM_VS","Style");
var C4=this.cR("LAYOUT","PRIM_TBLO");var C5=this.cR("LAYOUTCOLUMN1","PRIM_TBLO","Column");var C6=this.cR("LAYOUTROW1","PRIM_TBLO","Row");var C7=this.cR("LAYOUTROW2","PRIM_TBLO","Row");var C8=this.cR("LAYOUTROW3","PRIM_TBLO","Row");var C9=this.cR("LAYOUTITEM1","PRIM_TBLO","Item");var C10=this.cR("LAYOUTITEM2","PRIM_TBLO","Item");var C11=this.cR("LAYOUTITEM3","PRIM_TBLO","Item");var C12=this.cR("LAYOUTITEM4","PRIM_TBLO","Item");var C13=this.cR("PANELTEXT","PRIM_MD","Label");var C14=this.cR("USERPASSWORDEDIT","PRIM_MD","Edit");
var C15=this.cR("PANELACTION","PRIM_MD","FlatButton");var C16=this.cR("NEXTBUTTON","PRIM_MD","RaisedButton");this.cD("DIALOG");if((C0!=null)&&(C0.iI()==false)){C0.iC();}if((C1!=null)&&(C1.iI()==false)){C1.iC();}C2.iC();C3.setCursor("HAND");C3.iC();C4.iC();C5.setDisplayPosition(1);C5.setParent(C4);C5.iC();C6.setDisplayPosition(1);C6.setParent(C4);C6.iC();C7.setDisplayPosition(2);C7.setParent(C4);C7.setHeight(64);C7.setUnits("PIXELS");C7.iC();C8.setDisplayPosition(3);C8.setParent(C4);C8.setHeight(48);
C8.setUnits("PIXELS");C8.iC();C9.setAlignment("TOPLEFT");C9.setColumn(C5);C9.setManage(C13);C9.setParent(C4);C9.setRow(C6);C9.setSizing("CONTENTHEIGHTFITTOWIDTH");C9.iC();C10.setAlignment("CENTERLEFT");C10.setColumn(C5);C10.setManage(C14);C10.setParent(C4);C10.setRow(C6);C10.setSizing("FITTOWIDTH");C10.iC();C11.setAlignment("CENTERLEFT");C11.setColumn(C5);C11.setManage(C15);C11.setParent(C4);C11.setRow(C7);C11.setSizing("CONTENTWIDTHANDHEIGHT");C11.iC();C12.setManage(C16);C12.setParent(C4);C12.setRow(C7);
C12.setSizing("CONTENTWIDTHANDHEIGHT");C12.setColumn(C5);C12.setAlignment("CENTERRIGHT");C12.iC();C13.setCaption("Enter your password for &1");C13.setDisplayPosition(1);C13.setLeft(0);C13.setParent(this);C13.setTabPosition(1);C13.setThemeDrawStyle("Heading3");C13.setTop(0);C13.setWidth(352);C13.setHeight(19);C13.setCaptionAlignment("CENTER");C13.setWordWrap(true);C13.iC();C14.setCaption("Password");C14.setDisplayPosition(2);C14.setLeft(0);C14.setParent(this);C14.setTabPosition(2);C14.setTop(44);C14.setWidth(352);
C14.setPasswordChar("*");C14.iC();C15.setCaption("Forget Password?");C15.setDisplayPosition(3);C15.setLeft(0);C15.setParent(this);C15.setTabPosition(3);C15.setThemeDrawStyle("ForegroundMediumPrimary");C15.setTop(180);C15.setHeight(31);C15.setCaptionMarginBottom(8);C15.setCaptionMarginLeft(8);C15.setCaptionMarginRight(8);C15.setCaptionMarginTop(8);C15.setWidth(122);C15.setStyle(C3);C15.iC();C16.setCaption("Next");C16.setDisplayPosition(4);C16.setLeft(272);C16.setParent(this);C16.setTabPosition(4);
C16.setThemeDrawStyle("MediumTitle");C16.setTop(178);C16.setHeight(35);C16.setWidth(80);C16.setCaptionMarginBottom(10);C16.setCaptionMarginTop(10);C16.setCaptionMarginLeft(26);C16.setCaptionMarginRight(26);C16.setStyle(C3);C16.iC();C0.aH("LOGINFAILED",this,e3);C14.aH("ENTER",this,e5);C14.aH("CHANGED",this,e6);C15.aH("CLICK",this,e4);C16.aH("CLICK",this,e5);this.setDisplayPosition(1);this.setHeight(275);this.setTabPosition(1);this.setWidth(352);this.setLayoutManager(C4);this.aH("INITIALIZE",this,e1);
this.aH("PREPARE",this,e2);}});function e1(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#COM_OWNER.Initialize",44);r.ln=44;{r.ln=47;m.SESSION.ref.getMESSAGE().mthSENDACTION("LOGIN_ATTEMPT");r.ln=49;this.setrefDIALOG(l.gW("BPFPORTAL").getLOGINDIALOG());}r.ln=51;r.e();};function e2(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#COM_OWNER.Prepare",53);r.ln=53;{r.ln=55;m.PANELTEXT.setCaption(l.s.Replace(m.STRINGS.getTEXT("PANELTEXT.CAPTION"),"%%ACCOUNT%%",m.SESSION.ref.getREQUESTEDACCOUNT()));r.ln=57;m.USERPASSWORDEDIT.setCaption(m.STRINGS.getTEXT("USERPASSWORDEDIT.CAPTION"));
r.ln=58;m.PANELACTION.setCaption(m.STRINGS.getTEXT("PANELACTION.CAPTION"));r.ln=59;m.NEXTBUTTON.setCaption(m.STRINGS.getTEXT("NEXTBUTTON.CAPTION"));}r.ln=62;r.e();};function e3(sender,Ps){var r=l.eR(this,cO,"#Session.LoginFailed",65);var P0=Ps.r("REASON");r.ln=65;{r.ln=67;if(l.s.eq(l.s.UpperCase(P0.get()),"ACTIVE")){r.ln=69;this.mthHANDLELOGINACTIVE();}else{r.ln=73;this.mthHANDLELOGINFAILED();}}r.ln=77;r.e();};function e4(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#PanelAction.Click",80);r.ln=80;{
r.ln=83;m.NAVIGATE.ref.mthTO("REQUESTPASSWORDRESET",u,u,u);}r.ln=85;r.e();};function e5(sender,Ps){var r=l.eR(this,cO,"#NextButton.Click #UserPasswordEdit.Enter",88);r.ln=88;{r.ln=90;this.mthHANDLENEXT();}r.ln=92;r.e();};function e6(SENDER,Ps){var r=l.eR(this,cO,"#UserPasswordEdit.Changed",95);r.ln=95;{r.ln=97;if(SENDER.getHasError()){r.ln=99;SENDER.mthCLEARERROR();}}r.ln=103;r.e();};cO.mthHANDLENEXT=function(){var m=this.REF,r=l.mR(this,cO,"HandleNext",107);r.ln=107;{r.ln=109;if(l.s.ne(m.USERPASSWORDEDIT.get(),""))
{r.ln=111;m.DIALOG.mthSETWAITINGSTATE("ON");r.ln=112;m.SESSION.ref.mthLOGIN(m.USERPASSWORDEDIT.getValue());}else{r.ln=116;this.mthDISPLAYFIELDERRORS(m.USERPASSWORDEDIT,m.STRINGS.getTEXT("USERPASSWORDEDIT.INVALID"));}}r.ln=120;r.e();};cO.mthHANDLELOGINFAILED=function(){var m=this.REF,r=l.mR(this,cO,"HandleLoginFailed",123);r.ln=123;{r.ln=125;this.mthDISPLAYFIELDERRORS(m.USERPASSWORDEDIT,m.STRINGS.getTEXT("MESSAGE.LOGINFAILED"));}r.ln=127;r.e();};cO.mthHANDLELOGINACTIVE=function(){var m=this.REF,r=l.mR(this,cO,"HandleLoginActive",129);
r.ln=129;{r.ln=131;this.mthDISPLAYFIELDERRORS(m.USERPASSWORDEDIT,m.STRINGS.getTEXT("MESSAGE.LOGINACTIVE"));}r.ln=133;r.e();};cO.mthDISPLAYFIELDERRORS=function(p0,p1){var r=l.mR(this,cO,"DisplayFieldErrors",137);var P0=r.cPD("EDITFIELD");var P1=r.cP("MESSAGE","PRIM_DC","UnicodeString");P0=r.sR("EDITFIELD",p0);P1.set(p1);r.ln=137;{r.ln=141;P0.mthSHOWERROR(P1.get());}r.ln=143;r.e();};cO.getVALUE=function(){return this.REF.USERPASSWORDEDIT;};cO.setrefDIALOG=function(rn){this.sR("DIALOG",rn);};},{rc:["BPFAPP002","BPFAPP001","BPFPLR004"],
rp:["PRIM_VIEW","PRIM_VS.Style","PRIM_TBLO","PRIM_TBLO.Column","PRIM_TBLO.Row","PRIM_TBLO.Item","PRIM_MD.Label","PRIM_MD.Edit","PRIM_MD.FlatButton","PRIM_MD.RaisedButton"],dc:["BPFDLG001"]});