window.LANSA.addSrc("atlm",function(d,c,a,b,p){d.Ob("PRIM_CPST");a.Sha={kHc:0,mTb:1,jHc:2,lTb:4,lHc:8,uMd:15};a.CX={hBb:0,Ypc:1,Xpc:2,Mjd:3};a.CX.v={VERTICAL:a.CX.hBb,HORIZONTAL:a.CX.Ypc,DISPLAYPOSITION:a.CX.Xpc,EO:a.CX.Mjd};a.mLa={NJd:0,xLb:1,LJd:2,PJd:3,MJd:4,OJd:5,Lme:6};a.q9d={K2a:0,L2a:1};a.Fhb={lub:32};c.mgc=function(b,c,d){t.K.call(this);this.Tb=[];this.Tb=c;this.Dj=this.ek=d;this.dEa=this.XFa=0;this.zY=a.Sha.kHc};var t=c.u(c.mgc,c.kf);t.R=function(){t.k.R.call(this)};c.GLa=function(){m.K.call(this);
this.JTa=a.CX.hBb};d.Ob("PRIM_TBLO");var m=c.u(c.GLa,c.ULa);m.R=function(){m.k.R.call(this)};m.j1d=function(){return this.JTa};m.Fud=function(b){this.JTa!=b&&(this.JTa=b,this.m(a.g.j))};m.Zda=function(a,b){var c=this.Fya(a);c.Zda(b);return c};m.jW=function(a){return this.Lg(a).jW()};m.NTd=function(a){return this.Lg(a)};m.qob=function(){return a.mLa.xLb};m.Mo=function(b,c){var d=m.k.Mo.call(this,b,c);if(d){var e=this.Lg(b);!e||e.jW()!=a.bj.Tha&&e.jW()!=a.bj.Qha||(d=!1)}return d};m.qq=function(b,c){var d=
m.k.qq.call(this,b,c);if(d){var e=this.Lg(b);!e||e.jW()!=a.bj.xaa&&e.jW()!=a.bj.Rha||(d=!1)}return d};m.PWc=function(a){return this.Lg(a)};m.mN=function(a,b,c,e){e===p&&(e=!0);a=d.Bc("PRIM_ATLI");a.wk(b);e&&a.Oa(this);return a};m.xfd=function(a,b){return b=this.lf(a,void 0)};m.fVb=function(a){var b=new c.L1a;b.wk(a);return b};m.lf=function(b,d){for(var h=this.gE(b,!0);;){var e=new c.mgc(0,h,d);e.Dj.Xa(e.Dj.Te()+this.oh);e.Dj.Za(e.Dj.ve()+this.nh);e.Dj.Va(e.Dj.Vt()-this.oj);e.Dj.Ja(e.Dj.zN()-this.nj);
switch(this.JTa){case a.CX.hBb:this.PV(e,a.bj.Tha);this.PV(e,a.bj.Qha);this.PV(e,a.bj.xaa);this.PV(e,a.bj.Rha);this.PV(e,a.bj.IK);break;case a.CX.Ypc:this.PV(e,a.bj.xaa);this.PV(e,a.bj.Rha);this.PV(e,a.bj.Tha);this.PV(e,a.bj.Qha);this.PV(e,a.bj.IK);break;case a.CX.Xpc:for(var k=null,f=h,m=0;m<f.length&&null!=(k=f[m]);m++){var p=k;p.ifa!=a.bj.IK&&0==(k.ma().vb&a.Fhb.lub)&&this.Igb(e,p)}this.PV(e,a.bj.IK)}if(0==e.XFa&&0==e.dEa)break;d.n8(e.XFa,e.dEa)}return new c.AO(d.ja(),d.la())};m.PV=function(b,
c){var d=null,e=b.Tb;switch(c){case a.bj.Tha:case a.bj.xaa:case a.bj.IK:for(var k=0;k<e.length&&null!=(d=e[k]);k++){var f=d;if(f.ifa==c){var m=d.ma();0==(m.vb&a.Fhb.lub)&&this.Igb(b,f)}}break;case a.bj.Qha:case a.bj.Rha:for(k=e.length-1;0<=k&&null!=(d=e[k]);k--)f=d,f.ifa==c&&(m=d.ma(),0==(m.vb&a.Fhb.lub)&&this.Igb(b,f))}};m.Igb=function(b,c){var d=c.p3b(),e,k;switch(c.ifa){case a.bj.Tha:k=0;b.zY|=a.Sha.mTb;0!=c.JZ&&d.Vh(d.ja(),b.ek.la()*c.JZ/100);d.Rb(b.Dj.aa()+c.Sf(),b.Dj.$()+c.Jf());b.Dj.h5a(b.Dj.aa(),
b.Dj.$()+d.la()+c.Jf()+c.$g());e=b.Dj.ja()-(c.Sf()+c.Wg());d.Vh(Math.max(e,0),d.la());this.Rsa(c,d);0<k&&(k>b.Dj.la()&&(d=k-b.Dj.la(),d>b.dEa&&(b.dEa=d)),b.Dj.esc(0,k));break;case a.bj.Qha:k=0;b.zY|=a.Sha.jHc;0!=c.JZ&&d.Vh(d.ja(),b.ek.la()*c.JZ/100);e=b.Dj.la()-(d.la()+c.Jf()+c.$g());0!=(b.zY&a.Sha.mTb)&&(e=Math.max(e,0));b.Dj.Vh(b.Dj.ja(),e);d.Rb(b.Dj.aa()+c.Sf(),b.Dj.Fa()+c.Jf());e=b.Dj.ja()-(c.Sf()+c.Wg());d.Vh(Math.max(e,0),d.la());this.Rsa(c,d);0<k&&(k>b.Dj.la()&&(d=k-b.Dj.la(),d>b.dEa&&(b.dEa=
d)),b.Dj.n8(0,-k));break;case a.bj.xaa:k=0;b.zY|=a.Sha.lTb;0!=c.JZ&&d.Vh(b.ek.ja()*c.JZ/100,d.la());d.Rb(b.Dj.aa()+c.Sf(),b.Dj.$()+c.Jf());e=b.Dj.aa()+d.ja()+c.Sf()+c.Wg();b.Dj.h5a(Math.max(e,b.ek.aa()),b.Dj.$());e=b.Dj.la()-(c.Jf()+c.$g());d.Vh(d.ja(),Math.max(e,0));this.Rsa(c,d);0<k&&(k>b.Dj.ja()&&(d=k-b.Dj.ja(),d>b.XFa&&(b.XFa=d)),b.Dj.esc(k,0));break;case a.bj.Rha:k=0;b.zY|=a.Sha.lHc;0!=c.JZ&&d.Vh(b.ek.ja()*c.JZ/100,d.la());e=b.Dj.ja()-(d.ja()+c.Sf()+c.Wg());0!=(b.zY&a.Sha.lTb)&&(e=Math.max(e,
0));b.Dj.Vh(e,b.Dj.la());d.Rb(b.Dj.Ka()+c.Sf(),b.Dj.$()+c.Jf());e=b.Dj.la()-(c.Jf()+c.$g());d.Vh(d.ja(),Math.max(e,0));this.Rsa(c,d);0<k&&(k>b.Dj.ja()&&(d=k-b.Dj.ja(),d>b.XFa&&(b.XFa=d)),b.Dj.n8(-k,0));break;case a.bj.IK:d.Rb(b.Dj.aa()+c.Sf(),b.Dj.$()+c.Jf()),e=b.Dj.ja()-(c.Sf()+c.Wg()),k=b.Dj.la()-(c.Jf()+c.$g()),d.Vh(Math.max(e,0),Math.max(k,0)),this.Rsa(c,d)}};m.zBb=function(b,c){var d=this.PWc(b);if(d){if(d.jW()==a.bj.Tha||d.jW()==a.bj.Qha)c[0]=!0;if(d.jW()==a.bj.xaa||d.jW()==a.bj.Rha)c[1]=!0}};
d.Md(c.GLa,"PRIM_ATLM",{Aa:{MarginTop:{a:m.Jf,f:function(a){this.Ef(d.O(a))}},MarginBottom:{a:m.$g,f:function(a){this.jg(d.O(a))}},MarginLeft:{a:m.Sf,f:function(a){this.Bf(d.O(a))}},MarginRight:{a:m.Wg,f:function(a){this.we(d.O(a))}},MaxHeight:{a:m.oZa,f:function(a){this.iAa(d.O(a))}},MaxWidth:{a:m.pZa,f:function(a){this.hea(d.O(a))}},MinHeight:{a:m.rZa,f:function(a){this.jAa(d.O(a))}},MinWidth:{a:m.sZa,f:function(a){this.jea(d.O(a))}},ProcessingOrder:{a:function(){return d.va(this.JTa,a.CX.v)},f:function(b){this.Fud(d.wa(b,
a.CX.v))}}}})});window.LANSA.addSrc("atli",function(d,c,a,b){a.bj={wTb:0,Tha:1,Qha:2,xaa:3,Rha:4,IK:5,WIc:6};a.bj.v={NONE:a.bj.wTb,TOP:a.bj.Tha,BOTTOM:a.bj.Qha,LEFT:a.bj.xaa,RIGHT:a.bj.Rha,CENTER:a.bj.IK,EO:a.bj.WIc};a.YIc={Qsa:0};c.L1a=function(){p.K.call(this);this.JZ=0;this.ifa=a.bj.wTb;this.zY=a.YIc.Qsa};var p=c.u(c.L1a,c.VLa);b.M1a=function(a,b,d){var p=new c.L1a;p.Oa(a);p.wk(b);p.Zda(d);return p};p.R=function(){p.k.R.call(this)};p.qob=function(){return a.mLa.xLb};p.jW=function(){return this.ifa};p.Zda=function(b){this.ifa!=
b&&(this.ifa=b,this.m(a.g.j))};p.O0d=function(){return this.JZ};p.$ge=function(b){0>b?b=0:100<b&&(b=100);this.JZ!=b&&(this.JZ=b,this.m(a.g.j))};p.dsb=function(b){var c=!1;if(null!=this.gb&&this.gb.W()===b)if(this.gb.Zd()){if(this.gb.up()||this.ifa==a.bj.IK)c=!0}else this.gb.up()&&(c=!0);return c};p.G8b=function(a,b,c){this.Oa(a);this.wk(b);this.Zda(c)};d.Md(c.L1a,"PRIM_ATLI",{Aa:{MarginTop:{a:p.Jf,f:function(a){this.Ef(d.O(a))}},MarginBottom:{a:p.$g,f:function(a){this.jg(d.O(a))}},MarginLeft:{a:p.Sf,
f:function(a){this.Bf(d.O(a))}},MarginRight:{a:p.Wg,f:function(a){this.we(d.O(a))}},MaxHeight:{a:p.oZa,f:function(a){this.iAa(d.O(a))}},MaxWidth:{a:p.pZa,f:function(a){this.hea(d.O(a))}},MinHeight:{a:p.rZa,f:function(a){this.jAa(d.O(a))}},MinWidth:{a:p.sZa,f:function(a){this.jea(d.O(a))}},Manage:{a:p.ma,f:p.wk},Parent:{a:p.W,f:p.Oa},Attachment:{a:function(){return d.va(this.jW(),a.bj.v)},f:function(b){this.Zda(d.wa(b,a.bj.v))}}}})});
