window.LANSA.addSrc("evp",function(d,c,a,b){var p=a.Nm.oN,t=a.Qn.Iia,m=a.cg.Ev,q=a.yp.oda,s=null;a.Lw={Gxa:0,Sca:16,Ela:32,Cla:64,pla:128};a.Lw.v={NONE:a.Lw.Gxa,LEFT:a.Lw.Sca,TOP:a.Lw.Ela,RIGHT:a.Lw.Cla,BOTTOM:a.Lw.pla};a.n1={Cka:256,A_a:512,z_a:1024};a.n1.v={LEFT:a.n1.Cka,RIGHT:a.n1.A_a,CENTER:a.n1.z_a};a.o1={vCa:4096,M9a:8192,JKb:16384};a.o1.v={TOP:a.o1.vCa,BOTTOM:a.o1.M9a,CENTER:a.o1.JKb};a.Flb={Jke:0,IKb:65536};a.VK={M0b:15,U0b:240,S0b:3840,$0b:61440,$Rd:983040,N0b:15728640,Q0b:251658240,T0b:4026531840};
a.gD={iid:0,L3a:256,M3a:512,$Ma:1024,K3a:2048};a.tj={xlb:1,rlb:2,GXa:4,Alb:8,Blb:16,wlb:32,zlb:64,IXa:128,HXa:65536,Y0b:131072,Clb:262144,vlb:524288,X0b:3840,V0b:61440,Yta:4026531840};c.Nca=function(b){h.K.call(this);this.Jqa=b;this.xq(!1);this.mtc(p);this.bl(t);this.Pj(m);this.qo(q);this.iOa(!0);this.Tc&=~a.Xd.uS;this.Tc&=~a.Xd.j1};var h=c.u(c.Nca,c.$l);h.Nb=b.zO();h.oh=0;h.nh=150;h.oj=0;h.nj=0;h.kDa=150;h.jDa=0;h.pb=null;h.JKd=null;h.RZ=null;h.yu=null;h.xC=null;h.rv=a.Rp.Mia;h.ce=null;h.uo=0;h.gg=
0;h.RNb=null;h.QNb=null;h.PNb=null;h.NOb=null;h.MOb=null;h.AQ="";h.VDa="";h.mEa="";h.mQ=null;h.Fd=h.Fd|a.uc.RKa|a.uc.gxa|a.uc.l1|a.uc.dla|a.uc.TKa;h.uo=a.Nm.UF|a.Lw.Sca|a.n1.Cka|a.o1.JKb;h.gg=a.tj.GXa|a.tj.IXa|a.gD.$Ma|a.tj.HXa;h.nb=function(){b.ga(this.ce);h.k.nb.call(this)};h.R=function(){h.k.R.call(this);this.ROa(null);this.Tma();this.JKd=null;this.sea(null);b.ga(this.RZ);this.RZ=null;b.ga(this.mQ);this.mQ=null};h.zw=function(){return this.Jqa.zw()};h.n4b=function(){return this.uo&a.VK.S0b};h.uW=
function(){return this.uo&a.VK.U0b};h.iL=function(){return this.gg&a.tj.X0b};h.o4b=function(){return this.uo&a.VK.$0b};h.nea=function(b){this.AQ!=b&&(this.AQ=b,this.ci(),this.pa(a.g.j))};h.yZa=function(){return this.AQ};h.Bua=function(){var a=[""],b=this.nc();b&&b.X4a(a);return a[0]};h.wtd=function(b){b|=this.uo&~a.VK.S0b;this.uo!=b&&(this.uo=b,this.xb(),this.pa(a.g.j),this.Jg())};h.Ztc=function(b){b|=this.gg&~a.tj.X0b;this.gg!=b&&(this.gg=b,this.xb(),this.pa(a.g.j),this.sKb(),this.Jg())};h.xtd=function(b){b|=
this.uo&~a.VK.U0b;this.uo!=b&&(this.uo=b,this.xb(),this.pa(a.g.j),this.Jg())};h.Kmd=function(){var b=new c.qa(0,0,0,0);if(this.uW()!=a.Lw.Gxa){for(var b=this.xf(),d=b.Ka(),e=b.Fa(),h=0,l=0,m,p=this.pg,q=0;q<p.length&&null!=(m=p[q]);q++)if(m!=this.jf())var s=m.Xl(),d=Math.min(d,s.aa()),e=Math.min(e,s.$()),h=Math.max(h,s.Ka()),l=Math.max(l,s.Fa());switch(this.uW()){case a.Lw.Gxa:b.Vh(d,b.la());break;case a.Lw.Sca:b.Vh(d,b.la());break;case a.Lw.Ela:b.Vh(b.ja(),e);break;case a.Lw.Cla:b.h5a(h,0);break;
case a.Lw.pla:b.h5a(0,l)}}return b};h.Znb=function(){return(this.uo&a.VK.T0b)>>28};h.mtc=function(b){b=this.uo&~a.VK.T0b|b<<28;this.uo!=b&&(this.uo=b,this.xb(),this.pa(a.g.j),this.Jg())};h.mob=function(){return this.uo&a.VK.M0b};h.Atd=function(b){b|=this.uo&~a.VK.M0b;this.uo!=b&&(this.uo=b,this.xb(),this.Id(),this.pa(a.g.j),this.Jg())};h.SIa=function(){var b;switch(this.mob()){case a.Nm.UF:case a.Nm.N4:case a.Nm.UGa:b=this.rb().Nda(this.mob(),a.p6.P_a);break;case a.Nm.oN:b=this.ab()}return b};h.Btd=
function(b){b|=this.uo&~a.VK.$0b;this.uo!=b&&(this.uo=b,this.xb(),this.Id(),this.pa(a.g.j),this.Jg())};h.$0c=function(){return this.nj};h.Ktd=function(b){this.nj!=b&&(this.nj=b,this.zCa(32767,32767),b=0,this.uW()==a.Lw.pla&&(this.e1()&&this.iL()==a.gD.K3a&&(b=17),this.jDa=this.nj,this.jDa+=b),this.xb(!0),this.Jg(),this.pa(a.g.j))};h.a1c=function(){return this.nh};h.Ftc=function(b){this.nh!=b&&(this.nh=b,this.zCa(32767,32767),b=0,this.uW()==a.Lw.Sca&&(this.e1()&&this.iL()==a.gD.L3a&&(b=17),this.kDa=
this.nh,this.kDa+=b),this.xb(!0),this.Jg(),this.pa(a.g.j))};h.b1c=function(){return this.oj};h.Ntd=function(b){this.oj!=b&&(this.oj=b,this.zCa(32767,32767),b=0,this.uW()==a.Lw.Cla&&(this.e1()&&this.iL()==a.gD.$Ma&&(b=17),this.kDa=this.oj,this.kDa+=b),this.xb(!0),this.Jg(),this.pa(a.g.j))};h.c1c=function(){return this.oh};h.Ptd=function(b){this.oh!=b&&(this.oh=b,this.zCa(32767,32767),b=0,this.uW()==a.Lw.Ela&&(this.e1()&&this.iL()==a.gD.M3a&&(b=17),this.jDa=this.oh,this.jDa+=b),this.xb(!0),this.Jg(),
this.pa(a.g.j))};h.$g=function(){var b=0,b=this.nj;this.e1()&&this.iL()==a.gD.K3a&&(b+=17);return b};h.Sf=function(){var b=0,b=this.nh;this.e1()&&this.iL()==a.gD.L3a&&(b+=17);return b};h.Wg=function(){var b=0,b=this.oj;this.e1()&&this.iL()==a.gD.$Ma&&(b+=17);return b};h.Jf=function(){var b=0,b=this.oh;this.e1()&&this.iL()==a.gD.M3a&&(b+=17);return b};h.Af=function(){return 0!=(this.gg&a.tj.xlb)?!0:!1};h.di=function(b){b=this.gg&~a.tj.xlb|(b?a.tj.xlb:0);this.gg!=b&&(this.gg=b,this.Dd(a.ea.gLa),this.pa(a.g.j))};
h.d2c=function(){return 0!=(this.gg&a.tj.wlb)?!0:!1};h.bhe=function(b){b=this.gg&~a.tj.wlb|(b?a.tj.wlb:0);this.gg!=b&&(this.gg=b)};h.l1d=function(){return 17};h.nka=function(){return this};h.e2c=function(){var e=null;if(this.e1()){var f=this.nka();null==f.gG()&&(null==this.mQ&&(d.Ob("PRIM_PPNL"),this.mQ=new c.Ux),f.oA(this.mQ),f.gG().za(this,a.Q.Yx,this.QPc),this.urc());e=this.RZ}else f=this.nka(),null!=f.gG()&&(f.gG().za(this,a.Q.Yx,null),f.oA(null)),b.ga(this.RZ),this.RZ=null;return e};h.rb=function(){if(null==
this.pb){var b=this.Jqa;this.rU||0!=(this.gg&a.tj.Y0b)?(b.T5a(!1),this.yCa(b),b.l8(this.PJa()),b.T5a(!this.PJa())):b.T5a(!0);this.BJ(this.pb,b);this.pb=b}return this.pb};h.Hx=function(){return null};h.TR=function(){var a=null;this.jf()&&(a=this.jf().ha);return a};h.Aba=function(){var a=null;this.Hx()&&(a=this.Hx().Gh());return a};h.tna=function(b){this.Hx()&&this.Hx().Gh()!=b&&(this.Hx().Jb(b),this.m(a.g.j))};h.Mba=function(){var a=null;this.TR()&&(a=this.TR().Gh());return a};h.xna=function(b){this.TR()&&
this.TR().Gh()!=b&&(this.TR().Jb(b),this.m(a.g.j))};h.QYa=function(){var a=null;this.Hx()&&(a=this.Hx().pp());return a};h.J5a=function(b){this.Hx()&&this.Hx().pp()!=b&&(this.Hx().Bp(b),this.m(a.g.j))};h.OYa=function(){var a=null;this.Hx()&&(a=this.Hx().bB());return a};h.I5a=function(b){this.Hx()&&this.Hx().bB()!=b&&(this.Hx().UG(b),this.m(a.g.j))};h.cZa=function(){var a=null;this.TR()&&(a=this.TR().pp());return a};h.a6a=function(b){this.TR()&&this.TR().pp()!=b&&(this.TR().Bp(b),this.m(a.g.j))};h.Jua=
function(){null==this.RNb&&(this.RNb=new c.Nw(this.Hx(),a.fh.J1));return this.RNb};h.RYa=function(){null==this.QNb&&(this.QNb=new c.Nw(this.Hx(),a.fh.I1));return this.QNb};h.PYa=function(){null==this.PNb&&(this.PNb=new c.Nw(this.Hx(),a.fh.uda));return this.PNb};h.eZa=function(){null==this.NOb&&(this.NOb=new c.Nw(this.TR(),a.fh.J1));return this.NOb};h.dZa=function(){null==this.MOb&&(this.MOb=new c.Nw(this.TR(),a.fh.I1));return this.MOb};h.LZc=function(){return this.VDa};h.wsd=function(b){this.VDa!=
b&&(this.VDa=b,this.xQa(),this.pa(a.g.j))};h.i0c=function(){return this.mEa};h.ztd=function(b){this.mEa!=b&&(this.mEa=b,this.xQa(),this.pa(a.g.j))};h.Nu=function(){return this.Af()};h.z6d=function(){return this.Zd()};h.e1=function(){return this.eca()?this.n0a()?!0:this.d2c():!1};h.n0a=function(){return!1};h.A6d=function(){var b=!1;this.uW()==a.Lw.Sca&&this.iL()==a.gD.L3a?b=!0:this.uW()==a.Lw.Cla&&this.iL()==a.gD.$Ma&&(b=!0);return b};h.B6d=function(){var b=!1;this.uW()==a.Lw.Ela&&this.iL()==a.gD.M3a?
b=!0:this.uW()==a.Lw.pla&&this.iL()==a.gD.K3a&&(b=!0);return b};h.d0=function(){return 0!=(this.gg&a.tj.rlb)?!0:!1};h.aea=function(b){b=this.gg&~a.tj.rlb|(b?a.tj.rlb:0);this.gg!=b&&(this.gg=b,this.ci(),this.pa(a.g.j))};h.qm=function(){return 0!=(this.gg&a.tj.GXa)?!0:!1};h.po=function(b){b=this.gg&~a.tj.GXa|(b?a.tj.GXa:0);this.gg!=b&&(this.gg=b,this.ci(),this.pa(a.g.j))};h.Xj=function(){return 0!=(this.gg&a.tj.Alb)?!0:!1};h.Ym=function(b){b=this.gg&~a.tj.Alb|(b?a.tj.Alb:0);this.gg!=b&&(this.gg=b,this.ci(),
this.pa(a.g.j))};h.Nx=function(){return 0!=(this.gg&a.tj.Blb)?!0:!1};h.Yu=function(b){b=this.gg&~a.tj.Blb|(b?a.tj.Blb:0);this.gg!=b&&(this.gg=b,this.ci(),this.pa(a.g.j))};h.ud=function(){return 0!=(this.gg&a.tj.Clb)?!0:!1};h.Ff=function(b){b=this.gg&~a.tj.Clb|(b?a.tj.Clb:0);this.gg!=b&&(this.gg=b,this.ci(),this.pa(a.g.j))};h.eca=function(){return 0!=(this.gg&a.tj.zlb)?!0:!1};h.uAa=function(b){b=this.gg&~a.tj.zlb|(b?a.tj.zlb:0);this.gg!=b&&(this.gg=b,this.ci(),this.pa(a.g.j))};h.h0c=function(){return 0!=
(this.gg&a.tj.vlb)?!0:!1};h.ytd=function(b){var c=this.gg&~a.tj.vlb|(b?a.tj.vlb:0);this.gg!=c&&(this.gg=c,this.jf().muc(b),this.pa(a.g.j))};h.mJa=function(){return 0!=(this.gg&a.tj.HXa)?!0:!1};h.PEb=function(b){b=this.gg&~a.tj.HXa|(b?a.tj.HXa:0);this.gg!=b&&(this.gg=b,this.fHd(),this.pa(a.g.j))};h.PJa=function(){return 0!=(this.gg&a.tj.IXa)?!0:!1};h.Jwd=function(b){if(this.PJa()!=b){var c=null!=this.pb;this.l8(b);this.Tma();c&&this.rb();this.ci();this.pa(a.g.j)}};h.l8=function(b){b=this.gg&~a.tj.IXa|
(b?a.tj.IXa:0);this.gg!=b&&(this.gg=b,this.pa(a.g.j))};h.ej=function(){return(this.uo&a.VK.Q0b)>>24};h.bl=function(b){b=this.uo&~a.VK.Q0b|b<<24;this.uo!=b&&(this.uo=b,this.ci(),this.pa(a.g.j))};h.Vg=function(){return(this.uo&a.VK.N0b)>>20};h.Pj=function(b){b=this.uo&~a.VK.N0b|b<<20;this.uo!=b&&(this.uo=b,this.ci(),this.pa(a.g.j))};h.um=function(){return(this.gg&a.tj.V0b)>>12};h.qo=function(b){b=this.gg&~a.tj.V0b|b<<12;this.gg!=b&&(this.gg=b,this.ci(),this.pa(a.g.j))};h.eG=function(){return b.ES()};
h.GZa=function(){return this.yu};h.sea=function(b){this.yu!=b&&(null!=this.yu&&(this.yu.ub(),this.yu.Ha(this)),this.yu=b,null!=this.yu&&(this.yu.Ba(),this.yu.Ia(this,this.aXa)),this.urc(),this.Jg(),this.pa(a.g.j))};h.ROa=function(b){this.xC!=b&&(null!=this.xC&&this.xC.Ha(this),this.xC.vk(b),null!=this.xC&&this.xC.Ia(this,this.xSc),this.tk(!0),this.pa(a.g.j))};h.Lpb=function(){return this.xC};h.vg=function(b){this.rv!=b&&(this.rv=b,this.jf()&&this.jf().vg(b),this.Jg(),this.pa(a.g.j))};h.Se=function(){return this.rv};
h.kb=function(){return this.rb().kb()};h.ob=function(a){this.rb().ob(a)};h.Ee=function(){this.Ga(a.Q.Dh)};h.wSd=function(){};h.X0=function(){this.Wv(this,a.ea.Hub)};h.qUb=function(){this.Jua().bt(s)};h.rtc=function(){null==s&&(s=new c.yb,s.hr(a.o.jJ),s.ir(2),s.wq(2),s.Oo(2),s.Po(2));this.Jua().Zh(s)};h.p_=function(){return this};h.fHd=function(){this.RZ&&this.RZ.Pe(this.mJa())};h.urc=function(){var a=this.yu;null==a&&(a=b.ba().pva());this.RZ&&this.RZ.Bd(a);this.nka().sJ(a)};h.lf=function(){var a=
this.e2c();if(a){var b=this.dgd();a.sb(b)}this.jf()&&(a=this.Kmd(),this.AQa(),this.jf().sb(a))};h.AQa=function(){var b=this.SIa(),c=this.jf();if(c){c.tb(b);c.Qg(this.te());switch(this.n4b()){case a.n1.Cka:c.Wb(a.Bh.qaa);break;case a.n1.A_a:c.Wb(a.Bh.GK);break;case a.n1.z_a:c.Wb(a.Bh.BC)}switch(this.o4b()){case a.o1.vCa:c.Ro(a.gh.sY);break;case a.o1.M9a:c.Ro(a.gh.rM);break;case a.o1.JKb:c.Ro(a.gh.Bq)}}};h.jf=function(){null==this.ce&&this.Zd()&&(d.Ob("PRIM_LABL"),this.ce=new c.Ow,this.ce.Oa(this),
this.ce.Ff(!1),this.ce.Pe(!1),this.ce.xq(!1),this.ce.vg(this.Se()),this.ce.we(5),this.Xb()&&this.ce.jh());return this.ce};h.Cua=function(){return b.ES()};h.dgd=function(){var b=this.Cua(),d;switch(this.iL()){case a.gD.iid:d=new c.qa(b.aa(),b.$(),0,0);break;case a.gD.L3a:d=new c.qa(b.aa()-17,b.$(),17,b.la());break;case a.gD.$Ma:d=new c.qa(b.Ka(),b.$(),17,b.la());break;case a.gD.M3a:d=new c.qa(b.aa(),b.$()-17,b.ja(),17);break;case a.gD.K3a:d=new c.qa(b.aa(),b.Fa(),b.ja(),17)}return d};h.Tma=function(){var a=
this.pb;this.pb=null;this.BJ(a,null)};h.yCa=function(a){this.PJa()&&null==a.ez()&&this.l8(!1)};h.BJ=function(){};h.ip=function(b,c,d,e,l){if(d==a.Q.nB||d==a.Q.rB||d==a.Q.HG||d==a.Q.IG||d==a.Q.bJ||this.Zd()&&d==a.Q.Oq)return l;b==this.RZ&&d==a.Q.tc&&(this.xe().rI()!=this.RZ||this.mJa()||this.xe().VE(this),this.cxd(),l=!0);return h.k.ip.call(this,b,c,d,e,l)};h.Qz=function(){var a=null;this.kB()&&this.jO()&&(a=this);return a};h.zCa=function(a,c){this.nh=b.Mf(this.nh,-a,a);a=0<=this.nh?a-this.nh:a+this.nh;
this.oj=b.Mf(this.oj,-a,a);this.oh=b.Mf(this.oh,-c,c);c=0<=this.oh?c-this.oh:c+this.oh;this.nj=b.Mf(this.nj,-c,c)};h.Fma=function(){this.AQa();h.k.Fma.call(this)};h.Bma=function(){this.AQa();h.k.Bma.call(this)};h.ita=function(){var a=this.zw();return a&&(a=a.tv)?new c.Bxa(a):null};h.Ed=function(){this.dN(a.uc.vS,this.oS());h.k.Ed.call(this)};h.xQa=function(){};h.QPc=function(a,b){this.WXa();b.uk("CONTINUE",!1)};h.xSc=function(b,c){c.eb==a.g.Ub?this.ROa(null):c.eb==a.g.j&&this.tk(!0)};h.aXa=function(b,
c){switch(c.eb){case a.g.Bb:case a.g.Ub:c.Ej==this.yu&&this.sea(null);break;case a.g.j:c.Ej==this.yu&&this.Jg()}};h.akb=h[a.ea.gLa]=function(){this.ci()};h.OYb=h[a.ea.Hub]=function(){var a=null!=this.pb;this.Tma();a&&this.rb();this.ci()};h.FC=h[a.ea.wS]=function(a){this.Vn()||this.ZHa();h.k.FC.call(this,a)};h.GC=h[a.ea.xS]=function(a){var b=a.ad;this.Sia();b.ng()&&h.k.GC.call(this,a)};h.$Qc=h[a.ea.Jac]=function(a){this.e1()&&(this.cxd(),a.Uf=!0)};h.AR=h[a.ea.CE]=function(){this.xb();this.Jg()};h.pHa=
h[a.ea.jLa]=function(b){var c=!1,d="";switch(this.Znb()){case a.Nm.UF:case a.Nm.N4:case a.Nm.UGa:this.rb().Nda(this.Znb(),a.p6.Yqb,d);break;case a.Nm.oN:d=this.bL()}""!=d&&(b.pd.fb=d,c=!0);c||h.k.pHa.call(this,b)};d.Md(c.Nca,"PRIM_EVP",{dE:"PRIM_CTRL",Aa:{Placeholder:{a:h.yZa,f:function(a){this.nea(d.ka(a))}},UsePicklist:{a:h.PJa,f:function(a){this.Jwd(d.Ca(a))}},LabelSelectable:{a:h.h0c,f:function(a){this.ytd(d.Ca(a))}},MarginLeft:{a:h.a1c,f:function(a){this.Ftc(d.O(a))}},MarginTop:{a:h.c1c,f:function(a){this.Ptd(d.O(a))}},
MarginBottom:{a:h.$0c,f:function(a){this.Ktd(d.O(a))}},MarginRight:{a:h.b1c,f:function(a){this.Ntd(d.O(a))}},Caption:{a:h.ab,f:function(a){this.tb(d.ka(a))}},HintType:{a:h.Znb,f:h.mtc},LabelType:{a:function(){return d.va(this.mob(),a.Nm.v)},f:function(b){this.Atd(d.wa(b,a.Nm.v))}},LabelText:{a:h.SIa},LabelPosition:{a:function(){return d.va(this.uW(),a.Lw.v)},f:function(b){this.xtd(d.wa(b,a.Lw.v))}},LabelHorAlignment:{a:function(){return d.va(this.n4b(),a.n1.v)},f:function(b){this.wtd(d.wa(b,a.n1.v))}},
LabelVerAlignment:{a:function(){return d.va(this.o4b(),a.o1.v)},f:function(b){this.Btd(d.wa(b,a.o1.v))}},ReadOnly:{a:h.Af,f:function(a){this.di(d.Ca(a))}},Ellipses:{a:h.Se,f:h.vg},EditThemeDrawStyle:{a:h.LZc,f:function(a){this.wsd(d.ka(a))}},LabelThemeDrawStyle:{a:h.i0c,f:function(a){this.ztd(d.ka(a))}}}});var e=h;e.aD=e.applyDefault=function(){this.rb().raa()}});
