window.LANSA.addSrc("imag",function(d,c,a,b){c.bu=function(){p.K.call(this);this.xr="";this.xc=this.pb=this.QB=this.Hab=this.OY=this.of=this.uf=null;this.x3=a.ae.HAa;this.wga=null;this.LJ=this.kK=this.dK=this.CK=0;this.Fd|=a.uc.RKa;this.of=new c.mX;this.uf=new c.yb;this.uf.Ld(this.of);this.Pe(!1)};var p=c.u(c.bu,c.$l);p.vZ="";p.nb=function(){b.ga(this.wga);this.wga=null;b.ga(this.of);this.of=null;b.ga(this.uf);this.uf=null;p.k.nb.call(this)};p.R=function(){p.k.R.call(this);this.aAa(null);this.Hab=
null;this.Nj(null);this.Aq(null)};p.Be=function(){return this.Ew()?c.rlc:p.k.Be.call(this)};p.Ng=function(){return this.xr};p.Uu=function(c){b.Sx(this.xr,c)||(this.xr=c,this.aAa(b.bya(this.xr)),this.m(a.g.j))};p.sWd=function(){return this.OY};p.aAa=function(b){this.OY!=b&&(this.Nj(null),null!=this.OY&&this.OY.Ha(this,this.tXb),this.OY=b,null!=this.OY&&this.OY.Ia(this,this.tXb),this.CP(),this.xb(),this.m(a.g.j))};p.YK=function(){return this.QB};p.Nj=function(b){this.QB!=b&&(this.aAa(null),null!=this.QB&&
(this.QB.Ha(this,this.lp),this.QB.ub()),this.QB=b,null!=this.QB&&(this.QB.Ba(),this.QB.Ia(this,this.lp)),this.CP(),this.xb(),this.Id(),this.m(a.g.j))};p.rW=function(){return this.of.Qm()};p.kT=function(b){this.of.Qm()!=b&&(this.of.Rg(b),this.m(a.g.j))};p.HN=function(){return this.of.ve()};p.oP=function(b){this.of.ve()!=b&&(this.of.Za(b),this.m(a.g.j))};p.KN=function(){return this.of.Te()};p.pP=function(b){this.of.Te()!=b&&(this.of.Xa(b),this.m(a.g.j))};p.dL=function(){return this.of.Ua()};p.WG=function(b){this.of.Ua()!=
b&&(this.of.qc(b),this.m(a.g.j))};p.Lv=function(){return this.of.Na()};p.gu=function(b){this.of.Na()!=b&&(this.of.yc(b),this.m(a.g.j))};p.uE=function(){return this.x3};p.XE=function(b){this.x3!=b&&(this.x3=b,this.of.fc(b),this.xb(),this.Id(),this.m(a.g.j))};p.JN=function(){return this.of.w0()};p.vJ=function(b){this.of.w0()!=b&&(this.of.yea(b),this.m(a.g.j))};p.LN=function(){return this.of.wj()};p.qP=function(b){this.of.wj()!=b&&(this.of.Mk(b),this.m(a.g.j))};p.dB=function(){return this.of.li()};p.CB=
function(b){this.of.li()!=b&&(this.of.Wb(b),this.m(a.g.j))};p.Jh=function(b){this.pb!=b&&(this.Aq(b),this.m(a.g.j))};p.rb=function(){var a=null;return a=this.pb};p.nc=function(){return this.xc};p.Jf=function(){return this.CK};p.Ef=function(c){this.CK!=c&&(this.CK=c,this.xb(),this.Id(),b.qb().ee(this,!1),this.pa(a.g.j))};p.Sf=function(){return this.dK};p.Bf=function(c){this.dK!=c&&(this.dK=c,this.xb(),this.Id(),b.qb().ee(this,!1),this.pa(a.g.j))};p.Wg=function(){return this.kK};p.we=function(c){this.kK!=
c&&(this.kK=c,this.xb(),this.Id(),b.qb().ee(this,!1),this.pa(a.g.j))};p.$g=function(){return this.LJ};p.jg=function(c){this.LJ!=c&&(this.LJ=c,this.xb(),this.Id(),b.qb().ee(this,!1),this.pa(a.g.j))};p.Tp=function(){return this.vZ};p.W7=function(b){this.vZ!=b&&(this.vZ=b,this.ci(),this.pa(a.g.j))};p.ip=function(a,b,c,d,e){return e};p.$Q=function(){var a=this.xc.pk();""!=a?this.OY&&this.OY.Ng()==a||this.aAa(b.bya(a)):this.aAa(this.xc.QJa());this.pb.T_(this.nc())};p.Aq=function(a){var c=null;a&&(c=a.Kz(),
this.pb==a?c.Kn(this.xc):a.EC(c));this.pb&&(this.pb.Ha(this),this.xc.Ha(this),b.ga(this.xc),this.xc=null);if(this.pb=a)this.pb.Ia(this,this.Qp),this.xc=c,this.xc.Ia(this,this.Py);this.ci()};p.CP=function(){null==this.QB?this.of.Bd(this.OY):this.Hab&&0<this.Hab.Ng().length?this.of.Bd(this.Hab):this.of.Bd(this.QB)};p.lf=function(b){p.k.lf.call(this,b);this.Ew()||(b=new c.qa(0,0,b.ja(),b.la()),this.wga||(this.wga=new c.$l,this.wga.Pe(!1)),this.wga.qAa(this.uf),b.Xa(b.$()+this.Jf()),b.Za(b.aa()+this.Sf()),
b.Va(b.Ka()-this.Wg()),b.Ja(b.Fa()-this.$g()),this.wga.Ib(this),this.wga.sb(b),this.uE()==a.ae.HAa&&this.of.Zc()&&(this.of.Zc().Na()>b.la()||this.of.Zc().Ua()>b.ja()?this.of.fc(a.ae.hM):this.of.fc(a.ae.tf)))};p.fD=function(b){var d=this.Mo(),s=this.qq();if(0!=this.KN()||0!=this.HN()||100!=this.dL()||100!=this.Lv()||this.JN()!=a.Ht.Rea||this.LN()!=a.Ly.bfa||this.of.wi()==a.ae.r7a)s=d=!1;if(d||s){var h=new c.qa;if(this.of.Zc())switch(h.Va(this.of.Zc().Ua()),h.Ja(this.of.Zc().Na()),this.of.wi()){case a.ae.hM:if(s&&
!d&&0<b.ja()&&0<h.ja()){var e=b.ja()/h.ja();h.Ja(h.$()+h.la()*e)}}d&&b.Va(b.aa()+this.ha.Mi()+this.Sf()+h.ja()+this.Wg()+this.ha.Hj());s&&b.Ja(b.$()+this.ha.Vj()+this.Jf()+h.la()+this.$g()+this.ha.kl())}};p.hf=function(c){b.T1a();c=p.k.hf.call(this,c);if(!c){var d=this.Tp();b.Ywa(d)&&b.ba().dn&&b.Fg().KW().Hda({mx:b.Laa(d,!0),xY:!0,OT:!0,QM:a.KE.h1a})}return c};p.lp=function(b,c){switch(c.eb){case a.g.Bb:case a.g.Ub:this.Nj(null);break;case a.g.j:this.xb(),this.Id()}};p.tXb=function(b,c){switch(c.eb){case a.g.Bb:case a.g.Ub:this.aAa(null);
break;case a.g.j:this.xb()}};p.Qp=function(b,c){c.eb==a.g.j?c.xu==a.Ke.fA?this.pb.EC(this.nc()):this.Aq(this.pb):c.eb==a.g.Bb&&this.Jh(null)};p.Py=function(b,c){c.eb==a.g.j&&c.xu==a.Ke.fA&&this.$Q()};d.Md(c.bu,"PRIM_IMAG",{Aa:{FileName:{a:p.Ng,f:function(a){this.Uu(d.ka(a))}},Image:{a:p.YK,f:function(a){this.Nj(a)}},ImageTile:{a:function(){return d.va(this.JN(),a.Ht.v)},f:function(b){this.vJ(d.wa(b,a.Ht.v))}},ImageUnits:{a:function(){return d.va(this.LN(),a.Ly.v)},f:function(b){this.qP(d.wa(b,a.Ly.v))}},
ImageSizing:{a:function(){return d.va(this.uE(),a.ae.v)},f:function(b){this.XE(d.wa(b,a.ae.v))}},ImageOpacity:{a:p.rW,f:function(a){this.kT(d.O(a))}},ImageLeft:{a:p.HN,f:function(a){this.oP(d.O(a))}},ImageTop:{a:p.KN,f:function(a){this.pP(d.O(a))}},ImageWidth:{a:p.dL,f:function(a){this.WG(d.O(a))}},ImageHeight:{a:p.Lv,f:function(a){this.gu(d.O(a))}},ImageAlignment:{a:function(){return d.va(this.dB(),a.Jc.v)},f:function(b){this.CB(d.wa(b,a.Jc.v))}},DataClass:{a:p.rb,f:p.Jh},MarginLeft:{a:p.Sf,f:function(a){this.Bf(d.O(a))}},
MarginTop:{a:p.Jf,f:function(a){this.Ef(d.O(a))}},MarginBottom:{a:p.$g,f:function(a){this.jg(d.O(a))}},MarginRight:{a:p.Wg,f:function(a){this.we(d.O(a))}},Link:{a:p.Tp,f:function(a){this.W7(d.ka(a))}}}});c.rlc=function(a){t.K.call(this,a)};var t=c.u(c.rlc,c.HL);t.rsa=null;t.GEc="";t.QRb=null;t.Cqb=function(){return!1};t.rKb=function(a){this.QRb&&(a="0");t.k.rKb.call(this,a)};t.dAa=function(){this.QRb=!0;this.Lc()};t.Lc=function(){var c=this.L.of.Zc()?this.L.of.Zc().Ng():this.L.Ng(),q=this.L.uE();
q==a.ae.HAa&&(q=a.ae.Sg);t.k.Lc.call(this);""!=this.L.Tp()&&(this.G.href=b.Laa(this.L.Tp()));this.GEc!=c&&(this.GEc=c,this.QRb=!1,this.rsa.src=c);this.jEb(this.rsa,d.va(this.L.dB(),a.Jc.v),d.va(q,a.ae.am))};t.Hd=function(){""!=this.L.Tp()?(this.G=document.createElement("a"),this.G.setAttribute("LANSAHandle",this.hc),this.rsa=document.createElement("img"),this.rsa.style.width="100%",this.G.appendChild(this.rsa)):(this.G=document.createElement("img"),this.G.setAttribute("LANSAHandle",this.hc),this.rsa=
this.G);var a=this;a.rsa.addEventListener("error",function(){a.L&&a.dAa()},!1);return this.G}});
