window.LANSA.addSrc("wrtn",function(d,c,a,b,p){function t(a){return null===a?d.ed:"object"==typeof a?a.mimetype&&a.data&&a.filename?new c.WI(a):"":a}function m(a){if(a===d.ed)return null;switch(typeof a){case "object":if(a instanceof c.qk)return a.toString();if(c.ar&&a instanceof c.ar)return a.Jxc();if(a instanceof c.WI)return a.iEa}return a}function q(b,c,d){var e=document.createElement("form");e.setAttribute("method","post");e.setAttribute("action",b);d==a.O2.mwc&&e.setAttribute("target","_blank");
for(var f in c)c.hasOwnProperty(f)&&(b=document.createElement("input"),b.setAttribute("type","hidden"),b.setAttribute("name",f),b.setAttribute("value",c[f]),e.appendChild(b));document.body.appendChild(e);e.submit()}function s(a){return(a=a.sm)&&"M"==a}function h(a,b){u&&b.append("_SESSIONKEY",u);var e=a.FLD;if(e!==p)for(var f in e){var l=e[f];if(l===d.ed)return!1;l instanceof c.WI?b.append(f,l.Yua(),l.Ng()):b.append(f,m(l))}e=a.LIST;if(e!==p)for(var k in e){for(var h=e[k],r=h.bq={},q=h.entryCount(),
s=1;s<=q;s++)for(f in h.getEntry(s),1==s&&b.append(k+"..",1),r){l=s.toString();4>l.length&&(l="000"+l,l=l.substr(l.length-4));var t=k+"."+l+"."+f,l=r[f];if(l===d.ed)return delete h.bq,!1;l instanceof c.WI?b.append(t,l.Yua(),l.Ng()):b.append(t,m(l))}delete h.bq}return!0}function e(a,b){var c=b.webroutine={},d=c.context={};u&&(d["session-key"]=u);A&&(d["session-key-name"]=A);l&&(d["session-key-method"]=l);d=a.FLD;if(d!==p){var e=c.fields={},f;for(f in d)(e[f]={}).value=m(d[f])}d=a.LIST;if(d!==p){var c=
c.lists={},k;for(k in d){for(var h=c[k]={},e=h.header=[],h=h.entries=[],r=d[k],q=r.bq={},s=r.entryCount(),t=1;t<=s;t++){r.getEntry(t);if(1==t)for(f in q){var E={};e.push(E);E.name=f}E=[];h.push(E);for(f in q)E.push(m(q[f]))}delete r.bq}}}function k(a){if(a=a.context){var b=a["session-key"];b!=p&&""!=b&&b!=u&&b!=r&&(r=u,u=b,A=a["session-key-name"],l=a["session-key-method"])}}function f(a,b,c){function e(a){if(a!=p){var b=a.FLD;f(a.LIST);f(b)}}function f(b){if(b!=p)for(var c in b)if(null===b[c])throw d.yld(c,
a.ZEa,a.YEa);}e(b);e(c)}var u=p,A=p,l="hidden",r=p;a.O2={rHb:0,mwc:1};a.O2.v={CURRENT:a.O2.rHb,NEW:a.O2.mwc};d.Md(function(){},"PRIM_WRTN",{});c.zkc=function(){E.K.call(this)};var E=c.u(c.zkc,c.qd);E.K5=function(){return u!==p?u:""};E.Z5a=function(a){u=a;r=p};E.KCb=function(){var a=b.Fg().lZa();if(a.rua()){var c="lansa-session-"+b.YIa(),d=JSON.stringify({key:this.K5()});if(a.Zh(c,d))return!0}return!1};E.vCb=function(){var a=b.Fg().lZa();if(a.rua()&&(a=a.Jx("lansa-session-"+b.YIa()))){var c=null;try{c=
JSON.parse(a.kb())}catch(d){c=null}if(c)return this.Z5a(c.key),!0}return!1};E.Uk=function(){var a=b.Fg().lZa();a.rua()&&a.bt("lansa-session-"+b.YIa());l=A=u=p};d.Sa(c.zkc,"PRIM_WEB","Session",{Aa:{Key:{a:E.K5}},jc:{Save:E.KCb,Restore:E.vCb,Clear:E.Uk}});c.oMa=function(a,b){D.K.call(this);this.ZEa=a;this.YEa=b;this.vPb=this.wOb=""};var D=c.u(c.oMa,c.qd);D.oZd=function(){return this.wOb};D.Lge=function(a){this.wOb=a};D.I0d=function(){return this.vPb};D.Zge=function(a){this.vPb=a};D.d3c=function(){return this.ZEa};
D.M2c=function(){return this.YEa};D.Zz=function(){return b.QMc(this.wOb,b.xIa(),this.ZEa,this.YEa,this.y2c())};D.y2c=function(){var a=this.vPb;""==a&&(a=b.wIa());return a};d.Sa(c.oMa,"PRIM_WEB","ServerRequest",{Aa:{ServerModule:{a:D.d3c},Routine:{a:D.M2c}}});c.Oxa=function(a,b){x.K.call(this,a,b)};var x=c.u(c.Oxa,c.oMa);x.Z_=function(a,b){this.k1b(a,b,!1,null)};x.Y4=function(a,c){this.k1b(a,c,!0,b.dY())};x.k1b=function(c,m,r,q){function E(c){var e=null;try{e=JSON.parse(c)}catch(f){e=null}if(e){if(c=
e.webroutine)if(c=c.messages)for(var h=d.j1c(),r=0;r<c.length;r++)h.Zh(c[r],null);if(c=e["vlweb-error"]){var s=a.vY.bYa;switch(c["message-id"]){case "HM42":case "HM43":s=a.vY.n2b;l=A=u=p;break;case "HM05":s=a.vY.m2b}s=J.XHa(s);if(!s&&c.message!==p)throw d.eCb(J.ZEa,J.YEa,c.message);}else{h=m;if(e=e.webroutine){r=h.FLD;if(r!==p){var D=e.fields;if(D)for(var x in r)c=D[x],c!==p&&(c=t(c.value),r[x].set(c))}x=h.LIST;if(x!==p&&(h=e.lists))for(s in x)if(r=x[s],r.Sj(),c=h[s])for(var D=c.header,y=c.entries,
z=0;z<y.length;z++){for(var C=r.bq={},K=y[z],L=0;L<K.length;L++)c=t(K[L]),C[D[L].name]=c;r.Ag();delete r.bq}k(e)}J.c5()}}else if(s=J.XHa(a.vY.bYa),!s)throw d.eCb(J.ZEa,J.YEa,"Invalid JSON");b.EB(q)}function D(c){if(!J.XHa(a.vY.bYa))throw d.eCb(J.ZEa,J.YEa,"response code "+c);b.EB(q)}function x(a){a.lengthComputable&&J.VVc(a.loaded,a.total,d.O(a.loaded/a.total*100))}function K(a){if(a.lengthComputable){var b=a.loaded/a.total*100;J.Q1b(a.loaded,a.total,d.O(b))}else J.Q1b(a.loaded,-1,-1)}var J=this;
f(J,c,m);if(s(c)){var L=new FormData;if(h(c,L)){b.hid(this.Zz(),L,E,D,x,K,r);return}}L={};e(c,L);b.Toc(this.Zz(),L,E,D,x,K,r)};x.XHa=function(c){var e=!1,e=d.cc();e.fN("REASON",c,a.vY.v);e.mg("HANDLED",!1);this.Ga(a.Q.b5,e);(e=e.ah("HANDLED"))||(e=b.Fg().LVc(this,c));return e};x.c5=function(){this.Ga(a.Q.Gaa)};x.VVc=function(b,c,e){var f=d.cc();f.MF("LOADED",b);f.MF("TOTAL",c);f.MF("PROGRESS",e);this.Ga(a.Q.MHd,f)};x.Q1b=function(b,c,e){var f=d.cc();f.MF("LOADED",b);f.MF("TOTAL",c);f.MF("PROGRESS",
e);this.Ga(a.Q.fTc,f)};d.Sa(c.Oxa,"PRIM_WEB","DataRequest",{jc:{Execute:x.Z_,ExecuteAsync:x.Y4}});c.iya=function(b,c){K.K.call(this,b,c);this.Gn=a.O2.rHb};var K=c.u(c.iya,c.oMa);K.O3c=function(){return this.Gn};K.gFb=function(a){this.Gn=a};K.Z_=function(a,b){f(this,a,b);var c={};u&&(c._SESSIONKEY=u);var d=a.FLD;if(d!==p)for(var e in d)c[e]=m(d[e]);d=a.LIST;if(d!==p)for(var l in d){for(var k=d[l],h=k.bq={},r=k.entryCount(),s=1;s<=r;s++)for(e in k.getEntry(s),1==s&&(c[l+".."]=1),h){var t=s.toString();
4>t.length&&(t="000"+t,t=t.substr(t.length-4));c[l+"."+t+"."+e]=m(h[e])}delete k.bq}q(this.Zz(),c,this.Gn)};d.Sa(c.iya,"PRIM_WEB","WebPageRequest",{Aa:{Target:{a:function(){return d.va(this.Gn,a.O2.v)},f:function(b){this.gFb(d.wa(b,a.O2.v))}}},jc:{Execute:K.Z_}});c.aya=function(b,c){J.K.call(this,b,c);this.Gn=a.O2.rHb};var J=c.u(c.aya,c.oMa);J.O3c=function(){return this.Gn};J.gFb=function(a){this.Gn=a};J.Z_=function(a,b){f(this,a,b);var c={};u&&(c._SESSIONKEY=u);var d=a.FLD;if(d!==p)for(var e in d)c[e]=
m(d[e]);d=a.LIST;if(d!==p)for(var l in d){for(var k=d[l],h=k.bq={},r=k.entryCount(),s=1;s<=r;s++)for(e in k.getEntry(s),1==s&&(c[l+".."]=1),h){var t=s.toString();4>t.length&&(t="000"+t,t=t.substr(t.length-4));c[l+"."+t+"."+e]=m(h[e])}delete k.bq}q(this.Zz(),c,this.Gn)};d.Sa(c.aya,"PRIM_WEB","ResourceRequest",{Aa:{Target:{a:function(){return d.va(this.Gn,a.O2.v)},f:function(b){this.gFb(d.wa(b,a.O2.v))}}},jc:{Execute:J.Z_}});b.EUc=function(b,c){var d=c.webroutine;if(d){var e=b.wz.UIa(),f=d.fields;if(f){var l=
b.ONa(e),k;for(k in f){var h=null,m=b.gm[k];m&&(h=m.p_());if(!h&&l)for(var r in l)if(m=l[r],m.wh()==k){h=m;break}h&&(m=t(f[k].value),h.set(m))}}if(d=d.lists){var e=b.Lmd(e),p;for(p in d){f=null;if(m=b.gm[p])switch(m.Aua()){case a.Ny.QAc:case a.Ny.K9a:case a.Ny.Chb:f=m}!f&&e&&(f=e[p]);if(f)for(m=d[p],l=m.header,k=m.entries,h=0;h<k.length;h++){r=f.bq={};for(var u=k[h],q=0;q<u.length;q++)m=t(u[q]),r[l[q].name]=m;f.Ag();delete f.bq}}}}};b.DUc=function(a){(a=a.webroutine)&&k(a)}});
