window.LANSA.addSrc("coll",function(d,c,a,b,p){a.x0a={rLc:0,Olb:1};var t=0;c.zxa=function(){m.K.call(this)};var m=c.u(c.zxa,c.qd);m.MSb=function(){return!1};m.U9b=function(){return!1};m.Cc=function(){return 0};m.eh=function(){return 0==this.Cc()};m.x4=function(a){a&&(a.Ba(),a.PFc(this))};m.T4=function(a){a&&(a.ub(),a.Ukd(this))};m.O1=function(a,b){this.U3a(b);null!=this.xz&&this.xz.O1(a,b)};m.Dda=function(a,b){this.V3a(b);null!=this.xz&&this.xz.Dda(a,b)};d.Md(c.zxa,"PRIM_COLL",{Aa:{AllowsDuplicates:{a:function(){return this.MSb()}},
IsEmpty:{a:function(){return this.eh()}},IsOrdered:{a:function(){return this.U9b()}},ItemCount:{a:function(){return this.Cc()}}}});c.z1a=function(){q.K.call(this);this.jb=[];this.xz=null};var q=c.u(c.z1a,c.zxa);q.R=function(){this.Ml();q.k.R.call(this)};q.MSb=function(){return!0};q.U9b=function(){return!0};q.Cc=function(){return this.jb.length};q.he=function(a){if(0>a||a>=this.jb.length)throw d.Tu(a,this.jb.length);return this.jb[a]};q.Ol=function(a,b){if(0>a||a>this.jb.length)throw d.Tu(a,this.jb.length);
a==this.jb.length?this.us(b):this.aCb(b,a)};q.bob=function(a,b){return b===p?this.jb.indexOf(a):this.jb.indexOf(a,b)};q.p4b=function(a){return this.jb.lastIndexOf(a)+1};q.Snb=function(){return 0<this.jb.length?this.jb[0]:null};q.nob=function(){return 0<this.jb.length?this.jb[this.jb.length-1]:null};q.lVd=function(){return this.Fpa};q.O7=function(a){this.Fpa=a};q.pVa=function(a){this.O7(a.kqc())};q.Ze=function(a){return-1!=this.jb.indexOf(a)};q.us=q.J8b=function(a){this.x4(a);this.jb.push(a);this.O1(a,
this.Cc()-1)};q.I8b=function(a){this.x4(a);this.jb.unshift(a);this.O1(a,0)};q.H8b=function(a,b){if(0>b||b>=this.jb.length)throw d.Tu(b,this.jb.length);this.x4(a);this.jb.splice(b+1,0,a);this.O1(a,b+1)};q.Nrb=function(a,b){if(0>b||b>=this.jb.length)throw d.Tu(b,this.jb.length);this.x4(a);this.jb.splice(b,0,a);this.O1(a,b)};q.bt=function(a){a=this.jb.indexOf(a);if(-1==a)throw d.tld();return this.ys(a)};q.ys=function(a){if(0>a||a>=this.jb.length)throw d.Tu(a,this.jb.length);var b=this.jb[a];this.jb.splice(a,
1);d.Ssa(b);this.T4(b);this.Dda(b,a);return b};q.UBb=function(){return this.ys(0)};q.WBb=function(){return this.ys(this.jb.length-1)};q.Ml=function(){for(var a=0;a<this.jb.length;a++)this.T4(this.jb[a]);this.jb=[];this.Ama()};q.Szb=function(a){for(var b=0,c=0;c<this.jb.length;c++)this.jb[c]===a&&b++;return b};q.aCb=function(a,b){if(0>b||b>=this.jb.length)throw d.Tu(b,this.jb.length);var c=this.jb[b];d.Ssa(c);this.T4(c);this.jb[b]=a;this.x4(a);return c};q.Ag=function(){var a=d.njb(this.Fpa);if(a=d.Bc(a.y3a,
a.oY))this.sya(a),this.us(a)};q.Sj=function(){this.Ml()};q.Fh=function(a){if(0<=a&&a<this.Cc()){var b=this.he(a);b&&this.Wla(b);this.Cn=a;return"OK"}this.Cn=-1;return"NR"};q.mp=function(){return this.Cc()};q.Om=function(a){a===p&&(a=this.Cn);0<=a&&a<this.Cc()&&this.ys(a)};q.zl=function(){var a=this.Cn;0<=a&&a<this.Cc()&&(a=this.he(a))&&this.sya(a)};q.rn=function(a,b,c){for(var d=0;d<this.Cc();d++){var e=this.he(d);if(e&&(e=e.e6())){var f={},l;for(l in e)f[l]=e[l].get();if(a(f))return null!=b&&b.set(d+
1),c&&this.Fh(d),this.Cn=d,"OK"}}return"NR"};q.Xq=function(a){this.Ml();for(var b=0;b<a;b++)this.Ag()};q.Bs=function(){return new c.E1a(this)};q.zza=function(){null==this.xz&&(this.xz=new c.Rfc);return this.xz};c.Rfc=function(){s.K.call(this)};var s=c.u(c.Rfc,c.F1a);c.Mfc=function(){h.K.call(this);this.Cn=-1};var h=c.u(c.Mfc,c.z1a);h.i0=function(){return"PRIM_LCOL<"+this.Fpa+">"};h.QGc=function(a){for(var b=0;b<a.Cc();b++)this.us(a.he(b))};h.DLc=function(a){for(var b=d.Bc("PRIM_LCOL"),c=0;c<this.Cc();c++)b.us(this.he(c));
for(c=0;c<a.Cc();c++)b.us(a.he(c));d.Ssa(b);return b};d.Md(c.Mfc,"PRIM_LCOL",{$S:a.Ny.Chb,Aa:{First:{a:function(){return this.Snb()}},Last:{a:function(){return this.nob()}},Item:{a:function(a){return this.he(d.O(a)-1)},f:function(a,b){this.Ol(d.O(a)-1,b)}},IndexOf:{a:function(a,b){return this.bob(a,b===p?p:d.O(b)-1)+1}},LastIndexOf:{a:h.p4b},Collects:{f:h.O7}},jc:{Append:h.QGc,Concatenate:h.DLc,Contains:h.Ze,Insert:h.us,InsertFirst:h.I8b,InsertLast:h.J8b,InsertAfter:function(a,b){return this.H8b(a,
d.O(b)-1)},InsertBefore:function(a,b){return this.Nrb(a,d.O(b)-1)},Remove:h.bt,RemoveAt:function(a){return this.ys(d.O(a)-1)},RemoveFirst:h.UBb,RemoveLast:h.WBb,RemoveAll:h.Ml,OccurrencesOf:h.Szb,ReplaceAt:function(a,b){return this.aCb(a,d.O(b)-1)}},Ue:{Re:"Item"},Yq:{bla:function(a){var b=d.Bc("PRIM_NMBR");b.set(a);return b},rq:function(a){return this.he(d.O(a)-1)},Kw:function(){return this.Cc()}},hA:{Ag:h.Ag,Fh:function(a){return this.Fh(d.O(a)-1)},Xq:h.Xq,Sj:h.Sj,mp:h.mp,Om:function(a){this.Om(a?
d.O(a)-1:p)},zl:h.zl,rn:h.rn,Bs:h.Bs}});c.dcc=function(){e.K.call(this)};var e=c.u(c.dcc,c.z1a);e.i0=function(){return"PRIM_ACOL<"+this.Fpa+">"};d.Md(c.dcc,"PRIM_ACOL",{$S:a.Ny.Chb,Aa:{First:{a:function(){return this.Snb()}},Last:{a:function(){return this.nob()}},Item:{a:function(a){return this.he(d.O(a)-1)},f:function(a,b){this.Ol(d.O(a)-1,b)}},IndexOf:{a:function(a,b){return this.bob(a,b===p?p:d.O(b)-1)+1}},LastIndexOf:{a:e.p4b},Collects:{f:e.O7}},jc:{Contains:e.Ze,Insert:e.us,InsertFirst:e.I8b,
InsertLast:e.J8b,InsertAfter:function(a,b){return this.H8b(a,d.O(b)-1)},InsertBefore:function(a,b){return this.Nrb(a,d.O(b)-1)},Remove:e.bt,RemoveAt:function(a){return this.ys(d.O(a)-1)},RemoveFirst:e.UBb,RemoveLast:e.WBb,RemoveAll:e.Ml,OccurrencesOf:e.Szb,ReplaceAt:function(a,b){return this.aCb(a,d.O(b)-1)}},Ue:{Re:"Item"},Yq:{bla:function(a){var b=d.Bc("PRIM_NMBR");b.set(a);return b},rq:function(a){return this.he(d.O(a)-1)},Kw:function(){return this.Cc()}},hA:{Ag:e.Ag,Fh:function(a){return this.Fh(d.O(a)-
1)},Xq:e.Xq,Sj:e.Sj,mp:e.mp,Om:function(a){this.Om(a?d.O(a)-1:p)},zl:e.zl,rn:e.rn,Bs:e.Bs}});c.Xfc=function(){k.K.call(this)};var k=c.u(c.Xfc,c.z1a);k.us=function(b){this.x4(b);for(var c=0,d=this.jb.length-1;c<=d;){var e=Math.floor((c+d)/2);this.sVc(b,this.jb[e])==a.zd.ao?d=e-1:c=e+1}this.jb.splice(c,0,b)};k.sVc=function(b,c){var e=a.zd.mm,f=d.cc();f.kc("SUBJECT",b);f.kc("OBJECT",c);f.fN("RESULT",e,a.zd.v);this.Ga(a.Q.VVa,f);e=f.Mnb("RESULT",a.zd.v);f.Kc();return e};d.Md(c.Xfc,"PRIM_SACO",{Aa:{First:{a:function(){return this.Snb()}},
Last:{a:function(){return this.nob()}},Item:{a:function(a){return this.he(d.O(a)-1)},f:function(a,b){this.Ol(d.O(a)-1,b)}},IndexOf:{a:function(a,b){return this.bob(a,b===p?p:d.O(b)-1)+1}},Collects:{f:k.O7}},jc:{Remove:k.bt,RemoveAt:function(a){return this.ys(d.O(a)-1)},RemoveAll:k.Ml,RemoveLast:k.WBb,RemoveFirst:k.UBb,Contains:k.Ze,OccurrencesOf:k.Szb,Insert:k.us},Ue:{Re:"Item"},Yq:{bla:function(a){var b=d.Bc("PRIM_NMBR");b.set(a);return b},rq:function(a){return this.he(d.O(a)-1)},Kw:function(){return this.Cc()}}});
c.S6=function(a){f.K.call(this);this.xDc=a};var f=c.u(c.S6,c.zxa);f.he=function(a){if(0>a||a>=this.Cc())throw d.Tu(a,this.Cc());return this.Uz(a)};f.Cc=function(){return this.xDc.Cc()};f.Uz=function(a){return this.xDc.Uz(a)};d.Md(c.S6,"PRIM_PCOL",{Aa:{Item:{a:function(a){return this.he(d.O(a)-1)},f:function(a,b){this.Ol(d.O(a)-1,b)}}},Ue:{Re:"Item"},Yq:{rq:function(a){return this.Uz(d.O(a)-1)},Kw:function(){return this.Cc()}}});c.Lfc=function(){u.K.call(this);this.jb={};this.qZ=null;this.uf=a.x0a.Olb};
var u=c.u(c.Lfc,c.zxa);u.R=function(){this.Ml();u.k.R.call(this)};u.i0=function(){return"PRIM_KCOL<"+this.oab+" "+this.f0c()+">"};u.Gh=function(){return this.uf};u.Jb=function(a){this.uf=a};u.Cc=function(){return this.dma().length};u.he=function(b){b=this.Whb(b);if(this.jb[b]===p&&this.uf==a.x0a.Olb){var c=null;this.QMb?c=new this.QMb:this.oab&&(c=d.njb(this.oab),c=d.Bc(c.y3a,c.oY));c&&(this.jb[b]=c,this.x4(c),this.PL())}return this.jb[b]};u.Ol=function(a,b){a=this.Whb(a);var c=a.toString();this.jb[c]===
p?this.PL():this.T4(this.jb[c]);this.x4(b);this.jb[c]=b};u.Uz=function(a){a=this.dma()[a];return this.jb[a]};u.job=function(a){a=this.dma()[a];this.qZ.set(a);return this.qZ};u.kob=function(a){for(var b in this.jb)if(this.jb[b]===a)return this.Zhb(b);return this.qZ.D1c()};u.O7=function(a,b){"string"!==typeof a?this.QMb=a:(this.oab=a,this.QMb=b)};u.$5a=function(a){this.qZ=new a;this.qZ.Ba()};u.mVd=function(){return this.oab};u.f0c=function(){var a="";this.qZ&&(a=this.qZ.vIa());return a};u.pVa=function(a){this.O7(a.kqc(),
a.JUb(0));this.$5a(a.JUb(1))};u.Whb=function(a){this.qZ.set(a);a=this.qZ.get();return a.toString()};u.Zhb=function(a){this.qZ.set(a);return this.qZ.get()};u.bt=function(a){a=this.Whb(a);var b=null;this.jb[a]!==p&&(b=this.jb[a],d.Ssa(b),this.T4(b),delete this.jb[a],this.PL(),this.Dda(b,0));return b};u.Ml=function(){for(var a in this.jb)this.T4(this.jb[a]);this.jb={};this.PL();this.Ama()};u.PL=function(){delete this.ZJ};u.dma=function(){var a=this;if(this.ZJ===p){this.ZJ=[];for(var b in this.jb)this.ZJ.push(b);
this.ZJ.sort(function(b,c){b=a.Zhb(b);c=a.Zhb(c);return d.cmp(b,c)})}return this.ZJ};var A={COLLECTION:a.x0a.rLc,FACTORY:a.x0a.Olb};d.Md(c.Lfc,"PRIM_KCOL",{Aa:{Style:{a:function(){return d.va(this.Gh(),A)},f:function(a){this.Jb(d.wa(a,A))}},Item:{a:function(a){return this.he(a)},f:function(a,b){this.Ol(a,b)},Dx:"na"},Collects:{f:u.O7},KeyedBy:{f:u.$5a},KeyOf:{a:function(a){return this.kob(a)},Dx:"na"}},jc:{Remove:u.bt,RemoveAll:u.Ml},Ue:{Re:"Item"},Yq:{bla:function(a){return this.job(d.O(a)-1)},rq:function(a){return this.Uz(d.O(a)-
1)},Kw:function(){return this.Cc()}}});c.bfc=function(){l.K.call(this);this.fZ=(t++).toString();this.ND=[];this.Fpa=this.ZCc=""};var l=c.u(c.bfc,c.zxa);l.R=function(){this.Ml();l.k.R.call(this)};l.i0=function(){return"PRIM_DCOL<"+this.Fpa+" "+this.ZCc+">"};l.Cc=function(){return this.ND.length};l.Uz=function(a){return this.ND[a].vM[this.fZ]};l.he=function(a){return a.vM===p||a.vM[this.fZ]===p?null:a.vM[this.fZ]};l.Ol=function(a,b){a.vM===p&&(a.vM={});var c=a.vM[this.fZ];c===p?(this.ND.push(a),a.Ba()):
this.T4(c);a.vM[this.fZ]=b;this.x4(b)};l.job=function(a){return this.ND[a]};l.O7=function(a){this.Fpa=a};l.$5a=function(a){this.ZCc=a};l.kob=function(a,b){for(var c=b;c<this.ND.length;c++){var d=this.ND[c];if(d.vM[this.fZ]===a)return d}return null};l.YUc=function(a){return this.he(a)};l.Ze=function(a){return-1!=this.ND.indexOf(a)};l.ILc=function(a){for(var b=0;b<this.ND.length;b++)if(this.ND[b].vM[this.fZ]===a)return!0;return!1};l.us=function(a,b){var c=this.he(b);this.Ol(b,a);return c};l.bt=function(a){if(a.vM!==
p){var b=a.vM[this.fZ];if(b!==p)return delete a.vM[this.fZ],this.ND.splice(this.ND.indexOf(a),1),d.Ssa(b),this.T4(b),a.ub(),this.Dda(b,0),b}return null};l.Ml=function(){for(var a=0;a<this.ND.length;a++){var b=this.ND[a],c=b.vM[this.fZ];c!==p&&(delete b.vM[this.fZ],this.T4(c));b.ub()}this.ND=[];this.Ama()};d.Md(c.bfc,"PRIM_DCOL",{Aa:{Item:{a:function(a){return this.he(a)},f:function(a,b){this.Ol(a,b)},Dx:"na"},Collects:{f:l.O7,Dx:"na"},KeyedBy:{f:l.$5a,Dx:"na"},KeyOf:{a:function(a,b){return this.kob(a,
b!==p?d.O(b)-1:0)},Dx:"na"}},jc:{Contains:l.Ze,ContainsItem:l.ILc,Insert:l.us,Remove:l.bt,RemoveAll:l.Ml,Find:l.YUc},Ue:{Re:"Item"},Yq:{bla:function(a){return this.job(d.O(a)-1)},rq:function(a){return this.Uz(d.O(a)-1)},Kw:function(){return this.Cc()}}})});
