window.LANSA.addSrc("pdf",function(d,c,a,b){var p=!1;a.i9={Cx:0,Zed:0,TKc:1,l7c:2,pjd:3,xjd:4};a.i9.v={MM:a.i9.Zed,CM:a.i9.TKc,IN:a.i9.l7c,PT:a.i9.pjd,PX:a.i9.xjd};a.Gk={Cx:0,ZEc:0,UEc:1,VEc:2,XEc:3,YEc:4,$Ec:5,aFc:6,bFc:7,cFc:8,dFc:9,WEc:10,OIc:11,PIc:12,RIc:13,SIc:14,TIc:15,UIc:16,VIc:17,WIc:18,XIc:19,YIc:20,QIc:21,JMd:22,NJc:23,PJc:24,QJc:25,RJc:26,SJc:27,TJc:28,UJc:29,VJc:30,WJc:31,OJc:32,XMc:33,Qcd:34,w4c:35,Pcd:36,l$c:37,Mcd:38,mEd:39,CMc:40};a.Gk.v={A0:a.Gk.UEc,A1:a.Gk.VEc,A2:a.Gk.XEc,A3:a.Gk.YEc,
A4:a.Gk.ZEc,A5:a.Gk.$Ec,A6:a.Gk.aFc,A7:a.Gk.bFc,A8:a.Gk.cFc,A9:a.Gk.dFc,A10:a.Gk.WEc,B0:a.Gk.OIc,B1:a.Gk.PIc,B2:a.Gk.RIc,B3:a.Gk.SIc,B4:a.Gk.TIc,B5:a.Gk.UIc,B6:a.Gk.VIc,B7:a.Gk.WIc,B8:a.Gk.XIc,B9:a.Gk.YIc,B10:a.Gk.QIc,C1:a.Gk.NJc,C2:a.Gk.PJc,C3:a.Gk.QJc,C4:a.Gk.RJc,C5:a.Gk.SJc,C6:a.Gk.TJc,C7:a.Gk.UJc,C8:a.Gk.VJc,C9:a.Gk.WJc,C10:a.Gk.OJc,D1:a.Gk.XMc,LETTER:a.Gk.Qcd,GOVERNMENTLETTER:a.Gk.w4c,LEGAL:a.Gk.Pcd,JUNIORLEGAL:a.Gk.l$c,LEDGER:a.Gk.Mcd,TABLOID:a.Gk.mEd,CREDITCARD:a.Gk.CMc};a.G1={Cx:0,zUb:0,Quc:1,
Tyc:2,Uyc:3};a.G1.v={CONTINUOUS:a.G1.zUb,SINGLE:a.G1.Quc,TWOLEFT:a.G1.Tyc,TWORIGHT:a.G1.Uyc};a.Kya={Cx:0,nhd:0,Hcd:1};a.Kya.v={PORTRAIT:a.Kya.nhd,LANDSCAPE:a.Kya.Hcd};a.on={Cx:0,vrb:0,Z2a:1,uTb:2,J$b:3,vTb:4};a.on.v={INHERIT:a.on.vrb,NORMAL:a.on.Z2a,BOLD:a.on.uTb,ITALIC:a.on.J$b,BOLDITALIC:a.on.vTb};a.X_={GRd:0,cvc:0,p1b:1,q1b:2,MVb:3};a.X_.v={STROKE:a.X_.cvc,FILL:a.X_.p1b,FILLANDSTROKE:a.X_.q1b,DELAY:a.X_.MVb};a.kKa={R4d:0,f7c:0,g7c:1,i7c:2,h7c:3};a.kKa.v={BMP:a.kKa.f7c,GIF:a.kKa.g7c,PNG:a.kKa.i7c,
JPG:a.kKa.h7c};a.l6={W7b:0,G6c:0,E6c:1,F6c:2,H6c:3};a.l6.v={NONE:a.l6.G6c,FAST:a.l6.E6c,MEDIUM:a.l6.F6c,SLOW:a.l6.H6c};a.paa={dHc:0,hHc:0,eHc:1,gHc:2};a.paa.v={STRIPED:a.paa.hHc,GRID:a.paa.eHc,PLAIN:a.paa.gHc};a.Lu={owa:0,Jpb:0,wka:1,w_a:2,v_a:3};a.Lu.v={INHERIT:a.Lu.Jpb,LEFT:a.Lu.wka,RIGHT:a.Lu.w_a,CENTER:a.Lu.v_a};a.bv={pCa:0,xKb:0,qCa:1,YHd:2,G9a:3};a.bv.v={INHERIT:a.bv.xKb,TOP:a.bv.qCa,MIDDLE:a.bv.YHd,BOTTOM:a.bv.G9a};a.I1={Cx:0,xgb:0,Cgb:1,$Fc:2};a.I1.v={AUTO:a.I1.xgb,AVOID:a.I1.Cgb,ALWAYS:a.I1.$Fc};
a.sda={Cx:0,xgb:0,Cgb:1};a.sda.v={AUTO:a.sda.xgb,AVOID:a.sda.Cgb};a.uX={tgd:0,wgd:0,Hnc:1,ugd:2,xgd:3,vgd:4};a.uX.v={LINEBREAK:a.uX.Hnc,ELLIPSIZE:a.uX.ugd,VISIBLE:a.uX.xgd,HIDDEN:a.uX.vgd};a.SO={Cx:0,GHa:0,VHa:1,uMa:2};a.SO.v={EVERYPAGE:a.SO.GHa,FIRSTPAGE:a.SO.VHa,NEVER:a.SO.uMa};a.SO.KGb={everyPage:a.SO.GHa,firstPage:a.SO.VHa,never:a.SO.uMa};a.RO={Cx:0,GHa:0,VHa:1,uMa:2};a.RO.v={EVERYPAGE:a.RO.GHa,FIRSTPAGE:a.RO.VHa,NEVER:a.RO.uMa};a.RO.KGb={everyPage:a.RO.GHa,firstPage:a.RO.VHa,never:a.RO.uMa};
c.jkc=function(){t.K.call(this);if(!p){if(!window.jsPDF&&("function"!==typeof window.Promise&&b.sHa("promise/es6-promise.auto.min.js"),b.sHa("pdf/jspdf.min.js"),b.sHa("pdf/jspdf.plugin.autotable.min.js"),!window.LANSA.jsPDF)){b.sHa("pdf/jspdf_lansa_list_ext.js");var a=b.aZa(),a={lang:a.code[b.nba()]||a.code[a.def],pageFooter:b.z4b(),ovrFont:b.H4b()};window.LANSA.jsPDF.setLanguageInfo(a)}p=!0}this.sfb=null;this.zSa=[];this.OEa=[];this.m$a=[];this.LJd=window.LANSA.jsPDF;this.rfb=this.LJd.imageDataUrl};
var t=c.u(c.jkc,c.td);t.CUa=0;t.rTa=null;t.sTa=0;t.mme=null;t.o3=null;t.eSa=a.on.Cx;t.fU=12;t.lme=null;t.sme=0;t.rme=null;t.nb=function(){if(0<this.m$a.length)for(var a=null;null!=(a=this.m$a.pop());)a.nb()};t.c3d=function(){return this.CUa};t.awd=function(b){this.CUa!=b&&(this.CUa=b,this.m(a.g.j))};t.O_d=function(){return this.rTa};t.Btc=function(b){this.rTa!=b&&(this.rTa=b,this.m(a.g.j))};t.R_d=function(){return this.sTa};t.Rtd=function(b){this.sTa!=b&&(this.sTa=b,this.m(a.g.j))};t.Wle=function(){return this.rfb};
t.$le=function(){return this.OEa};t.zV=function(a,c,d,h,m){var l=document.createElement("script");c=b.G4(c);h&&(l.onload=function(a){h.call(this,a,d)});m&&(l.onerror=function(a){m.call(this,a,d)});l.src=c;a.appendChild(l)};t.KVa=function(a){var b=a.toLowerCase(),c=window.LANSA.jsPDF;a=c.jsPDF_fontList;var d=c.fontFiles,h=c.getFontFamily(b)||b;if(-1===a.indexOf(h)&&(b=d[h],a.push(h),b)){var l=this;a=new Promise(function(a){var b=d[h];l.zV(c.vfsNode,"pdf/font/"+b.vfs,b,function(){c.addFont(b);a()},
function(){a()})});this.OEa.push(a)}return h};t.uD=function(a,b){return(d.wa(a,b)||d.wa(0,b)).toLowerCase()};t.nxc=function(a,b){return d.wa(a,b)||d.wa(0,b)};t.Enb=function(b){var c="S";switch(b?d.va(b,a.X_.v):a.X_.cvc){case a.X_.p1b:c="F";break;case a.X_.q1b:c="FD";break;case a.X_.MVb:c=null}return c};t.UYc=function(a){a=a.toLowerCase();return/^(fullwidth|fullheight|fullpage|original|(\d{1,4}%))$/.test(a)?a:"original"};t.jZa=function(a){var c=[];return a?b.mla(a,!0,c):null};t.B_=function(a){a=t.jZa(a);
return[a.Fb||0,a.Eb||0,a.Db||0]};t.NE=function(a,b){this.zSa.push({inst:a,args:b})};t.yNa=function(){this.zSa=[];this.OEa=[];this.m$a=[];this.sfb=null;window.LANSA.jsPDF.instance=null};t.wmd=function(){var a=this.sfb,c=this.zSa,d=this;Promise.all(d.OEa).then(function(){for(var h=0,h=0;h<c.length;h++)try{var m=c[h],l=m.inst,p=m.args;"addImage"==l&&(p[0]=d.rfb[p[6]].base64);a[l].apply(a,p)}catch(q){throw b.aBc("Error: "+q+". jsPDF instruction: "+l+". Arguments: "+p),q;}d.yNa()},function(a){b.aBc("Error: "+
a)})};t.start=function(){this.sfb&&this.yNa();this.Btc(b.e3b().toUpperCase());this.sfb=window.LANSA.jsPDF.createDocument(this.uD(this.sTa,a.Kya.v),this.uD(this.CUa,a.i9.v),this.uD(this.rTa,a.Gk.v))};t.setDocumentProperties=function(a,b,c,d){this.NE("setDocumentProperties",[{title:a||"",author:b||"",creator:c||"",keywords:d||""}])};t.setDisplayMode=function(b,c){var f="continuous";switch(c?d.va(c,a.G1.v):a.G1.zUb){case a.G1.Quc:case a.G1.Tyc:case a.G1.Uyc:f=c.toLowerCase()}var h=this.UYc(b);this.NE("setDisplayMode",
[h,f])};t.setCreationDate=function(a){a instanceof c.$q&&(a=a.O8a(),this.NE("setCreationDate",[a]))};t.setLineWidth=function(a){this.NE("setLineWidth",[a])};t.FKd=function(a,b){this.NE("setLineDash",[a,b])};t.setLineDash=function(a,b){var c=[],d=b?b.kb():0;if(a)for(var h=a.Ac(),l=0;l<h;l++){var m=a.ee(l);c.push(m.kb())}this.FKd(c,d)};t.addPage=function(){this.NE("addPage",[])};t.text=function(a,b,c){this.NE("text",[a,b,c])};t.line=function(a,b,c,d){this.NE("line",[a,b,c,d])};t.save=function(a){this.NE("save",
[a]);this.wmd()};t.setFont=function(b,c){var f="normal";switch(c?d.va(c,a.on.v):a.on.Z2a){case a.on.uTb:case a.on.J$b:case a.on.vTb:f=c.toLowerCase()}this.KVa(b);this.zSa.push({inst:"setFont",args:[b,f]})};t.setFontSize=function(a){this.zSa.push({inst:"setFontSize",args:[a]})};t.setTextColor=function(a){a=this.jZa(a);this.NE("setTextColor",[a.Fb||0,a.Eb||0,a.Db||0])};t.setDrawColor=function(a){a=this.jZa(a);this.NE("setDrawColor",[a.Fb||0,a.Eb||0,a.Db||0])};t.setFillColor=function(a){a=this.jZa(a);
this.NE("setFillColor",[a.Fb||0,a.Eb||0,a.Db||0])};t.rect=function(a,b,c,d,h){this.NE("rect",[a,b,c,d,this.Enb(h)])};t.roundedRect=function(a,b,c,d,h,l,m){this.NE("roundedRect",[a,b,c,d,h,l,this.Enb(m)])};t.circle=function(a,b,c,d){this.NE("circle",[a,b,c,this.Enb(d)])};t.addImage=function(c,k,f,h,m,l,p,q){p=p||d.wa(a.l6.W7b,a.l6.v);q=q||0;c=c.Lg();var s=b.zmb(this.rfb,c);s&&this.OEa.push(s);this.NE("addImage",[null,k,f,h,m,l,c,p,q])};t.OLc=function(){var a=new c.Pxb(this);this.m$a.push(a);return a};
d.Ld(c.jkc,"PRIM_PDF",{Aa:{UnitM:{a:function(){return d.wa(this.CUa,a.i9.v)},f:function(b){this.awd(d.va(b,a.i9.v))}},PageFormat:{a:function(){return d.wa(this.rTa,a.Gk.v)},f:function(b){this.Btc(d.va(b,a.Gk.v))}},PageOrientation:{a:function(){return d.wa(this.sTa,a.Kya.v)},f:function(b){this.Rtd(d.va(b,a.Kya.v))}}},jc:{start:function(){this.start()},setDocumentProperties:function(a,b,c,h){this.setDocumentProperties(d.ka(a),d.ka(b),d.ka(c),d.ka(h))},setDisplayMode:function(a,b){this.setDisplayMode(d.ka(a),
b)},setCreationDate:function(a){this.setCreationDate(a)},setLineWidth:function(a){this.setLineWidth(d.kg(a))},setLineDash:function(a,b){this.setLineDash(a,b)},addPage:function(){this.addPage()},text:function(a,b,c){this.text(d.ka(a),d.kg(b),d.kg(c))},line:function(a,b,c,h){this.line(d.kg(a),d.kg(b),d.kg(c),d.kg(h))},save:function(a){this.save(d.ka(a))},setFont:function(a,b){this.setFont(d.ka(a),b)},setFontSize:function(a){this.setFontSize(d.O(a))},setTextColor:function(a){this.setTextColor(d.ka(a))},
setDrawColor:function(a){this.setDrawColor(d.ka(a))},setFillColor:function(a){this.setFillColor(d.ka(a))},rect:function(a,b,c,h,m){this.rect(d.kg(a),d.kg(b),d.kg(c),d.kg(h),m)},roundedRect:function(a,b,c,h,m,l,p){this.roundedRect(d.kg(a),d.kg(b),d.kg(c),d.kg(h),d.kg(m),d.kg(l),p)},circle:function(a,b,c,h){this.circle(d.kg(a),d.kg(b),d.kg(c),h)},addImage:function(a,b,c,h,m,l,p,q){this.addImage(a,b,d.kg(c),d.kg(h),d.kg(m),d.kg(l),p,d.O(q))},CreateAutoTable:function(a){return this.OLc(d.O(a))}}});c.hMa=
function(b){m.K.call(this);this.uha=b;this.XDa=a.Lu.owa;this.YDa=a.bv.pCa;this.nSa=null;this.WDa=a.on.Cx;this.oSa=-1;this.mSa=this.qSa=null;this.cRa=this.fTa=this.gTa=this.hDa=this.pSa=-1;this.UDa=a.Lu.owa;this.MFa=a.bv.pCa;this.o3=null;this.eSa=a.on.Cx;this.fU=-1;this.aSa=this.zu=null;this.zEa=a.uX.tgd};var m=c.u(c.hMa,c.td);m.yYd=function(){return this.XDa};m.ssd=function(b){this.XDa!=b&&(this.XDa=b,this.m(a.g.j))};m.BYd=function(){return this.YDa};m.vsd=function(b){this.YDa!=b&&(this.YDa=b,this.m(a.g.j))};
m.vYd=function(){return this.nSa};m.psd=function(b){this.nSa!=b&&(this.nSa=b,this.uha.KVa(b),this.m(a.g.j))};m.xYd=function(){return this.WDa};m.rsd=function(b){this.WDa!=b&&(this.WDa=b,this.m(a.g.j))};m.wYd=function(){return this.oSa};m.qsd=function(b){this.oSa!=b&&(this.oSa=b,this.m(a.g.j))};m.AYd=function(){return this.qSa};m.usd=function(b){this.qSa!=b&&(this.qSa=b,this.m(a.g.j))};m.uYd=function(){return this.mSa};m.osd=function(b){this.mSa!=b&&(this.mSa=b,this.m(a.g.j))};m.zYd=function(){return this.pSa};
m.tsd=function(b){this.pSa!=b&&(this.pSa=b,this.m(a.g.j))};m.uYa=function(){return this.hDa};m.dDb=function(b){this.hDa!=b&&(this.hDa=b,this.m(a.g.j))};m.a_d=function(){return this.gTa};m.xtd=function(b){this.gTa!=b&&(this.gTa=b,this.m(a.g.j))};m.$Zd=function(){return this.fTa};m.wtd=function(b){this.fTa!=b&&(this.fTa=b,this.m(a.g.j))};m.rUd=function(){return this.cRa};m.Kqd=function(b){this.cRa!=b&&(this.cRa=b,this.m(a.g.j))};m.pYd=function(){return this.UDa};m.ksd=function(b){this.UDa!=b&&(this.UDa=
b,this.m(a.g.j))};m.h3d=function(){return this.MFa};m.dwd=function(b){this.MFa!=b&&(this.MFa=b,this.m(a.g.j))};m.bYd=function(){return this.o3};m.gsd=function(b){this.o3!=b&&(this.o3=b,this.uha.KVa(b),this.m(a.g.j))};m.Jnb=function(){return this.eSa};m.isd=function(b){this.eSa!=b&&(this.eSa=b,this.m(a.g.j))};m.Jv=function(){return this.fU};m.eu=function(b){this.fU!=b&&(this.fU=b,this.m(a.g.j))};m.R5b=function(){return this.zu};m.ci=function(b){this.zu!=b&&(this.zu=b,this.m(a.g.j))};m.RXd=function(){return this.aSa};
m.asd=function(b){this.aSa!=b&&(this.aSa=b,this.m(a.g.j))};m.J_d=function(){return this.zEa};m.Ntd=function(b){this.zEa!=b&&(this.zEa=b,this.m(a.g.j))};m.nb=function(){};m.Tle=function(){return this.uha};m.$2a=function(a){return a?0<Object.keys(a).length:!1};m.Sed=function(a,b){for(var c in b)a[c]=b[c]};m.Yk=function(){var b=this.o3,c=this.Jnb(),d=this.Jv(),h=this.UDa,m=this.MFa,l=this.zu,p=this.aSa,q=this.uYa(),s=this.gTa,x=this.fTa,K=this.cRa,J=this.zEa,D={};null!=b&&(D.font=b);c!=a.on.vrb&&(D.fontStyle=
t.uD(c,a.on.v));-1!=d&&(D.fontSize=d);h!=a.Lu.Jpb&&(D.halign=t.uD(h,a.Lu.v));m!=a.bv.xKb&&(D.valign=t.uD(m,a.bv.v));null!=l&&(D.textColor=t.B_(l));null!=p&&(D.fillColor=t.B_(p));-1!=q&&(D.cellWidth=q);-1!=s&&(D.minCellWidth=s);-1!=x&&(D.minCellHeight=x);-1!=K&&(D.cellPadding=K);J!=a.uX.wgd&&(D.overflow=t.uD(J,a.uX.v));return D};m.H3b=function(){var b=this.nSa,c=this.WDa,d=this.oSa,h=this.XDa,m=this.YDa,l=this.qSa,p=this.mSa,q=this.pSa,s={};null!=b&&(s.font=b);c!=a.on.vrb&&(s.fontStyle=t.uD(c,a.on.v));
-1!=d&&(s.fontSize=d);h!=a.Lu.Jpb&&(s.halign=t.uD(h,a.Lu.v));m!=a.bv.xKb&&(s.valign=t.uD(m,a.bv.v));null!=l&&(s.textColor=t.B_(l));null!=p&&(s.fillColor=t.B_(p));-1!=q&&(s.minCellHeight=q);return s};d.Sa(c.hMa,"PRIM_PDF","Component",{Aa:{HeadHAlign:{a:function(){return d.wa(this.XDa,a.Lu.v)},f:function(b){this.ssd(d.va(b,a.Lu.v))}},HeadVAlign:{a:function(){return d.wa(this.YDa,a.bv.v)},f:function(b){this.vsd(d.va(b,a.bv.v))}},HeadFontName:{a:function(){return this.nSa},f:function(a){this.psd(a)}},
HeadFontStyle:{a:function(){return d.wa(this.WDa,a.on.v)},f:function(b){this.rsd(d.va(b,a.on.v))}},HeadFontSize:{a:function(){return this.oSa},f:function(a){this.qsd(d.O(a))}},HeadTextColor:{a:function(){return this.qSa},f:function(a){this.usd(d.ka(a))}},HeadFillColor:{a:function(){return this.mSa},f:function(a){this.osd(d.ka(a))}},HeadMinCellHeight:{a:function(){return this.pSa},f:function(a){this.tsd(d.kg(a))}},CellWidth:{a:function(){return this.uYa()},f:function(a){this.dDb(d.kg(a))}},MinCellWidth:{a:function(){return this.gTa},
f:function(a){this.xtd(d.kg(a))}},MinCellHeight:{a:function(){return this.fTa},f:function(a){this.wtd(d.kg(a))}},CellPadding:{a:function(){return this.cRa},f:function(a){this.Kqd(d.kg(a))}},HAlign:{a:function(){return d.wa(this.UDa,a.Lu.v)},f:function(b){this.ksd(d.va(b,a.Lu.v))}},VAlign:{a:function(){return d.wa(this.MFa,a.bv.v)},f:function(b){this.dwd(d.va(b,a.bv.v))}},FontName:{a:function(){return this.o3},f:function(a){this.gsd(a)}},FontStyle:{a:function(){return d.wa(this.Jnb(),a.on.v)},f:function(b){this.isd(d.va(b,
a.on.v))}},FontSize:{a:function(){return this.Jv()},f:function(a){this.eu(d.O(a))}},TextColor:{a:function(){return this.zu},f:function(a){this.ci(d.ka(a))}},FillColor:{a:function(){return this.aSa},f:function(a){this.asd(d.ka(a))}},Overflow:{a:function(){return d.wa(this.zEa,a.uX.v)},f:function(b){this.Ntd(d.va(b,a.uX.v))}}},jc:{}});c.Pxb=function(b){q.K.call(this,b);this.PQa=a.paa.dHc;this.kab=0;this.cFa=-1;this.JCa=this.KCa=null;this.lh=this.mj=this.nj=this.mh=-1;this.OCa=a.I1.Cx;this.PCa=a.sda.Cx;
this.wFa=-1;this.RCa=a.SO.Cx;this.QCa=a.RO.Cx;this.vFa=-1;this.uFa=null;this.EMb=[];this.QPb=[];this.ZY=!1;this.XDa=a.Lu.wka;this.YDa=a.bv.qCa;this.WDa=a.on.Z2a;this.UDa=a.Lu.wka;this.MFa=a.bv.qCa;this.eSa=a.on.Z2a;this.zEa=a.uX.Hnc};var q=c.u(c.Pxb,c.hMa);q.yc=function(){return this.PQa};q.$e=function(b){this.PQa!=b&&(this.PQa=b,this.m(a.g.j))};q.zYa=function(){return this.kab};q.crd=function(b){this.kab!=b&&(this.kab=b,this.m(a.g.j))};q.N1d=function(){return this.cFa};q.Uud=function(b){this.cFa!=
b&&(this.cFa=b,this.m(a.g.j))};q.QSd=function(){return this.KCa};q.Vpd=function(b){this.KCa!=b&&(this.KCa=b,this.m(a.g.j))};q.PSd=function(){return this.JCa};q.Upd=function(b){this.JCa!=b&&(this.JCa=b,this.m(a.g.j))};q.If=function(){return this.mh};q.Df=function(b){this.mh!=b&&(this.mh=b,this.m(a.g.j))};q.Ug=function(){return this.nj};q.ve=function(b){this.nj!=b&&(this.nj=b,this.m(a.g.j))};q.Yg=function(){return this.mj};q.ig=function(b){this.mj!=b&&(this.mj=b,this.m(a.g.j))};q.Rf=function(){return this.lh};
q.Af=function(b){this.lh!=b&&(this.lh=b,this.m(a.g.j))};q.N_d=function(){return this.OCa};q.Qtd=function(b){this.OCa!=b&&(this.OCa=b,this.m(a.g.j))};q.g1d=function(){return this.PCa};q.qud=function(b){this.PCa!=b&&(this.PCa=b,this.m(a.g.j))};q.n2d=function(){return this.wFa};q.evd=function(b){this.wFa!=b&&(this.wFa=b,this.m(a.g.j))};q.D1d=function(){return this.RCa};q.Hud=function(b){this.RCa!=b&&(this.RCa=b,this.m(a.g.j))};q.C1d=function(){return this.QCa};q.Gud=function(b){this.QCa!=b&&(this.QCa=
b,this.m(a.g.j))};q.m2d=function(){return this.vFa};q.cvd=function(b){this.vFa!=b&&(this.vFa=b,this.m(a.g.j))};q.l2d=function(){return this.uFa};q.bvd=function(b){this.uFa!=b&&(this.uFa=b,this.m(a.g.j))};q.nb=function(){};q.m3c=function(){var b={},c={};-1!=this.mh&&(b.top=this.mh);-1!=this.nj&&(b.right=this.nj);-1!=this.mj&&(b.bottom=this.mj);-1!=this.lh&&(b.left=this.lh);q.$2a(b)&&(c.margin=b);this.PQa!=a.I1.Cx&&(c.theme=t.uD(this.PQa,a.paa.v));-1!=this.cFa&&(c.startY=this.cFa);this.OCa!=a.I1.Cx&&
(c.pageBreak=t.uD(this.OCa,a.I1.v));this.PCa!=a.sda.Cx&&(c.rowPageBreak=t.uD(this.PCa,a.sda.v));-1!=this.wFa&&(c.tableWidth=this.wFa);this.RCa!=a.SO.Cx&&(c.showHead=t.nxc(this.RCa,a.SO.KGb));this.QCa!=a.RO.Cx&&(c.showFoot=t.nxc(this.QCa,a.RO.KGb));-1!=this.vFa&&(c.tableLineWidth=this.vFa);null!=this.uFa&&(c.tableLineColor=t.B_(this.uFa));return c};q.hWc=function(){var a={};null!=this.KCa&&(a.textColor=t.B_(this.KCa));null!=this.JCa&&(a.fillColor=t.B_(this.JCa));return a};q.qId=function(){var a=window.LANSA.jsPDF,
b=[],c=[],d=this.Yk(),h=this.hWc(),l=this.H3b(),p={},q=["didParseCell"],d={userData:{images:a.imageDataUrl},columns:b,body:c,styles:d,headStyles:l,columnStyles:p};m.Sed(d,this.m3c());m.$2a(h)&&(d.alternateRowStyles=h);for(h=0;h<this.EMb.length;h++){var t=s.lmc(h),x=this.EMb[h];l[t]=x.H3b();p[t]=x.Yk();b[h]={header:x.lSa,dataKey:t}}this.ZY&&q.push("didDrawCell");for(b=0;b<this.QPb.length;b++)c.push(this.QPb[b].LJc());a.addHooks(d,q);this.uha.NE("autoTable",[d])};q.ULc=function(){return new c.Qxb(this.uha)};
q.qFc=function(a){var b=this.kab,c=this.EMb;c.length<b?c.push(a):d.Su(c.length+1,b)};q.sMc=function(){return new c.Rxb(this,this.uha)};q.IFc=function(a){a.ZY&&(this.ZY=!0);this.QPb.push(a)};d.Sa(c.Pxb,"PRIM_PDF","AutoTable",{Aa:{Theme:{a:function(){return d.wa(this.yc(),a.paa.v)},f:function(b){this.$e(d.va(b,a.paa.v))}},ColumnCount:{a:function(){return this.zYa()},f:function(a){this.crd(d.O(a))}},StartY:{a:function(){return this.cFa},f:function(a){this.Uud(d.kg(a))}},AltRowTextColor:{a:function(){return this.KCa},
f:function(a){this.Vpd(a)}},AltRowFillColor:{a:function(){return this.JCa},f:function(a){this.Upd(a)}},MarginTop:{a:function(){return this.If()},f:function(a){this.Df(d.kg(a))}},MarginRight:{a:function(){return this.Ug()},f:function(a){this.ve(d.kg(a))}},MarginBottom:{a:function(){return this.Yg()},f:function(a){this.ig(d.kg(a))}},MarginLeft:{a:function(){return this.Rf()},f:function(a){this.Af(d.kg(a))}},PageBreak:{a:function(){return d.wa(this.OCa,a.I1.v)},f:function(b){this.Qtd(d.va(b,a.I1.v))}},
RowPageBreak:{a:function(){return d.wa(this.PCa,a.sda.v)},f:function(b){this.qud(d.va(b,a.sda.v))}},TableWidth:{a:function(){return this.wFa},f:function(a){this.evd(d.kg(a))}},ShowHead:{a:function(){return d.wa(this.RCa,a.SO.v)},f:function(b){this.Hud(d.va(b,a.SO.v))}},ShowFoot:{a:function(){return d.wa(this.QCa,a.RO.v)},f:function(b){this.Gud(d.va(b,a.RO.v))}},TableLineWidth:{a:function(){return this.vFa},f:function(a){this.cvd(d.kg(a))}},TableLineColor:{a:function(){return this.uFa},f:function(a){this.bvd(a)}}},
jc:{Write:function(){return this.qId()},CreateColumn:function(){return this.ULc()},AddColumn:function(a){return this.qFc(a)},CreateRow:function(){return this.sMc()},AddRow:function(a){return this.IFc(a)},CreateCell:function(){return this.Nn()}}});c.Qxb=function(a){s.K.call(this,a);this.lSa="";this.ZY=!1};var s=c.u(c.Qxb,c.hMa);s.tYd=function(){return this.lSa};s.nsd=function(b){this.lSa!=b&&(this.lSa=b,this.m(a.g.j))};s.sYd=function(){return this.ZY};s.msd=function(b){this.ZY!=b&&(this.ZY=b,this.m(a.g.j))};
s.nb=function(){};s.lmc=function(a){return"COL"+(a+1)};d.Sa(c.Qxb,"PRIM_WEB","AutoTableColumn",{Aa:{HeadCaption:{a:function(){return this.lSa},f:function(a){this.nsd(a)}},HasImageCells:{a:function(){return this.ZY},f:function(a){this.msd(a)}}},jc:{}});c.Rxb=function(a,b){h.K.call(this,b);this.vDc=a;this.Q$a=[];this.ZY=!1};var h=c.u(c.Rxb,c.hMa);h.nb=function(){};h.LJc=function(){for(var a={},b=0;b<this.Q$a.length;b++)a[s.lmc(b)]=this.Q$a[b];return a};h.ame=function(){return this.ZY};h.DId=function(b,
c,f,h,p,l,r,q){var s=this.vDc.zYa(),x=this.Q$a;x.length<s?(s={},b={content:b},c!=a.Lu.owa&&(s.halign=t.uD(c,a.Lu.v)),f!=a.bv.pCa&&(s.valign=t.uD(f,a.bv.v)),h!=a.on.Cx&&(s.fontStyle=t.uD(h,a.on.v)),p&&(s.fontName=this.uha.KVa(p)),!isNaN(l)&&0<l&&(s.fontSize=l),r&&(s.textColor=t.B_(r)),q&&(s.fillColor=t.B_(q)),m.$2a(s)&&(b.styles=s),x.push(b)):d.Su(x.length+1,s)};h.FId=function(c,k,f,h,p,l,r,q,s){var x=this.vDc.zYa(),K=this.Q$a,J=K.length;p=p||d.wa(a.l6.W7b,a.l6.v);l=l||0;J<x?(x=c.Lg(),c={},k={content:"",
_widget:{type:"image",format:k,url:x,width:f,height:h,compression:p,rotation:l}},f=this.uha,(h=b.zmb(f.rfb,x))&&f.OEa.push(h),r!=a.Lu.owa&&(c.halign=t.uD(r,a.Lu.v)),q!=a.bv.pCa&&(c.valign=t.uD(q,a.bv.v)),s&&(c.fillColor=t.B_(s)),m.$2a(c)&&(k.styles=c),K.push(k),this.ZY=!0):d.Su(K.length+1,x)};d.Sa(c.Rxb,"PRIM_WEB","AutoTableRow",{Aa:{Value:{a:function(){return this.kb()},f:function(a){this.ob(a)}}},jc:{addCell:function(b,c,f,h,m,l,p,q){return this.DId(d.ka(b),d.UPa(c,a.Lu.v,a.Lu.owa),d.UPa(f,a.bv.v,
a.bv.pCa),d.UPa(h,a.on.v,a.on.Cx),d.ka(m),d.O(l),d.ka(p),d.ka(q))},addImageCell:function(b,c,f,h,m,l,p,q,s){return this.FId(b,d.ka(c),d.kg(f),d.kg(h),d.ka(m),d.O(l),d.UPa(p,a.Lu.v,a.Lu.owa),d.UPa(q,a.bv.v,a.bv.pCa),d.ka(s))}}})});
