window.LANSA.addSrc("ppnl",function(d,c,a,b,p){d.Ob("PRIM_PHBN");d.Ob("PRIM_IMAG");d.Ob("PRIM_TBLO");a.jzb={xMa:0,fnc:3};a.OO={nda:0,xya:1,bnc:2};a.OO.v={NONE:a.OO.nda,POPUP:a.OO.xya};a.bm={Qma:8321,p4a:1,lBb:2,qBb:8,mBb:16,oBb:32,pBb:64,sBb:128,vBb:256,nBb:512,uBb:1024,Nbe:2048,tBb:4096,eqc:8192,rBb:16384};a.Yla={j7:0,rX:1,sX:2};a.Rae={fqc:0};a.lR={kib:0,gib:268435456,mib:536870912};a.lR.v={HIDDEN:a.lR.kib,ALL:a.lR.gib,NONE:a.lR.mib};a.Tya={Ghd:0,zAb:1,Doc:805306368};a.Yg={z2:0,dCa:1,b9a:3,c9a:4,
DJb:5,ezc:6,EJb:7,Xyc:8,Yyc:9,azc:10,gzc:11,bzc:12,Zyc:13,$yc:14,czc:15,dzc:16,fzc:17};a.Yg.v={NONE:a.Yg.z2,FADEINANDSCALE:a.Yg.dCa,SLIDEINLEFT:a.Yg.b9a,SLIDEINRIGHT:a.Yg.c9a,SLIDEINBOTTOM:a.Yg.DJb,NEWSPAPER:a.Yg.ezc,SLIDEINTOP:a.Yg.EJb,"3DFLIPHORIZONTAL":a.Yg.Xyc,"3DFLIPVERTICAL":a.Yg.Yyc,"3DSIGN":a.Yg.azc,SUPERSCALED:a.Yg.gzc,"3DSLIT":a.Yg.bzc,"3DROTATEBOTTOM":a.Yg.Zyc,"3DROTATEINLEFT":a.Yg.$yc,LETMEIN:a.Yg.czc,MAKEWAY:a.Yg.dzc,SLIPFROMTOP:a.Yg.fzc};a.Yg.gMa={NONE:a.Yg.z2,FADEINANDSCALE:a.Yg.dCa};
a.Yg.J9d={NONE:a.Yg.z2,FADEIN:a.Yg.dCa,SLIDEINLEFT:a.Yg.b9a,SLIDEINRIGHT:a.Yg.c9a,SLIDEINTOP:a.Yg.EJb,SLIDEINBOTTOM:a.Yg.DJb};a.Yg.v0b={"":a.Yg.z2,"md-effect-1":a.Yg.dCa,"md-effect-21":a.Yg.b9a,"md-effect-2":a.Yg.c9a,"md-effect-3":a.Yg.DJb,"md-effect-4":a.Yg.ezc,"md-effect-7":a.Yg.EJb,"md-effect-8":a.Yg.Xyc,"md-effect-9":a.Yg.Yyc,"md-effect-10":a.Yg.azc,"md-effect-11":a.Yg.gzc,"md-effect-13":a.Yg.bzc,"md-effect-14":a.Yg.Zyc,"md-effect-15":a.Yg.$yc,"md-effect-17":a.Yg.czc,"md-effect-18":a.Yg.dzc,"md-effect-19":a.Yg.fzc};
c.Kic=function(a){t.K.call(this,a);this.Ic=a};var t=c.u(c.Kic,c.T6);t.nb=function(){t.k.nb.call(this)};t.R=function(){this.ib.z7();t.k.R.call(this)};t.ma=function(){return this.Ic.Hb()};t.Ta=function(){return null};t.zka=function(){return!0};t.mea=function(){};t.Cna=function(){};t.Bna=function(){};t.qA=function(){};t.cy=function(){};t.Ava=function(){return null};t.qL=function(){return!1};t.Zd=function(){return!0};t.kO=function(){return!0};t.ZN=function(){return!1};t.N0=function(){return!1};t.Oe=function(b){b[0]=
a.V0a;b[1]=a.T0a};t.lMd=function(){};t.m_=function(a){t.k.m_.call(this,a)};t.TGc=function(){return!1};t.yma=function(){};t.Pg=function(){};t.Cda=function(){};t.$x=function(){};t.Fda=function(){};t.OE=function(){};c.Ux=function(){d.Ob("PRIM_IMAG");d.Ob("PRIM_TBLO");d.Ob("PRIM_LABL");m.K.call(this);this.Nb=b.Nf(10,10,280,120);this.yg=a.bm.Qma;this.Mm=this.qe=this.wY=this.Hp=null;this.SA=a.Yg.z2;this.UM=a.qh.Xx;this.FTa=this.R3=this.JU=null;this.Hg=new c.sd(0,0);this.geb=this.fha=this.ep=this.WD=this.HF=
this.tC=this.Os=this.fV=this.Gp=null;this.vUa="";this.$Ta=12;this.eha=a.o.Sb;b.ba().G8c(this);this.uGc();b.ba().kUc();var e=null;this.Ts();this.Os=new c.$l;this.Os.sb(new c.qa(0,0,0,30));this.Os.Pe(!1);this.Os.xq(!1);this.Os.$p(this.Oc);this.Os.Dna(!1);this.tC=new c.bu;this.tC.Pe(!1);this.tC.XE(a.ae.hM);this.tC.Oa(this.Os);this.tC.CB(a.Jc.jA);this.HF=new c.bu;this.HF.XE(a.ae.HAa);this.HF.Oa(this.Os);this.HF.Pe(!1);this.HF.za(this,a.Q.tc,this.ROc);this.HF.za(this,a.Q.HG,this.SOc);this.HF.za(this,a.Q.IG,
this.TOc);this.WD=new c.Ow;this.WD.Oa(this.Os);this.WD.Pe(!1);this.WD.Ro(a.gh.Bq);this.WD.Ff(!1);this.WD.vg(a.Rp.w0b);b.Qc(this.Oc,this.Os,null,null,1,1);e=b.Qc(this.Oc,this.tC,this.Oc.Fc(0),this.Oc.Nc(0),1,1);e.Wb(a.na.Mq);e.fc(a.ta.Nk);e.Bf(2);e=b.Qc(this.Oc,this.HF,this.Oc.Fc(0),this.Oc.Nc(0),1,1);e.Wb(a.na.AC);e.fc(a.ta.tf);e.we(2);e=b.Qc(this.Oc,this.WD,this.Oc.Fc(0),this.Oc.Nc(0),1,1);e.Wb(a.na.se);e.fc(a.ta.Nk);this.Pe(!1)};var m=c.u(c.Ux,c.$l);m.nb=function(){b.ga(this.TKd);this.TKd=null;
b.ga(this.Os);this.Os=null;b.ga(this.tC);this.tC=null;b.ga(this.HF);this.HF=null;b.ga(this.WD);this.WD=null;m.k.nb.call(this)};m.R=function(){b.ga(this.ep);this.ep=null;m.k.R.call(this);this.lna(null);this.k5a(null);this.o6a(null);this.p6a(null);this.jna(null);this.iFb(null);b.ba().$kd(this);b.ga(this.Mm);this.Mm=null;b.ga(this.FTa);this.FTa=null};m.Be=function(){var a=c.HL;this.pS()&&(a=c.Olc);return a};m.W0d=function(){return this.UM};m.mva=function(){if(null==this.FTa){var a=new c.Kic(this);this.FTa=
b.Uca(a);this.Ia(this,this.fRc)}return this.FTa};m.lna=function(b){this.Hp!=b&&(this.Hp&&this.Hp.Ha(this),(this.Hp=b)&&this.Hp.Ia(this,this.iXb),this.m(a.g.j))};m.sYc=function(){return this.Hp};m.Jja=function(){var a=null;this.Hp&&this.Hp instanceof c.Tx&&(a=this.Hp);return a};m.k5a=function(b){this.wY!=b&&(this.wY&&this.wY.Ha(this),(this.wY=b)&&this.wY.Ia(this,this.sOc),this.m(a.g.j))};m.rTd=function(){return this.wY};m.o6a=function(b){this.JU!=b&&(this.JU&&this.JU.Ha(this),(this.JU=b)&&this.JU.Ia(this,
this.dRc),this.m(a.g.j))};m.U0d=function(){return this.JU};m.p6a=function(b){this.R3!=b&&(this.R3&&this.R3.Ha(this),(this.R3=b)&&this.R3.Ia(this,this.eRc),this.m(a.g.j))};m.V0d=function(){return this.R3};m.Hb=function(){var a=this.qe;!this.qe||this.qe instanceof c.Ux||(a=this.qe);!a&&this.ctb()&&(a=this);return a};m.GVd=function(){return this.qe};m.bS=function(){null==this.Mm&&(this.Mm=new c.Ila,this.Mm.Xtc(),this.Mm.MOa(a.jy.X8a));return this.Mm};m.S1c=function(){return this.Mm};m.m2d=function(){return this.Hg};
m.Up=function(){this.jh();return this.Dg};m.$da=function(b){b=this.yg&~a.bm.lBb|(b?a.bm.lBb:0);this.yg!=b&&(this.yg=b,this.m(a.g.j))};m.ena=function(b){b=this.yg&~a.bm.p4a|(b?a.bm.p4a:0);this.yg!=b&&(this.yg=b,this.m(a.g.j))};m.kIa=function(){return 0!=(this.yg&a.bm.p4a)};m.aDb=function(b){b=this.yg&~a.bm.mBb|(b?a.bm.mBb:0);this.yg!=b&&(this.yg=b,this.m(a.g.j))};m.pua=function(){return 0!=(this.yg&a.bm.mBb)};m.hFb=function(b){b=this.yg&~a.bm.vBb|(b?a.bm.vBb:0);this.yg!=b&&(this.yg=b,this.pY(this.xf()),
this.m(a.g.j))};m.Cpb=function(){return 0!=(this.yg&a.bm.vBb)};m.j3c=function(){return this.$Ta};m.ruc=function(b){b!=this.$Ta&&(this.$Ta=b,this.xb(),this.pa(a.g.j))};m.n2d=function(){return this.eha};m.FOa=function(b){if(this.itb()||this.eha!=b)this.eha=b,this.m(a.g.j)};m.tvd=function(){!1==this.itb()&&(this.eha=a.o.Sb,this.m(a.g.j))};m.Msc=function(b){b=this.yg&~a.bm.nBb|(b?a.bm.nBb:0);this.yg!=b&&(this.yg=b,this.pY(this.xf()),this.m(a.g.j))};m.CYa=function(){return 0!=(this.yg&a.bm.nBb)};m.fhe=
function(b){b=this.yg&~a.bm.tBb|(b?a.bm.tBb:0);this.yg!=b&&(this.yg=b,this.m(a.g.j))};m.t2c=function(){return 0!=(this.yg&a.bm.tBb)};m.stc=function(){var b=this.yg&~a.bm.rBb|a.bm.rBb;this.yg!=b&&(this.yg=b,this.m(a.g.j))};m.d4b=function(){return 0!=(this.yg&a.bm.rBb)};m.ovd=function(){var b=this.yg&~a.bm.eqc|0;this.yg!=b&&(this.yg=b,this.m(a.g.j))};m.i3c=function(){return 0!=(this.yg&a.bm.eqc)};m.VG=function(b){b=this.yg&~a.bm.qBb|(b?a.bm.qBb:0);this.yg!=b&&(this.yg=b,this.m(a.g.j))};m.ctd=function(b){b=
this.yg&~a.bm.pBb|(b?a.bm.pBb:0);this.yg!=b&&(this.yg=b,this.m(a.g.j))};m.Xge=function(b){b=this.yg&~a.bm.sBb|(b?a.bm.sBb:0);this.yg!=b&&(this.yg=b,this.m(a.g.j))};m.cea=function(b){b=this.yg&~a.bm.oBb|(b?a.bm.oBb:0);this.yg!=b&&(this.yg=b,this.m(a.g.j))};m.a3b=function(){return 0!=(this.yg&a.bm.oBb)};m.$2b=function(){return this.Gp};m.jna=function(b){this.Gp!=b&&(null!=this.Gp&&(this.Gp.Ha(this,this.Gjb),this.Gp.ub()),this.Gp=b,null!=this.Gp&&(this.Gp.Ba(),this.Gp.Ia(this,this.Gjb)),this.pY(this.xf()),
this.pa(a.g.j))};m.i4c=function(){return this.fV};m.iFb=function(b){this.fV!=b&&(null!=this.fV&&(this.fV.Ha(this,this.iZb),this.fV.ub()),this.fV=b,null!=this.fV&&(this.fV.Ba(),this.fV.Ia(this,this.iZb)),this.pY(this.xf()),this.pa(a.g.j))};m.k3c=function(){return this.mva().Gh()};m.suc=function(b){this.mva().Gh()!=b&&(this.mva().Jb(b),this.m(a.g.j))};m.l3c=function(){return this.mva().Zk()};m.$a=function(){var a=null;null!=this.Ta()&&(a=this.Ta().$a());return a};m.DWc=function(){var a=!1;if(this.pS()||
!this.ctb())a=!0;return a};m.h4c=function(){return this.vUa};m.vwd=function(b){this.vUa!=b&&(this.vUa=b,this.xb(),this.pa(a.g.j))};m.Oh=function(){var a=!1;null!=this.Ta()&&(a=this.Ta().$a(),a=b.pe[a].GSa);return a};m.hsb=function(){return 0!=(this.yg&a.bm.lBb)};m.zKa=function(){return 0!=(this.yg&a.bm.p4a)};m.Osb=function(){return 0!=(this.yg&a.bm.qBb)};m.l6d=function(){return 0!=(this.yg&a.bm.pBb)};m.ctb=function(){return 0!=(this.yg&a.bm.sBb)};m.pS=function(){return 0!=(this.yg&a.bm.uBb)};m.Dsb=
function(){return!1};m.itb=function(){return!1==this.k7b()};m.k7b=function(){return this.eha!=a.o.Sb};m.M0=function(){var a=!1;this.Hb()==this&&this.Hb().W()&&this.Hb().W()!=this.Mm&&(a=!0);return a};m.O6c=function(){var a=this.M0();a&&!this.W().j0a()&&(a=!1);return a};m.N1=function(){if(null!=this.Ta()){var a=this.qka()?this.qka().wh():"DEFAULT";b.c$a(this.Ta().$a(),a,this.ha.J9)}};m.wjd=function(a){var c=!1;this.Oh()&&this.zKa()&&this.Jja()&&null!=a&&b.ba().NE(this.Jja())==a&&(c=!0);return c};m.xjd=
function(a){var c=!1;if(this.Oh()&&this.zKa()&&!this.Dsb())if(null==a)c=!0;else for(var d=b.ba().NE(a),c=!0;null!=a&&null!=d;)d==this?(c=!1,a=null):null!=d&&(d.Jja()?(d=d.Jja(),a=a!=d?d:null):a=null),d=b.ba().NE(a);return c};m.pY=function(d,e){e===p&&(e=!1);if(!b.ba().P0())if(this.Cpb()){var f=new c.qa(0,0,d.ja(),30),k=d.ja()-4;this.CYa()&&(k-=f.la());this.fV&&(k-=f.la());this.WD.tb(this.ab());this.WD.qc(Math.min(k,this.WD.e_a(this.WD.ab(),this.WD.op().length)+10));this.Os.Ib(this);this.Os.sb(f);
this.Os.Qb(""==this.vUa?a.Jca:this.vUa);this.tC.Ab(this.CYa());this.tC.qc(f.la());this.tC.Ab(null!=this.fV);this.tC.Bd(this.fV);this.tC.sb(new c.qa(this.tC.ve(),this.tC.Te(),Math.min(this.tC.Zc()?this.tC.Zc().Ua():this.Os.Na(),this.Os.Na()-4),Math.min(this.tC.Zc()?this.tC.Zc().Na():this.Os.Na(),this.Os.Na()-4)));this.HF.Ab(this.CYa());this.HF.sb(new c.qa(this.HF.ve(),this.HF.Te(),30,29));this.HF.Nj(this.Gp?this.Gp:a.oc.XId);e?b.ba().jGc(this.HF):b.ba().ild(this.HF);this.Os.W()&&d.Xa(d.$()+f.la())}else this.Os.Oa(null)};
m.lf=function(a){this.pY(a);m.k.lf.call(this,a)};m.jh=function(){this.M0()||this.Oa(this.bS());this.Urd(this.pS());this.DWc()&&m.k.jh.call(this)};m.Vk=function(){m.k.Vk.call(this);this.pY(this.xf())};m.fBb=function(b,c,d){m.k.fBb(b,c,d);d[0]&&this.NW()!=a.ky.$Ba&&this.Cpb()&&(d[0]=this.Os==c||this.WD==c)};m.Oe=function(b){""==b[0]&&(b[0]=a.V0a);""==b[1]&&(b[1]=a.T0a);m.k.Oe.call(this,b)};m.Gda=function(a){return this.Xia(this.Hp,a)};m.h4a=function(){this.pua()&&this.SA==a.Yg.z2&&this.Hb().Tf(!0);
this.X1b()};m.Dpc=function(){if(this.pua()){var a=b.CO();a&&a.vs(this)||this.Hb().Tf(!0)}};m.vjd=function(a){return this.VHa(a)};m.jza=function(){null!=this.Mm&&(null!=this.Hb()&&this.Wv(this.Hb(),a.ea.O0a),this.lna(null),this.Osb()||null==this.wY||this.kIa()||b.Mxa()!=this.wY||this.wY.VE(this.wY.rI()),this.k5a(null),this.o6a(null),this.p6a(null));this.hsb()&&this.ns()};m.jNa=function(){};m.INa=function(){this.Hg.wn(this.ve());this.Hg.Zm(this.Te());this.Oh()&&this.vD(this.UM,this.JU,this.Hg,this.Hp,
this.R3,this.SA)};m.Aea=function(d,e,f,k,h){var m=b.Wn();this.M0()&&(m.wn(this.ve()),m.Zm(this.Te()));d==p&&(d=m.Pb());e==p&&(e=m.Vb());f==p&&(f=a.qh.Xx);k==p&&(k=a.Yg.z2);this.vD(f,null,new c.sd(d,e),h,null,k)};m.vD=function(d,e,f,k,h,m){this.zf()&&d==a.qh.wma&&null==e&&k&&k.zf()&&(e=k);this.O6c()||this.Oa(this.bS());d==p&&(d=a.qh.Xx);e==p&&(e=null);f==p&&(f=b.Wn());k==p&&(k=null);h==p&&(h=null);m==p&&(m=a.Yg.z2);if(this.Oh()&&this.ctb()){if(this.JU==e&&this.R3==h&&this.Hp==k&&this.UM==d&&this.SA==
m){d=b.Vi(f.Pb(),f.Vb(),this.Hb().Ua(),this.Hb().Na());this.iza(d);this.bS().sb(new c.qa(0,0,d.ja(),d.la()));f.wn(d.aa());f.Zm(d.$());this.Hb().sb(d);this.evc(this.mva().DI());this.Hg=f;return}var u=this.hsb();this.$da(!1);this.Do();this.jza();this.$da(u)}this.UM!=a.qh.Xx&&this.W()!=this.Mm&&this.Oa(null);this.yg|=a.bm.uBb;this.juc(!1);null!=this.Up()&&(this.lna(k),this.bS(),this.d4b()&&this.bS().ha.rD(this.Jja()?this.Jja().ha:null),this.t2c()&&this.Wv(this.bS(),a.ea.N0a),this.k5a(b.Mxa()),this.UM=
d,this.SA=m,this.pY(this.xf()),this.o6a(e),this.p6a(h),this.Mhd(f,this.Osb()),this.W()==this.bS()?this.Wv(this.bS(),a.ea.lla):this.Wv(this,a.ea.lla),this.h4a())};m.Do=function(){if(this.Oh()){var c=b.ba().Pk;c&&c.vs(this)&&this.Wv(c,a.ea.eA);b.ba().iLc(this);null!=this.Ta()&&(c=this.Ta().$a(),b.pe[c].IGa());this.Ylb();this.jza()}else b.ba().P$&&(c=b.ba().P$,c.Ta()&&c.Ta().GSa&&c==this.Hp&&b.ba().Gu(c,!1))};m.UGc=function(a){for(var b=this.ha.DI(),c=null,d=b.length-1;null!=b&&0<=d&&null!=(c=b[d]);d--)a.splice(0,
0,c)};m.Mhd=function(a,c){this.Ta()&&(c||(b.ba().yy&&b.ba().yy.$7b(),b.ba().My(this.Jja(),!1,this)),this.Nhd(a))};m.Nhd=function(c){if(this.Gda(c)&&this.Hb()){this.Hb().jh();this.d4b()&&this.bS().AE(!0);c=this.Mm;c.cX()||c.F3a();c=this.Ta().$a();a.JCa+=2;b.pe[c].PEa=a.JCa;b.gLb(c,b.pe[c].dh());b.pe[c].AAa();var d=b.pe[c].L.ep?b.pe[c].L.ep.Ta():null;d&&d.G.parentElement!=document.body&&(null!=d.G.parentElement&&d.G.parentElement.removeChild(d.G),d.KBc=!1,d.G.style.zIndex=b.pe[c].PEa-1,document.body.appendChild(d.G))}};
m.iza=function(a){b.xed(this,a)};b.xed=function(d,e){switch(d.UM){case a.qh.G3a:var f=b.IE(),f=new c.qa(f.ve()-d.ha.Mi(),f.Te()-d.ha.Vj(),f.Ua()+(d.ha.Mi()+d.ha.Hj()),f.Na()+(d.ha.Vj()+d.ha.kl()));e.VA(f);break;case a.qh.eJ:var f=b.IE(),k=0,h=0,k=(f.ja()-e.Ua())/2,h=(f.la()-e.Na())/2;e.Rb(k,h);d.M0()&&e.VA(d.W().Vda(e));break;case a.qh.wma:f=b.IE();k=(f.ja()-e.Ua())/2;h=f.Fa()-e.Na();e.Rb(k,h);d.M0()&&e.VA(d.W().Vda(e));break;case a.qh.Fhd:f=b.IE();k=(f.ja()-e.Ua())/2;e.Rb(k,0);d.M0()&&e.VA(d.W().Vda(e));
break;case a.qh.Coc:f=b.IE();h=(f.la()-e.Na())/2;k=f.Ka()-e.Ua();e.Rb(k,h);d.M0()&&e.VA(d.W().Vda(e));break;case a.qh.Aoc:f=b.IE();h=(f.la()-e.Na())/2;e.Rb(0,h);d.M0()&&e.VA(d.W().Vda(e));break;default:b.V1a(e)}};m.bfd=function(){b.ba();this.ep=new c.$l;this.ep.za(this,a.Q.Vfb,this.DRc);this.ep.za(this,a.Q.tc,this.ERc);this.zf()&&(this.ep.O5().eg("positioning:flex; alignitems-center; justify-content:center;"),this.ep.hB().eg("position:fixed; top:0px; right:0px; left:0px;"),this.ep.MW().eg("height:100vh;"));
this.ep.Vd(1);this.ep.Za(0);this.ep.Jna(1);this.ep.Xa(0);this.ep.Ab(!1);this.ep.Pe(!1);this.geb=new c.Yf;this.fha=new c.yb;this.fha.Ld(this.geb)};m.evc=function(a){var d=b.ba().dn;this.ep||this.bfd();if(!this.ep.Xb()){if(this.zf()){var e=b.RL(this.zc(),this.eha,this.$Ta/100,[]);this.ep.ZF().eg("class:drawer-shroud;");this.ep.Rn().eg("background-color:"+e+";")}this.geb.Rd(this.eha);this.geb.Rg(this.$Ta);this.ep.Jb(this.k7b()?this.fha:null);for(e=0;e<a.length;e++)this.ep.Un(a[e]);null==this.ep.Gh()?
this.ep.Oa(null):(this.ep.Ib(d),this.ep.Vd(1),this.ep.XV())}this.ep.sb(new c.qa(0,0,d.Ua(),d.Na()))};m.X6c=function(){this.ep&&this.ep.zb()&&this.ep.Qr()};m.Mj=function(c){if(this.i3c()){var d=this.Ta().$a();a.JCa+=2;b.pe[d].PEa=a.JCa;b.gLb(d,b.pe[d].dh())}m.k.Mj.call(this,c)};m.Xia=function(b,e){var f=!0,k=d.cc(),h=this.Hb().Ua(),m=this.Hb().Na();k.kc("CONTEXT",b);k.MF("LEFT",e.Pb());k.MF("TOP",e.Vb());k.MF("WIDTH",h);k.MF("HEIGHT",m);k.fN("TRANSITION",this.SA,a.Yg.v);k.mg("CONTINUE",!0);this.Ga(a.Q.Yx,
k);e.wn(k.Wua("LEFT"));e.Zm(k.Wua("TOP"));f=k.ah("CONTINUE");h=h==k.Wua("WIDTH")?this.Hb().Ua():k.Wua("WIDTH");m=m==k.Wua("HEIGHT")?this.Hb().Na():k.Wua("HEIGHT");h=new c.qa(e.Pb(),e.Vb(),h,m);this.iza(h);this.bS().sb(new c.qa(0,0,h.ja(),h.la()));e.wn(h.aa());e.Zm(h.$());this.Hb().sb(h);this.SA=k.Mnb("TRANSITION",a.Yg.v);k.Kc();this.Hg=e;return f};m.VHa=function(b){var c=!1,c=d.cc();c.mg("CLOSEPOPUP",!0);this.Ga(a.Q.kR,c);return c=b?!0:c.ah("CLOSEPOPUP")};m.Ylb=function(){this.Ga(a.Q.kN);this.yg&=
~a.bm.uBb;this.juc(!0);this.M0()&&this.W().xb()};m.X1b=function(){this.Ga(a.Q.Xzb)};m.DRc=function(){this.ep.zb()||(this.ep.Oa(null),this.jNa())};m.ERc=function(){this.Dsb()&&this.zKa()&&b.ba().Gu(this,!1)};m.SOc=function(){this.pY(this.xf(),!0)};m.TOc=function(){this.pY(this.xf())};m.ROc=function(a,c){b.ba().Gu(this,!1);c.uk("HANDLED",!0)};m.fRc=function(){};m.iXb=function(b,c){switch(c.eb){case a.g.Bb:this.lna(null)}};m.dRc=function(b,c){switch(c.eb){case a.g.Bb:this.o6a(null)}};m.eRc=function(b,
c){switch(c.eb){case a.g.Bb:this.p6a(null)}};m.sOc=function(b,c){switch(c.eb){case a.g.Bb:this.k5a(null)}};m.Gjb=function(b,c){switch(c.eb){case a.g.Bb:case a.g.Ub:this.jna(null)}};m.iZb=function(b,c){switch(c.eb){case a.g.Bb:case a.g.Ub:this.iFb(null)}};m.mHa=m[a.ea.jxa]=function(){this.pS()&&this.INa()};m.AR=m[a.ea.CE]=function(a){m.k.AR.call(this,a);this.pY(this.xf())};m.Hv=m[a.ea.wL]=function(a){m.k.Hv.call(this,a);this.pY(this.xf())};d.Md(c.Ux,"PRIM_PPNL",{Aa:{CloseOnClick:{a:m.a3b,f:function(a){this.cea(d.Ca(a))}},
AutoClose:{a:m.kIa,f:function(a){this.ena(d.Ca(a))}},AutoFocus:{a:m.pua,f:function(a){this.aDb(d.Ca(a))}},TitleBar:{a:m.Cpb,f:function(a){this.hFb(d.Ca(a))}},ShroudColor:{a:function(){return this.itb()?d.ed:b.ug(this.eha)},f:function(a){a===d.ed?this.tvd():this.FOa(b.Xf(d.ka(a)))}},ShroudOpacity:{a:m.j3c,f:function(a){this.ruc(d.O(a))}},CloseButton:{a:m.CYa,f:function(a){this.Msc(d.Ca(a))}},CloseImage:{a:m.$2b,f:m.jna},TitleImage:{a:m.i4c,f:m.iFb},ShroudStyle:{a:m.k3c,f:m.suc},ShroudStyles:{a:m.l3c},
TitleBarThemeDrawStyle:{a:m.h4c,f:function(a){this.vwd(d.ka(a))}},IsOpen:{a:m.Oh}},jc:{ShowPopup:function(b,c,e,f,k){this.Aea(b===p?p:d.O(b),c===p?p:d.O(c),e===p||""==e?p:d.wa(e,a.qh.yed),f===p||""==f?p:d.wa(f,a.Yg.v),k)},ClosePopup:m.Do}});c.sxb=function(d){q.K.call(this,d);this.Nb=b.Nf(0,0,300,30);this.QEa=a.Tya.Ghd;this.eTa=new c.Pw;this.U9=this.cQ=this.bQ=null;this.FY=[];this.fdb=null;b.lo(this.eTa);b.ko(this.eTa);this.$p(this.eTa);this.Pe(!1);this.U9=new c.h2a;this.U9.pOa(a.OO.bnc);this.U9.za(this,
a.Q.Yx,this.XOc);this.bQ=new c.bu;this.bQ.Oa(this);this.bQ.sb(new c.qa);this.bQ.za(this,a.Q.tc,this.YOc);this.bQ.VX();this.fdb=new c.Hic(this)};var q=c.u(c.sxb,c.$l);q.nb=function(){q.k.nb.call(this)};q.R=function(){q.k.R.call(this);b.ga(this.fdb);this.fdb=null};q.ZXc=function(){return this.cQ};q.Nsc=function(b){this.cQ!=b&&(null!=this.cQ&&(this.cQ.Ha(this,this.dXb),this.cQ.ub()),this.cQ=b,null!=this.cQ&&(this.cQ.Ba(),this.cQ.Ia(this,this.dXb)),this.xb(),this.m(a.g.j))};q.nvd=function(b){b=this.yg&
~a.Tya.zAb|(b?a.Tya.zAb:0);this.QEa!=b&&(this.QEa=b,this.m(a.g.j))};q.lpb=function(){return 0!=(this.QEa&a.Tya.zAb)};q.Drd=function(b){this.DYa()!=b&&(this.QEa=this.QEa&~a.Tya.Doc|b,this.xb(),this.AE(),this.fpc(this.xf()),this.pa(a.g.j))};q.DYa=function(){return this.QEa&a.Tya.Doc};q.qnb=function(){var b=null;switch(this.DYa()){case a.lR.mib:case a.lR.kib:b=q.k.qnb.call(this);break;case a.lR.gib:d.Ob("PRIM_PCOL"),b=new c.Uwb(this.U9),b=new c.S6(b)}return b};q.Oe=function(b){""==b[0]&&(b[0]=a.Fbc);
""==b[1]&&(b[1]=a.rbd);q.k.Oe.call(this,b)};q.$Ab=function(){this.$p(this.eTa)};q.Zx=function(c,d){q.k.Zx.call(this,c,d);this.$Ab();b.Iic(this,this.eTa,a.La.Wk,a.na.bE,a.ta.Nk,this.Fjb)};q.lf=function(a){q.k.lf.call(this,a);this.fpc(a)};q.fpc=function(d){switch(this.DYa()){case a.lR.mib:for(this.bQ.Ab(!1);0<this.FY.length;)this.FY[0].ns();break;case a.lR.kib:for(var e=this.FY.length,f=0,k=null,h=this.Is,m=h.length-1;0<=m&&null!=(k=h[m]);m--)f=Math.max(f,k.Nb.Ka()),k.Vt()>d.Ka()&&(b.Gic(this,k),e++);
h=this.FY;for(m=0;m<h.length&&null!=(k=h[m]);m++)f+k.gb.Ua()<d.Ka()?(k.ns(),m--,e--):k.ma().Vd(m+1);if(0<e)this.bQ.Nj(this.cQ?this.cQ:a.oc.izb),this.bQ.sb(new c.qa(d.Ka()-(d.la()+2),0,d.la(),d.la())),this.bQ.Ab(!0),this.U9.d4a();else for(this.bQ.Ab(!1);0<this.FY.length;)this.FY[0].ns();break;case a.lR.gib:for(;0<this.Is.length;)b.Gic(this,this.Is[this.Is.length-1]);this.bQ.Nj(this.cQ?this.cQ:a.oc.izb);this.bQ.sb(new c.qa(d.Ka()-(d.la()+2),0,d.la(),d.la()));this.bQ.Ab(!0);this.U9.d4a()}this.Xb()&&
this.jh()};b.Iic=function(c,d,e,f,k,h){for(var m=null,p=c.Is,u=1,q=0;q<p.length&&null!=(m=p[q]);q++,u++){var s=d.Lg(m);s||(s=b.Qc(d,m,d.Fc(0),d.Nc(0),1,1),m.za(c,a.Q.bJ,h));s.pi(e);s.Wb(f);s.fc(k)}};q.dXb=function(b,c){switch(c.eb){case a.g.Bb:case a.g.Ub:this.Nsc(null);break;case a.g.j:this.xb()}};q.XOc=function(b,c){this.Ga(a.Q.Yx,c)};q.YOc=function(b,d){this.U9.vD(a.qh.Xx,this,new c.sd(this.Wt()+this.Ua()-this.U9.Ua(),this.Xt()+this.Na()),this);d.uk("HANDLED",!0)};q.Fjb=function(a){this.lpb()&&
(a=a instanceof c.Nla?a:null)&&a.QC()&&!a.QC().Oh()&&(a.lu(),this.fdb.Wh())};d.Sa(c.sxb,"PRIM_PPNL","MenuBar",{Aa:{CollapsedMenuImage:{a:q.ZXc,f:q.Nsc},ShowOnHover:{a:q.lpb,f:function(a){this.nvd(d.Ca(a))}},CollapseStyle:{a:function(){return d.va(this.DYa(),a.lR.v)},f:function(b){this.Drd(d.wa(b,a.lR.v))}}}});c.Hic=function(a){s.K.call(this,500);this.zZ=a};var s=c.u(c.Hic,c.w1);s.$_=function(){if(this.zZ.lpb()){var a=!1,c=!1,d=b.ba().AAb(b.Wn());d?a=!0:(d=b.lX(b.Wn()))&&(d==this.zZ||d.vs(this.zZ))&&
(a=!0);!a&&(d=b.ba().NE(b.CO()))&&(c=a=!0);a||(this.zZ.My(),c=!0);c&&this.qi()}return!1};c.h2a=function(){h.K.call(this);this.Nb=b.Nf(0,0,150,150);this.Fi=new c.Pw;this.yz=a.jzb.xMa;b.lo(this.Fi);b.ko(this.Fi);this.$p(this.Fi)};var h=c.u(c.h2a,c.Ux);h.nb=function(){h.k.nb.call(this)};h.R=function(){h.k.R.call(this)};h.pOa=function(b){this.aJa()!=b&&(this.yz=this.yz&~a.jzb.fnc|b,this.xb(),this.pa(a.g.j))};h.aJa=function(){return this.yz&a.jzb.fnc};h.Oe=function(b){""==b[0]&&(b[0]=a.Hbc);""==b[1]&&
(b[1]=a.sbd);h.k.Oe.call(this,b)};h.$Ab=function(){this.$p(this.Fi);this.cea(!0)};h.Zx=function(c,d){h.k.Zx.call(this,c,d);this.$Ab();b.Iic(this,this.Fi,a.La.Uj,a.na.jp,a.ta.fi,this.Fjb)};h.d4a=function(){if(this.aJa()!=a.OO.nda){for(var b=null,d=this.Is,e=[!0,2,2,0,0],f=0;f<d.length&&null!=(b=d[f]);f++){var k=b instanceof c.Nla?b:null;switch(this.aJa()){case a.OO.xya:k?k.upc(e):e[2]+=b.zb()?b.Na():0;break;case a.OO.bnc:e[1]=Math.max(e[1],b.Ua()),e[2]+=b.zb()?b.Na():0}}for(f=0;f<d.length&&null!=(b=
d[f]);f++)switch(this.aJa()){case a.OO.xya:(k=b instanceof c.Nla?b:null)&&k.qc(e[1])}this.qc(e[1]+this.ha.Mi()+this.ha.Hj());this.yc(e[2]+this.ha.Vj()+this.ha.kl())}};h.Gda=function(a){this.d4a();return h.k.Gda.call(this,a)};h.lf=function(a){h.k.lf.call(this,a)};h.kXb=h[a.ea.cub]=function(a){h.k.kXb.call(this,a);this.d4a()};h.Fjb=function(a){(a=a instanceof c.Nla?a:null)&&a.lu()};d.Sa(c.h2a,"PRIM_PPNL","Menu",{Aa:{MenuSizing:{a:function(){return d.va(this.aJa(),a.OO.v)},f:function(b){this.pOa(d.wa(b,
a.OO.v))}}}});c.Jic=function(a){e.K.call(this);this.M$=a};var e=c.u(c.Jic,c.HO);e.V$b=function(){return!0};e.phb=function(a,b){return e.k.phb.call(this,a,b,this.M$)};e.Oe=function(){};c.Nla=function(){k.K.call(this);this.Nb=b.Nf(0,0,100,25);this.zga=a.Yla.j7;this.uv=0;this.Gcb=this.GOb=this.ap=this.sU=this.G$=this.nZ=this.OQ=null;this.H$=new c.Pw;this.zy=0;this.bN=a.Jc.bD;b.lo(this.H$);b.ko(this.H$);this.$p(this.H$);this.iOa(!0);this.sU=new c.yb;this.sU.hr(a.o.ze);this.sU.Zj(a.o.ze);this.sU.wq(1);
this.sU.ir(1);this.sU.Oo(1);this.sU.Po(1);this.G$=new c.bu;this.G$.Oa(this);this.G$.sb(new c.qa(0,0,18,18));this.G$.Jb(this.sU);this.ap=new c.Jic(this);this.ap.Oa(this);this.ap.Bf(2);this.ap.we(2);this.GOb=b.Qc(this.H$,this.ap,this.H$.Fc(0),this.H$.Nc(0),1,1);this.Gcb=b.Qc(this.H$,this.G$,this.H$.Fc(0),this.H$.Nc(0),1,1)};var k=c.u(c.Nla,c.$l);k.nb=function(){k.k.nb.call(this)};k.R=function(){k.k.R.call(this);this.V5a(null)};k.QC=function(){return this.ap.QC()};k.X7=function(b){this.QC()!=b&&(this.ap.QC()&&
this.ap.QC().Ap(this,a.Q.Yx,this.$Xb),this.ap.X7(b),this.ap.QC()&&this.ap.QC().za(this,a.Q.Yx,this.$Xb),this.m(a.g.j))};k.Qba=function(){return this.ap.Qba()};k.U_c=function(){return this.nZ};k.V5a=function(b){this.nZ!=b&&(null!=this.nZ&&(this.nZ.Ha(this,this.ZXb),this.nZ.ub()),this.nZ=b,null!=this.nZ&&(this.nZ.Ba(),this.nZ.Ia(this,this.ZXb)),this.Iu(),this.m(a.g.j))};k.Lv=function(){return this.zy};k.gu=function(b){b!=this.zy&&(this.zy=b,this.Iu(),this.pa(a.g.j))};k.ju=function(b){this.bN!=b&&(this.bN=
b,this.Iu(),this.pa(a.g.j))};k.Jf=function(){return this.ap.Jf()};k.Ef=function(b){this.Jf()!=b&&(this.ap.Ef(b),this.m(a.g.j))};k.Sf=function(){return this.ap.Sf()};k.Bf=function(b){this.Sf()!=b&&(this.ap.Bf(b),this.m(a.g.j))};k.Wg=function(){return this.ap.Wg()};k.we=function(b){this.Wg()!=b&&(this.ap.we(b),this.m(a.g.j))};k.$g=function(){return this.ap.$g()};k.jg=function(b){this.$g()!=b&&(this.ap.jg(b),this.m(a.g.j))};k.Am=function(){return this.bN};k.oka=function(){return 0!=(this.zga&a.Yla.sX)?
!0:!1};k.yOa=function(b){b=this.zga&~a.Yla.sX|(b?a.Yla.sX:0);this.zga!=b&&(this.zga=b,this.Iu(),this.pa(a.g.j))};k.bh=function(){return 0!=(this.zga&a.Yla.rX)?!0:!1};k.Gi=function(b){var d=this.uI();if(b&&0!=d&&null!=this.W())for(var e=null,f=this.W().pg,k=0;k<f.length&&null!=(e=f[k]);k++)if(e instanceof c.Nla){var h=e;h!=this&&h.uI()==d&&h.Gi(!1)}b=this.zga&~a.Yla.rX|(b?a.Yla.rX:0);this.zga!=b&&(this.zga=b,this.Iu(),this.pa(a.g.j))};k.uI=function(){return this.uv};k.S7=function(b){this.uv!=b&&(this.uv=
b,this.Iu(),this.pa(a.g.j))};k.tpb=function(){return this.OQ};k.P6a=function(a){this.OQ!=a&&(this.OQ=a)};k.Oe=function(b){""==b[0]&&(b[0]=a.Ebc);k.k.Oe.call(this,b)};k.lu=function(){var a=b.ba().NE(this);(null==a||a.Oh())&&this.QC()&&!this.QC().Oh()&&this.ap.yIb(!0)};k.dKa=function(){var a=b.ba().NE(this);(null==a||a.Oh())&&this.QC()&&this.QC().Oh()&&this.ap.yIb(!0)};k.upc=function(b){var d=null,e=this.gc&&this.gc instanceof c.sxb?this.gc:null,f=this.zy;this.bh()?(d=this.oka()?a.oc.Xmc:a.oc.Wmc,this.sU.hr(a.o.BT),
this.sU.Zj(a.o.Mea)):(this.sU.hr(a.o.ze),this.sU.Zj(a.o.ze));this.nZ&&(d=this.nZ);d&&0==f&&(f=Math.min(this.Na(),d.Na()));this.ap.Qb(a.Wbd);this.ap.dT(!1);this.ap.ju(this.Am());this.ap.h6a(e?a.aJ.rMa:a.aJ.sMa);this.ap.qEb(e?a.tq.nda:a.tq.yya);this.ap.TL(a.$w.gR);this.ap.kAa(!1);this.ap.tb(this.ab());this.ap.Ro(a.gh.Bq);this.G$.Nj(d);this.G$.sb(new c.qa(this.G$.ve(),this.G$.Te(),f,f));this.GOb.fc(a.ta.Sg);this.GOb.Bf(e?0:f+2);this.Gcb.fc(a.ta.tf);this.Gcb.Wb(a.na.Mq);this.Gcb.Bf(e?0:2);this.ap.tk(!1,
!0);var k=this.ap.AN(),h=this.ap.Eja();e?(k+=f+4,d&&(k+=f+4)):(k+=60,h+=10);!0==b[0]&&(this.yc(h),b[1]=Math.max(b[1],k),b[2]+=this.zb()?h:0,b[3]+=k,b[4]+=h)};k.Zx=function(a,b){k.k.Zx.call(this,a,b);this.upc([!1,0,0])};k.hf=function(a){var d=!1;this.uI()&&this.Gi(!0);d=k.k.hf.call(this,a);if(!d){a=b.ba().zz;for(var e=null,f=0;f<a.length&&null!=(e=a[f]);f++)e instanceof c.h2a&&b.ba().Gu(e,!1)}return d};k.$Xb=function(a,b){b.Oud(this)};k.ZXb=function(b,c){switch(c.eb){case a.g.Bb:case a.g.Ub:this.V5a(null);
break;case a.g.j:this.Iu()}};d.Sa(c.Nla,"PRIM_PPNL","MenuItem",{Aa:{Checked:{a:k.bh,f:function(a){this.Gi(d.Ca(a))}},MenuPopup:{a:k.QC,f:k.X7},RadioItem:{a:k.oka,f:function(a){this.yOa(d.Ca(a))}},GroupIndex:{a:k.uI,f:function(a){this.S7(d.O(a))}},Image:{a:k.U_c,f:k.V5a},ImageHeight:{a:k.Lv,f:function(a){this.gu(d.O(a))}},MarginLeft:{a:k.Sf,f:function(a){this.Bf(d.O(a))}},MarginTop:{a:k.Jf,f:function(a){this.Ef(d.O(a))}},MarginBottom:{a:k.$g,f:function(a){this.jg(d.O(a))}},MarginRight:{a:k.Wg,f:function(a){this.we(d.O(a))}},
Alignment:{a:function(){return d.va(this.Am(),a.Jc.hR)},f:function(b){this.ju(d.wa(b,a.Jc.hR))}}},jc:{ShowMenu:k.lu,HideMenu:k.dKa}});c.Fic=function(a,b,c){f.K.call(this);this.zZ=a;this.gb=b;this.XJd=b.sg();-1==c&&(c=this.zZ.FY.length);this.zZ.FY.splice(c,0,this);this.gb.Ia(this,this.Fv);this.gb.Oa(a.U9)};var f=c.u(c.Fic,c.qd);f.R=function(){var a=this.zZ.Is.length+1;this.gb.Ha(this,this.Fv);this.zZ.FY.splice(this.zZ.FY.indexOf(this),1);this.gb.Ib(this.zZ);this.gb.Vd(a);this.gb.sb(this.XJd);f.k.R.call(this)};
f.ma=function(){return this.gb};b.Gic=function(a,b){-1==a.FY.indexOf(b)&&new c.Fic(a,b,0)};f.lp=function(b,c){switch(c.eb){case a.g.Bb:this.ns()}};c.Olc=function(a){u.K.call(this,a);this.GSa=!1;this.wC=null;this.CA="";this.PEa=null;this.vha=0};var u=c.u(c.Olc,c.HL);u.k6c=function(){var b=!1,c=d.va(this.L.SA,a.Yg.v0b);if("md-effect-17"==c||"md-effect-18"==c||"md-effect-19"==c)b=!0;return b};u.Hd=function(a){var c=this;this.G=document.createElement("div");this.G.setAttribute("id",a+this.hc);this.G.setAttribute("LANSAHandle",
this.hc);this.wC=document.createElement("div");this.wC.setAttribute("LANSAHandle",this.hc);c.wC.addEventListener("click",function(a){a=b.au(b.Lba(a.target||a.srcElement));c.L&&a.vqb()&&c.L.zKa()&&b.ba().Gu(c.L,!1)},!1);return this.G};u.Zea=function(){this.IGa()};u.ZJb=function(b){this.CA=d.va(this.L.SA,a.Yg.v0b);null!=this.PEa&&(b=this.PEa);9999<b&&(""==this.CA?u.k.ZJb.call(this,b):this.wC.style.zIndex=b)};u.bn=function(a,c,d,e){a=b.Vi(a,c,d,e);this.L.M0()&&a.VA(this.L.W().tUb(a));u.k.bn.call(this,
a.aa(),a.$(),a.ja(),a.la())};u.AAa=function(){var d=this;this.L.evc(this.L.mva().DI());if(""!=this.CA||this.L.zf()){if(1==this.vha&&this.I4a(),0==this.vha){this.vha=2;b.ba().dn.Ta().G.classList.add("container");if(this.L.zf())if(this.wC.style.left="0px",this.wC.style.right="0px",this.wC.style.height="100vh",this.wC.style.display="flex",this.wC.style.alignItems="center",this.wC.style.justifyContent="center",this.wC.style.zIndex=this.PEa,null!=this.L.JU&&this.L.UM==a.qh.wma){var e=[];b.iF(this.L.JU.$a(),
e);this.G.style.position="absolute";this.G.style.left=e[0]+"px";this.G.style.top=Number(e[1])+Number(e[3])+"px"}else this.L.UM==a.qh.Xx?(this.G.style.position="absolute",this.G.style.left=this.L.ve()+"px",this.G.style.top=this.L.Te()+"px"):(this.G.style.position="",this.G.style.left="",this.G.style.top="");this.wC.setAttribute("class","md-modal "+this.CA);e=b.pe[this.L.Hb().Ta().$a()];e.G.style.opacity="";e.G.setAttribute("class","md-content vl-control vl-popup");this.wC.appendChild(this.G);document.body.insertBefore(this.wC,
b.ba().dn.Ta().G);this.L.zf()&&"absolute"==this.G.style.position&&(e=[],b.iF(this.L.$a(),e),0!=e[2]&&0!=e[3]&&(e=new c.qa(e[0],e[1],e[2],e[3]),b.V1a(e),this.G.style.left=e.aa()+"px",this.G.style.top=e.$()+"px"));this.k6c()&&setTimeout(function(){document.documentElement.classList.add("md-perspective")},25);setTimeout(function(){d.wC.classList.add("md-show");setTimeout(function(){d.L&&d.L.Dpc()},300)},100)}}else 2==this.vha&&this.I4a(),0==this.vha&&(this.vha=1,document.body.appendChild(this.G));this.GSa=
!0};u.IGa=function(){this.GSa&&(this.GSa=!1,this.wC.classList.contains("md-show")?this.Dqc():this.I4a(),this.L.X6c())};u.I4a=function(){document.documentElement.classList.contains("md-perspective")&&document.documentElement.classList.remove("md-perspective");switch(this.vha){case 1:this.L.zf()?this.L.ep.removeChild(this.G):document.body.removeChild(this.G);break;case 2:document.body.removeChild(this.wC),this.wC.removeChild(this.G),b.ba().dn.Ta().G.classList.remove("container")}this.vha=0};u.Dqc=function(){var a=
this;this.wC.classList.remove("md-show");setTimeout(function(){a.I4a()},500)};u.tce=function(){this.Dqc()}},{rp:["PRIM_PHBN","PRIM_IMAG","PRIM_TBLO"]});
