window.LANSA.addSrc("gpbx",function(d,c,a,b){a.ZTc={lme:0,kme:9,xJd:6,mme:5,nme:10};a.b5c={sWc:0};c.khc=function(){p.K.call(this);this.ONb=a.ZTc.xJd;this.IM=a.b5c.sWc;this.QQ=new c.qa;new c.qa;this.Fd=this.Fd|a.uc.dla|a.uc.TKa|a.uc.Wtb|a.uc.SI|a.uc.k1|a.uc.RI;this.Tc=this.Tc|a.Xd.uS|a.Xd.j1;this.Pe(!1)};var p=c.u(c.khc,c.AL);p.Be=function(){return c.nlc};p.yge=function(b){this.ONb!=b&&(this.ONb=b,this.m(a.g.j),this.$y())};p.jYd=function(){return this.ONb};p.ct=function(a){p.k.ct.call(this,a);this.fhd()};
p.NJb=function(){if(this.Xb()){var a=this.ye(),a=Math.abs(a.Na()),d=this.xf();this.Zd();this.Zd();d.Za(d.aa()+a);new c.qa;""==this.ab()?(d.Va(d.aa()),d.Ja(a)):(this.ab(),d.Va(d.aa()+this.AN()),d.Ja(this.Eja()),d.Va(d.Ka()+a));b.$k(this.QQ,d)||(this.QQ=d,this.xb());this.ct(!0)}};p.lf=function(a){a.Xa(a.$()+this.QQ.la());a.Za(a.aa()+4);a.Va(a.Ka()-4);a.Ja(a.Fa()-4);p.k.lf.call(this,a)};p.kkd=function(a,b,c){a.Xa(a.$()+this.QQ.la());a.Za(a.aa()+4);a.Va(a.Ka()-4);a.Ja(a.Fa()-4);p.k.kkd.call(this,a,b,
c)};p.Vk=function(){p.k.Vk.call(this);this.Dd(a.ea.CE)};p.Ed=function(){var b=this.oS()||this.qn()&&(this.E6()||this.gX());this.dN(a.uc.vS,b);p.k.Ed.call(this)};p.hJ=function(a){var b=!1,b=a.zc().u4a(this,this.ha.sh,this.E6(),this.gX(),a);!1==b&&p.k.hJ.call(this,a)};p.R1=function(a){var b=!1;null!=a.zc()&&a.ma().qn()&&(b=a.zc().v4a(this,this.ha.sh,a,this.E6(),this.gX()));!1==b&&p.k.R1.call(this,a)};p.Oe=function(b){""==b[1]&&(b[1]=a.dbc);p.k.Oe.call(this,b)};p.fhd=function(){var a=this.xf(),a=this.DC(a,
null),c=this.xf();c.Xa(c.$()+this.QQ.la()/2+1);c.Za(c.aa()+2);c.Va(c.Ka()-2);c.Ja(c.Fa()-2);var d=this.Ta().$a(),h=this.ab();b.pe[d].hi(h,c,this.QQ);b.ga(a)};p.Hv=p[a.ea.wL]=function(a){this.NJb();p.k.Hv.call(this,a)};p.Gv=p[a.ea.TI]=function(){p.k.Gv.call(this);this.NJb()};p.AR=p[a.ea.CE]=function(){this.NJb();this.$y()};p.FRc=p[a.ea.Aub]=function(){this.ci()};d.Md(c.khc,"PRIM_GPBX",{Aa:{Caption:{a:p.ab,f:function(a){this.tb(d.ka(a))}},ThemeStyle:{a:function(){return d.va(this.hS(),a.jy.v)},f:function(b){this.MOa(d.wa(b,
a.jy.v))}}}});c.nlc=function(a){t.K.call(this,a);this.fb=this.x$a=this.YQa=this.Le=this.kd=null};var t=c.u(c.nlc,c.HL);t.Hd=function(a,b){var c=null;t.k.Hd.call(this,a,b);this.x$a=4;this.kd=document.createElement("div");this.Le=document.createElement("div");this.YQa=document.createElement("div");this.fb=document.createElement("span");this.G.appendChild(this.kd);this.G.appendChild(this.Le);this.G.appendChild(this.YQa);this.G.appendChild(this.fb);this.Jrb(this.kd,this.x$a);this.Jrb(this.Le,0);this.Jrb(this.YQa,
0);c=this.kd.style;c.borderTopWidth="0px";c=this.Le.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.YQa.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.fb.style;c.position="absolute";c.whiteSpace="nowrap";c.cursor="inherit";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";return this.G};t.Jrb=function(a,b){var c=a.style;c.position="absolute";
c.overflowX="hidden";c.overflowY="hidden";c.whiteSpace="nowrap";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.outline="none";c.background="rgba(0,0,0,0)";c.borderTopWidth="1px";c.borderBottomWidth="1px";c.borderLeftWidth="1px";c.borderRightWidth="1px";c.borderTopLeftRadius=b+"px";c.webkitBorderTopLeftRadius=b+"px";c.borderTopRightRadius=b+"px";c.webkitBorderTopRightRadius=b+"px";c.borderBottomLeftRadius=b+"px";c.webkitBorderBottomLeftRadius=
b+"px";c.borderBottomRightRadius=b+"px";c.webkitBorderBottomRightRadius=b+"px"};t.hi=function(a,b,c){var d=this.kd.style;d.left=b.aa()+"px";d.top=b.$()+"px";d.width=b.ja()+"px";d.height=b.la()+"px";d.borderColor=this.Sn();d=this.Le.style;d.left=b.aa()+this.x$a-1+"px";d.top=b.$()+"px";d.width=c.aa()-b.aa()+"px";d.height="1px";d.borderColor=this.Sn();d=this.YQa.style;d.left=c.Ka()+2+"px";d.top=b.$()+"px";d.width=b.Ka()-this.x$a-c.Ka()+"px";d.height="1px";d.borderColor=this.Sn();d=this.fb.style;d.left=
c.aa()+7+"px";d.top=c.$()+2+"px";d.height=c.la()+"px";d.width=c.ja()+"px";this.fb.textContent=a}});
