window.LANSA.addSrc("caro",function(d,c,a,b,p){d.Ob("PRIM_UDC");d.Ob("PRIM_IMAG");a.Yea={tnc:1,Yfd:0,snc:1};a.Yea.v={DEFAULT:a.Yea.tnc,NONE:a.Yea.Yfd,BUTTONS:a.Yea.snc};a.xD={TF:0,bNc:0,FOd:1,DOd:2,AOd:3,qR:4};a.xD.v={PAGE:a.xD.qR};a.lQa={Rnc:0,Jgd:0,Kgd:1};a.lQa.v={DEFAULT:a.lQa.Rnc,HORIZONTAL:a.lQa.Jgd,VERTICAL:a.lQa.Kgd};a.mQa={uwc:0,YEd:0,ZEd:1};a.mQa.v={DEFAULT:a.mQa.uwc,ANTICLOCKWISE:a.mQa.YEd,CLOCKWISE:a.mQa.ZEd};c.jcc=function(a){t.K.call(this);this.MJ=a;this.lH=new c.qa;this.lQ=1};var t=
c.u(c.jcc,c.Pw);t.R=function(){t.k.R.call(this)};t.lf=function(b,c){t.k.lf.call(this,b,c);this.MJ.Xz()==a.Pp.Lz&&this.MJ.Mg().jh()};t.lCa=function(b,c){t.k.lCa.call(this,b,c);if(this.MJ.Xz()==a.Pp.Lz){var d=[];d[0]=this.lQ;d[1]=this.lH;this.MJ.Ima(b,c,d);this.lQ=d[0];this.lH=d[1]}};t.gE=function(b,c,d){c=[];this.MJ.Xz()==a.Pp.Lz&&this.MJ.Mg().o0a()?(this.lH=this.MJ.AIa(),this.lQ=1,c=this.MJ.gE(c)):c=t.k.gE.call(this,b,c,d);return c};c.Hcc=function(a){m.K.call(this);this.MJ=a;this.mfb=!1;this.GFa=
0};var m=c.u(c.Hcc,c.vvb);m.M6d=function(){return this.mfb};m.lNa=function(a,b,c){m.k.lNa.call(this,a,b,c);this.GFa=this.ve()};m.Pma=function(a){var b=this.MJ.Ua()/this.MJ.Nga;a.Dm(this.GFa!=this.ve());m.k.Pma.call(this,a);0<b&&this.GFa!=this.ve()&&(this.GFa>this.ve()?(a=this.GFa-b*this.MJ.Mga,a<this.ve()||(a=this.ve()-(b+this.ve()%b))):(a=this.GFa+b*this.MJ.Mga,a>this.ve()||(a=this.ve()-(b+this.ve()%b),a+=b)),this.Rb(a,0,500));this.MJ.xb()};m.mza=function(a,c,d,e,l,h,p,q,s){if(0!=a){var t=b.Mf(this.ve()+
a,-(this.Ua()-this.MJ.Ua()),0);this.mfb=!0;this.Za(t);this.mfb=!1;s[0]=!0}m.k.mza.call(this,a,c,d,e,l,h,p,q,s)};c.icc=function(){q.K.call(this);this.Nb=b.Nf(10,10,400,400);this.Di=new c.lcc(this);this.pTa=a.Yea.tnc;this.gRa=a.xD.TF;this.QD=a.lQa.Rnc;this.yga=this.JOb=0;this.HOb=75;this.FNb=50;this.ENb=20;this.$i=500;this.ORb=a.mQa.uwc;this.Nga=3;this.Mga=1;var d=this.IU=this.HU=this.GZ=this.HZ=this.tx=this.vra=this.wra=this.S$=this.Yh=null,d=d=null;this.Yh=new c.Pw;d=b.lo(this.Yh);d.Mk(a.Yd.JB);d.yc(1);
d=b.ko(this.Yh);d.Mk(a.Yd.JB);d.qc(1);this.S$=new c.jcc(this);this.wra=b.lo(this.S$);this.wra.Mk(a.Yd.JB);this.wra.yc(1);this.vra=b.ko(this.S$);this.vra.Mk(a.Yd.JB);this.vra.qc(1);this.wra.kt(this.S$);this.vra.kt(this.S$);this.tx=new c.Hcc(this);this.tx.sb(new c.qa);this.tx.Ec=this;this.tx.$p(this.S$);this.tx.fM(!1);this.tx.j2(!1);this.tx.Pe(!1);this.tx.xq(!1);this.tx.za(this,a.Q.LX,this.Mjb);this.tx.za(this,a.Q.Vfb,this.IPc);this.tx.Nuc(a.xA.DIb);this.HZ=new c.bu;this.HZ.sb(new c.qa(0,0,20,90));
this.HZ.Nj(a.oc.QKc);this.HZ.za(this,a.Q.tc,this.VQc);this.GZ=new c.bu;this.GZ.sb(new c.qa(0,0,20,90));this.GZ.Nj(a.oc.RKc);this.GZ.za(this,a.Q.tc,this.UQc);this.HU=new c.bu;this.HU.sb(new c.qa(0,0,20,20));this.HU.Nj(a.oc.OKc);this.HU.Rg(0);this.HU.za(this,a.Q.tc,this.SQc);this.IU=new c.bu;this.IU.sb(new c.qa(0,0,20,20));this.IU.Nj(a.oc.PKc);this.IU.Rg(0);this.IU.za(this,a.Q.tc,this.TQc);b.ba().fVa(this.GZ);b.ba().gVa(this.GZ);b.ba().fVa(this.HZ);b.ba().gVa(this.HZ);b.ba().fVa(this.HU);b.ba().gVa(this.HU);
b.ba().fVa(this.IU);b.ba().gVa(this.IU);d=b.Qc(this.Yh,this.HZ,this.Yh.Fc(0),this.Yh.Nc(0),1,1);d.Wb(a.na.Mq);d.fc(a.ta.tf);d=b.Qc(this.Yh,this.GZ,this.Yh.Fc(0),this.Yh.Nc(0),1,1);d.Wb(a.na.Np);d.fc(a.ta.tf);d=b.Qc(this.Yh,this.HU,this.Yh.Fc(0),this.Yh.Nc(0),1,1);d.Wb(a.na.QH);d.fc(a.ta.tf);d=b.Qc(this.Yh,this.IU,this.Yh.Fc(0),this.Yh.Nc(0),1,1);d.Wb(a.na.RH);d.fc(a.ta.tf);this.bAa(a.Pp.oia);d=new c.sLa;d=new c.mcc(this,d);this.KXa(d)};var q=c.u(c.icc,c.uxa);q.nb=function(){b.ga(this.tx);b.ga(this.HZ);
b.ga(this.GZ);b.ga(this.HU);b.ga(this.IU);q.k.nb.call(this)};q.R=function(){b.ga(this.S$);this.S$=null;b.ga(this.wra);this.wra=null;b.ga(this.vra);this.vra=null;q.k.R.call(this)};q.Us=function(){return this.S$};q.Xz=function(){var b=a.Pp.oia;switch(this.GW()){case a.xD.qR:b=a.Pp.Lz;break;default:b=this.KYa()}return b};q.Mg=function(){var b=null;switch(this.GW()){case a.xD.qR:b=this.tx;break;default:b=q.k.Mg.call(this)}return b};q.Xua=function(){var b=null;switch(this.GW()){case a.xD.qR:b=-this.tx.ve();
break;default:b=q.k.Xua.call(this)}return b};q.J5=function(){var b=null;switch(this.GW()){case a.xD.qR:b=-this.tx.Te();break;default:b=q.k.J5.call(this)}return b};q.L1c=function(){return this.Nga};q.wud=function(b){b=Math.max(b,1);this.Nga!=b&&(this.Nga=b,this.IB(),this.pa(a.g.j))};q.K1c=function(){return this.Mga};q.vud=function(b){b=Math.max(b,1);this.Mga!=b&&(this.Mga=b,this.IB(),this.pa(a.g.j))};q.f0d=function(){return this.pTa};q.GW=function(){var b=this.gRa;b==a.xD.bNc&&this.Xb()&&d.wa("LINEAR",
a.xD.v);return b};q.RUd=function(){return this.gRa};q.Jo=function(){return this.QD};q.MZd=function(){return this.JOb};q.IZd=function(){return this.yga};q.KZd=function(){return this.HOb};q.hXd=function(){return this.FNb};q.gXd=function(){return this.ENb};q.zba=function(){return this.$i};q.D3d=function(){return this.ORb};q.kud=function(b){this.pTa!=b&&(this.pTa=b,this.pa(a.g.j))};q.crd=function(b){this.gRa!=b&&(this.gRa=b,this.ci(),this.pa(a.g.j))};q.oT=function(b){this.QD!=b&&(this.QD=b,this.pa(a.g.j))};
q.Sge=function(b){this.JOb!=b&&(this.JOb=b,this.pa(a.g.j))};q.Qge=function(b){this.yga!=b&&(this.yga=b,this.pa(a.g.j))};q.Rge=function(c){c=b.Mf(c,1,89);this.HOb!=c&&(this.HOb=c,this.pa(a.g.j))};q.uge=function(b){this.FNb!=b&&(this.FNb=b,this.pa(a.g.j))};q.tge=function(b){this.ENb!=b&&(this.ENb=b,this.pa(a.g.j))};q.mD=function(b){this.$i!=b&&(this.$i=b,this.pa(a.g.j))};q.die=function(b){this.ORb!=b&&(this.ORb=b,this.pa(a.g.j))};q.S2b=function(){return this.Dw()};q.pka=function(){return b.qb()};q.i0=
function(){return"PRIM_CARO<"+this.fG()+">"};q.g5=function(b){0==(this.Vq()&a.xp.Sw)&&this.Lk(!0);if(this.Rv(a.Q.rO)&&(this.od(b),!this.Pd())){var c=d.cc();c.kc("ITEM",b);this.Ga(a.Q.rO,c);c.Kc()}};q.h5=function(b){0==(this.Vq()&a.xp.Sw)&&this.Lk(!0);if(this.Rv(a.Q.tO)&&(this.od(b),!this.Pd())){var c=d.cc();c.kc("ITEM",b);this.Ga(a.Q.tO,c);c.Kc()}};q.kba=function(b){0==(this.Vq()&a.xp.Sw)&&this.Lk(!0);if(this.Rv(a.Q.sO)&&(this.od(b),!this.Pd())){var c=d.cc();c.kc("ITEM",b);this.Ga(a.Q.sO,c);c.Kc()}};
q.pE=function(b,c){this.od(b);b.pE(c);if(!c&&!this.Pd()){var e=d.cc();e.kc("ITEM",b);e.mg("CONTINUE",!0);this.Ga(a.Q.qO,e);e.ah("CONTINUE");e.Kc()}};q.Uia=function(b,c){this.od(b);if(!c&&!this.Pd()){var e=d.cc();e.kc("ITEM",b);e.mg("CONTINUE",!0);this.Ga(a.Q.Fca,e);c=!e.ah("CONTINUE");e.Kc()}return c};q.hI=function(b){var c=this.Rv(a.Q.EG);c&&this.od(b);b.hI();c&&!this.Pd()&&(c=d.cc(),c.kc("ITEM",b),this.Ga(a.Q.EG,c),c.Kc())};q.fI=function(b){0==(this.Vq()&a.xp.Sw)&&this.Lk(!0);this.od(b);b.fI();
if(!this.Pd()){var c=d.cc();c.kc("ITEM",b);this.Ga(a.Q.OI,c);c.Kc()}};q.gI=function(b){0==(this.Vq()&a.xp.Sw)&&this.Lk(!0);this.od(b);b.gI();if(!this.Pd()){var c=d.cc();c.kc("ITEM",b);this.Ga(a.Q.sS,c);c.Kc()}};q.WNa=function(b){null!=b&&null!=b.wc&&this.Mg().Gwa(b.wc,a.LI.vca)};q.v7=function(b){if(this.Us())switch(this.GW()){case a.xD.qR:switch(this.pTa){case a.Yea.snc:this.HZ.Oa(this),this.HZ.Vd(1),this.GZ.Oa(this),this.GZ.Vd(2),this.HU.Oa(this),this.HU.Vd(3),this.IU.Oa(this),this.IU.Vd(4)}this.tx.Oa(this);
this.tx.Vd(99);this.tx.dtd(this.xf().ja()/this.Mga);this.Xb()&&this.jh();this.$p(this.Yh);b.Xy().wk(b.wc);b.Xy().Oa(this.Us());b.Xy().Ef(b.Oda());b.Xy().Bf(b.Y4a());b.Xy().we(b.xCb());b.Xy().jg(0);b.Xy().fc(a.ta.Nk);b.Xy().pi(a.La.Wk);b.Xy().Wb(a.na.bE);b.Xy().ro(this.wra);b.Xy().Yn(this.vra);break;default:this.tx.Oa(null),this.HZ.Oa(null),this.GZ.Oa(null),this.HU.Oa(null),this.IU.Oa(null),this.$p(null)}q.k.v7.call(this,b)};q.Jfd=function(a){this.Zmc(a)};q.Kfd=function(a){this.$mc(a)};q.Ffd=function(a){this.szb(a)};
q.Ifd=function(a){this.tzb(a)};q.Hfd=function(a,b){this.Gfd(a-1,b)};q.Zmc=function(c){switch(this.GW()){case a.xD.qR:if(this.Mg().ve()==-(this.Mg().Ua()-this.Ua()))this.szb(c);else{var d=this.Ua()/this.Nga,d=this.Mg().ve()-d*this.Mga,d=b.Mf(d,-(this.Mg().Ua()-this.Ua()),0);c?this.Mg().Rb(d,0,1E3):this.Mg().Za(d)}}};q.$mc=function(c){switch(this.GW()){case a.xD.qR:if(0==this.Mg().ve())this.tzb(c);else{var d=this.Ua()/this.Nga,d=this.Mg().ve()+d*this.Mga,d=b.Mf(d,-(this.Mg().Ua()-this.Ua()),0);c?this.Mg().Rb(d,
0,1E3):this.Mg().Za(d)}}};q.szb=function(b){switch(this.GW()){case a.xD.qR:b?this.Mg().Rb(0,0,1E3):this.Mg().Za(0)}};q.tzb=function(b){switch(this.GW()){case a.xD.qR:var c=-(this.Mg().Ua()-this.Ua());b?this.Mg().Rb(c,0,1E3):this.Mg().Za(c)}};q.Gfd=function(c,d){switch(this.GW()){case a.xD.qR:c-=c%this.Nga;var e=this.Hca(c);e&&e.wc&&(e=-e.wc.ve(),e=b.Mf(e,-(this.Mg().Ua()-this.Ua()),0),d?this.Mg().Rb(e,0,1E3):this.Mg().Za(e))}};q.dza=function(a){this.g5(a)};q.fza=function(a){this.h5(a)};q.eza=function(a){this.kba(a)};
q.$ya=function(a,b){this.pE(a,b)};q.aza=function(a,b){return this.Uia(a,b)};q.Jma=function(a){this.hI(a)};q.Hma=function(b){this.fI(b);this.pa(a.g.j)};q.cza=function(a){this.gI(a)};q.DG=function(b){var c=null;switch(this.GW()){case a.xD.qR:c=q.k.DG.call(this,b)}return c};q.lf=function(a){q.k.lf.call(this,a);if(!this.tx.mfb&&!this.tx.Tv()){var d=b.ZC(this,null),e=d.Tb,h=null,l=a.ja()/this.Nga,m=this.tx.ve(),p=this.DG(new c.sd(Math.abs(m)+10,10));if(0<e.length){for(var s=0;s<e.length&&null!=(h=e[s]);s++)h.wc&&
h.wc.qc(l);h=-(l*e.length-a.Ua());0>m&&p&&(m=-(l*p.Fk()));this.tx.sb(new c.qa(b.Mf(m,h,0),0,l*e.length,a.la()))}b.ga(d)}};q.Vk=function(){q.k.Vk.call(this);this.td(a.Cb.e9a)};q.Zh=function(a){var b=null;return b=this.Di.Ag(a,!0,-1,!1)};q.Ag=function(a){a===p?this.Di.Ag(this.fG(),!0,-1,!0):this.Di.Ag(this.fG(),!1,a,!0)};q.Fh=function(a){return this.Di.Fh(!1,a)?"OK":"NR"};q.mp=function(){return this.Di.MR()};q.Sj=function(){this.Di.Sj()};q.Om=function(a){this.Di.Om(a==p?!0:!1,a)};q.zl=function(){this.Di.zl()};
q.rn=function(a,b,c){return this.Di.rn(a,b,c)};q.Xq=function(a){this.Sj();for(var b=0;b<a;b++)this.Ag()};q.VQc=function(){this.$mc(!0)};q.UQc=function(){this.Zmc(!0)};q.SQc=function(){this.szb(!0)};q.TQc=function(){this.tzb(!0)};q.IPc=function(){};q.Mjb=function(a,b){this.hmb(b.jB("ORIENTATION"))};q.GC=q[a.ea.xS]=function(a){var b=this.Gj(a.ad);b&&!b.ng()&&b.HC(!0,!1,!0);q.k.GC.call(this,a)};d.Md(c.icc,"PRIM_CARO",{$S:a.Ny.K9a,dE:"PRIM_CPST",Aa:{CurrentItem:{a:q.nd},FocusItem:{a:q.gd},PageSize:{a:q.L1c,
f:function(a){this.wud(d.O(a))}},PageScroll:{a:q.K1c,f:function(a){this.vud(d.O(a))}},CarouselStyle:{a:function(){return d.va(this.gRa,a.xD.v)},f:function(b){this.crd(d.wa(b,a.xD.v))}},NavigationStyle:{a:function(){return d.va(this.pTa,a.Yea.v)},f:function(b){this.kud(d.wa(b,a.Yea.v))}}},jc:{Add:q.Zh,Sort:q.Cea,FindItem:q.Lg,DeleteAll:q.XF,FindReference:q.ZV,NextItem:q.Jfd,PrevItem:q.Kfd,FirstItem:q.Ffd,LastItem:q.Ifd,MoveToItem:q.Hfd},hA:{Ag:q.Ag,Fh:function(a){return this.Fh(d.O(a)-1)},Xq:q.Xq,
Sj:q.Sj,mp:q.mp,Om:function(a){this.Om(a?d.O(a)-1:p)},zl:q.zl,rn:q.rn,Bs:q.Bs}});c.mcc=function(a,b){s.K.call(this,a,b)};var s=c.u(c.mcc,c.uLa);s.R=function(){s.k.R.call(this)};s.QUd=function(){return this.Qs.Ea()};s.H_=function(a,b){var c=null,e=null,l=null,h=null;null!=a&&(e=h=d.Bc(a),null!=e&&(e.Ab(!1),l=e,null!=l&&(c=d.Bc("PRIM_CARO","CarouselItem"),c.Ba())));b[0]=h;b[1]=c;b[2]=e;b[3]=l};s.NK=function(a,b,c,d){this.H_(a,b);null!=b[1]&&this.Zy(b[1],b[2],c,d)};s.oza=function(a){return a};c.lcc=
function(a){h.K.call(this,a)};var h=c.u(c.lcc,c.tLa);h.Ag=function(a,b,c,e){var l=this.Ea(),h=null,h=[];if(b)l.S2b().NK(a,h,e);else if(0<=c&&c<=this.MR())l.S2b().NK(a,h,e,c);else throw d.Tu(c-1,this.MR());return h=h[1]};c.kcc=function(){e.K.call(this)};var e=c.u(c.kcc,c.wxa);e.R=function(){e.k.R.call(this)};e.Zh=function(a){var b=null,c=this.Ea();c&&(b=c.Zh(a),b.Oa(this));return b};e.pE=function(c){if(!this.Pd()){var e=d.cc();e.kc("ITEM",this);e.mg("CONTINUE",!0);this.Ga(a.Q.qO,e);c=!e.ah("CONTINUE");
e.Kc()}e=this.Rt();null!=e&&b.sn(e,this,"ONITEMCLICK");return c};e.hI=function(){if(!this.Pd()){var c=d.cc();c.kc("ITEM",this);this.Ga(a.Q.EG,c);c.Kc()}c=this.Rt();null!=c&&b.sn(c,this,"ONITEMREALIZING")};e.fI=function(){if(!this.Pd()){var c=d.cc();c.kc("ITEM",this);this.Ga(a.Q.OI,c);c.Kc()}c=this.Rt();null!=c&&b.sn(c,this,"ONITEMGOTFOCUS")};e.gI=function(){if(!this.Pd()){var c=d.cc();c.kc("ITEM",this);this.Ga(a.Q.sS,c);c.Kc()}c=this.Rt();null!=c&&b.sn(c,this,"ONITEMLOSTFOCUS")};d.Sa(c.kcc,"PRIM_CARO",
"CarouselItem",{Aa:{Design:{a:e.LYa},Carousel:{a:e.Ea},Focus:{a:e.ng,f:e.Tf},Position:{a:e.jka},Entry:{a:e.Fh},Selected:{a:e.Gk,f:function(a){this.hu(d.Ca(a))}},RelatedReference:{a:e.EW,f:e.wJ},Visible:{a:e.zb,f:function(a){this.Ab(d.Ca(a))}}},jc:{Delete:e.Rs}})},{rp:["PRIM_UDC","PRIM_IMAG"]});
