window.LANSA.addSrc("menu",function(d,c,a,b,p){d.Ob("PRIM_TBLO");d.Ob("PRIM_PPNL");d.Ob("PRIM_IMAG");d.Ob("PRIM_SPBN");a.S2a={k7:16,Azb:16};a.E1={xMa:0,Hzb:1,Izb:2,Bzb:4};a.LO={Lmc:0,Zyb:1,Yyb:2};a.LO.v={NONE:a.LO.Lmc,BREAK:a.LO.Zyb,BARBREAK:a.LO.Yyb};a.MO={j7:25,ozb:1,mzb:2,l$d:4,pzb:8,nzb:16};a.LO={yfd:0};a.Q9d=3;a.P9d=2;a.R9d=255;a.afd=768;a.wmc=256;a.vmc=512;a.M2a=65536;a.N2a=131072;a.Myb=262144;a.Oyb=524288;a.Nyb=1048576;a.Iie=2;a.Hie=2;c.ZLa=function(){t.K.call(this);this.eK=null;this.yz=a.S2a.k7;
this.yU=a.E1.xMa;this.Hp=null;this.Tb=[];this.VM=new c.Ux;this.Cra=new c.yb;this.Fi=new c.Pw;this.FKd=new c.Ola;this.EKd=new c.ida;this.FKd.kt(this.Fi);this.EKd.kt(this.Fi);this.VM.$p(this.Fi);this.Cra.Zj(b.U(255,255,255));this.Cra.Yi(b.mb().mq(a.o.jl));this.Cra.wq(1);this.Cra.ir(1);this.Cra.Oo(1);this.Cra.Po(1);this.VM.za(this,a.Q.Yx,this.gRc);this.VM.Jb(this.Cra)};var t=c.u(c.ZLa,c.cz);t.nb=function(){this.Tb=null;t.k.nb.call(this)};t.R=function(){null!=this.eK&&this.G2();for(var a=null;null!=(a=
this.Tb[0]);)a.Oa(null);b.wed(this);t.k.R.call(this)};t.w_d=function(){return this.eK};t.A_d=function(){return this.Tb};t.z_d=function(){return this.Tb.length};t.$ja=function(){return this};t.j$c=function(){return 0!=(this.yU&a.E1.Izb)};t.$8c=function(){return 0!=(this.yU&a.E1.Bzb)};t.C_d=function(){return 0!=(this.yU&a.E1.Hzb)};t.Vtd=function(){var b=this.yU&~a.E1.Hzb|a.E1.Hzb;this.yU!=b&&(this.yU=b,this.pa(a.g.j))};t.vob=function(){return 0!=(this.yz&a.S2a.Azb)};t.Uge=function(b){b=this.yz&~a.S2a.Azb|
(b?a.S2a.Azb:0);this.yz!=b&&(this.yz=b,this.pa(a.g.j))};t.lna=function(a){this.Hp!=a&&(this.Hp=a,this.K4a())};t.sYc=function(){return this.Hp};t.Uy=function(){return this.Tb};t.Vka=function(){return null!=this.eK||null!=this.Dg};t.$4d=function(){for(var a,b=this.Tb,c=0;c<b.length&&null!=(a=b[c]);c++)if(!0==a.zb())return!0;return!1};t.Up=function(){null==this.Dg&&this.Zw(b.qb().iE(this));return this.Dg};t.Xia=function(b){var c=d.cc();c.kc("CONTEXT",b);this.Ga(a.Q.Yx,c);c.Kc()};t.Zy=function(b){this.Vka()&&
this.G2();b.gc=this;this.z9a(b);b.Ia(this,this.lHa);this.pa(a.g.j)};t.r8c=function(b){this.Vka()&&this.G2();b.gc=this;this.z9a(b);b.Ia(this,this.lHa);this.pa(a.g.j)};t.U1=function(b){this.Vka()&&this.G2();b.gc=null;b.Ha(this,this.lHa);this.z9a(b);this.pa(a.g.j)};t.dKa=function(){b.ba();this.G2()};t.pqc=function(a){if(null==this.eK){if(null!=this.Dg)this.eK=this.Dg;else{var c=b.ba().yEa;this.eK=this.Vhb();null!=this.eK&&(c[this.eK]=this)}this.H3a(null,a)}};t.G2=function(){if(null!=this.eK){for(var a,
c=this.Tb,d=0;d<c.length&&null!=(a=c[d]);d++){var h=a.mw;a.Zw(null);a.Qkd();h&&h.G2()}null!=this.eK&&(null!=this.Dg?(this.Zw(null),this.eK=null):(a=b.ba().yEa,null!=this.eK&&delete a[this.eK]));this.eK=null;this.Zw(null);b.ba().Gu(this.VM,!1)}};t.vid=function(){};t.JAb=function(){};t.H3a=function(a,b){this.VM.sb(new c.qa(0,0,0,5));for(var d,h=0,m=this.Tb,l=0;l<m.length&&null!=(d=m[l]);l++)h=this.Msa(a,b,d,h)};t.Msa=function(a,b,c,d,h){return c.Msa(a,b,this,d,h)};t.LUb=function(a){for(var b=!1,c,d=
this.Tb,h=0;h<d.length&&null!=(c=d[h]);h++)if(c==a||null!=c.mw&&c.mw.LUb(a)){b=!0;break}return b};t.z5c=function(b){for(var c=!1,d=null,h=this.Tb,m=0;m<h.length&&null!=(d=h[m]);m++)if(d.Xb()&&d.te()){var l=d.mw;if(null!=l&&l.z5c(b)){c=!0;break}if(d.cFa!=a.fa.VNa&&d.cFa==b){d.hf();c=!0;break}}return c};t.oSd=function(){for(var a=this.Tb,b=null,c=null,d=0;d<a.length&&null!=(c=a[d]);d++)if(c.vba()){b=c;break}return b};t.z9a=function(a){var c=this.Tb.indexOf(a);-1!=c&&this.Tb.splice(c,1);c+=1;if(a.gc==
this){0==a.dh()&&(a.yh=this.Tb.length+1);var d=a.dh(),h=0;0<c&&d>c&&d++;for(var m,c=this.Tb,l=0;l<c.length&&null!=(m=c[l])&&!(m.dh()>=d);l++)h++;this.Tb.splice(h,0,a)}b.ued(this)};t.dNa=function(b){b==a.W_&&(this.Vka()&&this.G2(),this.pda(),this.pa(a.g.j))};t.pda=function(){for(var b,c=this.Tb,d=0;d<c.length&&null!=(b=c[d]);d++)b.yh=1,b.pa(a.g.j)};t.g$d=function(a){var c=b.ba();return null!=c.yEa?c.yEa[a]:null};t.K4a=function(){};t.c4a=function(){b.ba().Gu(this.VM,!1)};t.JAb=function(){};t.hz=function(a){this.yU|=
a};t.BB=function(a){this.yU&=~a};t.kA=function(a,b){this.yU=this.yU&~a|(b?a:0)};t.iXb=function(b,c){switch(c.eb){case a.g.Bb:this.lna(null)}};t.lHa=function(){this.j$c()?this.hz(a.E1.Bzb):this.Vka()&&(this.G2(),this.pa(a.g.j))};t.gRc=function(){this.JAb(null,this.VM)};d.Md(c.ZLa,"PRIM_MENU",{Aa:{}});c.pxb=function(){m.K.call(this);this.hC=null};var m=c.u(c.pxb,c.ZLa);m.nb=function(){m.k.nb.call(this)};m.R=function(){this.zna(null);m.k.R.call(this)};m.D4b=function(){return this.hC};m.zna=function(b){this.hC!=
b&&(this.hC&&this.hC.sce(this),b&&b.J5d(this),this.pa(a.g.j))};m.vid=function(){this.Xia(null)};m.H3a=function(a,b){this.VM.sb(new c.qa(0,0,0,5));for(var d,h=0,m=this.Tb,l=0;l<m.length&&null!=(d=m[l]);l++)h=this.Msa(a,b,d,h,!0)};m.Vhb=function(){throw 0;};d.Md(c.pxb,"PRIM_MBAR",{Aa:{}});c.rxb=function(){q.K.call(this);this.KCa=null;this.LLb=0};var q=c.u(c.rxb,c.ZLa);q.nb=function(){q.k.nb.call(this)};q.R=function(){this.K4a();q.k.R.call(this)};q.gge=function(b){b!=this.LLb&&(this.LLb=b,this.K4a(),
this.pa(a.g.j))};q.PTd=function(){return this.LLb};q.uWc=function(){null==this.KCa&&(this.KCa=[]);return this.KCa};q.H3a=function(a,b){this.VM.sb(new c.qa(0,0,0,5));for(var d,h=0,m=this.uWc(),l=0;l<m.length&&null!=(d=m[l]);l++)h=this.Msa(a,b,d,h);m=this.Tb;for(l=0;l<m.length&&null!=(d=m[l]);l++)h=this.Msa(a,b,d,h)};q.Vhb=function(){return b.dka()};q.AAa=function(a,b){a===p&&(a=0);b===p&&(b=0);this.Moc(new c.sd(a,b),null,!0,null)};q.Moc=function(c,d){var f=b.ba(),h=!1,h=f.Pk,m=b.ba().sy;this.Xia(d,
c);b.g2a(a.W_);this.lna(d);h&&this.Wv(h,a.Ra.YAc);null!=m&&m.x6()&&m.IV();this.pqc(this.VM);0<this.VM.Na()&&(h=f.PSb(!0),this.VM.Aea(c.Pb(),c.Vb(),a.qh.Xx,p,null),f.PSb(h))};q.K4a=function(){this.G2();if(this.KCa){for(var a;null!=(a=this.KCa[0]);)b.ga(a);this.KCa=null}};q.qPd=function(a,b){var c=b.jva();c&&c.Cae(b.Ej.OQ)};d.Md(c.rxb,"PRIM_PMNU",{Aa:{},jc:{Show:q.AAa}});c.Zic=function(){s.K.call(this);this.hC=null};var s=c.u(c.Zic,c.ZLa);s.nb=function(){s.k.nb.call(this)};s.R=function(){this.hC&&this.hC.dFb(null);
s.k.R.call(this)};s.D4b=function(){return this.hC};s.zna=function(b){if(this.hC!=b&&!this.LUb(b)){var c=this.hC;this.hC=b;c&&c.uTb(null);this.hC&&this.hC.uTb(this);this.pa(a.g.j,a.Ke.P0a)}};s.vob=function(){var a=s.k.vob.call(this);a&&(a=this.hC.w$c());return a};s.$ja=function(){var a=null;this.hC&&(a=this.hC.$ja());return a};s.c4a=function(){s.k.c4a.call(this);this.hC.W().c4a()};s.Vhb=function(){return b.dka()};s.mGd=function(){if(null!=this.eK)for(var a,b=this.Tb,c=0;c<b.length&&null!=(a=b[c]);c++){var d=
a.mw;d&&d.G2()}};s.JAb=function(b,c){this.hz(a.E1.Izb);this.Xia(null);this.hz(a.E1.Izb);this.Vka()&&this.$8c()&&(this.mGd(),this.H3a(b,c));this.hz(a.E1.Bzb)};d.Md(c.Zic,"PRIM_SMNU",{Aa:{Parent:{a:s.D4b,f:s.zna}}});c.tic=function(){h.K.call(this);this.gc=null;this.uf=a.MO.j7;this.vb=a.LO.yfd;this.fg=a.M2a|a.N2a;this.cFa=a.fa.VNa;this.GCc=this.yh=this.uv=this.IEc=this.OQ=0;this.B$=this.Da=this.mw=this.gc=null;this.fb=this.Ueb="";this.QY=new c.$l;this.NRa=new c.bu;this.g$=new c.yb;this.kQ=new c.HO;this.ega=
b.Qc(null,this.QY,null,null,1,1);this.ORa=b.Qc(null,this.kQ,null,null,1,1);this.ODa=b.Qc(null,this.NRa,null,null,1,1);this.NRa.Jb(this.g$);this.NRa.Oa(this.QY);this.kQ.Oa(this.QY);this.QY.za(this,a.Q.tc,this.JPc);this.gGc()};var h=c.u(c.tic,c.cz);h.nb=function(){this.ONc();h.k.nb.call(this)};h.R=function(){this.dFb(null);this.Oa(null);h.k.R.call(this);this.Bd(null);this.jtd()};h.cXd=function(){var a="";this.X9c()||null!=this.$ja()&&this.$ja()instanceof c.rxb?a=this.ab():this.zXc();return a};h.ab=
function(){return this.fb};h.op=function(){return this.ab().Ae()};h.zXc=function(){this.ab()};h.zVd=function(){return this.UMb};h.d3d=function(){return!0};h.t1d=function(){return!0};h.s0d=function(){return!0};h.GEb=function(){var a=this.$ja();a&&a.Vtd()};h.bh=function(){return 0!=(this.fg&a.Myb)?!0:!1};h.vba=function(){return 0!=(this.fg&a.Nyb)?!0:!1};h.fge=function(b){b!=this.gsb()&&(this.uf=this.uf&~a.MO.mzb|(b?a.MO.mzb:0),this.pa(a.g.j))};h.uI=function(){return this.uv};h.z_c=function(){return this.GCc};
h.g1c=function(){var b=a.LO.Lmc;0!=(this.fg&a.wmc)?b=a.LO.Zyb:0!=(this.fg&a.vmc)&&(b=a.LO.Yyb);return b};h.W=function(){return this.gc};h.$ja=function(){var a=null;this.gc&&(a=this.gc.$ja());return a};h.oka=function(){return 0!=(this.fg&a.Oyb)?!0:!1};h.h2d=function(){return this.cFa};h.i2d=function(){return""};h.J3c=function(){return this.mw};h.tpb=function(){return this.OQ};h.L3d=function(){return this.IEc};h.zb=function(){return 0!=(this.fg&a.N2a)?!0:!1};h.tb=function(a){this.fb!=a&&(this.fb=a,
this.s7())};h.ul=function(a){this.ab().re(a)};h.Gi=function(b){var c=this.uI();if(b&&0!=c&&null!=this.W())for(var d,h=this.W().Tb,m=0;m<h.length&&null!=(d=h[m]);m++)d!=this&&d.uI()==c&&d.Gi(!1);b=b?this.fg|a.Myb:this.fg&~a.Myb;b!=this.fg&&(this.fg=b,this.pa(a.g.j))};h.D5a=function(b){b=b?this.fg|a.Nyb:this.fg&~a.Nyb;b!=this.fg&&(this.fg=b,this.pa(a.g.j))};h.dh=function(){return this.yh};h.Vd=function(b){this.gsb()||(null!=this.gc?(this.yh=b,this.gc.z9a(this)):this.yh!=b&&(this.yh=b,this.pa(a.g.j)))};
h.te=function(){return 0!=(this.fg&a.M2a)?!0:!1};h.Qg=function(b){b=b?this.fg|a.M2a:this.fg&~a.M2a;b!=this.fg&&(this.fg=b,this.pa(a.g.j))};h.S7=function(b){this.uv!=b&&(this.uv=b,this.pa(a.g.j))};h.$sd=function(b){this.GCc=b;this.pa(a.g.j)};h.Utd=function(b){var c=this.fg&~a.afd;switch(b){case a.LO.Zyb:c|=a.wmc;break;case a.LO.Yyb:c|=a.vmc}c!=this.fg&&(this.fg=c,this.pa(a.g.j))};h.Oa=function(b){this.gc!=b&&(this.gc&&this.gc.U1(this),b&&(this.gsb()?b.r8c(this):b.Zy(this)),null!=this.Da&&this.GEb(),
this.pa(a.g.j,a.Ke.P0a))};h.yOa=function(b){b=b?this.fg|a.Oyb:this.fg&~a.Oyb;b!=this.fg&&(this.fg=b,this.pa(a.g.j))};h.fvd=function(b){this.cFa!=b&&(this.cFa=b,this.pa(a.g.j))};h.dFb=function(a){this.mw!=a&&(this.mw&&this.mw.zna(null),a&&a.zna(this))};h.P6a=function(b){this.OQ!=b&&(this.OQ=b,this.pa(a.g.j))};h.eie=function(a){this.IEc=a};h.Zc=function(){return this.Da};h.Bd=function(b){this.Da!=b&&(null!=this.Da&&(this.Da.Ha(this,this.lp),this.Da.ub()),this.Da=b,null!=this.Da&&(this.Da.Ba(),this.Da.Ia(this,
this.lp)),this.GEb(),this.pa(a.g.j))};h.jtd=function(){null!=this.B$&&(null!=this.B$&&(this.B$.Ha(this,this.XXb),this.B$.ub()),this.B$=null,null!=this.B$&&(this.B$.Ba(),this.B$.Ia(this,this.XXb)),this.GEb(),this.pa(a.g.j))};h.wZd=function(){return this.B$};h.g4c=function(){return this.Ueb};h.swd=function(b){this.Ueb!=b&&(this.Ueb=b,this.pa(a.g.j,a.Ke.rad))};h.j_a=function(){return 0!=(this.uf&a.MO.ozb)?!0:!1};h.twd=function(b){b!=this.j_a()&&(this.uf=this.uf&~a.MO.ozb|(b?a.MO.ozb:0),this.pa(a.g.j))};
h.Bpb=function(){return 0!=(this.uf&a.MO.pzb)?!0:!1};h.uwd=function(b){b!=this.Bpb()&&(this.uf=this.uf&~a.MO.pzb|(b?a.MO.pzb:0),this.pa(a.g.j))};h.b2d=function(){return!0};h.zua=function(){return 0!=(this.uf&a.MO.nzb)?!0:!1};h.Ssc=function(b){b!=this.zua()&&(this.uf=this.uf&~a.MO.nzb|(b?a.MO.nzb:0),this.pa(a.g.j))};h.Ab=function(b){b=b?this.fg|a.N2a:this.fg&~a.N2a;b!=this.fg&&(this.fg=b,this.pa(a.g.j))};h.c5b=function(){return this.Nb};h.Up=function(){null==this.Dg&&this.Zw(b.qb().iE(this));return this.Dg};
h.Xb=function(){return null!=this.gc&&this.gc.Vka()?!0:!1};h.G6d=function(){return"-"==this.ab()?!0:!1};h.gsb=function(){return 0!=(this.uf&a.MO.mzb)?!0:!1};h.w$c=function(){var a=this.j_a();if(a&&this.Bpb()){var b=this.W();b&&(a=b.vob())}return a};h.X9c=function(){return null!=this.W()&&this.W()instanceof c.pxb};h.hf=function(b){b===p&&(b=null);var c=d.cc();c.kc("CONTEXT",b);this.Ga(a.Q.tc,c);c.Kc()};h.pke=function(){if(this.mw)for(var a,b=this.mw.Tb,c=0;c<b.length&&null!=(a=b[c]);c++)a.Gi(!1)};
h.uTb=function(b){this.mw!=b&&(this.mw&&(this.mw.hC==this?this.mw.zna(null):(this.pa(a.g.Xfd),this.mw.Ha(this,this.$Yb),this.mw=null)),b&&(b.hC!=this?b.zna(this):(this.mw=b,this.mw.Ia(this,this.$Yb))),this.pa(a.g.j))};h.i$d=function(a){return b.ba().fTa[a]};h.gGc=function(){this.UMb=b.ba().LSb();b.ba().fTa[this.UMb]=this};h.Msa=function(a,b,c,d){return this.RGc(b,d)};h.Qkd=function(){this.QY.Oa(null)};h.RGc=function(b,d){if(this.zb()){var f=b.Ni(),h=null;this.g$.hr(a.o.ze);this.g$.Zj(a.o.ze);this.g$.wq(1);
this.g$.ir(1);this.g$.Oo(1);this.g$.Po(1);this.bh()&&(h=this.oka()?a.oc.Xmc:a.oc.Wmc,this.g$.hr(a.o.BT),this.g$.Zj(a.o.Mea));this.Zc()&&(h=this.Zc());this.ega.Oa(f);this.ega.ro(f.Fc(0));this.ega.Yn(f.Nc(0));this.ega.pi(a.La.Uj);this.ega.Wb(a.na.jp);this.ega.fc(a.ta.fi);this.ega.Bf(4);this.ega.we(2);this.ODa.Oa(f);this.ODa.ro(f.Fc(0));this.ODa.Yn(f.Nc(0));this.ODa.fc(a.ta.tf);this.ODa.Wb(a.na.Mq);this.ODa.Bf(2);this.ORa.Oa(f);this.ORa.ro(f.Fc(0));this.ORa.Yn(f.Nc(0));this.ORa.fc(a.ta.Sg);this.ORa.Bf(22);
this.QY.Oa(b);this.QY.$p(f);this.QY.Vd(d+1);this.QY.iT(this.j_a()?this.Ueb:"");this.kQ.dT(!1);this.kQ.ju(a.Jc.bD);this.kQ.h6a(a.aJ.sMa);this.kQ.TL(a.$w.gR);this.kQ.tb(this.ab());this.kQ.Ro(a.gh.Bq);this.kQ.X7(this.mw?this.mw.VM:null);this.NRa.Nj(h);this.kQ.tk(!1,!0);f=60+this.kQ.AN();h=10+this.kQ.Eja();this.QY.yc(h);this.NRa.sb(new c.qa(2,2,18,18));this.kQ.sb(new c.qa(22,2,f,18));b.qc(Math.max(b.Ua(),f));b.yc(b.Na()+this.QY.Na());null!=this.mw&&this.mw.pqc(this.mw.VM);d++}return d};h.ONc=function(){delete b.ba().fTa[this.UMb];
b.ba()};h.yke=function(a){this.Vd(a);null!=this.gc&&this.gc.pda()};h.s7=function(){this.pa(a.g.j,a.Ke.Mac)};h.JPc=function(a,b){this.uI()&&this.Gi(!0);this.hf();this.W()&&this.W().c4a();b.HANDLED.set(!0)};h.$Yb=function(){this.Xb()&&this.pa(a.g.j)};h.lp=function(b,c){switch(c.eb){case a.g.Bb:case a.g.Ub:this.Bd(null)}};h.XXb=function(b,c){switch(c.eb){case a.g.Bb:case a.g.Ub:this.Bd(null)}};d.Md(c.tic,"PRIM_MITM",{Aa:{Parent:{a:h.W,f:h.Oa},Caption:{a:h.ab,f:function(a){this.tb(d.ka(a))}},Checked:{a:h.bh,
f:function(a){this.Gi(d.Ca(a))}},Default:{a:h.vba,f:function(a){this.D5a(d.Ca(a))}},GroupIndex:{a:h.uI,f:function(a){this.S7(d.O(a))}},HelpContext:{a:h.z_c,f:function(a){this.$sd(d.O(a))}},MenuBreak:{a:function(){return d.va(this.g1c(),a.LO.v)},f:function(b){this.Utd(d.wa(b,a.LO.v))}},RadioItem:{a:h.oka,f:function(a){this.yOa(d.Ca(a))}},SubMenu:{a:h.J3c,f:h.dFb},ShortCut:{a:function(){return d.va(this.cFa,a.fa.v)},f:function(b){this.fvd(d.wa(b,a.fa.v))}},Tag:{a:h.tpb,f:function(a){this.P6a(d.O(a))}},
Tip:{a:h.g4c,f:function(a){this.swd(d.ka(a))}},TipShow:{a:h.j_a,f:function(a){this.twd(d.Ca(a))}},TipShowOfParent:{a:h.Bpb,f:function(a){this.uwd(d.Ca(a))}},Enabled:{a:h.te,f:function(a){this.Qg(d.Ca(a))}},Visible:{a:h.zb,f:function(a){this.Ab(d.Ca(a))}},DisplayPosition:{a:h.dh,f:function(a){this.Vd(d.O(a))}},Image:{a:h.Zc,f:h.Bd}}})},{rp:["PRIM_TBLO","PRIM_PPNL","PRIM_IMAG","PRIM_SPBN"]});
