window.LANSA.addSrc("atlm",function(d,c,a,b,p){d.Ob("PRIM_CPST");a.Mha={PGc:0,ZSb:1,OGc:2,YSb:4,QGc:8,NLd:15};a.yX={VAb:0,Hpc:1,Gpc:2,ljd:3};a.yX.v={VERTICAL:a.yX.VAb,HORIZONTAL:a.yX.Hpc,DISPLAYPOSITION:a.yX.Gpc,EO:a.yX.ljd};a.hLa={fJd:0,kLb:1,dJd:2,hJd:3,eJd:4,gJd:5,eme:6};a.K8d={F2a:0,G2a:1};a.thb={Ztb:32};c.Xfc=function(b,c,d){t.K.call(this);this.Tb=[];this.Tb=c;this.Cj=this.ck=d;this.ZDa=this.SFa=0;this.vY=a.Mha.PGc};var t=c.u(c.Xfc,c.jf);t.R=function(){t.k.R.call(this)};c.BLa=function(){m.K.call(this);
this.ETa=a.yX.VAb};d.Ob("PRIM_TBLO");var m=c.u(c.BLa,c.PLa);m.R=function(){m.k.R.call(this)};m.C0d=function(){return this.ETa};m.bud=function(b){this.ETa!=b&&(this.ETa=b,this.m(a.g.j))};m.Tda=function(a,b){var c=this.Aya(a);c.Tda(b);return c};m.eW=function(a){return this.Jg(a).eW()};m.fTd=function(a){return this.Jg(a)};m.dob=function(){return a.hLa.kLb};m.Lo=function(b,c){var d=m.k.Lo.call(this,b,c);if(d){var e=this.Jg(b);!e||e.eW()!=a.aj.Nha&&e.eW()!=a.aj.Kha||(d=!1)}return d};m.pq=function(b,c){var d=
m.k.pq.call(this,b,c);if(d){var e=this.Jg(b);!e||e.eW()!=a.aj.qaa&&e.eW()!=a.aj.Lha||(d=!1)}return d};m.sWc=function(a){return this.Jg(a)};m.jN=function(a,b,c,e){e===p&&(e=!0);a=d.Dc("PRIM_ATLI");a.vk(b);e&&a.Oa(this);return a};m.Xed=function(a,b){return b=this.kf(a,void 0)};m.SUb=function(a){var b=new c.G1a;b.vk(a);return b};m.kf=function(b,d){for(var h=this.dE(b,!0);;){var e=new c.Xfc(0,h,d);e.Cj.Xa(e.Cj.Se()+this.mh);e.Cj.Za(e.Cj.ue()+this.lh);e.Cj.Va(e.Cj.Ut()-this.nj);e.Cj.Ja(e.Cj.wN()-this.mj);
switch(this.ETa){case a.yX.VAb:this.KV(e,a.aj.Nha);this.KV(e,a.aj.Kha);this.KV(e,a.aj.qaa);this.KV(e,a.aj.Lha);this.KV(e,a.aj.GK);break;case a.yX.Hpc:this.KV(e,a.aj.qaa);this.KV(e,a.aj.Lha);this.KV(e,a.aj.Nha);this.KV(e,a.aj.Kha);this.KV(e,a.aj.GK);break;case a.yX.Gpc:for(var k=null,f=h,m=0;m<f.length&&null!=(k=f[m]);m++){var p=k;p.cfa!=a.aj.GK&&0==(k.ma().vb&a.thb.Ztb)&&this.wgb(e,p)}this.KV(e,a.aj.GK)}if(0==e.SFa&&0==e.ZDa)break;d.g8(e.SFa,e.ZDa)}return new c.xO(d.ja(),d.la())};m.KV=function(b,
c){var d=null,e=b.Tb;switch(c){case a.aj.Nha:case a.aj.qaa:case a.aj.GK:for(var k=0;k<e.length&&null!=(d=e[k]);k++){var f=d;if(f.cfa==c){var m=d.ma();0==(m.vb&a.thb.Ztb)&&this.wgb(b,f)}}break;case a.aj.Kha:case a.aj.Lha:for(k=e.length-1;0<=k&&null!=(d=e[k]);k--)f=d,f.cfa==c&&(m=d.ma(),0==(m.vb&a.thb.Ztb)&&this.wgb(b,f))}};m.wgb=function(b,c){var d=c.a3b(),e,k;switch(c.cfa){case a.aj.Nha:k=0;b.vY|=a.Mha.ZSb;0!=c.FZ&&d.Th(d.ja(),b.ck.la()*c.FZ/100);d.Rb(b.Cj.aa()+c.Rf(),b.Cj.$()+c.If());b.Cj.b5a(b.Cj.aa(),
b.Cj.$()+d.la()+c.If()+c.Yg());e=b.Cj.ja()-(c.Rf()+c.Ug());d.Th(Math.max(e,0),d.la());this.Msa(c,d);0<k&&(k>b.Cj.la()&&(d=k-b.Cj.la(),d>b.ZDa&&(b.ZDa=d)),b.Cj.Mrc(0,k));break;case a.aj.Kha:k=0;b.vY|=a.Mha.OGc;0!=c.FZ&&d.Th(d.ja(),b.ck.la()*c.FZ/100);e=b.Cj.la()-(d.la()+c.If()+c.Yg());0!=(b.vY&a.Mha.ZSb)&&(e=Math.max(e,0));b.Cj.Th(b.Cj.ja(),e);d.Rb(b.Cj.aa()+c.Rf(),b.Cj.Fa()+c.If());e=b.Cj.ja()-(c.Rf()+c.Ug());d.Th(Math.max(e,0),d.la());this.Msa(c,d);0<k&&(k>b.Cj.la()&&(d=k-b.Cj.la(),d>b.ZDa&&(b.ZDa=
d)),b.Cj.g8(0,-k));break;case a.aj.qaa:k=0;b.vY|=a.Mha.YSb;0!=c.FZ&&d.Th(b.ck.ja()*c.FZ/100,d.la());d.Rb(b.Cj.aa()+c.Rf(),b.Cj.$()+c.If());e=b.Cj.aa()+d.ja()+c.Rf()+c.Ug();b.Cj.b5a(Math.max(e,b.ck.aa()),b.Cj.$());e=b.Cj.la()-(c.If()+c.Yg());d.Th(d.ja(),Math.max(e,0));this.Msa(c,d);0<k&&(k>b.Cj.ja()&&(d=k-b.Cj.ja(),d>b.SFa&&(b.SFa=d)),b.Cj.Mrc(k,0));break;case a.aj.Lha:k=0;b.vY|=a.Mha.QGc;0!=c.FZ&&d.Th(b.ck.ja()*c.FZ/100,d.la());e=b.Cj.ja()-(d.ja()+c.Rf()+c.Ug());0!=(b.vY&a.Mha.YSb)&&(e=Math.max(e,
0));b.Cj.Th(e,b.Cj.la());d.Rb(b.Cj.Ka()+c.Rf(),b.Cj.$()+c.If());e=b.Cj.la()-(c.If()+c.Yg());d.Th(d.ja(),Math.max(e,0));this.Msa(c,d);0<k&&(k>b.Cj.ja()&&(d=k-b.Cj.ja(),d>b.SFa&&(b.SFa=d)),b.Cj.g8(-k,0));break;case a.aj.GK:d.Rb(b.Cj.aa()+c.Rf(),b.Cj.$()+c.If()),e=b.Cj.ja()-(c.Rf()+c.Ug()),k=b.Cj.la()-(c.If()+c.Yg()),d.Th(Math.max(e,0),Math.max(k,0)),this.Msa(c,d)}};m.mBb=function(b,c){var d=this.sWc(b);if(d){if(d.eW()==a.aj.Nha||d.eW()==a.aj.Kha)c[0]=!0;if(d.eW()==a.aj.qaa||d.eW()==a.aj.Lha)c[1]=!0}};
d.Ld(c.BLa,"PRIM_ATLM",{Aa:{MarginTop:{a:m.If,f:function(a){this.Df(d.O(a))}},MarginBottom:{a:m.Yg,f:function(a){this.ig(d.O(a))}},MarginLeft:{a:m.Rf,f:function(a){this.Af(d.O(a))}},MarginRight:{a:m.Ug,f:function(a){this.ve(d.O(a))}},MaxHeight:{a:m.kZa,f:function(a){this.dAa(d.O(a))}},MaxWidth:{a:m.lZa,f:function(a){this.bea(d.O(a))}},MinHeight:{a:m.nZa,f:function(a){this.eAa(d.O(a))}},MinWidth:{a:m.oZa,f:function(a){this.dea(d.O(a))}},ProcessingOrder:{a:function(){return d.wa(this.ETa,a.yX.v)},f:function(b){this.bud(d.va(b,
a.yX.v))}}}})});window.LANSA.addSrc("atli",function(d,c,a,b){a.aj={iTb:0,Nha:1,Kha:2,qaa:3,Lha:4,GK:5,AIc:6};a.aj.v={NONE:a.aj.iTb,TOP:a.aj.Nha,BOTTOM:a.aj.Kha,LEFT:a.aj.qaa,RIGHT:a.aj.Lha,CENTER:a.aj.GK,EO:a.aj.AIc};a.CIc={Lsa:0};c.G1a=function(){p.K.call(this);this.FZ=0;this.cfa=a.aj.iTb;this.vY=a.CIc.Lsa};var p=c.u(c.G1a,c.QLa);b.H1a=function(a,b,d){var p=new c.G1a;p.Oa(a);p.vk(b);p.Tda(d);return p};p.R=function(){p.k.R.call(this)};p.dob=function(){return a.hLa.kLb};p.eW=function(){return this.cfa};p.Tda=function(b){this.cfa!=
b&&(this.cfa=b,this.m(a.g.j))};p.g0d=function(){return this.FZ};p.tge=function(b){0>b?b=0:100<b&&(b=100);this.FZ!=b&&(this.FZ=b,this.m(a.g.j))};p.Rrb=function(b){var c=!1;if(null!=this.gb&&this.gb.W()===b)if(this.gb.Yd()){if(this.gb.sp()||this.cfa==a.aj.GK)c=!0}else this.gb.sp()&&(c=!0);return c};p.r8b=function(a,b,c){this.Oa(a);this.vk(b);this.Tda(c)};d.Ld(c.G1a,"PRIM_ATLI",{Aa:{MarginTop:{a:p.If,f:function(a){this.Df(d.O(a))}},MarginBottom:{a:p.Yg,f:function(a){this.ig(d.O(a))}},MarginLeft:{a:p.Rf,
f:function(a){this.Af(d.O(a))}},MarginRight:{a:p.Ug,f:function(a){this.ve(d.O(a))}},MaxHeight:{a:p.kZa,f:function(a){this.dAa(d.O(a))}},MaxWidth:{a:p.lZa,f:function(a){this.bea(d.O(a))}},MinHeight:{a:p.nZa,f:function(a){this.eAa(d.O(a))}},MinWidth:{a:p.oZa,f:function(a){this.dea(d.O(a))}},Manage:{a:p.ma,f:p.vk},Parent:{a:p.W,f:p.Oa},Attachment:{a:function(){return d.wa(this.eW(),a.aj.v)},f:function(b){this.Tda(d.va(b,a.aj.v))}}}})});
