window.LANSA.addSrc("ppnl",function(d,c,a,b,p){d.Ob("PRIM_PHBN");d.Ob("PRIM_IMAG");d.Ob("PRIM_TBLO");a.Xyb={sMa:0,Pmc:3};a.KO={hda:0,sya:1,Lmc:2};a.KO.v={NONE:a.KO.hda,POPUP:a.KO.sya};a.am={Kma:8321,j4a:1,ZAb:2,dBb:8,$Ab:16,bBb:32,cBb:64,fBb:128,iBb:256,aBb:512,hBb:1024,gbe:2048,gBb:4096,Opc:8192,eBb:16384};a.Sla={d7:0,nX:1,oX:2};a.kae={Ppc:0};a.hR={Yhb:0,Uhb:268435456,$hb:536870912};a.hR.v={HIDDEN:a.hR.Yhb,ALL:a.hR.Uhb,NONE:a.hR.$hb};a.Oya={fhd:0,mAb:1,moc:805306368};a.Wg={v2:0,ZBa:1,W8a:3,X8a:4,
qJb:5,Myc:6,rJb:7,Eyc:8,Fyc:9,Iyc:10,Oyc:11,Jyc:12,Gyc:13,Hyc:14,Kyc:15,Lyc:16,Nyc:17};a.Wg.v={NONE:a.Wg.v2,FADEINANDSCALE:a.Wg.ZBa,SLIDEINLEFT:a.Wg.W8a,SLIDEINRIGHT:a.Wg.X8a,SLIDEINBOTTOM:a.Wg.qJb,NEWSPAPER:a.Wg.Myc,SLIDEINTOP:a.Wg.rJb,"3DFLIPHORIZONTAL":a.Wg.Eyc,"3DFLIPVERTICAL":a.Wg.Fyc,"3DSIGN":a.Wg.Iyc,SUPERSCALED:a.Wg.Oyc,"3DSLIT":a.Wg.Jyc,"3DROTATEBOTTOM":a.Wg.Gyc,"3DROTATEINLEFT":a.Wg.Hyc,LETMEIN:a.Wg.Kyc,MAKEWAY:a.Wg.Lyc,SLIPFROMTOP:a.Wg.Nyc};a.Wg.bMa={NONE:a.Wg.v2,FADEINANDSCALE:a.Wg.ZBa};
a.Wg.c9d={NONE:a.Wg.v2,FADEIN:a.Wg.ZBa,SLIDEINLEFT:a.Wg.W8a,SLIDEINRIGHT:a.Wg.X8a,SLIDEINTOP:a.Wg.rJb,SLIDEINBOTTOM:a.Wg.qJb};a.Wg.g0b={"":a.Wg.v2,"md-effect-1":a.Wg.ZBa,"md-effect-21":a.Wg.W8a,"md-effect-2":a.Wg.X8a,"md-effect-3":a.Wg.qJb,"md-effect-4":a.Wg.Myc,"md-effect-7":a.Wg.rJb,"md-effect-8":a.Wg.Eyc,"md-effect-9":a.Wg.Fyc,"md-effect-10":a.Wg.Iyc,"md-effect-11":a.Wg.Oyc,"md-effect-13":a.Wg.Jyc,"md-effect-14":a.Wg.Gyc,"md-effect-15":a.Wg.Hyc,"md-effect-17":a.Wg.Kyc,"md-effect-18":a.Wg.Lyc,"md-effect-19":a.Wg.Nyc};
c.uic=function(a){t.K.call(this,a);this.Hc=a};var t=c.u(c.uic,c.N6);t.nb=function(){t.k.nb.call(this)};t.R=function(){this.ib.t7();t.k.R.call(this)};t.ma=function(){return this.Hc.Hb()};t.Ta=function(){return null};t.tka=function(){return!0};t.gea=function(){};t.wna=function(){};t.vna=function(){};t.oA=function(){};t.ay=function(){};t.vva=function(){return null};t.nL=function(){return!1};t.Yd=function(){return!0};t.hO=function(){return!0};t.WN=function(){return!1};t.J0=function(){return!1};t.Ne=function(b){b[0]=
a.Q0a;b[1]=a.O0a};t.ELd=function(){};t.i_=function(a){t.k.i_.call(this,a)};t.xGc=function(){return!1};t.sma=function(){};t.Ng=function(){};t.wda=function(){};t.Yx=function(){};t.zda=function(){};t.ME=function(){};c.Sx=function(){d.Ob("PRIM_IMAG");d.Ob("PRIM_TBLO");d.Ob("PRIM_LABL");m.K.call(this);this.Nb=b.Mf(10,10,280,120);this.xg=a.am.Kma;this.Lm=this.pe=this.sY=this.Gp=null;this.QA=a.Wg.v2;this.PM=a.oh.Vx;this.ATa=this.N3=this.FU=null;this.Fg=new c.pd(0,0);this.Wdb=this.$ga=this.cp=this.UD=this.FF=
this.qC=this.Ns=this.aV=this.Fp=null;this.pUa="";this.VTa=12;this.Zga=a.o.Sb;b.ba().f8c(this);this.ZFc();b.ba().PTc();var e=null;this.Ss();this.Ns=new c.Zl;this.Ns.sb(new c.qa(0,0,0,30));this.Ns.Oe(!1);this.Ns.wq(!1);this.Ns.Zp(this.Nc);this.Ns.xna(!1);this.qC=new c.au;this.qC.Oe(!1);this.qC.VE(a.$d.eM);this.qC.Oa(this.Ns);this.qC.AB(a.Ic.hA);this.FF=new c.au;this.FF.VE(a.$d.CAa);this.FF.Oa(this.Ns);this.FF.Oe(!1);this.FF.za(this,a.Q.sc,this.vOc);this.FF.za(this,a.Q.FG,this.wOc);this.FF.za(this,a.Q.GG,
this.xOc);this.UD=new c.Nw;this.UD.Oa(this.Ns);this.UD.Oe(!1);this.UD.Qo(a.eh.Aq);this.UD.Ef(!1);this.UD.ug(a.Qp.h0b);b.Pc(this.Nc,this.Ns,null,null,1,1);e=b.Pc(this.Nc,this.qC,this.Nc.Ec(0),this.Nc.Mc(0),1,1);e.Wb(a.na.Lq);e.fc(a.ta.Mk);e.Af(2);e=b.Pc(this.Nc,this.FF,this.Nc.Ec(0),this.Nc.Mc(0),1,1);e.Wb(a.na.yC);e.fc(a.ta.sf);e.ve(2);e=b.Pc(this.Nc,this.UD,this.Nc.Ec(0),this.Nc.Mc(0),1,1);e.Wb(a.na.re);e.fc(a.ta.Mk);this.Oe(!1)};var m=c.u(c.Sx,c.Zl);m.nb=function(){b.ga(this.lKd);this.lKd=null;
b.ga(this.Ns);this.Ns=null;b.ga(this.qC);this.qC=null;b.ga(this.FF);this.FF=null;b.ga(this.UD);this.UD=null;m.k.nb.call(this)};m.R=function(){b.ga(this.cp);this.cp=null;m.k.R.call(this);this.fna(null);this.e5a(null);this.i6a(null);this.j6a(null);this.dna(null);this.WEb(null);b.ba().ykd(this);b.ga(this.Lm);this.Lm=null;b.ga(this.ATa);this.ATa=null};m.Ae=function(){var a=c.EL;this.lS()&&(a=c.xlc);return a};m.o0d=function(){return this.PM};m.hva=function(){if(null==this.ATa){var a=new c.uic(this);this.ATa=
b.Oca(a);this.Ia(this,this.JQc)}return this.ATa};m.fna=function(b){this.Gp!=b&&(this.Gp&&this.Gp.Ha(this),(this.Gp=b)&&this.Gp.Ia(this,this.VWb),this.m(a.g.j))};m.WXc=function(){return this.Gp};m.Eja=function(){var a=null;this.Gp&&this.Gp instanceof c.Rx&&(a=this.Gp);return a};m.e5a=function(b){this.sY!=b&&(this.sY&&this.sY.Ha(this),(this.sY=b)&&this.sY.Ia(this,this.XNc),this.m(a.g.j))};m.KSd=function(){return this.sY};m.i6a=function(b){this.FU!=b&&(this.FU&&this.FU.Ha(this),(this.FU=b)&&this.FU.Ia(this,
this.HQc),this.m(a.g.j))};m.m0d=function(){return this.FU};m.j6a=function(b){this.N3!=b&&(this.N3&&this.N3.Ha(this),(this.N3=b)&&this.N3.Ia(this,this.IQc),this.m(a.g.j))};m.n0d=function(){return this.N3};m.Hb=function(){var a=this.pe;!this.pe||this.pe instanceof c.Sx||(a=this.pe);!a&&this.Qsb()&&(a=this);return a};m.ZUd=function(){return this.pe};m.XR=function(){null==this.Lm&&(this.Lm=new c.Cla,this.Lm.Etc(),this.Lm.HOa(a.hy.R8a));return this.Lm};m.v1c=function(){return this.Lm};m.F1d=function(){return this.Fg};
m.Tp=function(){this.hh();return this.Cg};m.Uda=function(b){b=this.xg&~a.am.ZAb|(b?a.am.ZAb:0);this.xg!=b&&(this.xg=b,this.m(a.g.j))};m.Zma=function(b){b=this.xg&~a.am.j4a|(b?a.am.j4a:0);this.xg!=b&&(this.xg=b,this.m(a.g.j))};m.fIa=function(){return 0!=(this.xg&a.am.j4a)};m.OCb=function(b){b=this.xg&~a.am.$Ab|(b?a.am.$Ab:0);this.xg!=b&&(this.xg=b,this.m(a.g.j))};m.kua=function(){return 0!=(this.xg&a.am.$Ab)};m.VEb=function(b){b=this.xg&~a.am.iBb|(b?a.am.iBb:0);this.xg!=b&&(this.xg=b,this.lY(this.vf()),
this.m(a.g.j))};m.ppb=function(){return 0!=(this.xg&a.am.iBb)};m.L2c=function(){return this.VTa};m.Ztc=function(b){b!=this.VTa&&(this.VTa=b,this.xb(),this.pa(a.g.j))};m.G1d=function(){return this.Zga};m.AOa=function(b){if(this.Wsb()||this.Zga!=b)this.Zga=b,this.m(a.g.j)};m.Oud=function(){!1==this.Wsb()&&(this.Zga=a.o.Sb,this.m(a.g.j))};m.tsc=function(b){b=this.xg&~a.am.aBb|(b?a.am.aBb:0);this.xg!=b&&(this.xg=b,this.lY(this.vf()),this.m(a.g.j))};m.xYa=function(){return 0!=(this.xg&a.am.aBb)};m.zge=
function(b){b=this.xg&~a.am.gBb|(b?a.am.gBb:0);this.xg!=b&&(this.xg=b,this.m(a.g.j))};m.V1c=function(){return 0!=(this.xg&a.am.gBb)};m.$sc=function(){var b=this.xg&~a.am.eBb|a.am.eBb;this.xg!=b&&(this.xg=b,this.m(a.g.j))};m.P3b=function(){return 0!=(this.xg&a.am.eBb)};m.Jud=function(){var b=this.xg&~a.am.Opc|0;this.xg!=b&&(this.xg=b,this.m(a.g.j))};m.K2c=function(){return 0!=(this.xg&a.am.Opc)};m.TG=function(b){b=this.xg&~a.am.dBb|(b?a.am.dBb:0);this.xg!=b&&(this.xg=b,this.m(a.g.j))};m.zsd=function(b){b=
this.xg&~a.am.cBb|(b?a.am.cBb:0);this.xg!=b&&(this.xg=b,this.m(a.g.j))};m.qge=function(b){b=this.xg&~a.am.fBb|(b?a.am.fBb:0);this.xg!=b&&(this.xg=b,this.m(a.g.j))};m.Xda=function(b){b=this.xg&~a.am.bBb|(b?a.am.bBb:0);this.xg!=b&&(this.xg=b,this.m(a.g.j))};m.M2b=function(){return 0!=(this.xg&a.am.bBb)};m.L2b=function(){return this.Fp};m.dna=function(b){this.Fp!=b&&(null!=this.Fp&&(this.Fp.Ha(this,this.tjb),this.Fp.ub()),this.Fp=b,null!=this.Fp&&(this.Fp.Ca(),this.Fp.Ia(this,this.tjb)),this.lY(this.vf()),
this.pa(a.g.j))};m.I3c=function(){return this.aV};m.WEb=function(b){this.aV!=b&&(null!=this.aV&&(this.aV.Ha(this,this.VYb),this.aV.ub()),this.aV=b,null!=this.aV&&(this.aV.Ca(),this.aV.Ia(this,this.VYb)),this.lY(this.vf()),this.pa(a.g.j))};m.M2c=function(){return this.hva().Eh()};m.$tc=function(b){this.hva().Eh()!=b&&(this.hva().Jb(b),this.m(a.g.j))};m.N2c=function(){return this.hva().Yk()};m.$a=function(){var a=null;null!=this.Ta()&&(a=this.Ta().$a());return a};m.gWc=function(){var a=!1;if(this.lS()||
!this.Qsb())a=!0;return a};m.H3c=function(){return this.pUa};m.Pvd=function(b){this.pUa!=b&&(this.pUa=b,this.xb(),this.pa(a.g.j))};m.Mh=function(){var a=!1;null!=this.Ta()&&(a=this.Ta().$a(),a=b.oe[a].BSa);return a};m.Vrb=function(){return 0!=(this.xg&a.am.ZAb)};m.uKa=function(){return 0!=(this.xg&a.am.j4a)};m.Bsb=function(){return 0!=(this.xg&a.am.dBb)};m.F5d=function(){return 0!=(this.xg&a.am.cBb)};m.Qsb=function(){return 0!=(this.xg&a.am.fBb)};m.lS=function(){return 0!=(this.xg&a.am.hBb)};m.qsb=
function(){return!1};m.Wsb=function(){return!1==this.W6b()};m.W6b=function(){return this.Zga!=a.o.Sb};m.I0=function(){var a=!1;this.Hb()==this&&this.Hb().W()&&this.Hb().W()!=this.Lm&&(a=!0);return a};m.n6c=function(){var a=this.I0();a&&!this.W().f0a()&&(a=!1);return a};m.J1=function(){if(null!=this.Ta()){var a=this.kka()?this.kka().uh():"DEFAULT";b.W9a(this.Ta().$a(),a,this.ha.y9)}};m.Wid=function(a){var c=!1;this.Mh()&&this.uKa()&&this.Eja()&&null!=a&&b.ba().LE(this.Eja())==a&&(c=!0);return c};m.Xid=
function(a){var c=!1;if(this.Mh()&&this.uKa()&&!this.qsb())if(null==a)c=!0;else for(var d=b.ba().LE(a),c=!0;null!=a&&null!=d;)d==this?(c=!1,a=null):null!=d&&(d.Eja()?(d=d.Eja(),a=a!=d?d:null):a=null),d=b.ba().LE(a);return c};m.lY=function(d,e){e===p&&(e=!1);if(!b.ba().L0())if(this.ppb()){var f=new c.qa(0,0,d.ja(),30),k=d.ja()-4;this.xYa()&&(k-=f.la());this.aV&&(k-=f.la());this.UD.tb(this.ab());this.UD.pc(Math.min(k,this.UD.a_a(this.UD.ab(),this.UD.np().length)+10));this.Ns.Ib(this);this.Ns.sb(f);
this.Ns.Qb(""==this.pUa?a.Dca:this.pUa);this.qC.Ab(this.xYa());this.qC.pc(f.la());this.qC.Ab(null!=this.aV);this.qC.Ad(this.aV);this.qC.sb(new c.qa(this.qC.ue(),this.qC.Se(),Math.min(this.qC.Yc()?this.qC.Yc().Ua():this.Ns.Na(),this.Ns.Na()-4),Math.min(this.qC.Yc()?this.qC.Yc().Na():this.Ns.Na(),this.Ns.Na()-4)));this.FF.Ab(this.xYa());this.FF.sb(new c.qa(this.FF.ue(),this.FF.Se(),30,29));this.FF.Mj(this.Fp?this.Fp:a.oc.pId);e?b.ba().OFc(this.FF):b.ba().Gkd(this.FF);this.Ns.W()&&d.Xa(d.$()+f.la())}else this.Ns.Oa(null)};
m.kf=function(a){this.lY(a);m.k.kf.call(this,a)};m.hh=function(){this.I0()||this.Oa(this.XR());this.qrd(this.lS());this.gWc()&&m.k.hh.call(this)};m.Uk=function(){m.k.Uk.call(this);this.lY(this.vf())};m.TAb=function(b,c,d){m.k.TAb(b,c,d);d[0]&&this.JW()!=a.iy.VBa&&this.ppb()&&(d[0]=this.Ns==c||this.UD==c)};m.Ne=function(b){""==b[0]&&(b[0]=a.Q0a);""==b[1]&&(b[1]=a.O0a);m.k.Ne.call(this,b)};m.Ada=function(a){return this.Ria(this.Gp,a)};m.c4a=function(){this.kua()&&this.QA==a.Wg.v2&&this.Hb().Sf(!0);
this.I1b()};m.mpc=function(){if(this.kua()){var a=b.zO();a&&a.us(this)||this.Hb().Sf(!0)}};m.Vid=function(a){return this.QHa(a)};m.eza=function(){null!=this.Lm&&(null!=this.Hb()&&this.Vv(this.Hb(),a.ea.J0a),this.fna(null),this.Bsb()||null==this.sY||this.fIa()||b.Hxa()!=this.sY||this.sY.TE(this.sY.pI()),this.e5a(null),this.i6a(null),this.j6a(null));this.Vrb()&&this.ms()};m.eNa=function(){};m.DNa=function(){this.Fg.vn(this.ue());this.Fg.Ym(this.Se());this.Mh()&&this.sD(this.PM,this.FU,this.Fg,this.Gp,
this.N3,this.QA)};m.uea=function(d,e,f,k,h){var m=b.Vn();this.I0()&&(m.vn(this.ue()),m.Ym(this.Se()));d==p&&(d=m.Pb());e==p&&(e=m.Vb());f==p&&(f=a.oh.Vx);k==p&&(k=a.Wg.v2);this.sD(f,null,new c.pd(d,e),h,null,k)};m.sD=function(d,e,f,k,h,m){this.yf()&&d==a.oh.qma&&null==e&&k&&k.yf()&&(e=k);this.n6c()||this.Oa(this.XR());d==p&&(d=a.oh.Vx);e==p&&(e=null);f==p&&(f=b.Vn());k==p&&(k=null);h==p&&(h=null);m==p&&(m=a.Wg.v2);if(this.Mh()&&this.Qsb()){if(this.FU==e&&this.N3==h&&this.Gp==k&&this.PM==d&&this.QA==
m){d=b.Ui(f.Pb(),f.Vb(),this.Hb().Ua(),this.Hb().Na());this.dza(d);this.XR().sb(new c.qa(0,0,d.ja(),d.la()));f.vn(d.aa());f.Ym(d.$());this.Hb().sb(d);this.Muc(this.hva().BI());this.Fg=f;return}var u=this.Vrb();this.Uda(!1);this.Co();this.eza();this.Uda(u)}this.PM!=a.oh.Vx&&this.W()!=this.Lm&&this.Oa(null);this.xg|=a.am.hBb;this.Rtc(!1);null!=this.Tp()&&(this.fna(k),this.XR(),this.P3b()&&this.XR().ha.pD(this.Eja()?this.Eja().ha:null),this.V1c()&&this.Vv(this.XR(),a.ea.I0a),this.e5a(b.Hxa()),this.PM=
d,this.QA=m,this.lY(this.vf()),this.i6a(e),this.j6a(h),this.lhd(f,this.Bsb()),this.W()==this.XR()?this.Vv(this.XR(),a.ea.fla):this.Vv(this,a.ea.fla),this.c4a())};m.Co=function(){if(this.Mh()){var c=b.ba().Ok;c&&c.us(this)&&this.Vv(c,a.ea.bA);b.ba().NKc(this);null!=this.Ta()&&(c=this.Ta().$a(),b.oe[c].DGa());this.Llb();this.eza()}else b.ba().I$&&(c=b.ba().I$,c.Ta()&&c.Ta().BSa&&c==this.Gp&&b.ba().Fu(c,!1))};m.yGc=function(a){for(var b=this.ha.BI(),c=null,d=b.length-1;null!=b&&0<=d&&null!=(c=b[d]);d--)a.splice(0,
0,c)};m.lhd=function(a,c){this.Ta()&&(c||(b.ba().wy&&b.ba().wy.L7b(),b.ba().Ky(this.Eja(),!1,this)),this.mhd(a))};m.mhd=function(c){if(this.Ada(c)&&this.Hb()){this.Hb().hh();this.P3b()&&this.XR().yE(!0);c=this.Lm;c.ZW()||c.A3a();c=this.Ta().$a();a.ECa+=2;b.oe[c].KEa=a.ECa;b.UKb(c,b.oe[c].ah());b.oe[c].vAa();var d=b.oe[c].L.cp?b.oe[c].L.cp.Ta():null;d&&d.G.parentElement!=document.body&&(null!=d.G.parentElement&&d.G.parentElement.removeChild(d.G),d.pBc=!1,d.G.style.zIndex=b.oe[c].KEa-1,document.body.appendChild(d.G))}};
m.dza=function(a){b.Wdd(this,a)};b.Wdd=function(d,e){switch(d.PM){case a.oh.B3a:var f=b.GE(),f=new c.qa(f.ue()-d.ha.Li(),f.Se()-d.ha.Uj(),f.Ua()+(d.ha.Li()+d.ha.Gj()),f.Na()+(d.ha.Uj()+d.ha.jl()));e.TA(f);break;case a.oh.cJ:var f=b.GE(),k=0,h=0,k=(f.ja()-e.Ua())/2,h=(f.la()-e.Na())/2;e.Rb(k,h);d.I0()&&e.TA(d.W().Pda(e));break;case a.oh.qma:f=b.GE();k=(f.ja()-e.Ua())/2;h=f.Fa()-e.Na();e.Rb(k,h);d.I0()&&e.TA(d.W().Pda(e));break;case a.oh.ehd:f=b.GE();k=(f.ja()-e.Ua())/2;e.Rb(k,0);d.I0()&&e.TA(d.W().Pda(e));
break;case a.oh.loc:f=b.GE();h=(f.la()-e.Na())/2;k=f.Ka()-e.Ua();e.Rb(k,h);d.I0()&&e.TA(d.W().Pda(e));break;case a.oh.joc:f=b.GE();h=(f.la()-e.Na())/2;e.Rb(0,h);d.I0()&&e.TA(d.W().Pda(e));break;default:b.Q1a(e)}};m.Bed=function(){b.ba();this.cp=new c.Zl;this.cp.za(this,a.Q.Jfb,this.hRc);this.cp.za(this,a.Q.sc,this.iRc);this.yf()&&(this.cp.I5().dg("positioning:flex; alignitems-center; justify-content:center;"),this.cp.fB().dg("position:fixed; top:0px; right:0px; left:0px;"),this.cp.IW().dg("height:100vh;"));
this.cp.Ud(1);this.cp.Za(0);this.cp.Dna(1);this.cp.Xa(0);this.cp.Ab(!1);this.cp.Oe(!1);this.Wdb=new c.Xf;this.$ga=new c.yb;this.$ga.Kd(this.Wdb)};m.Muc=function(a){var d=b.ba().bn;this.cp||this.Bed();if(!this.cp.Xb()){if(this.yf()){var e=b.OL(this.yc(),this.Zga,this.VTa/100,[]);this.cp.XF().dg("class:drawer-shroud;");this.cp.Qn().dg("background-color:"+e+";")}this.Wdb.Qd(this.Zga);this.Wdb.Pg(this.VTa);this.cp.Jb(this.W6b()?this.$ga:null);for(e=0;e<a.length;e++)this.cp.Tn(a[e]);null==this.cp.Eh()?
this.cp.Oa(null):(this.cp.Ib(d),this.cp.Ud(1),this.cp.TV())}this.cp.sb(new c.qa(0,0,d.Ua(),d.Na()))};m.w6c=function(){this.cp&&this.cp.zb()&&this.cp.Pr()};m.Lj=function(c){if(this.K2c()){var d=this.Ta().$a();a.ECa+=2;b.oe[d].KEa=a.ECa;b.UKb(d,b.oe[d].ah())}m.k.Lj.call(this,c)};m.Ria=function(b,e){var f=!0,k=d.cc(),h=this.Hb().Ua(),m=this.Hb().Na();k.kc("CONTEXT",b);k.KF("LEFT",e.Pb());k.KF("TOP",e.Vb());k.KF("WIDTH",h);k.KF("HEIGHT",m);k.cN("TRANSITION",this.QA,a.Wg.v);k.lg("CONTINUE",!0);this.Ga(a.Q.Wx,
k);e.vn(k.Rua("LEFT"));e.Ym(k.Rua("TOP"));f=k.Zg("CONTINUE");h=h==k.Rua("WIDTH")?this.Hb().Ua():k.Rua("WIDTH");m=m==k.Rua("HEIGHT")?this.Hb().Na():k.Rua("HEIGHT");h=new c.qa(e.Pb(),e.Vb(),h,m);this.dza(h);this.XR().sb(new c.qa(0,0,h.ja(),h.la()));e.vn(h.aa());e.Ym(h.$());this.Hb().sb(h);this.QA=k.znb("TRANSITION",a.Wg.v);k.Jc();this.Fg=e;return f};m.QHa=function(b){var c=!1,c=d.cc();c.lg("CLOSEPOPUP",!0);this.Ga(a.Q.gR,c);return c=b?!0:c.Zg("CLOSEPOPUP")};m.Llb=function(){this.Ga(a.Q.hN);this.xg&=
~a.am.hBb;this.Rtc(!0);this.I0()&&this.W().xb()};m.I1b=function(){this.Ga(a.Q.Kzb)};m.hRc=function(){this.cp.zb()||(this.cp.Oa(null),this.eNa())};m.iRc=function(){this.qsb()&&this.uKa()&&b.ba().Fu(this,!1)};m.wOc=function(){this.lY(this.vf(),!0)};m.xOc=function(){this.lY(this.vf())};m.vOc=function(a,c){b.ba().Fu(this,!1);c.tk("HANDLED",!0)};m.JQc=function(){};m.VWb=function(b,c){switch(c.eb){case a.g.Bb:this.fna(null)}};m.HQc=function(b,c){switch(c.eb){case a.g.Bb:this.i6a(null)}};m.IQc=function(b,
c){switch(c.eb){case a.g.Bb:this.j6a(null)}};m.XNc=function(b,c){switch(c.eb){case a.g.Bb:this.e5a(null)}};m.tjb=function(b,c){switch(c.eb){case a.g.Bb:case a.g.Ub:this.dna(null)}};m.VYb=function(b,c){switch(c.eb){case a.g.Bb:case a.g.Ub:this.WEb(null)}};m.hHa=m[a.ea.exa]=function(){this.lS()&&this.DNa()};m.wR=m[a.ea.AE]=function(a){m.k.wR.call(this,a);this.lY(this.vf())};m.Gv=m[a.ea.tL]=function(a){m.k.Gv.call(this,a);this.lY(this.vf())};d.Ld(c.Sx,"PRIM_PPNL",{Aa:{CloseOnClick:{a:m.M2b,f:function(a){this.Xda(d.Ba(a))}},
AutoClose:{a:m.fIa,f:function(a){this.Zma(d.Ba(a))}},AutoFocus:{a:m.kua,f:function(a){this.OCb(d.Ba(a))}},TitleBar:{a:m.ppb,f:function(a){this.VEb(d.Ba(a))}},ShroudColor:{a:function(){return this.Wsb()?d.dd:b.tg(this.Zga)},f:function(a){a===d.dd?this.Oud():this.AOa(b.Wf(d.ka(a)))}},ShroudOpacity:{a:m.L2c,f:function(a){this.Ztc(d.O(a))}},CloseButton:{a:m.xYa,f:function(a){this.tsc(d.Ba(a))}},CloseImage:{a:m.L2b,f:m.dna},TitleImage:{a:m.I3c,f:m.WEb},ShroudStyle:{a:m.M2c,f:m.$tc},ShroudStyles:{a:m.N2c},
TitleBarThemeDrawStyle:{a:m.H3c,f:function(a){this.Pvd(d.ka(a))}},IsOpen:{a:m.Mh}},jc:{ShowPopup:function(b,c,e,f,k){this.uea(b===p?p:d.O(b),c===p?p:d.O(c),e===p||""==e?p:d.va(e,a.oh.Xdd),f===p||""==f?p:d.va(f,a.Wg.v),k)},ClosePopup:m.Co}});c.fxb=function(d){q.K.call(this,d);this.Nb=b.Mf(0,0,300,30);this.LEa=a.Oya.fhd;this.$Sa=new c.Ow;this.N9=this.$P=this.ZP=null;this.BY=[];this.Zcb=null;b.ko(this.$Sa);b.jo(this.$Sa);this.Zp(this.$Sa);this.Oe(!1);this.N9=new c.c2a;this.N9.kOa(a.KO.Lmc);this.N9.za(this,
a.Q.Wx,this.BOc);this.ZP=new c.au;this.ZP.Oa(this);this.ZP.sb(new c.qa);this.ZP.za(this,a.Q.sc,this.COc);this.ZP.RX();this.Zcb=new c.ric(this)};var q=c.u(c.fxb,c.Zl);q.nb=function(){q.k.nb.call(this)};q.R=function(){q.k.R.call(this);b.ga(this.Zcb);this.Zcb=null};q.CXc=function(){return this.$P};q.usc=function(b){this.$P!=b&&(null!=this.$P&&(this.$P.Ha(this,this.QWb),this.$P.ub()),this.$P=b,null!=this.$P&&(this.$P.Ca(),this.$P.Ia(this,this.QWb)),this.xb(),this.m(a.g.j))};q.Iud=function(b){b=this.xg&
~a.Oya.mAb|(b?a.Oya.mAb:0);this.LEa!=b&&(this.LEa=b,this.m(a.g.j))};q.Zob=function(){return 0!=(this.LEa&a.Oya.mAb)};q.$qd=function(b){this.yYa()!=b&&(this.LEa=this.LEa&~a.Oya.moc|b,this.xb(),this.yE(),this.Poc(this.vf()),this.pa(a.g.j))};q.yYa=function(){return this.LEa&a.Oya.moc};q.dnb=function(){var b=null;switch(this.yYa()){case a.hR.$hb:case a.hR.Yhb:b=q.k.dnb.call(this);break;case a.hR.Uhb:d.Ob("PRIM_PCOL"),b=new c.Hwb(this.N9),b=new c.M6(b)}return b};q.Ne=function(b){""==b[0]&&(b[0]=a.pbc);
""==b[1]&&(b[1]=a.Rad);q.k.Ne.call(this,b)};q.NAb=function(){this.Zp(this.$Sa)};q.Xx=function(c,d){q.k.Xx.call(this,c,d);this.NAb();b.sic(this,this.$Sa,a.La.Vk,a.na.ZD,a.ta.Mk,this.sjb)};q.kf=function(a){q.k.kf.call(this,a);this.Poc(a)};q.Poc=function(d){switch(this.yYa()){case a.hR.$hb:for(this.ZP.Ab(!1);0<this.BY.length;)this.BY[0].ms();break;case a.hR.Yhb:for(var e=this.BY.length,f=0,k=null,h=this.Hs,m=h.length-1;0<=m&&null!=(k=h[m]);m--)f=Math.max(f,k.Nb.Ka()),k.Ut()>d.Ka()&&(b.qic(this,k),e++);
h=this.BY;for(m=0;m<h.length&&null!=(k=h[m]);m++)f+k.gb.Ua()<d.Ka()?(k.ms(),m--,e--):k.ma().Ud(m+1);if(0<e)this.ZP.Mj(this.$P?this.$P:a.oc.Wyb),this.ZP.sb(new c.qa(d.Ka()-(d.la()+2),0,d.la(),d.la())),this.ZP.Ab(!0),this.N9.Z3a();else for(this.ZP.Ab(!1);0<this.BY.length;)this.BY[0].ms();break;case a.hR.Uhb:for(;0<this.Hs.length;)b.qic(this,this.Hs[this.Hs.length-1]);this.ZP.Mj(this.$P?this.$P:a.oc.Wyb);this.ZP.sb(new c.qa(d.Ka()-(d.la()+2),0,d.la(),d.la()));this.ZP.Ab(!0);this.N9.Z3a()}this.Xb()&&
this.hh()};b.sic=function(c,d,e,f,k,h){for(var m=null,p=c.Hs,u=1,q=0;q<p.length&&null!=(m=p[q]);q++,u++){var s=d.Jg(m);s||(s=b.Pc(d,m,d.Ec(0),d.Mc(0),1,1),m.za(c,a.Q.$I,h));s.ni(e);s.Wb(f);s.fc(k)}};q.QWb=function(b,c){switch(c.eb){case a.g.Bb:case a.g.Ub:this.usc(null);break;case a.g.j:this.xb()}};q.BOc=function(b,c){this.Ga(a.Q.Wx,c)};q.COc=function(b,d){this.N9.sD(a.oh.Vx,this,new c.pd(this.Vt()+this.Ua()-this.N9.Ua(),this.Wt()+this.Na()),this);d.tk("HANDLED",!0)};q.sjb=function(a){this.Zob()&&
(a=a instanceof c.Hla?a:null)&&a.OC()&&!a.OC().Mh()&&(a.ku(),this.Zcb.Uh())};d.Sa(c.fxb,"PRIM_PPNL","MenuBar",{Aa:{CollapsedMenuImage:{a:q.CXc,f:q.usc},ShowOnHover:{a:q.Zob,f:function(a){this.Iud(d.Ba(a))}},CollapseStyle:{a:function(){return d.wa(this.yYa(),a.hR.v)},f:function(b){this.$qd(d.va(b,a.hR.v))}}}});c.ric=function(a){s.K.call(this,500);this.vZ=a};var s=c.u(c.ric,c.s1);s.W_=function(){if(this.vZ.Zob()){var a=!1,c=!1,d=b.ba().nAb(b.Vn());d?a=!0:(d=b.hX(b.Vn()))&&(d==this.vZ||d.us(this.vZ))&&
(a=!0);!a&&(d=b.ba().LE(b.zO()))&&(c=a=!0);a||(this.vZ.Ky(),c=!0);c&&this.oi()}return!1};c.c2a=function(){h.K.call(this);this.Nb=b.Mf(0,0,150,150);this.Di=new c.Ow;this.wz=a.Xyb.sMa;b.ko(this.Di);b.jo(this.Di);this.Zp(this.Di)};var h=c.u(c.c2a,c.Sx);h.nb=function(){h.k.nb.call(this)};h.R=function(){h.k.R.call(this)};h.kOa=function(b){this.WIa()!=b&&(this.wz=this.wz&~a.Xyb.Pmc|b,this.xb(),this.pa(a.g.j))};h.WIa=function(){return this.wz&a.Xyb.Pmc};h.Ne=function(b){""==b[0]&&(b[0]=a.rbc);""==b[1]&&
(b[1]=a.Sad);h.k.Ne.call(this,b)};h.NAb=function(){this.Zp(this.Di);this.Xda(!0)};h.Xx=function(c,d){h.k.Xx.call(this,c,d);this.NAb();b.sic(this,this.Di,a.La.Tj,a.na.ip,a.ta.di,this.sjb)};h.Z3a=function(){if(this.WIa()!=a.KO.hda){for(var b=null,d=this.Hs,e=[!0,2,2,0,0],f=0;f<d.length&&null!=(b=d[f]);f++){var k=b instanceof c.Hla?b:null;switch(this.WIa()){case a.KO.sya:k?k.dpc(e):e[2]+=b.zb()?b.Na():0;break;case a.KO.Lmc:e[1]=Math.max(e[1],b.Ua()),e[2]+=b.zb()?b.Na():0}}for(f=0;f<d.length&&null!=(b=
d[f]);f++)switch(this.WIa()){case a.KO.sya:(k=b instanceof c.Hla?b:null)&&k.pc(e[1])}this.pc(e[1]+this.ha.Li()+this.ha.Gj());this.xc(e[2]+this.ha.Uj()+this.ha.jl())}};h.Ada=function(a){this.Z3a();return h.k.Ada.call(this,a)};h.kf=function(a){h.k.kf.call(this,a)};h.XWb=h[a.ea.Qtb]=function(a){h.k.XWb.call(this,a);this.Z3a()};h.sjb=function(a){(a=a instanceof c.Hla?a:null)&&a.ku()};d.Sa(c.c2a,"PRIM_PPNL","Menu",{Aa:{MenuSizing:{a:function(){return d.wa(this.WIa(),a.KO.v)},f:function(b){this.kOa(d.va(b,
a.KO.v))}}}});c.tic=function(a){e.K.call(this);this.F$=a};var e=c.u(c.tic,c.DO);e.E$b=function(){return!0};e.dhb=function(a,b){return e.k.dhb.call(this,a,b,this.F$)};e.Ne=function(){};c.Hla=function(){k.K.call(this);this.Nb=b.Mf(0,0,100,25);this.tga=a.Sla.d7;this.tv=0;this.zcb=this.tOb=this.$o=this.oU=this.z$=this.jZ=this.KQ=null;this.A$=new c.Ow;this.xy=0;this.YM=a.Ic.ZC;b.ko(this.A$);b.jo(this.A$);this.Zp(this.A$);this.dOa(!0);this.oU=new c.yb;this.oU.gr(a.o.ye);this.oU.Yj(a.o.ye);this.oU.vq(1);
this.oU.hr(1);this.oU.No(1);this.oU.Oo(1);this.z$=new c.au;this.z$.Oa(this);this.z$.sb(new c.qa(0,0,18,18));this.z$.Jb(this.oU);this.$o=new c.tic(this);this.$o.Oa(this);this.$o.Af(2);this.$o.ve(2);this.tOb=b.Pc(this.A$,this.$o,this.A$.Ec(0),this.A$.Mc(0),1,1);this.zcb=b.Pc(this.A$,this.z$,this.A$.Ec(0),this.A$.Mc(0),1,1)};var k=c.u(c.Hla,c.Zl);k.nb=function(){k.k.nb.call(this)};k.R=function(){k.k.R.call(this);this.P5a(null)};k.OC=function(){return this.$o.OC()};k.R7=function(b){this.OC()!=b&&(this.$o.OC()&&
this.$o.OC().zp(this,a.Q.Wx,this.MXb),this.$o.R7(b),this.$o.OC()&&this.$o.OC().za(this,a.Q.Wx,this.MXb),this.m(a.g.j))};k.Kba=function(){return this.$o.Kba()};k.x_c=function(){return this.jZ};k.P5a=function(b){this.jZ!=b&&(null!=this.jZ&&(this.jZ.Ha(this,this.LXb),this.jZ.ub()),this.jZ=b,null!=this.jZ&&(this.jZ.Ca(),this.jZ.Ia(this,this.LXb)),this.Hu(),this.m(a.g.j))};k.Kv=function(){return this.xy};k.fu=function(b){b!=this.xy&&(this.xy=b,this.Hu(),this.pa(a.g.j))};k.iu=function(b){this.YM!=b&&(this.YM=
b,this.Hu(),this.pa(a.g.j))};k.If=function(){return this.$o.If()};k.Df=function(b){this.If()!=b&&(this.$o.Df(b),this.m(a.g.j))};k.Rf=function(){return this.$o.Rf()};k.Af=function(b){this.Rf()!=b&&(this.$o.Af(b),this.m(a.g.j))};k.Ug=function(){return this.$o.Ug()};k.ve=function(b){this.Ug()!=b&&(this.$o.ve(b),this.m(a.g.j))};k.Yg=function(){return this.$o.Yg()};k.ig=function(b){this.Yg()!=b&&(this.$o.ig(b),this.m(a.g.j))};k.zm=function(){return this.YM};k.ika=function(){return 0!=(this.tga&a.Sla.oX)?
!0:!1};k.tOa=function(b){b=this.tga&~a.Sla.oX|(b?a.Sla.oX:0);this.tga!=b&&(this.tga=b,this.Hu(),this.pa(a.g.j))};k.$g=function(){return 0!=(this.tga&a.Sla.nX)?!0:!1};k.Fi=function(b){var d=this.rI();if(b&&0!=d&&null!=this.W())for(var e=null,f=this.W().og,k=0;k<f.length&&null!=(e=f[k]);k++)if(e instanceof c.Hla){var h=e;h!=this&&h.rI()==d&&h.Fi(!1)}b=this.tga&~a.Sla.nX|(b?a.Sla.nX:0);this.tga!=b&&(this.tga=b,this.Hu(),this.pa(a.g.j))};k.rI=function(){return this.tv};k.M7=function(b){this.tv!=b&&(this.tv=
b,this.Hu(),this.pa(a.g.j))};k.gpb=function(){return this.KQ};k.J6a=function(a){this.KQ!=a&&(this.KQ=a)};k.Ne=function(b){""==b[0]&&(b[0]=a.obc);k.k.Ne.call(this,b)};k.ku=function(){var a=b.ba().LE(this);(null==a||a.Mh())&&this.OC()&&!this.OC().Mh()&&this.$o.lIb(!0)};k.ZJa=function(){var a=b.ba().LE(this);(null==a||a.Mh())&&this.OC()&&this.OC().Mh()&&this.$o.lIb(!0)};k.dpc=function(b){var d=null,e=this.gc&&this.gc instanceof c.fxb?this.gc:null,f=this.xy;this.$g()?(d=this.ika()?a.oc.Gmc:a.oc.Fmc,this.oU.gr(a.o.xT),
this.oU.Yj(a.o.Gea)):(this.oU.gr(a.o.ye),this.oU.Yj(a.o.ye));this.jZ&&(d=this.jZ);d&&0==f&&(f=Math.min(this.Na(),d.Na()));this.$o.Qb(a.vbd);this.$o.$S(!1);this.$o.iu(this.zm());this.$o.b6a(e?a.ZI.mMa:a.ZI.nMa);this.$o.dEb(e?a.sq.hda:a.sq.tya);this.$o.QL(a.Yw.$Q);this.$o.fAa(!1);this.$o.tb(this.ab());this.$o.Qo(a.eh.Aq);this.z$.Mj(d);this.z$.sb(new c.qa(this.z$.ue(),this.z$.Se(),f,f));this.tOb.fc(a.ta.Qg);this.tOb.Af(e?0:f+2);this.zcb.fc(a.ta.sf);this.zcb.Wb(a.na.Lq);this.zcb.Af(e?0:2);this.$o.rk(!1,
!0);var k=this.$o.xN(),h=this.$o.zja();e?(k+=f+4,d&&(k+=f+4)):(k+=60,h+=10);!0==b[0]&&(this.xc(h),b[1]=Math.max(b[1],k),b[2]+=this.zb()?h:0,b[3]+=k,b[4]+=h)};k.Xx=function(a,b){k.k.Xx.call(this,a,b);this.dpc([!1,0,0])};k.gf=function(a){var d=!1;this.rI()&&this.Fi(!0);d=k.k.gf.call(this,a);if(!d){a=b.ba().xz;for(var e=null,f=0;f<a.length&&null!=(e=a[f]);f++)e instanceof c.c2a&&b.ba().Fu(e,!1)}return d};k.MXb=function(a,b){b.kud(this)};k.LXb=function(b,c){switch(c.eb){case a.g.Bb:case a.g.Ub:this.P5a(null);
break;case a.g.j:this.Hu()}};d.Sa(c.Hla,"PRIM_PPNL","MenuItem",{Aa:{Checked:{a:k.$g,f:function(a){this.Fi(d.Ba(a))}},MenuPopup:{a:k.OC,f:k.R7},RadioItem:{a:k.ika,f:function(a){this.tOa(d.Ba(a))}},GroupIndex:{a:k.rI,f:function(a){this.M7(d.O(a))}},Image:{a:k.x_c,f:k.P5a},ImageHeight:{a:k.Kv,f:function(a){this.fu(d.O(a))}},MarginLeft:{a:k.Rf,f:function(a){this.Af(d.O(a))}},MarginTop:{a:k.If,f:function(a){this.Df(d.O(a))}},MarginBottom:{a:k.Yg,f:function(a){this.ig(d.O(a))}},MarginRight:{a:k.Ug,f:function(a){this.ve(d.O(a))}},
Alignment:{a:function(){return d.wa(this.zm(),a.Ic.aR)},f:function(b){this.iu(d.va(b,a.Ic.aR))}}},jc:{ShowMenu:k.ku,HideMenu:k.ZJa}});c.pic=function(a,b,c){f.K.call(this);this.vZ=a;this.gb=b;this.pJd=b.rg();-1==c&&(c=this.vZ.BY.length);this.vZ.BY.splice(c,0,this);this.gb.Ia(this,this.Ev);this.gb.Oa(a.N9)};var f=c.u(c.pic,c.td);f.R=function(){var a=this.vZ.Hs.length+1;this.gb.Ha(this,this.Ev);this.vZ.BY.splice(this.vZ.BY.indexOf(this),1);this.gb.Ib(this.vZ);this.gb.Ud(a);this.gb.sb(this.pJd);f.k.R.call(this)};
f.ma=function(){return this.gb};b.qic=function(a,b){-1==a.BY.indexOf(b)&&new c.pic(a,b,0)};f.kp=function(b,c){switch(c.eb){case a.g.Bb:this.ms()}};c.xlc=function(a){u.K.call(this,a);this.BSa=!1;this.uC=null;this.AA="";this.KEa=null;this.pha=0};var u=c.u(c.xlc,c.EL);u.K5c=function(){var b=!1,c=d.wa(this.L.QA,a.Wg.g0b);if("md-effect-17"==c||"md-effect-18"==c||"md-effect-19"==c)b=!0;return b};u.Gd=function(a){var c=this;this.G=document.createElement("div");this.G.setAttribute("id",a+this.hc);this.G.setAttribute("LANSAHandle",
this.hc);this.uC=document.createElement("div");this.uC.setAttribute("LANSAHandle",this.hc);c.uC.addEventListener("click",function(a){a=b.$t(b.Fba(a.target||a.srcElement));c.L&&a.iqb()&&c.L.uKa()&&b.ba().Fu(c.L,!1)},!1);return this.G};u.Tea=function(){this.DGa()};u.MJb=function(b){this.AA=d.wa(this.L.QA,a.Wg.g0b);null!=this.KEa&&(b=this.KEa);9999<b&&(""==this.AA?u.k.MJb.call(this,b):this.uC.style.zIndex=b)};u.$m=function(a,c,d,e){a=b.Ui(a,c,d,e);this.L.I0()&&a.TA(this.L.W().fUb(a));u.k.$m.call(this,
a.aa(),a.$(),a.ja(),a.la())};u.vAa=function(){var d=this;this.L.Muc(this.L.hva().BI());if(""!=this.AA||this.L.yf()){if(1==this.pha&&this.C4a(),0==this.pha){this.pha=2;b.ba().bn.Ta().G.classList.add("container");if(this.L.yf())if(this.uC.style.left="0px",this.uC.style.right="0px",this.uC.style.height="100vh",this.uC.style.display="flex",this.uC.style.alignItems="center",this.uC.style.justifyContent="center",this.uC.style.zIndex=this.KEa,null!=this.L.FU&&this.L.PM==a.oh.qma){var e=[];b.gF(this.L.FU.$a(),
e);this.G.style.position="absolute";this.G.style.left=e[0]+"px";this.G.style.top=Number(e[1])+Number(e[3])+"px"}else this.L.PM==a.oh.Vx?(this.G.style.position="absolute",this.G.style.left=this.L.ue()+"px",this.G.style.top=this.L.Se()+"px"):(this.G.style.position="",this.G.style.left="",this.G.style.top="");this.uC.setAttribute("class","md-modal "+this.AA);e=b.oe[this.L.Hb().Ta().$a()];e.G.style.opacity="";e.G.setAttribute("class","md-content vl-control vl-popup");this.uC.appendChild(this.G);document.body.insertBefore(this.uC,
b.ba().bn.Ta().G);this.L.yf()&&"absolute"==this.G.style.position&&(e=[],b.gF(this.L.$a(),e),0!=e[2]&&0!=e[3]&&(e=new c.qa(e[0],e[1],e[2],e[3]),b.Q1a(e),this.G.style.left=e.aa()+"px",this.G.style.top=e.$()+"px"));this.K5c()&&setTimeout(function(){document.documentElement.classList.add("md-perspective")},25);setTimeout(function(){d.uC.classList.add("md-show");setTimeout(function(){d.L&&d.L.mpc()},300)},100)}}else 2==this.pha&&this.C4a(),0==this.pha&&(this.pha=1,document.body.appendChild(this.G));this.BSa=
!0};u.DGa=function(){this.BSa&&(this.BSa=!1,this.uC.classList.contains("md-show")?this.kqc():this.C4a(),this.L.w6c())};u.C4a=function(){document.documentElement.classList.contains("md-perspective")&&document.documentElement.classList.remove("md-perspective");switch(this.pha){case 1:this.L.yf()?this.L.cp.removeChild(this.G):document.body.removeChild(this.G);break;case 2:document.body.removeChild(this.uC),this.uC.removeChild(this.G),b.ba().bn.Ta().G.classList.remove("container")}this.pha=0};u.kqc=function(){var a=
this;this.uC.classList.remove("md-show");setTimeout(function(){a.C4a()},500)};u.Nbe=function(){this.kqc()}},{rp:["PRIM_PHBN","PRIM_IMAG","PRIM_TBLO"]});
