window.LANSA.addSrc("gpbx",function(d,c,a,b){a.ETc={Fle:0,Ele:9,QId:6,Gle:5,Hle:10};a.B4c={WVc:0};c.Vgc=function(){p.K.call(this);this.BNb=a.ETc.QId;this.FM=a.B4c.WVc;this.MQ=new c.qa;new c.qa;this.Ed=this.Ed|a.tc.Yka|a.tc.OKa|a.tc.Jtb|a.tc.QI|a.tc.f1|a.tc.OI;this.Sc=this.Sc|a.Wd.pS|a.Wd.e1;this.Oe(!1)};var p=c.u(c.Vgc,c.xL);p.Ae=function(){return c.Xkc};p.Sfe=function(b){this.BNb!=b&&(this.BNb=b,this.m(a.g.j),this.Yy())};p.CXd=function(){return this.BNb};p.bt=function(a){p.k.bt.call(this,a);this.Fgd()};
p.AJb=function(){if(this.Xb()){var a=this.xe(),a=Math.abs(a.Na()),d=this.vf();this.Yd();this.Yd();d.Za(d.aa()+a);new c.qa;""==this.ab()?(d.Va(d.aa()),d.Ja(a)):(this.ab(),d.Va(d.aa()+this.xN()),d.Ja(this.zja()),d.Va(d.Ka()+a));b.Zk(this.MQ,d)||(this.MQ=d,this.xb());this.bt(!0)}};p.kf=function(a){a.Xa(a.$()+this.MQ.la());a.Za(a.aa()+4);a.Va(a.Ka()-4);a.Ja(a.Fa()-4);p.k.kf.call(this,a)};p.Kjd=function(a,b,c){a.Xa(a.$()+this.MQ.la());a.Za(a.aa()+4);a.Va(a.Ka()-4);a.Ja(a.Fa()-4);p.k.Kjd.call(this,a,b,
c)};p.Uk=function(){p.k.Uk.call(this);this.Cd(a.ea.AE)};p.Dd=function(){var b=this.kS()||this.pn()&&(this.v6()||this.cX());this.$M(a.tc.qS,b);p.k.Dd.call(this)};p.fJ=function(a){var b=!1,b=a.yc().o4a(this,this.ha.qh,this.v6(),this.cX(),a);!1==b&&p.k.fJ.call(this,a)};p.N1=function(a){var b=!1;null!=a.yc()&&a.ma().pn()&&(b=a.yc().p4a(this,this.ha.qh,a,this.v6(),this.cX()));!1==b&&p.k.N1.call(this,a)};p.Ne=function(b){""==b[1]&&(b[1]=a.Oac);p.k.Ne.call(this,b)};p.Fgd=function(){var a=this.vf(),a=this.BC(a,
null),c=this.vf();c.Xa(c.$()+this.MQ.la()/2+1);c.Za(c.aa()+2);c.Va(c.Ka()-2);c.Ja(c.Fa()-2);var d=this.Ta().$a(),h=this.ab();b.oe[d].fi(h,c,this.MQ);b.ga(a)};p.Gv=p[a.ea.tL]=function(a){this.AJb();p.k.Gv.call(this,a)};p.Fv=p[a.ea.RI]=function(){p.k.Fv.call(this);this.AJb()};p.wR=p[a.ea.AE]=function(){this.AJb();this.Yy()};p.jRc=p[a.ea.mub]=function(){this.ai()};d.Ld(c.Vgc,"PRIM_GPBX",{Aa:{Caption:{a:p.ab,f:function(a){this.tb(d.ka(a))}},ThemeStyle:{a:function(){return d.wa(this.dS(),a.hy.v)},f:function(b){this.HOa(d.va(b,
a.hy.v))}}}});c.Xkc=function(a){t.K.call(this,a);this.fb=this.q$a=this.TQa=this.Ke=this.jd=null};var t=c.u(c.Xkc,c.EL);t.Gd=function(a,b){var c=null;t.k.Gd.call(this,a,b);this.q$a=4;this.jd=document.createElement("div");this.Ke=document.createElement("div");this.TQa=document.createElement("div");this.fb=document.createElement("span");this.G.appendChild(this.jd);this.G.appendChild(this.Ke);this.G.appendChild(this.TQa);this.G.appendChild(this.fb);this.wrb(this.jd,this.q$a);this.wrb(this.Ke,0);this.wrb(this.TQa,
0);c=this.jd.style;c.borderTopWidth="0px";c=this.Ke.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.TQa.style;c.borderTopWidth="1px";c.borderBottomWidth="0px";c.borderLeftWidth="0px";c.borderRightWidth="0px";c=this.fb.style;c.position="absolute";c.whiteSpace="nowrap";c.cursor="inherit";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";return this.G};t.wrb=function(a,b){var c=a.style;c.position="absolute";
c.overflowX="hidden";c.overflowY="hidden";c.whiteSpace="nowrap";c.boxSizing="border-box";c.webkitBoxSizing="border-box";c.MozBoxSizing="border-box";c.borderStyle="solid";c.outline="none";c.background="rgba(0,0,0,0)";c.borderTopWidth="1px";c.borderBottomWidth="1px";c.borderLeftWidth="1px";c.borderRightWidth="1px";c.borderTopLeftRadius=b+"px";c.webkitBorderTopLeftRadius=b+"px";c.borderTopRightRadius=b+"px";c.webkitBorderTopRightRadius=b+"px";c.borderBottomLeftRadius=b+"px";c.webkitBorderBottomLeftRadius=
b+"px";c.borderBottomRightRadius=b+"px";c.webkitBorderBottomRightRadius=b+"px"};t.fi=function(a,b,c){var d=this.jd.style;d.left=b.aa()+"px";d.top=b.$()+"px";d.width=b.ja()+"px";d.height=b.la()+"px";d.borderColor=this.Rn();d=this.Ke.style;d.left=b.aa()+this.q$a-1+"px";d.top=b.$()+"px";d.width=c.aa()-b.aa()+"px";d.height="1px";d.borderColor=this.Rn();d=this.TQa.style;d.left=c.Ka()+2+"px";d.top=b.$()+"px";d.width=b.Ka()-this.q$a-c.Ka()+"px";d.height="1px";d.borderColor=this.Rn();d=this.fb.style;d.left=
c.aa()+7+"px";d.top=c.$()+2+"px";d.height=c.la()+"px";d.width=c.ja()+"px";this.fb.textContent=a}});
