window.LANSA.addSrc("msg",function(d,c,a,b,p){d.Ob("PRIM_PPNL");a.uya={hda:0,ofd:1,pfd:2,lfd:4,mfd:8};a.uya.v={NONE:a.uya.hda,TEXT:a.uya.ofd,WARNING:a.uya.pfd,ERROR:a.uya.lfd,FATAL:a.uya.mfd};a.b7={vmc:1,xmc:2,wmc:4};a.b7.v={ERROR:a.b7.vmc,QUESTION:a.b7.xmc,INFORMATION:a.b7.wmc};a.Ir={gMd:16,Dgb:1,vVa:16,sVa:32,xVa:64,uVa:128,wVa:256,tVa:512};a.Ir.v={NONE:a.Ir.Dgb,OK:a.Ir.vVa,CANCEL:a.Ir.sVa,YES:a.Ir.xVa,NO:a.Ir.uVa,RETRY:a.Ir.wVa,IGNORE:a.Ir.tVa};a.FL={Nyb:16,zmc:48,Amc:192,Bmc:224,ymc:768};a.FL.v=
{OK:a.FL.Nyb,OKCANCEL:a.FL.zmc,YESNO:a.FL.Amc,YESNOCANCEL:a.FL.Bmc,IGNORERETRY:a.FL.ymc};c.yfc=function(){t.K.call(this)};var t=c.u(c.yfc,c.td);d.Ld(c.yfc,"PRIM_MSG",{});c.wvb=function(){m.K.call(this);this.vH=[]};var m=c.u(c.wvb,c.td);m.P0c=function(){d.Ob("PRIM_PCOL");var a=new c.Adc(this);return new c.M6(a)};m.Xh=function(a,b){var d=new c.xvb(this,a);this.vH.push(d);d.vk(b);this.iVc(d);return d};m.Tk=function(a){if(a)for(var b=0;b<this.vH.length;b++){var c=this.vH[b];c.ma()==a&&(this.H1b(c),this.vH.splice(b--,
1),c.FWa())}};m.HKc=function(){for(;0<this.vH.length;){var a=this.vH.shift();this.H1b(a);a.FWa()}};m.iVc=function(b){var c=d.cc();c.kc("MESSAGE",b);this.Ga(a.Q.Ted,c);c.Jc()};m.H1b=function(b){var c=d.cc();c.kc("MESSAGE",b);this.Ga(a.Q.Ued,c);c.Jc()};d.Ld(c.wvb,"PRIM_MSGQ",{Aa:{Messages:{a:m.P0c}},jc:{Add:function(a,b){return this.Xh(d.ka(a),b===p?null:b)},Clear:function(a){return this.Tk(a===p?null:a)},ClearAll:function(){return this.HKc()}}});c.Adc=function(a){q.K.call(this);this.dTa=a};var q=c.u(c.Adc,
c.vla);q.Ac=function(){return this.dTa.vH.length};q.Sz=function(a){return this.dTa.vH[a]};c.xvb=function(a,b){s.K.call(this);this.dTa=a;this.yh=b;this.gb=null};var s=c.u(c.xvb,c.td);s.ze=function(){return this.yh};s.ma=function(){return this.gb};s.vk=function(a){this.ng()&&this.gb!=a&&(null!=this.gb&&(this.gb.SS(this),this.gb.Ha(this,this.Ev)),this.gb=a)&&(a.VQ(this),a.Ia(this,this.Ev))};s.ng=function(){return null!==this.dTa};s.FWa=function(){this.vk(null);this.yh="";this.dTa=null};s.Ev=function(b,
c){switch(c.eb){case a.g.Bb:this.vk(null)}};d.Sa(c.xvb,"PRIM_MSGQ","Message",{Aa:{Text:{a:s.ze},Control:{a:s.ma,f:s.vk}}});c.gkc=function(){h.K.call(this);this.gDa=[]};var h=c.u(c.gkc,c.td);h.R=function(){this.Ll();h.k.R.call(this)};h.ee=function(a){return this.gDa[a]};h.Ac=function(){return this.gDa.length};h.Xh=function(b){this.gDa.push(b);this.m(a.g.j)};h.Ll=function(){this.gDa=[];this.m(a.g.j)};h.A0c=function(){for(var a="",b=0;b<this.gDa.length;b++){var c=this.gDa[b];c.length>a.length&&(a=c)}return a};
d.Sa(c.gkc,"PRIM_WEB","MessageBoxCaptions",{jc:{Add:h.Xh,RemoveAll:h.Ll}});c.fkc=function(){e.K.call(this);d.Ob("PRIM_PHBN");d.Ob("PRIM_LABL");this.WTa=this.$ga=this.psa=null;this.cTa=a.b7.wmc;this.mF=a.FL.Nyb;this.Tf=a.Ir.Dgb;this.M$a=[];this.JY=null;this.Geb=new c.Nw;this.Feb=new c.CO;this.IH=new c.Zl;this.yM=d.Dc("PRIM_WEB","MessageBoxCaptions");this.yM.Ca();this.yM.Ia(this,this.OWb);this.vg=new c.Qwb;this.Ep=new c.CO;this.Dn=new c.CO;this.TQ=new c.CO;this.yU=new c.CO;this.LU=new c.CO;this.nQ=
new c.CO;this.Dn.za(this,a.Q.sc,this.oQc);this.Ep.za(this,a.Q.sc,this.kOc);this.TQ.za(this,a.Q.sc,this.mSc);this.yU.za(this,a.Q.sc,this.mQc);this.LU.za(this,a.Q.sc,this.TQc);this.nQ.za(this,a.Q.sc,this.JPc);this.IH.Oa(this);this.vg.Oa(this);this.Ep.Oa(this);this.Dn.Oa(this);this.TQ.Oa(this);this.yU.Oa(this);this.LU.Oa(this);this.nQ.Oa(this);this.$ga=new c.yb;this.WTa=new c.Xf;this.$ga.Kd(this.WTa);this.WTa.Qd(a.o.dY);this.WTa.Pg(9);this.$tc(this.$ga);this.$ga.Ca();this.WTa.Ca();this.IH.Za(90);this.IH.Oe(!1);
this.IH.Xa(57);this.IH.Ab(!0);this.IH.cM(!0);this.IH.e2(!0);this.vg.Ud(6);this.vg.AB(a.eh.Aq);this.vg.Za(20);this.vg.Xa(57);this.vg.fu(64);this.vg.UG(64);this.vg.xc(64);this.vg.pc(64);this.vg.Oe(!1);this.Dn.tb(b.Xk().ok||"OK");this.yU.tb(b.Xk().no||"No");this.TQ.tb(b.Xk().yes||"Yes");this.LU.tb(b.Xk().retry||"Retry");this.Ep.tb(b.Xk().cancel||"Cancel");this.nQ.tb(b.Xk().ignore||"Ignore");this.msc(this.mF);this.Zma(!1);this.VEb(!0)};var e=c.u(c.fkc,c.Sx);e.R=function(){this.yM.Ha(this,this.OWb);this.yM.ub();
this.yM=null;this.PVb();e.k.R.call(this)};e.yqd=function(a){this.Geb.Jb(a)};e.aXc=function(){return this.Geb.Eh()};e.bXc=function(){return this.Geb.Yk()};e.qua=function(){return this.Feb.Eh()};e.QL=function(a){this.Feb.Jb(a)};e.TWc=function(){return this.Feb.Yk()};e.Fna=function(b){b!=this.FI()&&(this.tb(b),this.u9a(),this.m(a.g.j))};e.FI=function(){return this.ab()};e.std=function(b){this.yM.Ll();b!=this.p4b()&&(this.yM.Xh(b),this.m(a.g.j))};e.dXc=function(){return this.yM};e.p4b=function(){return 0<
this.yM.Ac()?this.yM.ee(0):""};e.Bsc=function(b){this.JY!==b&&(null!=this.JY&&(this.JY.Ha(this,this.dXb),this.JY.ub()),this.JY=b,null!==this.JY&&(this.JY.Ca(),this.JY.Ia(this,this.dXb)),this.u9a(),this.m(a.g.j))};e.aYc=function(){return this.JY};e.ttd=function(b){this.cTa!=b&&(this.cTa=b,this.u9a(),this.m(a.g.j))};e.XZd=function(){return this.cTa};e.msc=function(b){this.mF=b;this.Dn.Ab(0!=(this.mF&a.Ir.vVa));this.Ep.Ab(0!=(this.mF&a.Ir.sVa));this.TQ.Ab(0!=(this.mF&a.Ir.xVa));this.yU.Ab(0!=(this.mF&
a.Ir.uVa));this.nQ.Ab(0!=(this.mF&a.Ir.tVa));this.LU.Ab(0!=(this.mF&a.Ir.wVa))};e.bUd=function(){return this.mF};e.Bge=function(a){this.Tf=a};e.S0d=function(){return this.Tf};e.kMc=function(b,d,e){var l=new c.Nw;l.Oa(this.IH);l.Za(0);l.Oe(!1);l.Xa(d);l.Qo(a.eh.Aq);l.pc(e.Ua());l.xc(e.Na());l.Ef(!1);l.tb(b);return l};e.Tuc=function(a,d){var e=b.gA(0,0),l=new c.qa(0,0,0,0);b.DG(a,l,0,d);e.pc(l.ja()+2);e.xc(l.la()+2);return e};e.Y1c=function(){if(null!=this.JY)return this.JY;var d="";switch(this.cTa){case a.b7.vmc:d=
"lansa_error.png";break;case a.b7.xmc:d="lansa_question.png";break;default:d="lansa_information.png"}var e=new c.uO;e.Tu(b.Qc(d));return e};e.AGc=function(){var a=this.Feb.Yk().ib.BI(),b=null;this.Dn.Yk().Ll();this.Ep.Yk().Ll();this.TQ.Yk().Ll();this.yU.Yk().Ll();this.LU.Yk().Ll();this.nQ.Yk().Ll();for(var c=0;null!=a&&c<a.length&&null!=(b=a[c]);c++)this.Dn.Yk().Xh(b),this.Ep.Yk().Xh(b),this.TQ.Yk().Xh(b),this.yU.Yk().Xh(b),this.LU.Yk().Xh(b),this.nQ.Yk().Xh(b);this.Dn.rk(!1,!0);this.Ep.rk(!1,!0);
this.TQ.rk(!1,!0);this.yU.rk(!1,!0);this.LU.rk(!1,!0);this.nQ.rk(!1,!0)};e.GGc=function(){var a=this.Geb.Yk().ib.BI(),b=null;this.IH.Yk().Ll();for(var c=0;null!=a&&c<a.length&&null!=(b=a[c]);c++)this.IH.Yk().Xh(b);this.IH.rk(!1,!0)};e.vAa=function(){this.psa=b.$X();this.Tf=a.Ir.Dgb;this.TUb();var c=b.Vn();this.sD(a.oh.cJ,null,c,null);this.zrd()};e.u9a=function(){this.lS()&&(this.TUb(),this.hh())};e.TUb=function(){var a;this.PVb();this.vg.Ad(this.Y1c());this.AGc();this.GGc();a=this.vSb();this.khd(a)};
e.DNa=function(){this.vSb();e.k.DNa.call(this)};e.vSb=function(){var a=this.eE(),b=this.bKc(),c=this.hKc(),c=this.gKc(c),d=this.dKc(a),e=this.cKc(b),k=this.kKc(c,d,e);this.Kld(k,b,d);this.PFc(b,c,e,k);return a};e.Kld=function(a,b,c){this.pc(a.Ua());this.xc(a.Na());a=b.Ua();b=b.Na();this.Ep.pc(a);this.Dn.pc(a);this.TQ.pc(a);this.yU.pc(a);this.LU.pc(a);this.nQ.pc(a);this.Ep.xc(b);this.Dn.xc(b);this.TQ.xc(b);this.yU.xc(b);this.LU.xc(b);this.nQ.xc(b);this.IH.pc(c.Ua());this.IH.xc(c.Na())};e.PFc=function(a,
b,c,d){this.wqd(a);a=d.Na()-c.Na();this.Ep.Xa(a);this.Dn.Xa(a);this.TQ.Xa(a);this.yU.Xa(a);this.LU.Xa(a);this.nQ.Xa(a);this.vg.Za(20);this.vg.Xa(this.Ns.Na()+20);this.IH.Za(40+b.Ua());this.IH.Xa(this.Ns.Na()+20)};e.kKc=function(a,c,d){var e=b.GE(),k=b.gA(0,0);a=this.fKc(a,c);c=this.UD.a_a(this.UD.ab(),this.UD.np().length)+10;k.pc(Math.max(a.Ua(),c,d.Ua())+60);k.xc(this.Ns.Na()+a.Na()+d.Na()+40);k.pc(Math.min(e.ja()-40,k.Ua()));k.xc(Math.min(e.la()-40,k.Na()));return k};e.Wua=function(a,b){var c=a;
b.length>a.length&&(c=b);return c};e.z0c=function(){var a="",a=this.Wua(this.Dn.ab(),a),a=this.Wua(this.Ep.ab(),a),a=this.Wua(this.TQ.ab(),a),a=this.Wua(this.yU.ab(),a),a=this.Wua(this.LU.ab(),a),a=this.Wua(this.nQ.ab(),a);return" "+a+" "};e.bKc=function(){var a=this.z0c(),c=b.gA(0,0),c=this.Dn.xe();return c=this.Tuc(a,c)};e.eE=function(){var a=this.yM.A0c(),c=b.gA(0,0),c=this.IH.xe();return c=this.Tuc(a,c)};e.hKc=function(){var a=b.gA(0,0);a.pc(this.vg.Ua());a.xc(this.vg.Na());return a};e.dKc=function(a){var c=
b.gA(0,0),d=a.Ua()+4;a=this.yM.Ac()*(a.Na()+4);d+=20;a+=20;d=170>d?170:d;a=70>a?70:a;a=630<a?630:a;c.pc(630<d?630:d);c.xc(a);return c};e.gKc=function(a){var c=b.gA(0,0);c.xc(a.Na()+16);c.pc(a.Ua()+8);return c};e.fKc=function(a,c){var d=b.gA(0,0);d.xc(Math.max(a.Na(),c.Na()));d.pc(2+a.Ua()+2+c.Ua()+2);return d};e.cKc=function(a){var c=b.gA(0,0),d=66>a.Ua()?66:a.Ua(),e=25>a.Na()?25:a.Na();a.pc(d);a.xc(e);c.xc(a.Na()+24);c.pc(3*a.Ua()+8);return c};e.wqd=function(b){b=b.Ua()+20;var c=1;this.mF&a.Ir.wVa&&
(this.LU.Za(this.Ua()-c*b),++c);this.mF&a.Ir.tVa&&(this.nQ.Za(this.Ua()-c*b),++c);this.mF&a.Ir.sVa&&(this.Ep.Za(this.Ua()-c*b),++c);this.mF&a.Ir.vVa&&(this.Dn.Za(this.Ua()-c*b),++c);this.mF&a.Ir.uVa&&(this.yU.Za(this.Ua()-c*b),++c);this.mF&a.Ir.xVa&&this.TQ.Za(this.Ua()-c*b)};e.khd=function(a){for(var b=0,c=a.Na(),d=0;d<this.yM.Ac();d++)this.M$a.push(this.kMc(this.yM.ee(d),b,a)),b+=c};e.zrd=function(){switch(this.mF){case a.FL.Nyb:case a.FL.zmc:this.Dn.Sf(!0,!0);break;case a.FL.Amc:case a.FL.Bmc:this.TQ.Sf(!0,
!0);break;case a.FL.ymc:this.nQ.Sf(!0,!0)}};e.qwa=function(a){this.Tf=a;this.Co();b.CB(this.psa);this.psa=null};e.PVb=function(){for(var a=0;a<this.M$a.length;++a)this.M$a[a].Oa(null);this.M$a=[]};e.OWb=function(){this.u9a()};e.oQc=function(){this.qwa(a.Ir.vVa)};e.kOc=function(){this.qwa(a.Ir.sVa)};e.mSc=function(){this.qwa(a.Ir.xVa)};e.mQc=function(){this.qwa(a.Ir.uVa)};e.TQc=function(){this.qwa(a.Ir.wVa)};e.JPc=function(){this.qwa(a.Ir.tVa)};e.dXb=function(b,c){switch(c.eb){case a.g.Bb:case a.g.Ub:this.Bsc(null);
break;case a.g.j:this.m(a.g.j)}};d.Sa(c.fkc,"PRIM_WEB","MessageBox",{Aa:{Title:{a:e.FI,f:function(a){this.Fna(d.ka(a))}},Caption:{a:e.p4b,f:function(a){this.std(d.ka(a))}},Text:{a:e.ze,f:function(a){this.qe(d.ka(a))}},Captions:{a:e.dXc},Image:{a:function(){return d.wa(this.cTa,a.b7.v)},f:function(b){this.ttd(d.va(b,a.b7.v))}},CustomImage:{a:e.aYc,f:function(a){this.Bsc(a)}},Result:{a:function(){return d.wa(this.Tf,a.Ir.v)}},Buttons:{a:function(){return d.wa(this.mF,a.FL.v)},f:function(b){this.msc(d.va(b,
a.FL.v))}},CaptionStyle:{a:e.aXc,f:function(a){this.yqd(a)}},CaptionStyles:{a:e.bXc},ButtonStyle:{a:e.qua,f:function(a){this.QL(a)}},ButtonStyles:{a:e.TWc}},jc:{Show:e.vAa}});c.Iwb=function(b){this.Hcb=[];this.vH=[];this.gb=b;this.Hc=new c.Sx;this.Hc.za(this,a.Q.Wx,this.uia);this.Hc.za(this,a.Q.hN,this.Jjb);this.vra=new c.Zl;this.vra.sb(new c.qa(0,0,100,25));this.vra.Oa(this.Hc);this.vra.Oe(!1);this.vra.Qb(a.ebc)};var k=c.u(c.Iwb,c.Bm);k.zw=function(){return this.Hc};k.bh=function(){return 0==this.vH.length};
k.VQ=function(a){this.vH.push(a)};k.SS=function(a){this.vH.splice(this.vH.indexOf(a),1);this.bh()&&this.Hc.Co()};k.uia=function(){d.Ob("PRIM_LABL");for(var b=0,e=6,k=100;b<this.vH.length;b++){var l=this.Hcb[b],h=this.vH[b];l||(l=new c.Nw,l.Za(5),l.Oe(!1),l.Xa(e),l.Qo(a.eh.Aq),l.pc(320),l.xc(20),l.Ef(!1),this.Hcb.push(l));l.Oa(this.vra);l.tb(h.ze());l.AKc();k<l.Ua()+15&&(k=l.Ua()+15);e+=25}for(;b<this.Hcb.length;b++)l=this.Hcb[b],l.Oa(null);this.vra.xc(e+6);this.vra.pc(k);this.Hc.xc(e+6);this.Hc.pc(k)};
k.Jjb=function(){this.gb.rk(!0)}},{rp:["PRIM_PPNL"]});
