window.LANSA.addSrc("wdgt",function(d,c,a,b,p){var t={};c.Plc=function(a){m.K.call(this);this.gSa=a;this.qab=function(){};this.nU=this.POb=!1;this.pPb=[];this.oPb=[];this.kPb=[];this.jPb=[];this.mPb=[]};var m=c.u(c.Plc,c.jf);m.$W=function(){return this.POb};m.uh=function(){return this.gSa.nm};m.r2c=function(){return this.gSa.js||[]};m.f3c=function(){return this.gSa.st||[]};m.EYc=function(){return this.gSa.fn};m.zZc=function(){return this.gSa.fe};m.m5=function(){return this.qab};m.dkd=function(){function a(){if(m<
p.length){var c=p[m],e=document.createElement("script");e.type="text/javascript";e.onload=function(){e.onload=null;e.onerror=null;m++;a()};e.onerror=function(){e.onload=null;e.onerror=null;throw"Error defining Widget "+d+", failed to load script: "+c;};document.body.appendChild(e);e.src=c}else b()}function b(){function a(){if(!c.POb){for(c.POb=!0;0<c.jPb.length;){var b=c.jPb.shift();c.Mrb(b)}for(;0<c.oPb.length;)b=c.oPb.shift(),c.Orb(b.gLb,b.yKd,b.value);for(;0<c.mPb.length;)b=c.mPb.shift(),c.C8b(b.gLb,
b.parent);for(;0<c.pPb.length;)b=c.pPb.shift(),c.Prb(b);for(;0<c.kPb.length;)b=c.kPb.shift(),c.Nrb(b)}}var d=c.EYc(),f=c.qab.prototype;e&&e(f);var l={Loading:{},Completed:{},Finalize:function(){a()}};d(f,l)!==l.Loading&&a()}var c=this,d=c.uh(),e=c.zZc();t[d]=c;for(var f=c.f3c(),l=0;l<f.length;l++){var k=f[l],h=document.createElement("link");h.type="text/css";h.rel="stylesheet";h.href=k;document.body.appendChild(h)}var m=0,p=c.r2c();a()};m.Orb=function(a,b,c){if(this.$W()){var e=a["set"+b];if(!e)throw d.Tkd("set"+
b);e&&e.call(a,c)}else this.oPb.push({gLb:a,yKd:b,value:c})};m.Nrb=function(a){this.$W()?a.QXa():this.kPb.push(a)};m.Mrb=function(a){if(this.$W()){var b=a.onCreateInstance;b&&b.call(a)}else this.jPb.push(a)};m.C8b=function(a,b){if(this.$W()){var c=a.onRealizeControl;if(!c)throw d.Skd();c.call(a,b)}else this.mPb.push({gLb:a,parent:b})};m.Prb=function(a){if(this.$W()){var b=a.onSizeChanged;b&&b.call(a)}else this.pPb.push(a)};c.k2a=function(){q.K.call(this)};var q=c.u(c.k2a,c.Zl);q.Sc|=a.Wd.LKa;q.Oz=
function(){return this.Ta()&&this.Ta().V5c()?this:null};q[a.ea.Zy]=function(b){var c=!1;this.Ta()&&(c=b.$c!==p?b.$c:a.fa.dP,c=c==a.fa.dP||c==a.fa.jA||c==a.fa.RE?this.Ta().P1b(null):this.Ta().Q1b(null));c||q.k.uR.call(this,b)};q[a.ea.ZKa]=function(b){var c=!1;this.Ta()&&(c=(b.$c!==p?b.$c:a.fa.dP)==a.fa.dP?this.Ta().P1b(document.activeElement):this.Ta().Q1b(document.activeElement));c||q.k.Njb.call(this,b)};c.pkc=function(){s.K.call(this)};var s=c.u(c.pkc,c.td);d.Ld(c.pkc,"PRIM_WDGT",{});c.rkc=function(){h.K.call(this);
var a=this.CYa(),a=this.e_=t[a],b=this.IM=new (a.m5());b.LANSA_Component=this;b.LANSA_Class=a;a.Mrb(b)};var h=c.u(c.rkc,c.td);h.Lrb=function(a,b){if(this.e_.$W()){var c=this.IM[a];if(!c)throw d.uqc(a);return c.apply(this.IM,b)}throw d.D4a();};h.iJa=function(a){if(this.e_.$W()){var b=this.IM["get"+a];if(!b)throw d.sqc("get"+a);return b.call(this.IM)}throw d.D4a();};h.sOa=function(a,b){this.e_.Orb(this.IM,a,b)};h.T0=function(){var a=this;setTimeout(function(){a.e_.Nrb(a)},5)};h.QXa=function(){this.Ga(a.Q.rca)};
d.Sa(c.rkc,"PRIM_WDGT","Object",{});var e=h;e.get=e.iJa;e.set=e.sOa;e.invoke=e.Lrb;c.qkc=function(){k.K.call(this);var b=this.CYa(),b=this.e_=t[b],c=this.IM=new (b.m5());c.LANSA_Component=this;c.LANSA_Class=b;b.Mrb(c);this.Sc&=~a.Wd.pS;this.Sc&=~a.Wd.e1};var k=c.u(c.qkc,c.k2a);k.Ae=function(){return c.Olc};k.Kc=function(a,c,d){k.k.Kc.call(this,a,c,d);a=this.Ta().$a();b.oe[a].Ucd(this.IM)};k.Lrb=function(a,b){if(this.e_.$W()){var c=this.IM[a];if(!c)throw d.uqc(a);return c.apply(this.IM,b)}throw d.D4a();
};k.iJa=function(a){if(this.e_.$W()){var b=this.IM["get"+a];if(!b)throw d.sqc("get"+a);return b.call(this.IM)}throw d.D4a();};k.sOa=function(a,b){this.e_.Orb(this.IM,a,b)};k.Y$d=function(){this.QXa()};k[a.ea.dla]=function(){this.e_.Nrb(this)};k[a.ea.RI]=function(){this.Xb()&&this.e_.Prb(this.IM)};k.Ima=function(){k.k.Ima.call(this);this.Xb()&&this.e_.Prb(this.IM)};d.Sa(c.qkc,"PRIM_WDGT","Control",{});e=k;e.get=e.iJa;e.set=e.sOa;e.invoke=e.Lrb;c.bkc=function(){f.K.call(this);this.Nb=b.Mf(0,0,100,100);
this.Y9=this.uSa=""};var f=c.u(c.bkc,c.k2a);f.Ae=function(){return c.Ykc};f.q_c=function(){return this.uSa};f.Csd=function(b){this.uSa!=b&&(this.uSa=b,this.pa(a.g.j),this.Hd())};f.JC=function(){return this.Y9};f.hna=function(a){this.Y9=a};f.dD=function(a){var d=this.Lo(),e=this.pq();if(d||e){var f=new c.qa;new c.qa(0,0,1E4,1E4);var l=[];l[0]=d;l[1]=e;l[2]=a;l[3]=0;l[4]=0;var k=this.$a();l[3]=0;l[4]=0;null!=k&&b.oe[k].Bzc(l);f.Va(l[3]);f.Ja(l[4]);d&&a.Va(a.aa()+this.ha.Li()+f.ja()+this.ha.Gj());e&&
a.Ja(a.$()+this.ha.Uj()+f.la()+this.ha.jl())}};d.Sa(c.bkc,"PRIM_WEB","HtmlContainer",{Aa:{Html:{a:f.q_c,f:function(a){this.Csd(d.ka(a))}},Description:{a:f.JC,f:function(a){this.hna(d.ka(a))}}},Te:{Qe:"Html"}});c.y2a=function(a){u.K.call(this,a)};var u=c.u(c.y2a,c.lo);u.VJa=function(){return!1};u.V5c=function(){return 0<this.Qhb().length};u.LS=function(a){u.k.LS.call(this,a);return!1};u.P1b=function(a){var b=this.Qhb();for(a=a?b.indexOf(a)+1:0;0<=a&&a<b.length;){var c=b[a];if(c&&(c.focus(),c==document.activeElement))return!0;
a++}return!1};u.Q1b=function(a){var b=this.Qhb();for(a=a?b.indexOf(a)-1:b.length-1;0<=a;){var c=b[a];if(c&&(c.focus(),c==document.activeElement))return!0;a--}return!1};u.Qhb=function(){var a=[],b=[];this.uoc(this.G,b);for(var c=1;c<b.length;c++)a=a.concat(b[c]||[]);return a=a.concat(b[0]||[])};u.uoc=function(a,b){var c=a.tabIndex;0<=c&&(b[c]===p&&(b[c]=[]),b[c].push(a));for(var c=a.childNodes,d=0;d<c.length;d++)a=c[d],this.uoc(a,b)};u.Yaa=u[a.Ra.IT]=function(b){b.Tf=a.Ra.fia|a.Ra.nWa};c.Olc=function(a){A.K.call(this,
a);this.gb=null};var A=c.u(c.Olc,c.y2a);A.Gd=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.hc);this.G.setAttribute("LANSAHandle",this.hc);return A.k.Gd.call(this,a,b)};A.Ucd=function(a){null==this.gb&&(this.gb=document.createElement("div"),this.gb.style.left="0px",this.gb.style.top="0px",this.gb.style.width="100%",this.gb.style.height="100%",a.LANSA_Class.C8b(a,this.gb),this.G.appendChild(this.gb))};c.Ykc=function(a){l.K.call(this,a);this.gb=null};var l=c.u(c.Ykc,
c.y2a);l.Gz=function(){l.k.Gz.call(this);this.G.style.whiteSpace="normal"};l.Gd=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.hc);this.G.setAttribute("LANSAHandle",this.hc);this.gb=document.createElement("div");this.gb.style.left="0px";this.gb.style.top="0px";this.gb.style.width="100%";this.gb.style.height="100%";this.gb.innerHTML=this.L.uSa;this.G.appendChild(this.gb);return l.k.Gd.call(this,a,b)};l.kGd=function(){var a=this.L.Lo(),b=this.L.pq();this.gb.style.width=
a?"":"100%";this.gb.style.height=b?"":"100%";this.gb.innerHTML=this.L.uSa};l.Kc=function(){l.k.Kc.call(this);this.kGd()};l.Bzc=function(a){var b=a[0],c=a[2],d=this.gb.style.width;a[1]&&!b&&(this.gb.style.width=c.ja()+"px");a[3]=this.gb.clientWidth;a[4]=this.gb.clientHeight;this.gb.style.width=d}});
