window.LANSA.addSrc("web",function(d,c,a,b,p){d.Ob("PRIM_LABL");var t=localStorage,m=sessionStorage;a.dP={ICb:0,Krc:1,Lrc:2,Jrc:3};a.dP.v={INLINE:a.dP.ICb,LEFT:a.dP.Krc,RIGHT:a.dP.Lrc,CENTER:a.dP.Jrc};a.VI={EXa:0,m0b:1,q0b:2,r0b:3,t0b:4,jlb:5};a.VI.v={NONE:a.VI.EXa,NOTLOADED:a.VI.m0b,PERMISSIONDENIED:a.VI.q0b,POSITIONUNAVAILABLE:a.VI.r0b,TIMEOUT:a.VI.t0b,UNKNOWNERROR:a.VI.jlb};a.E_={kUb:0,iUb:1,lUb:2,jUb:4};a.E_.v={NONE:a.E_.kUb,ERROR:a.E_.iUb,WARNING:a.E_.lUb,INFORMATION:a.E_.jUb};c.ayb=function(){q.K.call(this);
this.jb=[]};var q=c.u(c.ayb,c.qd);q.R=function(){q.k.R.call(this)};q.Cc=function(){return this.jb.length};q.he=function(a){return this.jb[a-1]};q.Jx=function(a){for(var c=null,d=0;d<this.jb.length;d++){var e=this.jb[d];if(b.Sx(e.yo,a)){c=e;break}}return c};d.Sa(c.ayb,"PRIM_WEB","URLParameters",{Aa:{Item:{a:function(a){return this.Jx(d.ka(a))},Dx:"na"},ItemCount:{a:q.Cc}},Ue:{Re:"Item"},Yq:{rq:function(a){return this.he(d.O(a))},Kw:q.Cc}});b.Red=function(a,b,d){a.jb.push(new c.$xb(b,d))};c.$xb=function(a,
b){s.K.call(this);this.yo=a;this.cb=b};var s=c.u(c.$xb,c.qd);s.wh=function(){return this.yo.toUpperCase()};s.kb=function(){return this.cb};d.Sa(c.$xb,"PRIM_WEB","URLParameter",{Aa:{Name:{a:s.wh},Value:{a:s.kb}}});c.Vxb=function(){h.K.call(this);this.Kp=null;this.L9=p};var h=c.u(c.Vxb,c.qd);h.R=function(){h.k.R.call(this)};h.rua=function(){if(this.L9===p&&(this.L9=!1,t))try{var a,c=b.Fg().K5b();t.setItem(c,c);a=t.getItem(c)==c;t.removeItem(c);a&&(this.L9=!0)}catch(d){}return this.L9};h.Cc=function(){return this.tW().length};
h.he=function(a){return this.tW()[a-1]};h.Jx=function(a){for(var b=null,c=this.tW(),d=0;d<c.length;d++){var e=c[d];if(e.yo==a){b=e;break}}return b};h.tW=function(){if(null==this.Kp&&(this.Kp=[],t))for(var a=0;a<t.length;a++){var b=t.key(a);""!=b&&t[b]!=p&&this.Kp.push(new c.w2a(b))}return this.Kp};h.FNa=function(){this.Kp=null};h.Zh=function(a,b){var d=this.tW(),e=this.Jx(a);null==e&&(e=new c.w2a(a),d.push(e));e.ob(b)||d.splice(d.indexOf(e),1)};h.bt=function(c){var d=this.tW(),e=this.Jx(c);null!=
e&&(t.removeItem(c),d.splice(d.indexOf(e),1),b.Fg().Yia(a.zJ.CAa))};h.Uk=function(){t&&(t.clear(),this.FNa(),b.Fg().Yia(a.zJ.CAa))};d.Sa(c.Vxb,"PRIM_WEB","LocalStorage",{Aa:{Available:{a:h.rua},Item:{a:function(a){return this.Jx(d.ka(a))},Dx:"na"},ItemCount:{a:h.Cc}},jc:{Add:h.Zh,Remove:h.bt,Clear:h.Uk},Ue:{Re:"Item"},Yq:{rq:function(a){return this.he(d.O(a))},Kw:h.Cc}});c.w2a=function(a){e.K.call(this);this.yo=a};var e=c.u(c.w2a,c.qd);e.wh=function(){return this.yo};e.kb=function(){var a="";t&&(a=
t[this.yo],a===p&&(a=""));return a};e.ob=function(c){var d=!0;try{t[this.yo]=c,b.Fg().Yia(a.zJ.CAa)}catch(e){b.Fg().a2b(a.zJ.CAa),d=!1}return d};d.Sa(c.w2a,"PRIM_WEB","LocalStorageItem",{Aa:{Name:{a:e.wh},Value:{a:e.kb,f:function(a){this.ob(d.ka(a))}}},Ue:{Re:"Value"}});c.Zxb=function(){k.K.call(this);this.Kp=null;this.L9=p};var k=c.u(c.Zxb,c.qd);k.R=function(){k.k.R.call(this)};k.rua=function(){if(this.L9===p&&(this.L9=!1,m))try{var a,c=b.Fg().K5b();m.setItem(c,c);a=m.getItem(c)==c;m.removeItem(c);
a&&(this.L9=!0)}catch(d){}return this.L9};k.Cc=function(){return this.tW().length};k.he=function(a){return this.tW()[a-1]};k.Jx=function(a){for(var b=null,c=this.tW(),d=0;d<c.length;d++){var e=c[d];if(e.yo==a){b=e;break}}return b};k.tW=function(){if(null==this.Kp&&(this.Kp=[],m))for(var a=0;a<m.length;a++){var b=m.key(a);""!=b&&m[b]!=p&&this.Kp.push(new c.A2a(b))}return this.Kp};k.FNa=function(){this.Kp=null};k.Zh=function(a,b){var d=this.tW(),e=this.Jx(a);null==e&&(e=new c.A2a(a),d.push(e));return e.ob(b)?
!0:(d.splice(d.indexOf(e),1),!1)};k.bt=function(c){var d=this.tW(),e=this.Jx(c);null!=e&&(m.removeItem(c),d.splice(d.indexOf(e),1),b.Fg().Yia(a.zJ.DAa))};k.Uk=function(){m&&(m.clear(),this.FNa(),b.Fg().Yia(a.zJ.DAa))};d.Sa(c.Zxb,"PRIM_WEB","SessionStorage",{Aa:{Available:{a:k.rua},Item:{a:function(a){return this.Jx(d.ka(a))},Dx:"na"},ItemCount:{a:k.Cc}},jc:{Add:k.Zh,Remove:k.bt,Clear:k.Uk},Ue:{Re:"Item"},Yq:{rq:function(a){return this.he(d.O(a))},Kw:k.Cc}});c.A2a=function(a){f.K.call(this);this.yo=
a};var f=c.u(c.A2a,c.qd);f.wh=function(){return this.yo};f.kb=function(){var a="";m&&(a=m[this.yo],a===p&&(a=""));return a};f.ob=function(c){var d=!0;try{m[this.yo]=c,b.Fg().Yia(a.zJ.DAa)}catch(e){b.Fg().a2b(a.zJ.DAa),d=!1}return d};d.Sa(c.A2a,"PRIM_WEB","SessionStorageItem",{Aa:{Name:{a:f.wh},Value:{a:f.kb,f:function(a){this.ob(d.ka(a))}}},Ue:{Re:"Value"}});c.Uxb=function(){u.K.call(this)};var u=c.u(c.Uxb,c.qd);u.R=function(){u.k.R.call(this)};u.V4c=function(a){0<a&&window.history.go(0-a)};u.W4c=
function(a){0<a&&window.history.go(a)};u.Zh=function(a,c){var d=window.location.protocol+"//"+window.location.host+window.location.pathname;0<a.length&&(d+="?"+a);window.history.pushState(null,"",d);b.Fg().oCb();c&&b.Fg().XXa()};u.$Bb=function(a,c){var d=window.location.protocol+"//"+window.location.host+window.location.pathname;0<a.length&&(d+="?"+a);window.history.replaceState(null,"",d);b.Fg().oCb();c&&b.Fg().XXa()};d.Sa(c.Uxb,"PRIM_WEB","History",{jc:{Add:function(a,b){this.Zh(d.ka(a),b===p?!0:
d.Ca(b))},Replace:function(a,b){this.$Bb(d.ka(a),b===p?!0:d.Ca(b))},GoBack:function(a){this.V4c(a===p?1:d.O(a))},GoForward:function(a){this.W4c(a===p?1:d.O(a))}}});a.Rw={ozc:0,nzc:1,S8b:2,R8b:3,Z9a:4,ySb:5,Mfb:6,oqc:7,rqc:8};a.Rw.v={UNSUPPORTED:a.Rw.ozc,UNREGISTERED:a.Rw.nzc,INSTALLING:a.Rw.S8b,INSTALLED:a.Rw.R8b,WAITING:a.Rw.Z9a,ACTIVATING:a.Rw.ySb,ACTIVATED:a.Rw.Mfb,READY:a.Rw.oqc,REDUNDANT:a.Rw.rqc};c.ykc=function(){A.K.call(this);this.bUa=this.Qdb=this.Rdb=!0;this.NQ=navigator.serviceWorker?a.Rw.nzc:
a.Rw.ozc};var A=c.u(c.ykc,c.qd);A.R=function(){A.k.R.call(this)};A.r2c=function(){return this.Rdb};A.Qud=function(b){this.Rdb!=b&&(this.Rdb=b,this.m(a.g.j))};A.q2c=function(){return this.Qdb};A.Pud=function(b){this.Qdb!=b&&(this.Qdb=b,this.m(a.g.j))};A.m3c=function(){return this.bUa};A.vvd=function(b){this.bUa!=b&&(this.bUa=b,this.m(a.g.j))};A.C3c=function(){return this.NQ};A.h8=function(c){this.NQ!=c&&(this.NQ=c,this.m(a.g.j),b.Fg().PVc())};A.jxd=function(){this.NQ===a.Rw.Z9a&&navigator.serviceWorker.getRegistration(b.l5()).then(function(a){a&&
a.waiting&&a.waiting.postMessage("SKIP_WAITING")})};d.Sa(c.ykc,"PRIM_WEB","ServiceWorker",{Aa:{ReloadFirstTime:{a:A.r2c,f:function(a){this.Qud(a)}},ReloadAfterUpgrade:{a:A.q2c,f:function(a){this.Pud(a)}},SkipWaitingAfterUpgrade:{a:A.m3c,f:function(a){this.vvd(a)}},Status:{a:function(){return d.va(this.NQ,a.Rw.v)}}},jc:{SkipWaiting:A.jxd}});c.Xjc=function(){l.K.call(this);this.Nb=b.Nf(0,0,400,400);this.f$=this.Ye="";this.Tc&=~a.Xd.uS;this.Tc&=~a.Xd.j1};var l=c.u(c.Xjc,c.$l);l.Be=function(){return c.Kkc};
l.iB=function(){return this.Ye};l.yl=function(b){this.Ye!=b&&(this.Ye=b,this.pa(a.g.j))};l.LC=function(){return this.f$};l.nna=function(a){this.f$=a};l.Lc=function(a,c,d){l.k.Lc.call(this,a,c,d);a=this.Ta().$a();b.pe[a].yl(this.Ye)};l.CVc=function(){this.Ga(a.Q.Zbc)};d.Sa(c.Xjc,"PRIM_WEB","Page",{Aa:{Source:{a:l.iB,f:function(a){this.yl(d.ka(a))}},Description:{a:l.LC,f:function(a){this.nna(d.ka(a))}}}});c.jya=function(){r.K.call(this)};var r=c.u(c.jya,c.$l);r.bpb=function(){for(var a=null,b=this;b;){if(b instanceof
c.hyb){a=b;break}b=b.gc}return a};r.u7=function(){r.k.u7.call(this);var a=this.bpb();a&&a.g5(this)};r.BX=function(){r.k.BX.call(this);var a=this.bpb();a&&a.h5(this)};r.hf=function(a){r.k.hf.call(this,a);var b=this.bpb();b==this&&b.pE(a,!1)};d.Sa(c.jya,"PRIM_WEB","RichTextItem",{});c.lyb=function(){E.K.call(this)};var E=c.u(c.lyb,c.jya);E.Be=function(){return c.Tlc};d.Sa(c.lyb,"PRIM_WEB","RichTextLine",{});c.iyb=function(){D.K.call(this)};var D=c.u(c.iyb,c.jya);D.Be=function(){return c.Rlc};d.Sa(c.iyb,
"PRIM_WEB","RichTextBreak",{});c.jyb=function(){x.K.call(this);this.T3=null;this.QTa=a.dP.ICb;this.Sdb=this.Tdb=0};var x=c.u(c.jyb,c.jya);x.R=function(){x.k.R.call(this);this.z6a(null)};x.Be=function(){return c.Slc};x.G2c=function(){return this.T3};x.z6a=function(b){this.T3!=b&&(null!=this.T3&&(this.T3.Ha(this,this.GYb),this.T3.ub()),this.T3=b,null!=this.T3&&(this.T3.Ba(),this.T3.Ia(this,this.GYb)),this.pa(a.g.j))};x.A1d=function(){return this.QTa};x.cuc=function(b){this.QTa!=b&&(this.QTa=b,this.pa(a.g.j))};
x.H2c=function(){return this.Tdb};x.euc=function(b){this.Tdb!=b&&(this.Tdb=b,this.pa(a.g.j))};x.F2c=function(){return this.Sdb};x.duc=function(b){this.Sdb!=b&&(this.Sdb=b,this.pa(a.g.j))};x.Lc=function(a,c,d){x.k.Lc.call(this,a,c,d);a=this.Ta().$a();b.pe[a].hi(this.QTa,this.Tdb,this.Sdb)};x.ZBb=function(){var a=this.T3,c=this.Ta().$a(),a=a?a.Ng():"";b.pe[c].Bd(a)};x.GYb=function(b,c){switch(c.eb){case a.g.Bb:case a.g.Ub:this.z6a(null);break;case a.g.j:this.pa(a.g.j)}};d.Sa(c.jyb,"PRIM_WEB","RichTextImage",
{Aa:{Image:{a:x.G2c,f:function(a){this.z6a(a)}},Width:{a:x.H2c,f:function(a){this.euc(d.O(a))}},Height:{a:x.F2c,f:function(a){this.duc(d.O(a))}},Alignment:{a:function(){return d.va(this.QTa,a.dP.v)},f:function(b){this.cuc(d.wa(b,a.dP.v))}}}});c.B2a=function(){K.K.call(this);this.FA=null};var K=c.u(c.B2a,c.jya);K.Be=function(){return c.Ulc};K.Uy=function(){null==this.FA&&(this.FA=new c.kyb(this));return this.FA};d.Sa(c.B2a,"PRIM_WEB","RichTextParagraph",{Aa:{Items:{a:K.Uy}}});c.hyb=function(){J.K.call(this);
this.Nb=b.Nf(0,0,100,100)};var J=c.u(c.hyb,c.B2a);J.Be=function(){return c.Qlc};J.g5=function(b){if(!this.Pd()){var c=d.cc();c.kc("ITEM",b);this.Ga(a.Q.rO,c);c.Kc()}};J.h5=function(b){if(!this.Pd()){var c=d.cc();c.kc("ITEM",b);this.Ga(a.Q.tO,c);c.Kc()}};J.kba=function(b){if(!this.Pd()){var c=d.cc();c.kc("ITEM",b);this.Ga(a.Q.sO,c);c.Kc()}};J.pE=function(b,c){if(!c&&!this.Pd()){var e=d.cc();e.kc("ITEM",b);e.mg("CONTINUE",!0);this.Ga(a.Q.qO,e);c=!e.ah("CONTINUE");e.Kc()}return c};d.Sa(c.hyb,"PRIM_WEB",
"RichText",{});c.kyb=function(a){C.K.call(this);this.jb=[];this.ZD=a};var C=c.u(c.kyb,c.qd);C.R=function(){C.k.R.call(this)};C.Cc=function(){return this.jb.length};C.he=function(a){return this.jb[a-1]};C.Zh=function(b,d,e,f){var l=new c.lyb;l.Ba();l.tb(b);d!=p&&l.Jb(d);e!=p&&l.Bp(e);f!=p&&l.lr(f);l.Oa(this.ZD);this.jb[this.jb.length]=l;this.ZD.pa(a.g.j);this.ZD.Xb()&&this.ZD.jh();return l};C.JFc=function(){var b=new c.iyb;b.Ba();b.Oa(this.ZD);this.jb[this.jb.length]=b;this.ZD.pa(a.g.j);this.ZD.Xb()&&
this.ZD.jh();return b};C.TFc=function(b,d,e,f,l,k,h){var m=new c.jyb;m.Ba();m.z6a(b);d!=p&&m.cuc(d);e!=p&&m.euc(e);f!=p&&m.duc(f);l!=p&&m.Jb(l);k!=p&&m.Bp(k);h!=p&&m.lr(h);m.Oa(this.ZD);this.jb[this.jb.length]=m;this.ZD.pa(a.g.j);this.ZD.Xb()&&this.ZD.jh();return m};C.YFc=function(b,d,e,f){var l=new c.B2a;l.Ba();b!=p&&l.tb(b);d!=p&&l.Jb(d);e!=p&&l.Bp(e);f!=p&&l.lr(f);l.Oa(this.ZD);this.jb[this.jb.length]=l;this.ZD.pa(a.g.j);this.ZD.Xb()&&this.ZD.jh();return l};C.bt=function(b){this.jb.splice(this.jb.indexOf(b),
1);b.Oa(null);b.ub();this.ZD.pa(a.g.j)};C.Ml=function(){for(;0<this.jb.length;)this.bt(this.jb[0]);this.ZD.pa(a.g.j)};d.Sa(c.kyb,"PRIM_WEB","RichTextItems",{Aa:{Item:{a:function(a){return this.he(d.O(a))},Dx:"na"},ItemCount:{a:C.Cc}},jc:{Add:C.Zh,AddBreak:C.JFc,AddImage:function(b,c,e,f,l,k,h){return this.TFc(b,d.wa(c,a.dP.v),e,f,l,k,h)},AddParagraph:C.YFc,Remove:C.bt,RemoveAll:C.Ml},Ue:{Re:"Item"},Yq:{rq:function(a){return this.he(d.O(a))},Kw:C.Cc}});c.ekc=function(){M.K.call(this);this.Nb=b.Nf(0,
0,100,100)};var M=c.u(c.ekc,c.$l);M.Be=function(){return c.dlc};M.Lc=function(a,b,c){M.k.Lc.call(this,a,b,c)};M.hg=function(a){this.RG();a&&this.bNa();b.qb().SF(this)};M.PG=function(){this.ha.q4()};d.Sa(c.ekc,"PRIM_WEB","Camera",{});c.Fkc=function(){ca.K.call(this);this.Nb=b.Nf(0,0,100,100);this.IJ=null;this.cWa("")};var ca=c.u(c.Fkc,c.$l);ca.R=function(){this.IJ=null;ca.k.R.call(this)};ca.Be=function(){return c.Vlc};ca.nIa=function(){this.Ta()&&this.cWa(this.Ta().dXc());return this.IJ};ca.cWa=function(a){this.IJ=
new c.WI({data:a,mimetype:"image/png",filename:"signature.png"})};ca.Uk=function(){if(this.Ta()){var a=this.Ta().$a();b.pe[a].Uk();this.Ee()}};ca.Lc=function(a,b,c){ca.k.Lc.call(this,a,b,c)};ca.hg=function(a){this.RG();a&&this.bNa();b.qb().SF(this)};ca.PG=function(){this.ha.q4()};ca.Ee=function(){this.Ga(a.Q.Dh)};d.Sa(c.Fkc,"PRIM_WEB","Signature",{Aa:{Blob:{a:ca.nIa}},jc:{Clear:ca.Uk}});c.qkc=function(){G.K.call(this);this.wQb=this.sOb=this.GLb=this.FLb=this.yLb=this.Pcb=this.dPb=0;this.kga=a.VI.m0b};
var G=c.u(c.qkc,c.qd);G.Y0c=function(){return this.dPb};G.k0c=function(){return this.Pcb};G.tWc=function(){return this.yLb};G.JWc=function(){return this.FLb};G.KWc=function(){return this.GLb};G.y_c=function(){return this.sOb};G.r3c=function(){return this.wQb};G.sYd=function(){return this.kga};G.skd=function(){var b=this;navigator.geolocation&&navigator.geolocation.getCurrentPosition(function(d){b.dPb=d.coords.longitude;b.Pcb=d.coords.latitude;b.yLb=d.coords.accuracy;b.FLb=d.coords.altitude?d.coords.altitude:
0;b.GLb=d.coords.altitudeAccuracy?d.coords.altitudeAccuracy:0;b.sOb=d.coords.heading?d.coords.heading:0;b.wQb=d.coords.speed?d.coords.speed:0;b.kga=a.VI.EXa;b.Ga(a.Q.sqc,new c.Hxa)},function(d){b.dPb=0;b.Pcb=0;b.yLb=0;b.FLb=0;b.GLb=0;b.sOb=0;b.wQb=0;b.kga=a.VI.jlb;switch(d.code){case d.PERMISSION_DENIED:b.kga=a.VI.q0b;break;case d.POSITION_UNAVAILABLE:b.kga=a.VI.r0b;break;case d.TIMEOUT:b.kga=a.VI.t0b;break;case d.UNKNOWN_ERROR:b.kga=a.VI.jlb}b.Ga(a.Q.sqc,new c.Hxa)});return this.Pcb};d.Sa(c.qkc,
"PRIM_WEB","Geolocation",{Aa:{Longitude:{a:G.Y0c},Latitude:{a:G.k0c},Accuracy:{a:G.tWc},Altitude:{a:G.JWc},AltitudeAccuracy:{a:G.KWc},Heading:{a:G.y_c},Speed:{a:G.r3c},ErrorCode:{a:function(){return d.va(this.kga,a.VI.v)}}},jc:{Refresh:G.skd}});c.mkc=function(){z.K.call(this)};var z=c.u(c.mkc,c.qd);z.Gdd=function(b,c){if("undefined"!==typeof console)switch(c){case a.E_.iUb:console.error(b);break;case a.E_.lUb:console.warn(b);break;case a.E_.jUb:console.info(b);break;default:console.log(b)}};d.Sa(c.mkc,
"PRIM_WEB","Console",{Aa:{},jc:{Log:function(b,c){return this.Gdd(d.ka(b),c?d.wa(c,a.E_.v):a.E_.kUb)}}});c.pkc=function(){V.K.call(this);this.xc=this.pb=null;this.HM=this.xr="";this.lra=!1};var V=c.u(c.pkc,c.Ow);V.R=function(){V.k.R.call(this);this.Aq(null)};V.Be=function(){return c.mlc};V.Ng=function(){return this.xr};V.Qnb=function(){return this.HM};V.Jh=function(b){this.pb!=b&&(this.Aq(b),this.m(a.g.j))};V.rb=function(){var a=null;return a=this.pb};V.nc=function(){return this.xc};V.cka=function(){return this.lra};
V.k6a=function(b){this.lra!=b&&(this.lra=b,this.pa(a.g.j))};V.Ee=function(){this.Ga(a.Q.Dh)};V.cua=function(b,c){var e=d.cc();e.kc("FILE",b);e.kc("FILES",c);this.Ga(a.Q.Qlb,e);e.Kc()};V.$Q=function(){this.OY=b.bya(this.xc.pk());this.pb.T_(this.nc())};V.Aq=function(a){var c=null;a&&(c=a.Kz(),this.pb==a?c.Kn(this.xc):a.EC(c));this.pb&&(this.pb.Ha(this),this.xc.Ha(this),b.ga(this.xc),this.xc=null);if(this.pb=a)this.pb.Ia(this,this.Qp),this.xc=c,this.xc.Ia(this,this.Py);this.ci()};V.NGd=function(){};
V.Qp=function(b,c){c.eb==a.g.j?c.xu==a.Ke.fA?this.pb.EC(this.nc()):this.Aq(this.pb):c.eb==a.g.Bb&&this.Jh(null)};V.Py=function(b,c){c.eb==a.g.j&&c.xu==a.Ke.fA&&this.$Q()};d.Sa(c.pkc,"PRIM_WEB","FilePicker",{Aa:{MultiSelect:{a:V.cka,f:function(a){this.k6a(d.Ca(a))}}}});c.lMa=function(a){y.K.call(this);this.Kcb=a;this.DU=this.IJ=null};var y=c.u(c.lMa,c.qd);y.R=function(){null!=this.IJ&&(this.IJ=null);null!=this.DU&&(b.bWb(this.DU),this.DU=null);y.k.R.call(this)};y.wh=function(){return this.Kcb.name};
y.nIa=function(){null==this.IJ&&(this.IJ=new c.Ffc(this.Kcb));return this.IJ};y.npb=function(){return this.Kcb.size};y.n1c=function(){return this.Kcb.type};d.Sa(c.lMa,"PRIM_WEB","File",{Aa:{Name:{a:y.wh},Blob:{a:y.nIa},FileSize:{a:y.npb},MimeType:{a:y.n1c}}});c.Txb=function(){da.K.call(this);this.jb=[]};var da=c.u(c.Txb,c.qd);da.R=function(){for(var a=0;a<this.jb.length;a++)this.jb[a].ub();this.jb=[];da.k.R.call(this)};da.Cc=function(){return this.jb.length};da.he=function(a){return this.jb[a-1]};
da.us=function(a){this.jb.push(a);a.Ba()};d.Sa(c.Txb,"PRIM_WEB","Files",{Aa:{Item:{a:function(a){return this.he(d.O(a))},Dx:"na"},ItemCount:{a:da.Cc}},Ue:{Re:"Item"},Yq:{rq:function(a){return this.he(d.O(a))},Kw:da.Cc}});c.lkc=function(){$.K.call(this)};var $=c.u(c.lkc,c.qd);$.MBb=function(a){var d=this;if(window.FileReader&&a instanceof c.WI){if(a=a.Yua()){var e=b.dY(),f=new FileReader;f.onload=function(a){d.c5(a.target.result);b.EB(e)};f.readAsText(a)}}else d.c5("")};$.c5=function(b){var c=d.cc();
c.zC("DATA",b);this.Ga(a.Q.Gaa,c)};d.Sa(c.lkc,"PRIM_WEB","ClobReader",{jc:{Read:$.MBb}});c.$jc=function(){L.K.call(this)};var L=c.u(c.$jc,c.qd);L.MBb=function(a){var d=this;if(window.FileReader&&a instanceof c.WI){if(a=a.Yua()){var e=b.dY(),f=new FileReader;f.onload=function(a){d.c5(b.n1b(a.target.result));b.EB(e)};f.readAsDataURL(a)}}else d.c5("","")};L.c5=function(b){var c=d.cc();c.zC("DATA",b);this.Ga(a.Q.Gaa,c)};d.Sa(c.$jc,"PRIM_WEB","BlobReader",{jc:{Read:L.MBb}});c.Qlc=function(a){T.K.call(this,
a)};var T=c.u(c.Qlc,c.mo);T.tb=function(a){this.G.textContent=a};T.Iz=function(){T.k.Iz.call(this);this.G.style.whiteSpace="normal";this.G.style.overflowX="auto";this.G.style.overflowY="auto"};T.Hd=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.hc);this.G.setAttribute("LANSAHandle",this.hc);return T.k.Hd.call(this,a,b)};c.Ulc=function(a){H.K.call(this,a)};var H=c.u(c.Ulc,c.mo);H.tb=function(a){this.G.textContent=a};H.WJa=function(){return!1};H.dpa=function(){};
H.Iz=function(){};H.Hd=function(a,b){this.G=document.createElement("p");this.G.setAttribute("id",a+this.hc);this.G.setAttribute("LANSAHandle",this.hc);return H.k.Hd.call(this,a,b)};c.Rlc=function(a){I.K.call(this,a)};var I=c.u(c.Rlc,c.mo);I.WJa=function(){return!1};I.dpa=function(){};I.Iz=function(){};I.Hd=function(a,b){this.G=document.createElement("br");this.G.setAttribute("id",a+this.hc);this.G.setAttribute("LANSAHandle",this.hc);return I.k.Hd.call(this,a,b)};c.Slc=function(a){W.K.call(this,a)};
var W=c.u(c.Slc,c.mo);W.Bd=function(a){this.G.src=a};W.WJa=function(){return!1};W.hi=function(b,c,d){this.G.style.width=0==c?"auto":c+"px";this.G.style.height=0==d?"auto":d+"px";switch(b){case a.dP.ICb:this.G.style.marginLeft="initial";this.G.style.marginRight="initial";this.G.style.display="inline";this.G.style.cssFloat="none";break;case a.dP.Krc:this.G.style.marginLeft="initial";this.G.style.marginRight="initial";this.G.style.display="inline";this.G.style.cssFloat="left";break;case a.dP.Lrc:this.G.style.marginLeft=
"initial";this.G.style.marginRight="initial";this.G.style.display="inline";this.G.style.cssFloat="right";break;case a.dP.Jrc:this.G.style.marginLeft="auto",this.G.style.marginRight="auto",this.G.style.display="block",this.G.style.cssFloat="none"}};W.dpa=function(){};W.Iz=function(){this.G.style.borderStyle="solid"};W.Hd=function(a,b){this.G=document.createElement("img");this.G.setAttribute("id",a+this.hc);this.G.setAttribute("LANSAHandle",this.hc);return W.k.Hd.call(this,a,b)};c.Tlc=function(a){na.K.call(this,
a)};var na=c.u(c.Tlc,c.mo);na.tb=function(a){this.G.textContent=a};na.WJa=function(){return!1};na.dpa=function(){};na.Iz=function(){};na.Hd=function(a,b){this.G=document.createElement("span");this.G.setAttribute("id",a+this.hc);this.G.setAttribute("LANSAHandle",this.hc);return na.k.Hd.call(this,a,b)};c.dlc=function(a){qa.K.call(this,a)};var qa=c.u(c.dlc,c.mo);qa.Hd=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.hc);this.G.setAttribute("LANSAHandle",this.hc);return qa.k.Hd.call(this,
a,b)};c.Vlc=function(a){fa.K.call(this,a);this.kv=this.Hp=null;this.lCc=this.LRb=!1;this.BOb=null};var fa=c.u(c.Vlc,c.mo);fa.W7b=function(){return!0};fa.Hd=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.hc);this.G.setAttribute("LANSAHandle",this.hc);this.G.style.msTouchAction="none";this.kv=document.createElement("canvas");this.kv.style.touchAction="none";this.G.appendChild(this.kv);this.Hp=this.kv.getContext("2d");this.ZVb();return fa.k.Hd.call(this,a,b)};fa.vq=
function(a,b,c,d){fa.k.vq.call(this,a,b,c,d);if(c>this.kv.width||d>this.kv.height)a=this.Hp.getImageData(0,0,this.kv.width-1,this.kv.height-1),this.kv.width=this.Jd,this.kv.height=this.Qd,this.Hp.putImageData(a,0,0)};fa.PS=function(a){this.MFb(a);return!0};fa.rzb=function(a){this.hvc(a);return!0};fa.T2a=function(a){this.LFb(a);return!0};fa.HG=function(a){a.buttons&&this.MFb(a);return fa.k.HG.call(this,a)};fa.IG=function(a){this.LFb(a);return fa.k.IG.call(this,a)};fa.bCa=function(a){this.MFb(a);return!0};
fa.ky=function(a){this.hvc(a);return!0};fa.Yoa=function(a){this.LFb(a);return!0};fa.Q8b=function(a){this.G.onpointerdown===p&&a.touches!==p?(a.oLb=a.touches[0].pageX-this.L.Wt(),a.pLb=a.touches[0].pageY-this.L.Xt()):(a.oLb=a.clientX-this.L.Wt(),a.pLb=a.clientY-this.L.Xt());this.L.Ee()};fa.ZVb=function(){this.xhb(!0);this.BOb=new Image;this.BOb.onload=function(){throw 0;};this.BOb.src=null};fa.xhb=function(a){(this.lCc||a)&&this.Hp.clearRect(0,0,this.Hp.canvas.width,this.Hp.canvas.height);this.lCc=
!1};fa.dXc=function(){var a=this.kv.toDataURL("image/png");return b.n1b(a)};fa.Uk=function(){this.ZVb()};fa.MFb=function(a){a.preventDefault();this.xhb(!1);this.Hp.beginPath();this.Q8b(a);this.Hp.moveTo(a.oLb,a.pLb);this.LRb=!0};fa.LFb=function(a){a.preventDefault();this.LRb=!1};fa.nie=function(a){this.ky(a)};fa.hvc=function(a){this.LRb&&(a.preventDefault(),this.xhb(!1),this.Hp.strokeStyle="rgb(0,0,0)",this.Hp.lineWidth=1,this.Q8b(a),this.Hp.lineTo(a.oLb,a.pLb),this.Hp.stroke())};c.Kkc=function(a){ta.K.call(this,
a);this.Bsa=this.gb=null};var ta=c.u(c.Kkc,c.mo);ta.yl=function(a){this.Bsa.src=a};ta.Hd=function(a,b){this.G=document.createElement("div");this.G.setAttribute("id",a+this.hc);this.G.setAttribute("LANSAHandle",this.hc);this.Bsa=document.createElement("iframe");this.n_(this.Bsa);this.Bsa.style.width="100%";this.Bsa.style.height="100%";this.G.appendChild(this.Bsa);return ta.k.Hd.call(this,a,b)};ta.Ky=function(){var a=this;ta.k.Ky.call(this);a.Bsa.addEventListener("load",function(){a.L&&a.L.CVc()},!1)};
ta.n_=function(a){ta.k.n_.call(this,a);this.G.style.overflowX="auto";this.G.style.overflowY="auto"};c.mlc=function(a){ra.K.call(this,a);this.yr=null};var ra=c.u(c.mlc,c.uyb);ra.Hd=function(a,b){var c=ra.k.Hd.call(this,a,b);this.yr=document.createElement("input");this.yr.type="File";this.yr.title="";var d=this.yr.style;this.fb.style.zIndex=1;d.opacity=0;d.position="absolute";d.zIndex=99998;d.background="rgb( 255, 0, 0 )";c.appendChild(this.yr);return c};ra.Lc=function(){ra.k.Lc.call(this);this.yQa()};
ra.vq=function(a,b,c,d){ra.k.vq.call(this,a,b,c,d);this.yr.style.left="0px";this.yr.style.top="0px";this.yr.style.width=c+"px";this.yr.style.height=d+"px"};ra.Ky=function(){var a=this;this.t_();a.yr.addEventListener("change",function(b){a.L&&(a.DGa(b),a.yr.value="")},!1)};ra.yQa=function(){this.yr.multiple=this.L.cka()};ra.DGa=function(a){a=a.target.files||a.dataTransfer.files;for(var b=null,d=new c.Txb,e=0,f;f=a[e];e++)f=new c.lMa(f),null==b&&(b=f),d.us(f);b&&this.L.cua(b,d)}},{rp:["PRIM_LABL"]});
