LANSA.addComponent({id:"DF_PRM04O",ot:"rp",tp:"Reusable Part",pt:"ap",de:"\\OC=5250 Prompter - 4 - Tree View",tl:15000000},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")){cL=l.gCL();}var Fd={F1:{ic:0,nm:"STD_INT",ft:"I",ln:4,dc:0,ec:"J",lb:{"ENG":"Std Integer","FRA":"?","JPN":"?"}[cL],h1:{"ENG":"Standard","FRA":"?","JPN":"?"}[cL],h2:{"ENG":"Integer","FRA":"?","JPN":"?"}[cL],h3:{"ENG":"Field","FRA":"?","JPN":"?"}[cL],de:{"ENG":"Standard Integer field","FRA":"?","JPN":"?"}[cL],
dv:0,ia:["FE","RB"]},F2:{nm:"XDEPTMENT",an:"xDepartmentCode",ft:"A",ln:4,dc:0,lb:{"ENG":"Department","FRA":"Département","JPN":"部門"}[cL],h1:{"ENG":"Department","FRA":"Code","JPN":"部門"}[cL],h2:{"ENG":"Code","FRA":"Département","JPN":"コード"}[cL],h3:" ",de:{"ENG":"Department","FRA":"Département","JPN":"部門"}[cL],dv:"",ia:["FE"]},F3:{nm:"XEMPLOYID",an:"xEmployeeIdentification",ft:"A",ln:10,dc:0,lb:{"ENG":"Employee Id","FRA":"Id employé","JPN":"社員 ID"}[cL],h1:{"ENG":"Employee","FRA":"Identification","JPN":"社員"}[cL],
h2:{"ENG":"Identification","FRA":"Employé","JPN":"ID"}[cL],h3:" ",de:{"ENG":"Identification","FRA":"Identification","JPN":"身分証明"}[cL],dv:"",ia:["FE"]},F4:{nm:"LISTCOUNT",ft:"P",ln:7,dc:0,ec:"J",lb:{"ENG":"Entries .......","FRA":"Entrées . . . .","JPN":"?"}[cL],h1:{"ENG":"Number","FRA":"Nombre","JPN":"?"}[cL],h2:{"ENG":"of Entrys","FRA":"d´entrées","JPN":"?"}[cL],h3:"",de:{"ENG":"Number of entries in a browse list","FRA":"Nombre d´entrées dans une browse list","JPN":"?"}[cL],dv:0,ia:["FE","RB"]},F5:
{nm:"XDEPTDESC",an:"xDepartmentDescription",ft:"A",ln:20,dc:0,ks:"O",lb:{"ENG":"Description....","FRA":"Description . .","JPN":"説明...."}[cL],h1:{"ENG":"Department","FRA":"Description","JPN":"部門"}[cL],h2:{"ENG":"Description","FRA":"Département","JPN":"説明"}[cL],h3:" ",de:{"ENG":"Department Description","FRA":"Description du département","JPN":"部門説明"}[cL],dv:"",ia:["FE","LC"],vr:[{wt:"N",wf:"E",vi:"Y",vu:"Y",vd:"N",rd:rl1,mt:{"ENG":"A description is required for department","FRA":"A description is required for department","JPN":"A description is required for department"}[cL]
}]},F6:{nm:"XSURNAME",an:"xEmployeeSurname",ft:"N",ln:40,dc:0,lb:{"ENG":"Surname","FRA":"Nom","JPN":"姓"}[cL],h1:{"ENG":"Employee","FRA":"Nom","JPN":"社員"}[cL],h2:{"ENG":"Surname","FRA":"Employé","JPN":"姓"}[cL],h3:" ",de:{"ENG":"Surname","FRA":"Nom","JPN":"姓"}[cL],dv:"",ia:["FE","LC"]},F7:{nm:"XGIVENAME",an:"xEmployeeGivenNames",ft:"N",ln:40,dc:0,lb:{"ENG":"Given Names","FRA":"Prénoms","JPN":"名前"}[cL],h1:{"ENG":"Employee","FRA":"Prénoms","JPN":"社員"}[cL],h2:{"ENG":"Given","FRA":"Employé","JPN":"ファースト"}[cL],
h3:{"ENG":"Names","FRA":" ","JPN":"ネーム"}[cL],de:{"ENG":"Given Names","FRA":"Prénoms","JPN":"ファーストネーム"}[cL],dv:"",ia:["FE","LC"]}};var cO=l.rC(oI,{an:"VF_AC017O",fd:Fd,mt:{uInitialize:{},uTerminate:{},AddDepartment:{ps:{"uDepartment":{pt:"i"},"uEmployee":{pt:"i"},"uDescription":{pt:"i"},"ParentMenu":{pt:"i"}}},AddEmployee:{ps:{"uDepartment":{pt:"i"},"uEmployee":{pt:"i"},"uDescription":{pt:"i"},"ParentMenuItem":{pt:"i"}}},uShow:{ps:{"Top":{pt:"i"},"Left":{pt:"i"},"Height":{pt:"i"},"Width":{pt:"i"}}
}},co:function(){cO.aN.call(this);var f=this.aF("DF_PRM04O",Fd);var C0=this.cR("ATTACHLAYOUT2","PRIM_ATLM");var C1=this.cR("ATTACHLAYOUT2ITEM1","PRIM_ATLI");var C2=this.cR("MENU","PRIM_MD","Menu");var C3=this.cR("ATTACHLAYOUT1","PRIM_ATLM");var C4=this.cR("COL_DEPARTMENTS","PRIM_ACOL");var C5=this.cR("COL_EMPLOYEES","PRIM_ACOL");var C6=this.cR("ITEMFOCUSSTYLE","PRIM_VS","Style");C0.iC();C1.setAttachment("CENTER");C1.setManage(C2);C1.setParent(C0);C1.iC();C2.setDisplayPosition(1);C2.setHeight(313);
C2.setParent(this);C2.setTabPosition(1);C2.setWidth(295);C2.setDisableNoScroll(true);C2.setVerticalScroll(true);C2.setLayoutManager(C3);C2.setTop(30);C2.iC();C3.iC();C4.setCollects("PRIM_MD.MenuItem");C4.iC();C5.setCollects("PRIM_MD.MenuItem");C5.iC();C6.setBold(true);C6.iC();C5.aH("CLICK",this,e2);this.setHeight(345);this.setWidth(297);this.setLayoutManager(C0);this.setCloseButton(true);this.setTitleBar(true);var li=this.aL("DF_PRM04O");li.DEPEMPLIST=l.cLT({"XDEPTMENT":f.F2,"XDEPTDESC":f.F5,"XEMPLOYID":f.F3,"XSURNAME":f.F6,"XGIVENAME":f.F7},f.F4);
}});cO.mthUINITIALIZE=function(){var li=this.LIST.DF_PRM04O,f=this.FLD.DF_PRM04O,m=this.REF,r=l.mR(this,cO,"uInitialize",52),mth=r;var C0=r.cDR("FINDALL_DEPTEMP","DF_PRMDSO","FINDALL_DEPTEMP");C0.iC();C0.aH("COMPLETED",this,e1);r.ln=52;{r.ln=56;C0.mthEXECUTE({},{LIST:{"DEPEMPLIST":li.DEPEMPLIST}});}r.ln=79;r.e();function e1(sender,Ps){var r=l.eR(this,cO,"#FindAll_DeptEmp.Completed",58,mth);var C1=r.cD("C1");r.ln=58;{r.ln=63;{var l1=li.DEPEMPLIST.selectList();while(l1.step()){r.ln=65;if(l.s.eq(f.F3.get(),""))
{r.ln=67;C1=r.sR("C1",cO.mthADDDEPARTMENT.call(this,f.F2.get(),"",f.F5.get(),m.MENU));}else{r.ln=70;cO.mthADDEMPLOYEE.call(this,f.F2.get(),f.F3.get(),l.add(l.cat(f.F6.get()," "),f.F7.get()),C1);}r.ln=72;}l1.end();}r.ln=74;{var l1=m.COL_DEPARTMENTS.cI();while(l1.step()){var ITEM=r.sR("ITEM",l1.item());r.ln=75;ITEM.setExpanded(false);r.ln=76;}l1.end();r.dR("ITEM");}}r.ln=77;r.e();}};cO.mthUTERMINATE=function(){var m=this.REF,r=l.mR(this,cO,"uTerminate",83);r.ln=83;{r.ln=84;m.COL_DEPARTMENTS.mthREMOVEALL();
r.ln=85;m.COL_EMPLOYEES.mthREMOVEALL();}r.ln=87;r.e();};cO.mthADDDEPARTMENT=function(p0,p1,p2,p3){var m=this.REF,r=l.mR(this,cO,"AddDepartment",91);var P0=r.cP("UDEPARTMENT","PRIM_ALPH");var P1=r.cP("UEMPLOYEE","PRIM_ALPH");var P2=r.cP("UDESCRIPTION","PRIM_ALPH");var P3=r.cPD("PARENTMENU");var P4=r.cPD("RESULT");P0.set(p0);P1.set((p1===u)?(""):(p1));P2.set(p2);P3=r.sR("PARENTMENU",(p3===u)?(null):(p3));P4=null;r.ln=91;{r.ln=99;P4=r.sR("P4",l.cC("PRIM_MD","MenuItem"));r.ln=100;P4.setParent(m.MENU);
P4.setCaption(l.cat(l.cat(P0.get()," -  "),P2.get()));P4.setComponentTag(P0.get());P4.setHeight(50);r.ln=101;m.COL_DEPARTMENTS.mthINSERT(P4);}r.ln=103;return r.rR(P4);};cO.mthADDEMPLOYEE=function(p0,p1,p2,p3){var m=this.REF,r=l.mR(this,cO,"AddEmployee",107);var P0=r.cP("UDEPARTMENT","PRIM_ALPH");var P1=r.cP("UEMPLOYEE","PRIM_ALPH");var P2=r.cP("UDESCRIPTION","PRIM_ALPH");var P3=r.cPD("PARENTMENUITEM");var P4=r.cPD("RESULT");P0.set(p0);P1.set((p1===u)?(""):(p1));P2.set(p2);P3=r.sR("PARENTMENUITEM",(p3===u)?(null):(p3));
P4=null;r.ln=107;{r.ln=115;P4=r.sR("P4",l.cC("PRIM_MD","MenuItem"));r.ln=116;P4.setParentItem(P3);P4.setParent(m.MENU);P4.setCaption(l.cat(l.cat(P1.get()," -  "),P2.get()));P4.setComponentTag(P1.get());P4.setHeight(50);P4.setCaptionMarginLeft(50);P4.setFocusedStyle(m.ITEMFOCUSSTYLE);r.ln=117;m.COL_EMPLOYEES.mthINSERT(P4);}r.ln=119;return r.rR(P4);};cO.mthUSHOW=function(p0,p1,p2,p3){var m=this.REF,r=l.mR(this,cO,"uShow",123);var P0=r.cPF("TOP",Fd.F1.Dc);var P1=r.cPF("LEFT",Fd.F1.Dc);var P2=r.cPF("HEIGHT",Fd.F1.Dc);
var P3=r.cPF("WIDTH",Fd.F1.Dc);P0.set((p0===u)?(-999999):(p0));P1.set((p1===u)?(-999999):(p1));P2.set((p2===u)?(-999999):(p2));P3.set((p3===u)?(-999999):(p3));var C0=r.cF("PROMPTDEPTMENT",Fd.F2.Dc);var C1=r.cF("PROMPTEMPLOYEE",Fd.F3.Dc);C0.iC();C1.iC();r.ln=123;{r.ln=130;this.mthUGET5250FIELD(this.getUPROMPT5250FIELD(),this.getUPROMPT5250INDEX(),C0,u);r.ln=131;this.mthUGET5250FIELD("EMPLOYEE",u,C1,u);r.ln=134;{var l1=m.COL_EMPLOYEES.cI();while(l1.step()){var ITEM=r.sR("ITEM",l1.item());r.ln=135;if(l.s.eq(ITEM.getComponentTag(),C1.get()))
{r.ln=136;ITEM.getParentItem().setExpanded(true);r.ln=137;m.MENU.mthVERTICALSCROLLTO(ITEM,"TOP");r.ln=138;ITEM.mthSETFOCUS();r.ln=139;break;}r.ln=141;}l1.end();r.dR("ITEM");}r.ln=143;this.setVisible(true);r.ln=144;this.mthSHOWPOPUP(P1.get(),P0.get(),"ABSOLUTE",u,u);}r.ln=146;r.e();};function e2(USENDER,Ps){var r=l.eR(this,cO,"#Col_Employees<>.Click",150);r.ln=150;{r.ln=153;this.mthUSET5250FIELD(this.getUPROMPT5250FIELD(),USENDER.getParentItem().getComponentTag(),u,this.getUPROMPT5250INDEX());r.ln=156;
this.mthUSET5250FIELD("EMPLOYEE",USENDER.getComponentTag(),u,u);r.ln=159;this.mthUHIDE();}r.ln=161;r.e();};function rl1(F5){return (l.s.ne(F5.get(),""));};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"STD_INT"});}{Fd.F2.Dc=function(){this.aN.call(this,Fd.F2);};l.cFC({co:Fd.F2.Dc,an:"PRIM_FLD",fn:"XDEPTMENT"});}{Fd.F3.Dc=function(){this.aN.call(this,Fd.F3);};l.cFC({co:Fd.F3.Dc,an:"PRIM_FLD",fn:"XEMPLOYID"});}},{rc:["VF_AC017O"],rp:["PRIM_ATLM","PRIM_ATLI","PRIM_MD.Menu","PRIM_ACOL","PRIM_VS.Style","PRIM_WEB.DataRequest","PRIM_FLD"],
dp:["PRIM_MD.MenuItem"]});