LANSA.addComponent({id:"DF_T76F1O",ot:"rp",tp:"Reusable Part",pt:"ap",de:"\\OC= Filter adds images to instance list",tl:15000000},function(l,oI,u){var lIO="";var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")){cL=l.gCL();}var m1={"ENG":"Search","FRA":"Rechercher","JPN":"検索"}[cL],m2={"ENG":"Clear List","FRA":"Vider la liste","JPN":"ﾘｽﾄのｸﾘｱ"}[cL];var Fd={F1:{ic:0,nm:"XSURNAME",an:"xEmployeeSurname",ft:"N",ln:40,dc:0,lb:{"ENG":"Surname","FRA":"Nom","JPN":"姓"}[cL],h1:{"ENG":"Employee","FRA":"Nom","JPN":"社員"}[cL],
h2:{"ENG":"Surname","FRA":"Employé","JPN":"姓"}[cL],h3:" ",de:{"ENG":"Surname","FRA":"Nom","JPN":"姓"}[cL],dv:"",ia:["FE","LC"]},F2:{ic:0,nm:"XGIVENAME",an:"xEmployeeGivenNames",ft:"N",ln:40,dc:0,lb:{"ENG":"Given Names","FRA":"Prénoms","JPN":"名前"}[cL],h1:{"ENG":"Employee","FRA":"Prénoms","JPN":"社員"}[cL],h2:{"ENG":"Given","FRA":"Employé","JPN":"ファースト"}[cL],h3:{"ENG":"Names","FRA":" ","JPN":"ネーム"}[cL],de:{"ENG":"Given Names","FRA":"Prénoms","JPN":"ファーストネーム"}[cL],dv:"",ia:["FE","LC"]},F3:{nm:"LISTCOUNT",
ft:"P",ln:7,dc:0,ec:"J",lb:{"ENG":"Entries .......","FRA":"Entrées . . . .","JPN":"?"}[cL],h1:{"ENG":"Number","FRA":"Nombre","JPN":"?"}[cL],h2:{"ENG":"of Entrys","FRA":"d´entrées","JPN":"?"}[cL],h3:"",de:{"ENG":"Number of entries in a browse list","FRA":"Nombre d´entrées dans une browse list","JPN":"?"}[cL],dv:0,ia:["FE","RB"]},F4:{nm:"XEMPLOYID",an:"xEmployeeIdentification",ft:"A",ln:10,dc:0,lb:{"ENG":"Employee Id","FRA":"Id employé","JPN":"社員 ID"}[cL],h1:{"ENG":"Employee","FRA":"Identification","JPN":"社員"}[cL],
h2:{"ENG":"Identification","FRA":"Employé","JPN":"ID"}[cL],h3:" ",de:{"ENG":"Identification","FRA":"Identification","JPN":"身分証明"}[cL],dv:"",ia:["FE"]},F5:{nm:"XEMPTITLE",an:"xEmployeeTitle",ft:"N",ln:40,dc:0,lb:{"ENG":"Title","FRA":"Titre","JPN":"役職"}[cL],h1:{"ENG":"Employee","FRA":"Titre","JPN":"社員"}[cL],h2:{"ENG":"Title","FRA":"Employé","JPN":"役職"}[cL],h3:" ",de:{"ENG":"Title","FRA":"Titre","JPN":"役職"}[cL],dv:"",ia:["FE","LC"]},F6:{nm:"XGENDER",an:"xEmployeeGender",ft:"A",ln:10,dc:0,lb:{"ENG":"Gender","FRA":"Genre","JPN":"性別"}[cL],
h1:{"ENG":"Employee","FRA":"Genre","JPN":"社員"}[cL],h2:{"ENG":"Gender","FRA":"Employé","JPN":"性別"}[cL],h3:" ",de:{"ENG":"Gender","FRA":"Genre","JPN":"性別"}[cL],dv:"Male",ia:["FE","LC"]},F7:{nm:"XSALARY",an:"xEmployeeSalary",ft:"P",ln:15,dc:2,ec:"1",lb:{"ENG":"Annual Salary","FRA":"Salaire annuel","JPN":"年収"}[cL],h1:{"ENG":"Annual","FRA":"Salaire","JPN":"年収"}[cL],h2:{"ENG":"Salary","FRA":"Annuel","JPN":" "}[cL],h3:" ",de:{"ENG":"Annual Salary","FRA":"Salaire annuel","JPN":"年収"}[cL],dv:0,ia:["FE","RB"]
},F8:{nm:"XSTARTDTE",an:"xEmployeeStartDate",ft:"D",ln:10,dc:0,lb:{"ENG":"Start Date","FRA":"Date Embauche","JPN":"開始日"}[cL],h1:{"ENG":"Start","FRA":"Date","JPN":"開始"}[cL],h2:{"ENG":"Date","FRA":"Embauche","JPN":"日付"}[cL],h3:" ",de:{"ENG":"Start Date","FRA":"Date d'Embauche","JPN":"開始日"}[cL],dv:l.SqlNull,ia:["FE","ASQN"]},F9:{nm:"XEMPTHM",an:"xEmployeeImageThumbnail",ft:"BL",ln:0,dc:0,lb:{"ENG":"Employee Image","FRA":"Image Employé","JPN":"社員画像"}[cL],h1:{"ENG":"Employee","FRA":"Image","JPN":"社員"}[cL],
h2:{"ENG":"Image","FRA":"employé","JPN":"画像"}[cL],h3:" ",de:{"ENG":"Employee Image Thumbnail","FRA":"Image miniature employé","JPN":"社員サムネイル画像"}[cL],dv:l.SqlNull,ia:["ASQN","FE","LC"]},F10:{nm:"IO$STS",ft:"A",ln:2,dc:0,lb:{"ENG":"I/O status ....","FRA":"Code retour E/S","JPN":"I/O戻りコード"}[cL],h1:{"ENG":"I/O","FRA":"Code","JPN":" I/O"}[cL],h2:{"ENG":"Status","FRA":"retour E/S","JPN":"コード"}[cL],h3:"",de:{"ENG":"Data base I/O operation status code","FRA":"Code retour opérations E/S B. de données","JPN":" DB入出力戻りコード"}[cL],
dv:"",ia:["FE"]}};var cO=l.rC(oI,{an:"VF_AC007O",fd:Fd,rm:["dt"],mt:{uInitialize:{},uSelectData:{}},co:function(){cO.aN.call(this);var f=this.aF("DF_T76F1O",Fd);var C0=this.cR("DATAITEMPANEL","PRIM_PANL");var C1=this.cR("BUTTONPANEL","PRIM_PANL");var C2=this.cR("ATTACHDATAITEMPANEL","PRIM_ATLI");var C3=this.cR("ATTACHBUTTONPANEL","PRIM_ATLI");var C4=this.cR("BUTTONPANELATTACHMENTHMANAGER","PRIM_ATLM");var C5=this.cR("BUTTONPANELATTACHMENTSAVE","PRIM_ATLI");var C6=this.cR("ATTACHITEM1","PRIM_ATLI");
var C7=this.cR("FLOWLAYOUT1","PRIM_FWLM");var C8=this.cR("FLOWLAYOUT1ITEM1","PRIM_FWLI");var C9=this.cR("FLOWLAYOUT1ITEM2","PRIM_FWLI");var C10=this.cR("SEARCH_BUTTON","PRIM_MD","RaisedButton");var C11=this.cR("CLEAR_LIST","PRIM_MD","CheckBox");var C12=this.cF("XEMPLOYEESURNAME",Fd.F1.EDITFIELD);var C13=this.cF("XEMPLOYEEGIVENNAMES",Fd.F2.EDITFIELD);C0.setParent(this);C0.setDisplayPosition(1);C0.setTabPosition(1);C0.setHeight(134);C0.setLeft(4);C0.setTop(0);C0.setWidth(207);C0.setHorizontalScroll(true);
C0.setVerticalScroll(true);C0.setTabStop(false);C0.setLayoutManager(C7);C0.iC();C1.setParent(this);C1.setDisplayPosition(2);C1.setTabPosition(2);C1.setLeft(4);C1.setTop(134);C1.setWidth(207);C1.setLayoutManager(C4);C1.setHeight(44);C1.setTabStop(false);C1.iC();C2.setManage(C0);C2.setParent(this.REF.MAINPANELATTACHMENTMANAGER);C2.setAttachment("CENTER");C2.setMarginRight(4);C2.setMarginLeft(4);C2.iC();C3.setManage(C1);C3.setParent(this.REF.MAINPANELATTACHMENTMANAGER);C3.setAttachment("BOTTOM");C3.setMarginRight(4);
C3.setMarginLeft(4);C3.setMarginBottom(4);C3.iC();C4.iC();C5.setParent(C4);C5.setManage(C10);C5.setAttachment("RIGHT");C5.iC();C6.setManage(C11);C6.setParent(C4);C6.setAttachment("LEFT");C6.iC();C7.setDirection("TOPTOBOTTOM");C7.setSizingRuleHor("MAXIMIZE");C7.iC();C8.setManage(C12);C8.setParent(C7);C8.iC();C9.setManage(C13);C9.setParent(C7);C9.iC();C10.setParent(C1);C10.setCaption(m1);C10.setDisplayPosition(1);C10.setTabPosition(1);C10.setLeft(107);C10.setTop(0);C10.setButtonDefault(true);C10.setHeight(44);
C10.iC();C11.setCaption(m2);C11.setParent(C1);C11.setDisplayPosition(2);C11.setTabPosition(2);C11.setCheckState("CHECKED");C11.setLeft(0);C11.setTop(0);C11.setHeight(44);C11.iC();C12.setParent(C0);C12.setDisplayPosition(1);C12.setTabPosition(1);C12.setLeft(0);C12.setHeight(48);C12.setHelperPosition("NONE");C12.setTop(0);C12.setWidth(207);C12.aD();C12.iC();C13.setParent(C0);C13.setDisplayPosition(2);C13.setTabPosition(2);C13.setLeft(0);C13.setHeight(48);C13.setHelperPosition("NONE");C13.setTop(58);
C13.setWidth(207);C13.aD();C13.iC();C10.aH("CLICK",this,e1);this.setHeight(182);this.setWidth(215);var li=this.aL("DF_T76F1O");li.ACCESSKEYS=l.cLT({"XSURNAME":C12,"XGIVENAME":C13},null);li.INSTANCELIST_COLUMNS=l.cLT({"XEMPLOYID":f.F4,"XEMPTITLE":f.F5,"XSURNAME":C12,"XGIVENAME":C13,"XGENDER":f.F6,"XSALARY":f.F7,"XSTARTDTE":f.F8,"XEMPTHM":f.F9},f.F3);}});var cA=cO.aN.prototype;cO.mthUINITIALIZE=function(){var r=l.mR(this,cO,"uInitialize",57);r.ln=57;{r.ln=61;cA.mthUINITIALIZE.call(this);r.ln=63;this.setAVFILTERLOCATION("LEFT");
r.ln=64;this.setAVALLOWLOCATIONCHANGE(true);r.ln=67;if((this.REF.AVLISTMANAGER.mthAVVISUALLIST()!=null)){r.ln=70;this.REF.AVLISTMANAGER.mthAVVISUALLIST().setRowHeight(50);r.ln=73;{var l1=this.REF.AVLISTMANAGER.mthAVVISUALLIST().getColumns().cI();while(l1.step()){var COLUMN=r.sR("COLUMN",l1.item());r.ln=75;if(l.Io(COLUMN,"PRIM_LIST.Image")){r.ln=77;l.cast(COLUMN,"PRIM_LIST.Image").setCellMarginTop(2);r.ln=78;l.cast(COLUMN,"PRIM_LIST.Image").setCellMarginBottom(2);}r.ln=82;}l1.end();r.dR("COLUMN");
}r.ln=85;this.REF.AVLISTMANAGER.setAVNCOLUMNPREFIX1("$");}}r.ln=88;r.e();};function e1(sender,Ps){var r=l.eR(this,cO,"#Search_Button.Click",91);r.ln=91;{r.ln=92;this.mthUSELECTDATA();}r.ln=93;r.e();};cO.mthUSELECTDATA=function(){var li=this.LIST.DF_T76F1O,f=this.FLD.DF_T76F1O,m=this.REF,r=l.mR(this,cO,"uSelectData",96),mth=r;var C0=r.cDR("SEARCH","DF_T76DSO","SEARCH");C0.iC();C0.aH("COMPLETED",this,e2);C0.aH("FAILED",this,e3);r.ln=96;{r.ln=102;li.ACCESSKEYS.initList(1);r.ln=105;this.mthAVGOTOBUSYSTATE("Searching",false,u);
r.ln=108;C0.mthEXECUTEASYNC({LIST:{"ACCESSKEYS":li.ACCESSKEYS}},{LIST:{"INSTANCELIST_COLUMNS":li.INSTANCELIST_COLUMNS}});}r.ln=164;r.e();function e2(sender,Ps){var r=l.eR(this,cO,"#Search.Completed",111,mth);var C1=r.cR("USTATUS","PRIM_BOLN");var C2=r.cD("C2");var C3=r.cD("C3");var C4=r.cD("C4");var C5=r.cD("C5");C1.iC();r.ln=111;{r.ln=121;if(l.s.eq(m.CLEAR_LIST.getCheckState(),"CHECKED")){r.ln=122;this.REF.AVLISTMANAGER.mthCLEARLIST(u,u);}r.ln=128;C2=r.sR("C2",l.APPL().mthCREATEBITMAP("VLFONE/IMAGES/OTHER/CROSS.PNG"));
r.ln=129;C3=r.sR("C3",l.APPL().mthCREATEBITMAP("VLFONE/IMAGES/OTHER/CHECK_MARK.PNG"));r.ln=131;{var l1=li.INSTANCELIST_COLUMNS.selectList();while(l1.step()){r.ln=135;C5=r.sR("C5",l.APPL().mthCREATEBITMAP(f.F9.get()));r.ln=137;if(l.tB(C1.get())){r.ln=138;C4=r.sR("C4",C3);}else{r.ln=140;C4=r.sR("C4",C2);}r.ln=142;C1.set(l.b.Not(C1.get()));r.ln=145;this.REF.AVLISTMANAGER.mthADDTOLIST(f.F4.get(),f.F5.get(),f.F4.get(),u,u,u,u,u,u,u,u,u,u,u,u,u,u,u,u,u,m.XEMPLOYEESURNAME.get(),m.XEMPLOYEEGIVENNAMES.get(),f.F6.get(),u,u,u,u,u,u,u,f.F7.get(),u,u,u,u,u,u,u,u,u,u,l.d.AsString(f.F8.get()),u,u,u,u,C5,C4,u,u);
r.ln=147;}l1.end();}r.ln=149;li.INSTANCELIST_COLUMNS.clearList();r.ln=152;f.F10.set(lIO=li.ACCESSKEYS.getEntry(1));r.ln=155;this.mthAVGOTOFREESTATE();}r.ln=157;r.e();}function e3(sender,Ps){var r=l.eR(this,cO,"#Search.Failed",160,mth);var P0=Ps.r("HANDLED");r.ln=160;{r.ln=161;P0.set(this.REF.AVFRAMEWORKMANAGER.mthAVHANDLESERVERERROR(this));}r.ln=162;r.e();}};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"XSURNAME"});Fd.F1.EDITFIELD=function(){this.aN.call(this,new Fd.F1.Dc());
};l.cFC({co:Fd.F1.EDITFIELD,an:"PRIM_MD",at:"EditField",fn:"XSURNAME",cn:"EditField"});}{Fd.F2.Dc=function(){this.aN.call(this,Fd.F2);};l.cFC({co:Fd.F2.Dc,an:"PRIM_FLD",fn:"XGIVENAME"});Fd.F2.EDITFIELD=function(){this.aN.call(this,new Fd.F2.Dc());};l.cFC({co:Fd.F2.EDITFIELD,an:"PRIM_MD",at:"EditField",fn:"XGIVENAME",cn:"EditField"});}{Fd.F5.Dc=function(){this.aN.call(this,Fd.F5);};l.cFC({co:Fd.F5.Dc,an:"PRIM_FLD",fn:"XEMPTITLE"});Fd.F5.pl=function(){this.aN.call(this);var C0=this.cR("PKIT_1","PRIM_PKIT");
var C1=this.cR("PKIT_2","PRIM_PKIT");var C2=this.cR("PKIT_3","PRIM_PKIT");var C3=this.cR("PKIT_4","PRIM_PKIT");var C4=this.cR("PKIT_5","PRIM_PKIT");C0.setValue("Mr");C0.setCaption("Mr");C0.setParent(this);C0.iC();C1.setValue("Mrs");C1.setCaption("Mrs");C1.setParent(this);C1.iC();C2.setValue("Miss");C2.setCaption("Miss");C2.setParent(this);C2.iC();C3.setValue("Ms");C3.setCaption("Ms");C3.setParent(this);C3.iC();C4.setValue("Dr");C4.setCaption("Dr");C4.setParent(this);C4.iC();this.setNoMatchAction("SHOWVALUE");
};l.cFC({co:Fd.F5.pl,an:"PRIM_PKLT",fn:"XEMPTITLE",cn:"Picklist"});}{Fd.F6.Dc=function(){this.aN.call(this,Fd.F6);};l.cFC({co:Fd.F6.Dc,an:"PRIM_FLD",fn:"XGENDER"});Fd.F6.pl=function(){this.aN.call(this);var C0=this.cR("ITEM_1","PRIM_PKIT");var C1=this.cR("ITEM_2","PRIM_PKIT");var C2=this.cR("ITEM_3","PRIM_PKIT");C0.setCaption("Male");C0.setParent(this);C0.setValue("Male");C0.iC();C1.setCaption("Female");C1.setParent(this);C1.setValue("Female");C1.iC();C2.setCaption("Not Disclosed");C2.setParent(this);
C2.setValue("NoDisclose");C2.iC();this.setNoMatchAction("SHOWVALUE");};l.cFC({co:Fd.F6.pl,an:"PRIM_PKLT",fn:"XGENDER",cn:"Picklist"});}cO.setrefAVLISTMANAGER=function(rn){cA.setrefAVLISTMANAGER.call(this,rn);};cO.setrefAVFRAMEWORKMANAGER=function(rn){cA.setrefAVFRAMEWORKMANAGER.call(this,rn);};},{rc:["VF_AC007O"],rp:["PRIM_PANL","PRIM_ATLI","PRIM_ATLM","PRIM_FWLM","PRIM_FWLI","PRIM_MD.RaisedButton","PRIM_MD.CheckBox","PRIM_FLD","PRIM_MD.EditField","PRIM_WEB.DataRequest","PRIM_PKLT","PRIM_DTIM"],dp:["PRIM_BOLN","PRIM_BMP"]
});