LANSA.addComponent({id:"XEX00022",nm:"XDemoSendEmailPage",ot:"wp",tp:"Web Page",de:"[pkg-ex-integration-lib]",tl:14020401},function(l,oI,u){var cO=l.rC(oI,{an:"PRIM_WEB",co:function(){cO.aN.call(this);var C0=this.cR("LAYOUTMAIN","PRIM_TBLO");var C1=this.cR("LAYOUTMAINCOLUMN1","PRIM_TBLO","Column");var C2=this.cR("LAYOUTMAINROW1","PRIM_TBLO","Row");var C3=this.cR("LAYOUTMAINROW2","PRIM_TBLO","Row");var C4=this.cR("LAYOUTMAINITEM1","PRIM_TBLO","Item");var C5=this.cR("LAYOUTMAINITEM2","PRIM_TBLO","Item");
var C6=this.cR("LAYOUT","PRIM_TBLO");var C7=this.cR("LAYOUTCOLUMN1","PRIM_TBLO","Column");var C8=this.cR("LAYOUTROW1","PRIM_TBLO","Row");var C9=this.cR("LAYOUTROW2","PRIM_TBLO","Row");var C10=this.cR("LAYOUTROW3","PRIM_TBLO","Row");var C11=this.cR("LAYOUTROW4","PRIM_TBLO","Row");var C12=this.cR("LAYOUTITEM1","PRIM_TBLO","Item");var C13=this.cR("LAYOUTITEM2","PRIM_TBLO","Item");var C14=this.cR("LAYOUTITEM3","PRIM_TBLO","Item");var C15=this.cR("LAYOUTITEM5","PRIM_TBLO","Item");var C16=this.cR("SENDBUTTON","PRIM_MD","RaisedButton");
var C17=this.cR("PANEL1","PRIM_PANL");var C18=this.cR("RECIPIENTINPUT","PRIM_MD","Edit");var C19=this.cR("SENDERINPUT","PRIM_MD","Edit");var C20=this.cR("SUBJECTINPUT","PRIM_MD","Edit");var C21=this.cR("BODYINPUT","PRIM_MD","Edit");C0.setMarginBottom(20);C0.setMarginLeft(20);C0.setMarginRight(20);C0.setMarginTop(20);C0.iC();C1.setDisplayPosition(1);C1.setParent(C0);C1.iC();C2.setDisplayPosition(1);C2.setParent(C0);C2.setHeight(530);C2.setUnits("CONTENT");C2.iC();C3.setDisplayPosition(2);C3.setParent(C0);
C3.setHeight(40);C3.setUnits("CONTENT");C3.iC();C4.setManage(C16);C4.setParent(C0);C4.setRow(C3);C4.setSizing("CONTENTWIDTHANDHEIGHT");C4.setColumn(C1);C4.setAlignment("TOPLEFT");C4.iC();C5.setManage(C17);C5.setParent(C0);C5.setRow(C2);C5.setColumn(C1);C5.setAlignment("TOPLEFT");C5.setSizing("CONTENTHEIGHTFITTOWIDTH");C5.iC();C6.iC();C7.setDisplayPosition(1);C7.setParent(C6);C7.iC();C8.setDisplayPosition(1);C8.setParent(C6);C8.setHeight(90);C8.setUnits("CONTENT");C8.iC();C9.setDisplayPosition(2);
C9.setParent(C6);C9.setHeight(90);C9.setUnits("CONTENT");C9.iC();C10.setDisplayPosition(3);C10.setParent(C6);C10.setHeight(90);C10.setUnits("CONTENT");C10.iC();C11.setDisplayPosition(4);C11.setParent(C6);C11.setHeight(260);C11.setUnits("CONTENT");C11.iC();C12.setManage(C18);C12.setParent(C6);C12.setRow(C8);C12.setSizing("CONTENTHEIGHTFITTOWIDTH");C12.setColumn(C7);C12.setAlignment("TOPLEFT");C12.iC();C13.setManage(C19);C13.setParent(C6);C13.setRow(C9);C13.setSizing("CONTENTHEIGHTFITTOWIDTH");C13.setColumn(C7);
C13.setAlignment("TOPLEFT");C13.iC();C14.setManage(C20);C14.setParent(C6);C14.setRow(C10);C14.setSizing("CONTENTHEIGHTFITTOWIDTH");C14.setColumn(C7);C14.setAlignment("TOPLEFT");C14.iC();C15.setManage(C21);C15.setParent(C6);C15.setRow(C11);C15.setSizing("FITTOWIDTH");C15.setColumn(C7);C15.setAlignment("TOPLEFT");C15.iC();C16.setCaption("SEND EMAIL");C16.setDisplayPosition(1);C16.setParent(this);C16.setTabPosition(1);C16.setTop(550);C16.setThemeDrawStyle("MediumTitle");C16.setWidth(164);C16.setHeight(40);
C16.setCaptionMarginBottom(10);C16.setCaptionMarginLeft(40);C16.setCaptionMarginRight(40);C16.setCaptionMarginTop(10);C16.setLeft(20);C16.iC();C17.setDisplayPosition(2);C17.setParent(this);C17.setTabPosition(2);C17.setTabStop(false);C17.setHeight(530);C17.setWidth(1160);C17.setLayoutManager(C6);C17.setLeft(20);C17.setTop(20);C17.iC();C18.setCaption("Recipient");C18.setDisplayPosition(2);C18.setLeft(0);C18.setParent(C17);C18.setTabPosition(3);C18.setTop(0);C18.setHeight(90);C18.setWidth(1160);C18.setPlaceholder("recipient@acme.com");
C18.iC();C19.setCaption("Sender");C19.setDisplayPosition(3);C19.setLeft(0);C19.setParent(C17);C19.setTabPosition(2);C19.setTop(90);C19.setHeight(90);C19.setWidth(1160);C19.setPlaceholder("sender@acme.com");C19.iC();C20.setCaption("Subject");C20.setDisplayPosition(4);C20.setLeft(0);C20.setParent(C17);C20.setTabPosition(1);C20.setTop(180);C20.setHeight(90);C20.setWidth(1160);C20.setPlaceholder("This is a test email");C20.iC();C21.setAppearance("TEXTFIELDAREA");C21.setCaption("Enter email body here");
C21.setDisplayPosition(1);C21.setHeight(260);C21.setLeft(0);C21.setMultiLine(true);C21.setParent(C17);C21.setTabPosition(4);C21.setTop(270);C21.setWidth(1160);C21.iC();C16.aH("CLICK",this,e1);this.setTheme(l.THEME().get("MATERIALDESIGNBLUE"));this.setLayoutManager(C0);this.setCaption("Example: Sending Email using SendGrid API");}});function e1(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#SendButton.Click",28);var C0=r.cDR("SERVICE","XEX00023","SENDEMAIL");var C1=r.cR("OK","PRIM_BOLN");var C2=r.cR("ERRORMESSAGE","PRIM_DC","UnicodeString");
C0.iC();C1.iC();C2.iC();r.ln=28;{r.ln=33;C0.mthEXECUTE({FLD:{"FLD_RECIPIENT":m.RECIPIENTINPUT.get(),"FLD_SENDER":m.SENDERINPUT.get(),"FLD_SUBJECT":m.SUBJECTINPUT.get(),"FLD_BODY":m.BODYINPUT.get()}},{FLD:{"FLD_OK":C1,"FLD_ERRORMESSAGE":C2}});r.ln=35;if(l.tB(C1.get())){r.ln=36;l.WEB().mthALERT("The email has been sent successfully");}else{r.ln=38;l.WEB().mthALERT(C2.get());}}r.ln=40;r.e();};},{rp:["PRIM_WEB","PRIM_TBLO","PRIM_TBLO.Column","PRIM_TBLO.Row","PRIM_TBLO.Item","PRIM_MD.RaisedButton","PRIM_PANL","PRIM_MD.Edit","PRIM_WEB.DataRequest"],
dp:["PRIM_BOLN","PRIM_DC.UnicodeString"]});