LANSA.addComponent({id:"XLBA0094",nm:"XDevice_SqlDb",ot:"rp",tp:"Reusable Part",de:"[pkg-lansa-mobile]",tl:14020401},function(l,oI,u){var cL="ENG";var Fd={F1:{ic:0,nm:"STD_CLOB",ft:"CL",ln:0,dc:0,lb:"Standard CLOB",h1:"Standard",h2:"CLOB",h3:" ",de:"Standard CLOB",dv:l.SqlNull,ia:["ASQN","FE","LC"]}};var cO=l.rC(oI,{an:"XLBA0099",fd:Fd,mt:{Open:{ps:{"Schema":{pt:"i"}}},CreateQuery:{ps:{"Sql":{pt:"i"},"Tag":{pt:"i"}}},AdvanceState:{},LoadSchema:{},ApplySchema:{ps:{"SchemaName":{pt:"i"}}},ReadSchemaFromClob:
{ps:{"Input":{pt:"i"}}},ExecuteQuery:{ps:{"Query":{pt:"i"}}},ExecuteQueryString:{ps:{"String":{pt:"i"},"Tag":{pt:"i"}}},DownloadData:{ps:{"Url":{pt:"i"},"Tag":{pt:"i"}}}},ev:{ExecQueryCompleted:{ps:{"Result":{pt:"i"},"Query":{pt:"i"},"Tag":{pt:"i"}}},DownloadDataCompleted:{ps:{"Status":{pt:"i"},"Message":{pt:"i"},"Tag":{pt:"i"}}}},co:function(){cO.aN.call(this);this.aF("XLBA0094",Fd);var C0=this.cR("WIDGET","XLBA0093");var C1=this.cR("GSCHEMANAME","PRIM_DC","UnicodeString");var C2=this.cR("GOPENINVOKED","PRIM_BOLN");
var C3=this.cR("GSCHEMALOADINITIATED","PRIM_BOLN");var C4=this.cR("GSCHEMAISREADY","PRIM_BOLN");var C5=this.cR("GWIDGETISREADY","PRIM_BOLN");var C6=this.cR("EXECQUEUE","XLBA0101");C0.iC();C1.iC();C2.iC();C3.iC();C4.iC();C5.iC();C6.iC();C0.aH("INITIALIZE",this,e3);C0.aH("APPLYSCHEMACOMPLETED",this,e4);C0.aH("DOWNLOADDATACOMPLETED",this,e8);C6.aH("QUERYCOMPLETED",this,e2);this.aH("CREATEINSTANCE",this,e1);}});function e1(sender,Ps){var r=l.eR(this,cO,"#COM_OWNER.CreateInstance",22);r.ln=22;{}r.ln=23;
r.e();};function e2(sender,Ps){var r=l.eR(this,cO,"#ExecQueue.QueryCompleted",25);var P0=Ps.r("CONTEXT");var P1=Ps.r("RESULT");r.ln=25;{r.ln=26;if((P0.getPARENTCONTEXT()==null)){r.ln=27;{var eP=l.ePs();eP.cD("RESULT");eP.cD("QUERY");eP.cR("TAG","PRIM_DC","UnicodeString");eP.sR("RESULT",P1);eP.sR("QUERY",P0.getQUERY());eP.r("TAG").set(P0.getQUERY().getTAG());this.fE("EXECQUERYCOMPLETED",eP);eP.e();}}}r.ln=29;r.e();};cO.mthOPEN=function(p0){var m=this.REF,r=l.mR(this,cO,"Open",31);var P0=r.cP("SCHEMA","PRIM_DC","UnicodeString");
P0.set((p0===u)?(""):(p0));r.ln=31;{r.ln=34;if(l.tB(m.GOPENINVOKED.get())){r.ln=35;this.mthFATALERROR("'Open' has previously been invoked, should be invoked once only");}r.ln=38;m.GOPENINVOKED.set(true);r.ln=39;m.GSCHEMANAME.set(P0.get());r.ln=41;this.mthADVANCESTATE();}r.ln=42;r.e();};cO.mthCREATEQUERY=function(p1,p2){var r=l.mR(this,cO,"CreateQuery",44);var P0=r.cPD("RESULT");var P1=r.cP("SQL","PRIM_DC","UnicodeString");var P2=r.cP("TAG","PRIM_DC","UnicodeString");P1.set((p1===u)?(""):(p1));P2.set((p2===u)?(""):(p2));
r.ln=44;{r.ln=49;this.mthASSERTISREADY();r.ln=51;P0=r.sR("P0",l.cAs("XLBA0098",u,"mthCREATE",[this]));r.ln=52;P0.setSQL(P1.get());r.ln=53;P0.setTAG(P2.get());}r.ln=54;return r.rR(P0);};function e3(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Widget.Initialize",56);r.ln=56;{r.ln=57;m.GWIDGETISREADY.set(true);r.ln=59;this.mthADVANCESTATE();}r.ln=60;r.e();};function e4(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Widget.ApplySchemaCompleted",62);var P0=Ps.r("STATUS");var P1=Ps.r("MESSAGE");r.ln=62;{r.ln=63;
{var v1=P0.get();if(r.ln=65,l.s.eq(v1,"APPLY_FAILED")){r.ln=66;this.mthFATALERROR(l.cat("Failed to apply database schema: ",P1.get()));}else{r.ln=69;m.GSCHEMAISREADY.set(true);r.ln=71;this.mthLOGINFO("Asynchronous schema loading completed");r.ln=72;this.mthADVANCESTATE();}r.ln=73;}}r.ln=75;r.e();};cO.mthADVANCESTATE=function(){var m=this.REF,r=l.mR(this,cO,"AdvanceState",77);r.ln=77;{r.ln=78;if(l.tB(m.GWIDGETISREADY.get())){r.ln=79;if(l.tB(l.not(m.GSCHEMALOADINITIATED.get()))){r.ln=80;this.mthLOADSCHEMA();
}else{r.ln=82;if(l.tB(l.and(m.GSCHEMAISREADY.get(),l.not(this.getISREADY())))){r.ln=83;this.mthLOGINFO("Ready");r.ln=84;this.mthSIGNALREADY();}}}}r.ln=88;r.e();};cO.mthLOADSCHEMA=function(){var m=this.REF,r=l.mR(this,cO,"LoadSchema",90);r.ln=90;{r.ln=91;if(l.tB(l.and(m.GOPENINVOKED.get(),m.GWIDGETISREADY.get()))){r.ln=92;if(l.tB(m.GSCHEMALOADINITIATED.get())){r.ln=93;this.mthFATALERROR("Schema has begin loading");}r.ln=96;m.GSCHEMALOADINITIATED.set(true);r.ln=97;this.mthLOGINFO("Begin loading schema");
r.ln=99;if(l.tB(l.s.ne(m.GSCHEMANAME.get(),""))){r.ln=100;this.mthAPPLYSCHEMA(m.GSCHEMANAME.get());}else{r.ln=102;m.GSCHEMAISREADY.set(true);r.ln=104;this.mthLOGINFO("Using null schema");r.ln=105;this.mthADVANCESTATE();}}}r.ln=108;r.e();};cO.mthAPPLYSCHEMA=function(p0){var m=this.REF,r=l.mR(this,cO,"ApplySchema",110),mth=r;var P0=r.cP("SCHEMANAME","PRIM_DC","UnicodeString");P0.set(p0);var C0=r.cF("SCHEMACONTENT",Fd.F1.Dc);var C1=r.cDR("SERVER","XLBA0100","FETCHSCHEMA");C0.iC();C1.iC();C1.aH("COMPLETED",this,e5);
C1.aH("FAILED",this,e6);r.ln=110;{r.ln=116;C1.mthEXECUTEASYNC({FLD:{"FLD_SCHEMANAME":P0.get()}},{FLD:{"STD_CLOB":C0}});}r.ln=140;r.e();function e5(sender,Ps){var r=l.eR(this,cO,"#Server.Completed",118,mth);r.ln=118;{r.ln=119;if(l.tB(l.s.ne(C0.get(),""))){r.ln=120;this.mthREADSCHEMAFROMCLOB(C0);}else{r.ln=122;this.mthFATALERROR(l.cat(l.add("Schema was either blank, or not found. Ensure that the schema file ",P0.get())," is placed on the server under the partition execute folder"));}}r.ln=124;r.e();
}function e6(sender,Ps){var r=l.eR(this,cO,"#Server.Failed",126,mth);var P1=Ps.r("REASON");var P2=Ps.r("HANDLED");r.ln=126;{r.ln=127;if(l.s.eq(P1.get(),"SERVERERROR")){r.ln=128;P2.set(true);r.ln=131;m.GSCHEMAISREADY.set(true);r.ln=133;this.mthLOGINFO("Failed to contact the server to retrieve schema, possibly offline");r.ln=134;this.mthADVANCESTATE();}else{r.ln=136;this.mthFATALERROR(l.cat(l.cat("Failed to fetch schema from the server [reason = ",P1.get()),"]"));}}r.ln=138;r.e();}};cO.mthREADSCHEMAFROMCLOB=function(p0)
{var m=this.REF,r=l.mR(this,cO,"ReadSchemaFromClob",142),mth=r;var P0=r.cPD("INPUT");P0=p0;var C0=r.cR("READER","PRIM_WEB","ClobReader");C0.iC();C0.aH("COMPLETED",this,e7);r.ln=142;{r.ln=146;C0.mthREAD(P0.get());}r.ln=152;r.e();function e7(sender,Ps){var r=l.eR(this,cO,"#Reader.Completed",148,mth);var P1=Ps.r("DATA");r.ln=148;{r.ln=149;m.WIDGET.mthAPPLYSCHEMA(P1.get());}r.ln=150;r.e();}};cO.mthEXECUTEQUERY=function(p0){var m=this.REF,r=l.mR(this,cO,"ExecuteQuery",154);var P0=r.cPD("QUERY");P0=p0;
r.ln=154;{r.ln=157;if(l.and(l.s.eq(P0.getSQL(),""),l.n.eq(P0.getQUERYCOUNT(),0))){r.ln=158;this.mthFATALERROR("Query's SQL property has not been set and this is not a query group (no sub-queries specified)");}else{r.ln=160;if(l.and(l.s.ne(P0.getSQL(),""),l.n.gt(P0.getQUERYCOUNT(),0))){r.ln=161;this.mthFATALERROR("Query group can't have its SQL property set");}}r.ln=166;m.EXECQUEUE.mthQUEUE(P0);}r.ln=167;r.e();};cO.mthEXECUTEQUERYSTRING=function(p0,p1){var r=l.mR(this,cO,"ExecuteQueryString",169);
var P0=r.cP("STRING","PRIM_DC","UnicodeString");var P1=r.cP("TAG","PRIM_DC","UnicodeString");P0.set(p0);P1.set((p1===u)?(""):(p1));var C0=r.cD("C0");r.ln=169;{r.ln=175;C0=r.sR("C0",this.mthCREATEQUERY(P0.get(),P1.get()));r.ln=176;this.mthEXECUTEQUERY(C0);}r.ln=177;r.e();};cO.mthDOWNLOADDATA=function(p0,p1){var m=this.REF,r=l.mR(this,cO,"DownloadData",179);var P0=r.cP("URL","PRIM_DC","UnicodeString");var P1=r.cP("TAG","PRIM_DC","UnicodeString");P0.set(p0);P1.set((p1===u)?(""):(p1));r.ln=179;{r.ln=183;
m.WIDGET.mthDOWNLOADDATA(P0.get(),P1.get());}r.ln=184;r.e();};function e8(sender,Ps){var r=l.eR(this,cO,"#Widget.DownloadDataCompleted",186);var P0=Ps.r("STATUS");var P1=Ps.r("MESSAGE");var P2=Ps.r("TAG");r.ln=186;{r.ln=187;{var eP=l.ePs();eP.cR("STATUS","PRIM_DC","UnicodeString");eP.cR("MESSAGE","PRIM_DC","UnicodeString");eP.cR("TAG","PRIM_DC","UnicodeString");eP.r("STATUS").set(P0.get());eP.r("MESSAGE").set(P1.get());eP.r("TAG").set(P2.get());this.fE("DOWNLOADDATACOMPLETED",eP);eP.e();}}r.ln=188;
r.e();};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"STD_CLOB"});}},{rc:["XLBA0099","XLBA0093","XLBA0101"],rp:["PRIM_DC.UnicodeString","PRIM_BOLN","PRIM_FLD","PRIM_WEB.DataRequest"],dc:["XLBA0098"],dp:["PRIM_WEB.ClobReader"]});