LANSA.addComponent({id:"XTAPRSLST",nm:"XTAPersonList",ot:"wv",tp:"View",pt:"ap",de:"Tasks Person List",tl:15000300},function(l,oI,u){var cL="ENG";if(l.gCL()=="FRA"){cL=l.gCL();}var Fd={F1:{nm:"XEMPLOYID",an:"xEmployeeIdentification",ft:"A",ln:10,dc:0,lb:{"ENG":"Employee Id","FRA":"Id employé"}[cL],h1:{"ENG":"Employee","FRA":"Identification"}[cL],h2:{"ENG":"Identification","FRA":"Employé"}[cL],h3:" ",de:"Identification",dv:"",ia:["FE"]},F2:{nm:"XGIVENAME",an:"xEmployeeGivenNames",ft:"N",ln:40,dc:0,
lb:{"ENG":"Given Names","FRA":"Prénoms"}[cL],h1:{"ENG":"Employee","FRA":"Prénoms"}[cL],h2:{"ENG":"Given","FRA":"Employé"}[cL],h3:{"ENG":"Names","FRA":" "}[cL],de:{"ENG":"Given Names","FRA":"Prénoms"}[cL],dv:"",ia:["FE","LC"]},F3:{nm:"XSURNAME",an:"xEmployeeSurname",ft:"N",ln:40,dc:0,lb:{"ENG":"Surname","FRA":"Nom"}[cL],h1:{"ENG":"Employee","FRA":"Nom"}[cL],h2:{"ENG":"Surname","FRA":"Employé"}[cL],h3:" ",de:{"ENG":"Surname","FRA":"Nom"}[cL],dv:"",ia:["FE","LC"]},F4:{nm:"XEMPTHM",an:"xEmployeeImageThumbnail",
ft:"BL",ln:0,dc:0,lb:{"ENG":"Employee Image","FRA":"Image Employé"}[cL],h1:{"ENG":"Employee","FRA":"Image"}[cL],h2:{"ENG":"Image","FRA":"employé"}[cL],h3:" ",de:{"ENG":"Employee Image Thumbnail","FRA":"Image miniature employé"}[cL],dv:l.SqlNull,ia:["ASQN","FE","LC"]},F5:{nm:"XSTREET",an:"xEmployeeStreet",ft:"N",ln:40,dc:0,lb:{"ENG":"Street","FRA":"Rue"}[cL],h1:{"ENG":"Street","FRA":"Rue"}[cL],h2:" ",h3:" ",de:{"ENG":"Street","FRA":"Rue"}[cL],dv:"",ia:["FE","LC"]},F6:{nm:"XCITY",an:"xEmployeeCity",
ft:"N",ln:40,dc:0,lb:{"ENG":"City","FRA":"Commune"}[cL],h1:{"ENG":"City","FRA":"Commune"}[cL],h2:" ",h3:" ",de:{"ENG":"City","FRA":"Commune"}[cL],dv:"",ia:["FE","LC"]},F7:{nm:"XSTATE",an:"xEmployeeState",ft:"N",ln:40,dc:0,lb:{"ENG":"State","FRA":"Etat"}[cL],h1:{"ENG":"State","FRA":"Etat"}[cL],h2:" ",h3:" ",de:{"ENG":"State","FRA":"Etat"}[cL],dv:"",ia:["FE","LC"]},F8:{nm:"XPHONEHME",an:"xEmployeeHomeTelephone",ft:"A",ln:15,dc:0,lb:{"ENG":"Home Phone","FRA":"Téléphone perso"}[cL],h1:{"ENG":"Home","FRA":"Téléphone"}[cL],
h2:{"ENG":"Telephone","FRA":"Personnel"}[cL],h3:" ",de:{"ENG":"Home Telephone","FRA":"Téléphone personnel"}[cL],dv:"",ia:["FE"]},F9:{nm:"XPHONEBUS",an:"xEmployeeBusinessTelephone",ft:"A",ln:15,dc:0,lb:{"ENG":"Business Phone","FRA":"Tél. travail"}[cL],h1:{"ENG":"Business","FRA":"Téléphone"}[cL],h2:{"ENG":"Telephone","FRA":"Travail"}[cL],h3:" ",de:{"ENG":"Business Telephone","FRA":"Téléphone travail"}[cL],dv:"",ia:["FE"]},F10:{nm:"XPHONEMOB",an:"xEmployeeMobilePhone",ft:"A",ln:15,dc:0,lb:{"ENG":"Mobile Phone","FRA":"Téléphone mob."}[cL],
h1:{"ENG":"Employee","FRA":"Téléphone"}[cL],h2:{"ENG":"Mobile Phone","FRA":"Mobile"}[cL],h3:" ",de:{"ENG":"Mobile Phone","FRA":"Téléphone mobile"}[cL],dv:"",ia:["FE"]},F11:{nm:"XTASKPNDG",an:"xTaskPendingCount",ft:"I",ln:4,dc:0,lb:"Pending Tasks",h1:"Pending",h2:"Tasks",h3:" ",de:"Pending Tasks",dv:0,ia:["FE","RB"]},F12:{nm:"XTASKCOMP",an:"xTaskCompletedCount",ft:"I",ln:4,dc:0,lb:"Completed Tasks",h1:"Completed",h2:"Tasks",h3:" ",de:"Completed Tasks",dv:0,ia:["FE","RB"]}};var cO=l.rC(oI,{an:"PRIM_VIEW",
fd:Fd,mt:{RefreshPeople:{}},co:function(){cO.aN.call(this);var f=this.aF("XTAPRSLST",Fd);var C0=this.cR("LAYOUT","PRIM_TBLO");var C1=this.cR("COLUMN1","PRIM_TBLO","Column");var C2=this.cR("ROW1","PRIM_TBLO","Row");var C3=this.cR("LAYOUTITEM1","PRIM_TBLO","Item");var C4=this.cR("PEOPLELIST","PRIM_TREE");C0.iC();C1.setDisplayPosition(1);C1.setParent(C0);C1.iC();C2.setDisplayPosition(1);C2.setParent(C0);C2.iC();C3.setColumn(C1);C3.setManage(C4);C3.setParent(C0);C3.setRow(C2);C3.iC();C4.setDisplayPosition(1);
C4.setLeft(0);C4.setParent(this);C4.setTabPosition(1);C4.setTabStop(false);C4.setTop(0);C4.setHeight(505);C4.setWidth(457);C4.iC();C4.aDS("XTAPRSITM");C4.aLF({"XEMPLOYID":f.F1,"XGIVENAME":f.F2,"XSURNAME":f.F3,"XEMPTHM":f.F4,"XSTREET":f.F5,"XCITY":f.F6,"XSTATE":f.F7,"XPHONEHME":f.F8,"XPHONEBUS":f.F9,"XPHONEMOB":f.F10,"XTASKPNDG":f.F11,"XTASKCOMP":f.F12});this.setDisplayPosition(1);this.setHeight(505);this.setWidth(457);this.setLayoutManager(C0);this.setTabPosition(1);this.aH("PREPARE",this,e1);}});
function e1(sender,Ps){var r=l.eR(this,cO,"#COM_OWNER.Prepare",16);r.ln=16;{r.ln=18;this.mthREFRESHPEOPLE();}r.ln=20;r.e();};cO.mthREFRESHPEOPLE=function(){var m=this.REF,r=l.mR(this,cO,"RefreshPeople",26),mth=r;var C0=r.cDR("LOADPEOPLE","XTASRVM","LOADPEOPLE");C0.iC();C0.aH("COMPLETED",this,e2);r.ln=26;{r.ln=29;m.PEOPLELIST.clearList();r.ln=31;this.setImage(l.WEB().getLoadingImage());r.ln=33;C0.mthEXECUTEASYNC({},{LIST:{"XTAPEOPLELIST":m.PEOPLELIST}});}r.ln=41;r.e();function e2(sender,Ps){var r=l.eR(this,cO,"#LoadPeople.Completed",35,mth);
r.ln=35;{r.ln=37;this.setImage(null);}r.ln=39;r.e();}};},{rp:["PRIM_VIEW","PRIM_TBLO","PRIM_TBLO.Column","PRIM_TBLO.Row","PRIM_TBLO.Item","PRIM_TREE","PRIM_WEB.DataRequest","PRIM_FLD"],dc:["XTAPRSITM"]});